[package]
name = "astersql-ingestor-engineapi"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[dependencies]
membuf = { package = "astersql-lightning-membuf", path = "../../lightning/membuf" }

[package.metadata.porting]
go-package = "pkg/ingestor/engineapi"
legacy-tasks = ["task-168"]
