[package]
name = "astersql-store-copr-copr_test"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[package.metadata.porting]
go-package = "pkg/store/copr/copr_test"
legacy-tasks = ["task-1491"]

[dev-dependencies]
"astersql-config" = { package = "astersql-config", path = "../../../config" }
"astersql-config-kerneltype" = { package = "astersql-config-kerneltype", path = "../../../config/kerneltype" }
"astersql-kv" = { package = "astersql-kv", path = "../../../kv" }
"astersql-resourcegroup-runaway" = { package = "astersql-resourcegroup-runaway", path = "../../../resourcegroup/runaway" }
"astersql-store-copr" = { package = "astersql-store-copr", path = ".." }
"astersql-store-mockstore" = { package = "astersql-store-mockstore", path = "../../mockstore" }
"astersql-testkit" = { package = "astersql-testkit", path = "../../../testkit" }
"astersql-testkit-testfailpoint" = { package = "astersql-testkit-testfailpoint", path = "../../../testkit/testfailpoint" }
"astersql-testkit-testmain" = { package = "astersql-testkit-testmain", path = "../../../testkit/testmain" }
"astersql-testkit-testsetup" = { package = "astersql-testkit-testsetup", path = "../../../testkit/testsetup" }
