[package]
name = "astersql-ddl-tests-fail"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[package.metadata.porting]
go-package = "pkg/ddl/tests/fail"
legacy-tasks = ["task-1304"]

[target.'cfg(any())'.dev-dependencies]
"astersql-config" = { package = "astersql-config", path = "../../../config" }
"astersql-config-kerneltype" = { package = "astersql-config-kerneltype", path = "../../../config/kerneltype" }
"astersql-ddl" = { package = "astersql-ddl", path = "../.." }
"astersql-ddl-schematracker" = { package = "astersql-ddl-schematracker", path = "../../schematracker" }
"astersql-ddl-schemaver" = { package = "astersql-ddl-schemaver", path = "../../schemaver" }
"astersql-domain" = { package = "astersql-domain", path = "../../../domain" }
"astersql-kv" = { package = "astersql-kv", path = "../../../kv" }
"astersql-parser-ast" = { package = "astersql-parser-ast", path = "../../../parser/ast" }
"astersql-session" = { package = "astersql-session", path = "../../../session" }
"astersql-sessionctx-vardef" = { package = "astersql-sessionctx-vardef", path = "../../../sessionctx/vardef" }
"astersql-store-mockstore" = { package = "astersql-store-mockstore", path = "../../../store/mockstore" }
"astersql-store-mockstore-teststore" = { package = "astersql-store-mockstore-teststore", path = "../../../store/mockstore/teststore" }
"astersql-tablecodec" = { package = "astersql-tablecodec", path = "../../../tablecodec" }
"astersql-testkit" = { package = "astersql-testkit", path = "../../../testkit" }
"astersql-testkit-testfailpoint" = { package = "astersql-testkit-testfailpoint", path = "../../../testkit/testfailpoint" }
"astersql-testkit-testsetup" = { package = "astersql-testkit-testsetup", path = "../../../testkit/testsetup" }
