// Copyright 2026 AsterSQL.
// Copyright 2019 PingCAP, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Index Nested Loop Hash Join（索引嵌套循环哈希连接）执行器。
//
// 一个 outer worker 批量读外表行并建哈希表任务，N 个 inner worker 按外表
// key 做索引 lookup（回表查找）取内表行后探测哈希表。可选择保持外表顺序
//（`KeepOuterOrder`）或乱序输出以提高吞吐。

// IndexNestedLoopHashJoin 的 outer/inner worker、任务队列、结果回收和乱序/保序 join 流程。
// 下面按文件顺序保留常量、变量、类型、函数和方法。
// #![allow(dead_code, non_snake_case, non_camel_case_types, non_upper_case_globals, unused_variables)]
// use std::any::Any;
// use std::collections::HashMap;
// numResChkHold indicates the number of resource chunks that an inner worker
// holds at the same time.
// It's used in 2 cases individually:
//  1. IndexMergeJoin
//  2. IndexNestedLoopHashJoin:
//     It's used when IndexNestedLoopHashJoin.KeepOuterOrder is true.
//     Otherwise, there will be at most `concurrency` resource chunks throughout
//     the execution of IndexNestedLoopHashJoin.
// 常量声明对应 Go const；保留原始取值和分组顺序。
// const numResChkHold = 4
// 常量声明对应 Go const；保留原始取值和分组顺序。
// const maxRowsPerFetch = 4096
// IndexNestedLoopHashJoin employs one outer worker and N inner workers to
// execute concurrently. The output order is not promised.
// The execution flow is very similar to IndexLookUpReader:
// 1. The outer worker reads N outer rows, builds a task and sends it to the
// inner worker channel.
// 2. The inner worker receives the tasks and does 3 things for every task:
//  1. builds hash table from the outer rows
//  2. builds key ranges from outer rows and fetches inner rows
//  3. probes the hash table and sends the join result to the main thread channel.
//     Note: step 1 and step 2 runs concurrently.
// 3. The main thread receives the join results.
// IndexNestedLoopHashJoin 对应 Go 的同名 struct；字段顺序、嵌入字段和指针形状按源码保留。
// pub struct IndexNestedLoopHashJoin {
//     pub IndexLookUpJoin: IndexLookUpJoin,
//     pub resultCh chan: Option<Box<indexHashJoinResult>>,
//     pub joinChkResourceCh []chan: Option<Box<chunk::Chunk>>,
// We build individual joiner for each inner worker when using chunk-based
// execution, to avoid the concurrency of joiner.chk and joiner.selected.
//     pub Joiners: Vec<Joiner>,
//     pub KeepOuterOrder: bool,
//     pub curTask: Option<Box<indexHashJoinTask>>,
// taskCh is only used when `KeepOuterOrder` is true.
//     pub taskCh chan: Option<Box<indexHashJoinTask>>,
//     pub stats: Option<Box<indexLookUpJoinRuntimeStats>>,
//     pub prepared: bool,
// panicErr records the error generated by panic recover. This is introduced to
// return the actual error message instead of `context cancelled` to the client.
//     pub panicErr struct: {,
//         pub Mutex: sync::Mutex,
//         pub Bool: atomic::Bool,
//         pub error: errors::Error,
// }
//     ctxWithCancel context.Context
// }
// indexHashJoinOuterWorker 对应 Go 的同名 struct；字段顺序、嵌入字段和指针形状按源码保留。
// pub struct indexHashJoinOuterWorker {
//     pub outerWorker: outerWorker,
//     pub innerCh chan: Option<Box<indexHashJoinTask>>,
//     pub keepOuterOrder: bool,
// taskCh is only used when the outer order needs to be promised.
//     pub taskCh chan: Option<Box<indexHashJoinTask>>,
// }
// indexHashJoinInnerWorker 对应 Go 的同名 struct；字段顺序、嵌入字段和指针形状按源码保留。
// pub struct indexHashJoinInnerWorker {
//     pub innerWorker: innerWorker,
//     pub joiner: Joiner,
//     pub joinChkResourceCh chan: Option<Box<chunk::Chunk>>,
// resultCh is valid only when indexNestedLoopHashJoin do not need to keep
// order. Otherwise, it will be nil.
//     pub resultCh chan: Option<Box<indexHashJoinResult>>,
//     pub taskCh <-chan: Option<Box<indexHashJoinTask>>,
//     pub wg: Option<Box<sync::WaitGroup>>,
//     pub joinKeyBuf: Vec<u8>,
//     pub outerRowStatus: Vec<outerRowStatusFlag>,
//     pub rowIter: Option<Box<chunk::Iterator4Slice>>,
// }
// indexHashJoinResult 对应 Go 的同名 struct；字段顺序、嵌入字段和指针形状按源码保留。
// pub struct indexHashJoinResult {
//     pub chk: Option<Box<chunk::Chunk>>,
//     pub err: errors::Error,
//     pub src chan<-: Option<Box<chunk::Chunk>>,
// }
// indexHashJoinTask 对应 Go 的同名 struct；字段顺序、嵌入字段和指针形状按源码保留。
// pub struct indexHashJoinTask {
//     pub lookUpJoinTask: Option<Box<lookUpJoinTask>>,
//     pub outerRowStatus: Vec<Vec<outerRowStatusFlag>>,
//     pub lookupMap: BaseHashTable,
//     pub err: errors::Error,
//     pub keepOuterOrder: bool,
// resultCh is only used when the outer order needs to be promised.
//     pub resultCh chan: Option<Box<indexHashJoinResult>>,
// matchedInnerRowPtrs is only valid when the outer order needs to be
// promised. Otherwise, it will be nil.
// len(matchedInnerRowPtrs) equals to
// lookUpJoinTask.outerResult.NumChunks(), and the elements of every
// matchedInnerRowPtrs[chkIdx][rowIdx] indicates the matched inner row ptrs
// of the corresponding outer row.
//     pub matchedInnerRowPtrs: Vec<Vec<Vec<chunk::RowPtr>>>,
// }
// Open implements the IndexNestedLoopHashJoin Executor interface.
// Open 对应 Go 声明 `func (e *IndexNestedLoopHashJoin) Open(ctx context.Context) error {`；保留原控制流、错误处理和外部依赖调用形状。
// impl IndexNestedLoopHashJoin {
//     pub fn Open(&mut self, ctx: context::Context) -> Result<(), errors::Error> {
//     err = exec.Open(ctx, self.Children(0))
//     if err != None {
//         return err
//     }
//     if len(self.InnerCtx.HashIsNullEQ) != len(self.InnerCtx.HashCols) {
//         return errors.New("index lookup hash join: hash null-eq flags length must match hash cols length")
//     }
//     if self.memTracker != None {
//         self.memTracker.Reset()
//     } else {
//         self.memTracker = memory.NewTracker(self.ID(), -1)
//     }
//     self.memTracker.AttachTo(self.Ctx().GetSessionVars().StmtCtx.MemTracker)
//     self.cancelFunc = None
//     self.innerPtrBytes = make([][]byte, 0, 8)
//     if self.RuntimeStats() != None {
//         self.stats = &indexLookUpJoinRuntimeStats{}
//     }
//     self.Finished.Store(false)
//     return None
// }
// }
// startWorkers 对应 Go 声明 `func (e *IndexNestedLoopHashJoin) startWorkers(ctx context.Context, initBatchSize int) {`；保留原控制流、错误处理和外部依赖调用形状。
// impl IndexNestedLoopHashJoin {
//     pub fn startWorkers(&mut self, ctx: context::Context, initBatchSize: i32) {
//     concurrency = self.Ctx().GetSessionVars().IndexLookupJoinConcurrency()
//     if self.stats != None {
//         self.stats.concurrency = concurrency
//     }
//     workerCtx, cancelFunc = context.WithCancel(ctx)
//     self.ctxWithCancel, self.cancelFunc = workerCtx, cancelFunc
//     innerCh = make(chan *indexHashJoinTask, concurrency)
//     if self.KeepOuterOrder {
//         self.taskCh = make(chan *indexHashJoinTask, concurrency)
// When `KeepOuterOrder` is true, each task holds their own `resultCh`
// individually, thus we do not need a global resultCh.
//         self.resultCh = None
//     } else {
//         self.resultCh = make(chan *indexHashJoinResult, concurrency)
//     }
//     self.joinChkResourceCh = make([]chan *chunk.Chunk, concurrency)
//     self.WorkerWg.Add(1)
//     ow = self.newOuterWorker(innerCh, initBatchSize)
// Go 这里启动 goroutine；仅保留异步/并发启动点，不真正调度线程。
//     go util.WithRecovery(func() { ow.run(self.ctxWithCancel) }, self.finishJoinWorkers)
//     for i = range concurrency {
//         if !self.KeepOuterOrder {
//             self.joinChkResourceCh[i] = make(chan *chunk.Chunk, 1)
//             self.joinChkResourceCh[i] <- exec.NewFirstChunk(e)
//         } else {
//             self.joinChkResourceCh[i] = make(chan *chunk.Chunk, numResChkHold)
//             for range numResChkHold {
//                 self.joinChkResourceCh[i] <- exec.NewFirstChunk(e)
//             }
//         }
//     }
//     self.WorkerWg.Add(concurrency)
//     for i = range concurrency {
//         workerID = i
//         go util.WithRecovery(func() { self.newInnerWorker(innerCh, workerID).run(self.ctxWithCancel, cancelFunc) }, self.finishJoinWorkers)
//     }
//     go self.wait4JoinWorkers()
// }
// }
// finishJoinWorkers 对应 Go 声明 `func (e *IndexNestedLoopHashJoin) finishJoinWorkers(r any) {`；保留原控制流、错误处理和外部依赖调用形状。
// impl IndexNestedLoopHashJoin {
//     pub fn finishJoinWorkers(&mut self, r: Box<dyn Any>) {
//     if r != None {
// panic/recover 分支对应 Go 的故障保护，Rust 迁移时需映射为 catch_unwind 或错误返回。
// record the panic error first to avoid returning context canceled
//         err = fmt.Errorf("%v", r)
//         if recoverdErr, ok = r.(error); ok {
//             err = recoverdErr
//         }
//         if !self.panicErr.Load() {
//             self.panicErr.Lock()
//             if !self.panicErr.Load() {
//                 self.panicErr.error = err
//                 self.panicErr.Store(true)
//             }
//             self.panicErr.Unlock()
//         }
// then cancel workers
//         self.IndexLookUpJoin.Finished.Store(true)
//         if self.cancelFunc != None {
//             self.cancelFunc()
//         }
//         if !self.KeepOuterOrder {
//             self.resultCh <- &indexHashJoinResult{err: err}
//         } else {
//             task = &indexHashJoinTask{err: err}
//             self.taskCh <- task
//         }
//     }
//     self.WorkerWg.Done()
// }
// }
// wait4JoinWorkers 对应 Go 声明 `func (e *IndexNestedLoopHashJoin) wait4JoinWorkers() {`；保留原控制流、错误处理和外部依赖调用形状。
// impl IndexNestedLoopHashJoin {
//     pub fn wait4JoinWorkers(&mut self) {
//     self.WorkerWg.Wait()
//     if self.resultCh != None {
//         close(self.resultCh)
//     }
//     if self.taskCh != None {
//         close(self.taskCh)
//     }
// }
// }
// Next implements the IndexNestedLoopHashJoin Executor interface.
// Next 对应 Go 声明 `func (e *IndexNestedLoopHashJoin) Next(ctx context.Context, req *chunk.Chunk) error {`；保留原控制流、错误处理和外部依赖调用形状。
// impl IndexNestedLoopHashJoin {
//     pub fn Next(&mut self, ctx: context::Context, req: Option<Box<chunk::Chunk>>) -> Result<(), errors::Error> {
//     if !self.prepared {
//         self.startWorkers(ctx, req.RequiredRows())
//         self.prepared = true
//     }
//     req.Reset()
//     if self.KeepOuterOrder {
//         return self.runInOrder(self.ctxWithCancel, req)
//     }
//     return self.runUnordered(self.ctxWithCancel, req)
// }
// }
// runInOrder 对应 Go 声明 `func (e *IndexNestedLoopHashJoin) runInOrder(ctx context.Context, req *chunk.Chunk) error {`；保留原控制流、错误处理和外部依赖调用形状。
// impl IndexNestedLoopHashJoin {
//     pub fn runInOrder(&mut self, ctx: context::Context, req: Option<Box<chunk::Chunk>>) -> Result<(), errors::Error> {
//     for {
//         if self.isDryUpTasks(ctx) {
//             if self.panicErr.Load() {
//                 return self.panicErr.error
//             }
//             return None
//         }
//         if self.curTask.err != None {
//             return self.curTask.err
//         }
//         result, err = self.getResultFromChannel(ctx, self.curTask.resultCh)
//         if err != None {
//             return err
//         }
//         if result == None {
//             self.curTask = None
//             continue
//         }
//         return self.handleResult(req, result)
//     }
// }
// }
// runUnordered 对应 Go 声明 `func (e *IndexNestedLoopHashJoin) runUnordered(ctx context.Context, req *chunk.Chunk) error {`；保留原控制流、错误处理和外部依赖调用形状。
// impl IndexNestedLoopHashJoin {
//     pub fn runUnordered(&mut self, ctx: context::Context, req: Option<Box<chunk::Chunk>>) -> Result<(), errors::Error> {
//     result, err = self.getResultFromChannel(ctx, self.resultCh)
//     if err != None {
//         return err
//     }
//     return self.handleResult(req, result)
// }
// }
// isDryUpTasks indicates whether all the tasks have been processed.
// isDryUpTasks 对应 Go 声明 `func (e *IndexNestedLoopHashJoin) isDryUpTasks(ctx context.Context) bool {`；保留原控制流、错误处理和外部依赖调用形状。
// impl IndexNestedLoopHashJoin {
//     pub fn isDryUpTasks(&mut self, ctx: context::Context) -> bool {
//     if self.curTask != None {
//         return false
//     }
//     let mut ok: bool = Default::default()
// Go select 同时监听 channel/context；保留分支结构，后续需替换为异步 select。
//     select {
//     case self.curTask, ok = <-self.taskCh:
//         if !ok {
//             return true
//         }
//     case <-ctx.Done():
//         return true
//     }
//     return false
// }
// }
// getResultFromChannel 对应 Go 声明 `func (e *IndexNestedLoopHashJoin) getResultFromChannel(ctx context.Context, resultCh <-chan *indexHashJoinResult) (*indexHashJoinResult, error) {`；保留原控制流、错误处理和外部依赖调用形状。
// impl IndexNestedLoopHashJoin {
//     pub fn getResultFromChannel(&mut self, ctx: context::Context, resultCh <-chan: Option<Box<indexHashJoinResult>>) -> (Option<Box<indexHashJoinResult>>, errors::Error) {
//     var (
//         result *indexHashJoinResult
//         ok     bool
//     )
// Go select 同时监听 channel/context；保留分支结构，后续需替换为异步 select。
//     select {
//     case result, ok = <-resultCh:
//         if !ok {
//             return None, None
//         }
//         if result.err != None {
//             return None, result.err
//         }
//     case <-ctx.Done():
//         failpoint.Inject("TestIssue49692", func() {
//             for !self.panicErr.Load() {
//                 runtime.Gosched()
//             }
//         })
//         err = error(None)
//         if self.panicErr.Load() {
//             err = self.panicErr.error
//         }
//         if err == None {
//             err = ctx.Err()
//         }
//         return None, err
//     }
//     return result, None
// }
// }
// handleResult 对应 Go 声明 `func (*IndexNestedLoopHashJoin) handleResult(req *chunk.Chunk, result *indexHashJoinResult) error {`；保留原控制流、错误处理和外部依赖调用形状。
// impl IndexNestedLoopHashJoin {
//     pub fn handleResult(&mut self, req: Option<Box<chunk::Chunk>>, result: Option<Box<indexHashJoinResult>>) -> Result<(), errors::Error> {
//     if result == None {
//         return None
//     }
//     req.SwapColumns(result.chk)
//     result.src <- result.chk
//     return None
// }
// }
// Close implements the IndexNestedLoopHashJoin Executor interface.
// Close 对应 Go 声明 `func (e *IndexNestedLoopHashJoin) Close() error {`；保留原控制流、错误处理和外部依赖调用形状。
// impl IndexNestedLoopHashJoin {
//     pub fn Close(&mut self) -> Result<(), errors::Error> {
//     if self.stats != None {
// Go defer 的资源收尾/统计注册语义在此保留为迁移线索，后续需接入 Rust Drop 或显式收尾。
//         defer self.Ctx().GetSessionVars().StmtCtx.RuntimeStatsColl.RegisterStats(self.ID(), self.stats)
//     }
//     if self.cancelFunc != None {
//         self.cancelFunc()
//     }
//     if self.resultCh != None {
// channel 工具调用保留 Go 的队列清理/发送语义。
//         channel.Clear(self.resultCh)
//         self.resultCh = None
//     }
//     if self.taskCh != None {
//         channel.Clear(self.taskCh)
//         self.taskCh = None
//     }
//     for i = range self.joinChkResourceCh {
//         close(self.joinChkResourceCh[i])
//     }
//     self.joinChkResourceCh = None
//     self.Finished.Store(false)
//     self.prepared = false
//     self.ctxWithCancel = None
//     return self.BaseExecutor.Close()
// }
// }
// run 对应 Go 声明 `func (ow *indexHashJoinOuterWorker) run(ctx context.Context) {`；保留原控制流、错误处理和外部依赖调用形状。
// impl indexHashJoinOuterWorker {
//     pub fn run(&mut self, ctx: context::Context) {
// Go defer 的资源收尾/统计注册语义在此保留为迁移线索，后续需接入 Rust Drop 或显式收尾。
//     defer trace.StartRegion(ctx, "IndexHashJoinOuterWorker").End()
//     defer close(self.innerCh)
//     for {
//         failpoint.Inject("TestIssue30211", None)
//         task, err = self.buildTask(ctx)
//         failpoint.Inject("testIndexHashJoinOuterWorkerErr", func() {
//             err = errors.New("mockIndexHashJoinOuterWorkerErr")
//         })
//         failpoint.Inject("testIssue54055_1", func(val failpoint.Value) {
//             if val.(bool) {
//                 err = errors.New("testIssue54055_1")
//             }
//         })
//         if err != None {
//             task = &indexHashJoinTask{err: err}
//             if self.keepOuterOrder {
// The outerBuilder and innerFetcher run concurrently, we may
// get 2 errors at simultaneously. Thus the capacity of task.resultCh
// needs to be initialized to 2 to avoid waiting.
//                 task.keepOuterOrder, task.resultCh = true, make(chan *indexHashJoinResult, 2)
//                 self.pushToChan(ctx, task, self.taskCh)
//             }
//             self.pushToChan(ctx, task, self.innerCh)
//             return
//         }
//         if task == None {
//             return
//         }
//         if finished = self.pushToChan(ctx, task, self.innerCh); finished {
//             return
//         }
//         if self.keepOuterOrder {
//             failpoint.Inject("testIssue20779", func() {
// panic/recover 分支对应 Go 的故障保护，Rust 迁移时需映射为 catch_unwind 或错误返回。
//                 panic("testIssue20779")
//             })
//             if finished = self.pushToChan(ctx, task, self.taskCh); finished {
//                 return
//             }
//         }
//     }
// }
// }
// buildTask 对应 Go 声明 `func (ow *indexHashJoinOuterWorker) buildTask(ctx context.Context) (*indexHashJoinTask, error) {`；保留原控制流、错误处理和外部依赖调用形状。
// impl indexHashJoinOuterWorker {
//     pub fn buildTask(&mut self, ctx: context::Context) -> (Option<Box<indexHashJoinTask>>, errors::Error) {
//     task, err = self.outerWorker.buildTask(ctx)
//     if task == None || err != None {
//         return None, err
//     }
//     var (
//         resultCh            chan *indexHashJoinResult
//         matchedInnerRowPtrs [][][]chunk.RowPtr
//     )
//     if self.keepOuterOrder {
//         resultCh = make(chan *indexHashJoinResult, numResChkHold)
//         matchedInnerRowPtrs = make([][][]chunk.RowPtr, task.outerResult.NumChunks())
//         for i = range matchedInnerRowPtrs {
//             matchedInnerRowPtrs[i] = make([][]chunk.RowPtr, task.outerResult.GetChunk(i).NumRows())
//         }
//     }
//     numChks = task.outerResult.NumChunks()
//     outerRowStatus = make([][]outerRowStatusFlag, numChks)
//     for i = range numChks {
//         outerRowStatus[i] = make([]outerRowStatusFlag, task.outerResult.GetChunk(i).NumRows())
//     }
//     return &indexHashJoinTask{
//         lookUpJoinTask:      task,
//         outerRowStatus:      outerRowStatus,
//         keepOuterOrder:      self.keepOuterOrder,
//         resultCh:            resultCh,
//         matchedInnerRowPtrs: matchedInnerRowPtrs,
//     }, None
// }
// }
// pushToChan 对应 Go 声明 `func (*indexHashJoinOuterWorker) pushToChan(ctx context.Context, task *indexHashJoinTask, dst chan<- *indexHashJoinTask) bool {`；保留原控制流、错误处理和外部依赖调用形状。
// impl indexHashJoinOuterWorker {
//     pub fn pushToChan(&mut self, ctx: context::Context, task: Option<Box<indexHashJoinTask>>, dst chan<-: Option<Box<indexHashJoinTask>>) -> bool {
// Go select 同时监听 channel/context；保留分支结构，后续需替换为异步 select。
//     select {
//     case <-ctx.Done():
//         return true
//     case dst <- task:
//     }
//     return false
// }
// }
// newOuterWorker 对应 Go 声明 `func (e *IndexNestedLoopHashJoin) newOuterWorker(innerCh chan *indexHashJoinTask, initBatchSize int) *indexHashJoinOuterWorker {`；保留原控制流、错误处理和外部依赖调用形状。
// impl IndexNestedLoopHashJoin {
//     pub fn newOuterWorker(&mut self, innerCh chan: Option<Box<indexHashJoinTask>>, initBatchSize: i32) -> Option<Box<indexHashJoinOuterWorker>> {
//     maxBatchSize = self.Ctx().GetSessionVars().IndexJoinBatchSize
//     batchSize = min(initBatchSize, maxBatchSize)
//     ow = &indexHashJoinOuterWorker{
//         outerWorker: outerWorker{
//             OuterCtx:         self.OuterCtx,
//             ctx:              self.Ctx(),
//             executor:         self.Children(0),
//             batchSize:        batchSize,
//             maxBatchSize:     maxBatchSize,
//             parentMemTracker: self.memTracker,
//             lookup:           &self.IndexLookUpJoin,
//         },
//         innerCh:        innerCh,
//         keepOuterOrder: self.KeepOuterOrder,
//         taskCh:         self.taskCh,
//     }
//     return ow
// }
// }
// supportIncrementalLookUp 对应 Go 声明 `func (e *IndexNestedLoopHashJoin) supportIncrementalLookUp() bool {`；保留原控制流、错误处理和外部依赖调用形状。
// impl IndexNestedLoopHashJoin {
//     pub fn supportIncrementalLookUp(&mut self) -> bool {
//     return !self.KeepOuterOrder &&
//         (JoinerType(self.Joiners[0]) == base.InnerJoin ||
//             JoinerType(self.Joiners[0]) == base.LeftOuterJoin ||
//             JoinerType(self.Joiners[0]) == base.RightOuterJoin ||
//             JoinerType(self.Joiners[0]) == base.AntiSemiJoin)
// }
// }
// newInnerWorker 对应 Go 声明 `func (e *IndexNestedLoopHashJoin) newInnerWorker(taskCh chan *indexHashJoinTask, workerID int) *indexHashJoinInnerWorker {`；保留原控制流、错误处理和外部依赖调用形状。
// impl IndexNestedLoopHashJoin {
//     pub fn newInnerWorker(&mut self, taskCh chan: Option<Box<indexHashJoinTask>>, workerID: i32) -> Option<Box<indexHashJoinInnerWorker>> {
// Since multiple inner workers run concurrently, we should copy join's IndexRanges for every worker to avoid data race.
//     copiedRanges = make([]*ranger.Range, 0, len(self.IndexRanges.Range()))
//     for _, ran = range self.IndexRanges.Range() {
//         copiedRanges = append(copiedRanges, ran.Clone())
//     }
//     let mut innerStats: Option<Box<innerWorkerRuntimeStats>> = Default::default()
//     if self.stats != None {
//         innerStats = &self.stats.innerWorker
//     }
//     let mut maxRows: i32 = Default::default()
// If the joiner supports incremental look up, we can fetch inner results in batches,
// retrieving partial results multiple times until all are fetched.
// Otherwise, we fetch all inner results in one batch.
//     if self.supportIncrementalLookUp() {
//         maxRows = maxRowsPerFetch
//     }
//     iw = &indexHashJoinInnerWorker{
//         innerWorker: innerWorker{
//             InnerCtx:      self.InnerCtx,
//             outerCtx:      self.OuterCtx,
//             ctx:           self.Ctx(),
//             maxFetchSize:  maxRows,
//             indexRanges:   copiedRanges,
//             keyOff2IdxOff: self.KeyOff2IdxOff,
//             stats:         innerStats,
//             lookup:        &self.IndexLookUpJoin,
//             memTracker:    memory.NewTracker(memory.LabelForIndexJoinInnerWorker, -1),
//         },
//         taskCh:            taskCh,
//         joiner:            self.Joiners[workerID],
//         joinChkResourceCh: self.joinChkResourceCh[workerID],
//         resultCh:          self.resultCh,
//         joinKeyBuf:        make([]byte, 1),
//         outerRowStatus:    make([]outerRowStatusFlag, 0, self.MaxChunkSize()),
//         rowIter:           chunk.NewIterator4Slice([]chunk.Row{}),
//     }
//     iw.memTracker.AttachTo(self.memTracker)
//     if len(copiedRanges) != 0 {
// We should not consume this memory usage in `iw.memTracker`. The
// memory usage of inner worker will be reset the end of iw.handleTask.
// While the life cycle of this memory consumption exists throughout the
// whole active period of inner worker.
//         self.Ctx().GetSessionVars().StmtCtx.MemTracker.Consume(2 * types.EstimatedMemUsage(copiedRanges[0].LowVal, len(copiedRanges)))
//     }
//     if self.LastColHelper != None {
// nextCwf.TmpConstant needs to be reset for every individual
// inner worker to avoid data race when the inner workers is running
// concurrently.
//         nextCwf = *self.LastColHelper
//         nextCwf.TmpConstant = make([]*expression.Constant, len(self.LastColHelper.TmpConstant))
//         for i = range self.LastColHelper.TmpConstant {
//             nextCwf.TmpConstant[i] = &expression.Constant{RetType: nextCwf.TargetCol.RetType}
//         }
//         iw.nextColCompareFilters = &nextCwf
//     }
//     return iw
// }
// }
// run 对应 Go 声明 `func (iw *indexHashJoinInnerWorker) run(ctx context.Context, cancelFunc context.CancelFunc) {`；保留原控制流、错误处理和外部依赖调用形状。
// impl indexHashJoinInnerWorker {
//     pub fn run(&mut self, ctx: context::Context, cancelFunc: context::CancelFunc) {
// Go defer 的资源收尾/统计注册语义在此保留为迁移线索，后续需接入 Rust Drop 或显式收尾。
//     defer trace.StartRegion(ctx, "IndexHashJoinInnerWorker").End()
//     let mut task: Option<Box<indexHashJoinTask>> = Default::default()
//     joinResult, ok = self.getNewJoinResult(ctx)
//     if !ok {
//         cancelFunc()
//         return
//     }
//     h, resultCh = fnv.New64(), self.resultCh
//     for {
// The previous task has been processed, so release the occupied memory
//         if task != None {
//             task.memTracker.Detach()
//         }
// Go select 同时监听 channel/context；保留分支结构，后续需替换为异步 select。
//         select {
//         case <-ctx.Done():
//             return
//         case task, ok = <-self.taskCh:
//         }
//         if !ok {
//             break
//         }
// We need to init resultCh before the err is returned.
//         if task.keepOuterOrder {
//             resultCh = task.resultCh
//         }
//         if task.err != None {
//             joinResult.err = task.err
//             break
//         }
//         err = self.handleTask(ctx, task, joinResult, h, resultCh)
//         if err != None && !task.keepOuterOrder {
// Only need check non-keep-outer-order case because the
// `joinResult` had been sent to the `resultCh` when err != None.
//             joinResult.err = err
//             break
//         }
//         if task.keepOuterOrder {
// We need to get a new result holder here because the old
// `joinResult` hash been sent to the `resultCh` or to the
// `joinChkResourceCh`.
//             joinResult, ok = self.getNewJoinResult(ctx)
//             if !ok {
//                 cancelFunc()
//                 return
//             }
//         }
//     }
//     failpoint.Inject("testIndexHashJoinInnerWorkerErr", func() {
//         joinResult.err = errors.New("mockIndexHashJoinInnerWorkerErr")
//     })
// When task.KeepOuterOrder is TRUE (resultCh != self.resultCh):
//   - the last joinResult will be handled when the task has been processed,
//     thus we DO NOT need to check it here again.
//   - we DO NOT check the error here neither, because:
//     - if the error is from task.err, the main thread will check the error of each task
//     - if the error is from handleTask, the error will be handled in handleTask
// We should not check `task != None && !task.KeepOuterOrder` here since it's
// possible that `join.chk.NumRows > 0` is true even if task == None.
//     if resultCh == self.resultCh {
//         if joinResult.err != None {
//             resultCh <- joinResult
//             return
//         }
//         if joinResult.chk != None && joinResult.chk.NumRows() > 0 {
// Go select 同时监听 channel/context；保留分支结构，后续需替换为异步 select。
//             select {
//             case resultCh <- joinResult:
//             case <-ctx.Done():
//                 return
//             }
//         }
//     }
// }
// }
// */
use crate::index_lookup_join::{
    IndexJoinExecutorBuilder, IndexJoinLookupContent, encode_key, extract_key,
};
use crate::joiner::{JoinType, Joiner, NaajType, Row};
use std::collections::HashMap;

/// 保序模式下每个 inner worker 同时持有的结果 chunk 资源数。
pub const NUM_RESULT_CHUNKS_HELD: usize = 4;
/// 单次外表取行的上限，防止 batch 无限膨胀。
pub const MAX_ROWS_PER_FETCH: usize = 4096;

/// 一次 next 返回的连接结果包装。
#[derive(Clone, Debug, Default)]
pub struct IndexHashJoinResult {
    pub rows: Vec<Row>,
    pub error: Option<String>,
}

/// Outer/inner worker 之间传递的哈希 join 任务。
#[derive(Clone, Debug, Default)]
pub struct IndexHashJoinTask {
    /// 本批外表行。
    pub outer_rows: Vec<Row>,
    /// 去重后的索引 lookup 内容。
    pub lookup_contents: Vec<IndexJoinLookupContent>,
    /// 外表 key → 行下标列表，用于探测。
    pub outer_hash: HashMap<Vec<u8>, Vec<usize>>,
    /// Lookup 取回的内表行。
    pub inner_rows: Vec<Row>,
    /// 每条外表行对应的匹配内表行（保序路径使用）。
    pub matched_inner_rows: Vec<Vec<Row>>,
    /// Inner worker 是否已处理完成。
    pub done: bool,
}

/// 外表 worker：按指数增长的 batch 切分外表行并构建哈希任务。
pub struct IndexHashJoinOuterWorker {
    rows: Vec<Row>,
    key_columns: Vec<usize>,
    cursor: usize,
    batch_size: usize,
}
impl IndexHashJoinOuterWorker {
    /// 构造 outer worker；`initial_batch_size` 必须为正。
    pub fn new(
        rows: Vec<Row>,
        key_columns: Vec<usize>,
        initial_batch_size: usize,
    ) -> Result<Self, String> {
        if initial_batch_size == 0 {
            return Err("initial batch size must be positive".into());
        }
        Ok(Self {
            rows,
            key_columns,
            cursor: 0,
            batch_size: initial_batch_size,
        })
    }
    /// 取出下一批外表行，跳过 NULL key，构建 outer_hash 与 lookup_contents。
    pub fn build_task(&mut self) -> Result<Option<IndexHashJoinTask>, String> {
        if self.cursor >= self.rows.len() {
            return Ok(None);
        }
        let end = (self.cursor + self.batch_size.min(MAX_ROWS_PER_FETCH)).min(self.rows.len());
        let rows = self.rows[self.cursor..end].to_vec();
        self.cursor = end;
        // batch 指数增长，但不超过 MAX_ROWS_PER_FETCH。
        self.batch_size = (self.batch_size * 2).min(MAX_ROWS_PER_FETCH);
        let mut task = IndexHashJoinTask {
            outer_rows: rows,
            ..IndexHashJoinTask::default()
        };
        for (index, row) in task.outer_rows.iter().enumerate() {
            let key = extract_key(row, &self.key_columns)?;
            // NULL key 不参与 lookup / 哈希探测。
            if key
                .iter()
                .any(|value| matches!(value, crate::row_table_builder::Value::Null))
            {
                continue;
            }
            task.outer_hash
                .entry(encode_key(&key))
                .or_default()
                .push(index);
            task.lookup_contents.push(IndexJoinLookupContent {
                keys: key,
                row: row.clone(),
                key_columns: Vec::new(),
                key_column_ids: Vec::new(),
            });
        }
        // 按 key 排序去重，减少重复索引范围请求。
        task.lookup_contents
            .sort_by(|left, right| crate::index_lookup_join::compare_row(&left.keys, &right.keys));
        task.lookup_contents
            .dedup_by(|left, right| left.keys == right.keys);
        Ok(Some(task))
    }
}

/// 内表 worker：按 lookup_contents 取内表行并回填匹配关系到 task。
pub struct IndexHashJoinInnerWorker<'a> {
    builder: &'a dyn IndexJoinExecutorBuilder,
    inner_key_columns: &'a [usize],
}
impl IndexHashJoinInnerWorker<'_> {
    /// 拉取内表行，按 outer_hash 把匹配内表行挂到对应外表下标。
    pub fn handle_task(&self, task: &mut IndexHashJoinTask) -> Result<(), String> {
        task.inner_rows = self.builder.build(&task.lookup_contents)?;
        task.matched_inner_rows = vec![Vec::new(); task.outer_rows.len()];
        for inner in &task.inner_rows {
            let key = extract_key(inner, self.inner_key_columns)?;
            if let Some(indices) = task.outer_hash.get(&encode_key(&key)) {
                for index in indices {
                    task.matched_inner_rows[*index].push(inner.clone());
                }
            }
        }
        task.done = true;
        Ok(())
    }
}

/// Index Nested Loop Hash Join 执行器主体。
pub struct IndexNestedLoopHashJoin {
    outer_worker: IndexHashJoinOuterWorker,
    builder: Box<dyn IndexJoinExecutorBuilder>,
    inner_key_columns: Vec<usize>,
    joiner: Joiner,
    /// 为 true 时按外表顺序 join；否则乱序探测以提升吞吐。
    keep_outer_order: bool,
    output: Vec<Row>,
    cursor: usize,
    opened: bool,
    closed: bool,
}

impl IndexNestedLoopHashJoin {
    /// 构造执行器；内外 key 列数必须一致。
    pub fn new(
        outer_rows: Vec<Row>,
        outer_key_columns: Vec<usize>,
        inner_key_columns: Vec<usize>,
        builder: Box<dyn IndexJoinExecutorBuilder>,
        joiner: Joiner,
        keep_outer_order: bool,
        initial_batch_size: usize,
    ) -> Result<Self, String> {
        if outer_key_columns.len() != inner_key_columns.len() {
            return Err("index hash join key count mismatch".into());
        }
        Ok(Self {
            outer_worker: IndexHashJoinOuterWorker::new(
                outer_rows,
                outer_key_columns,
                initial_batch_size,
            )?,
            builder,
            inner_key_columns,
            joiner,
            keep_outer_order,
            output: Vec::new(),
            cursor: 0,
            opened: false,
            closed: false,
        })
    }
    /// 仅乱序的 Inner/Outer/AntiSemi Join 支持增量 lookup，与 Go 门禁一致。
    pub fn support_incremental_lookup(&self) -> bool {
        !self.keep_outer_order
            && matches!(
                self.joiner.join_type(),
                JoinType::Inner | JoinType::LeftOuter | JoinType::RightOuter | JoinType::AntiSemi
            )
    }
    /// 打开执行器并重置输出游标。
    pub fn open(&mut self) -> Result<(), String> {
        if self.closed {
            return Err("cannot reopen closed index hash join".into());
        }
        self.output.clear();
        self.cursor = 0;
        self.opened = true;
        Ok(())
    }
    /// 消费全部 outer task：inner handle 后按保序/乱序路径写出结果。
    fn execute(&mut self) -> Result<(), String> {
        while let Some(mut task) = self.outer_worker.build_task()? {
            IndexHashJoinInnerWorker {
                builder: self.builder.as_ref(),
                inner_key_columns: &self.inner_key_columns,
            }
            .handle_task(&mut task)?;
            if self.keep_outer_order {
                self.join_in_order(task)?;
            } else {
                self.join_unordered(task)?;
            }
        }
        Ok(())
    }
    /// 保序：按外表行顺序匹配已挂好的内表行，未命中走 on_miss_match。
    fn join_in_order(&mut self, task: IndexHashJoinTask) -> Result<(), String> {
        for (outer, inners) in task.outer_rows.iter().zip(&task.matched_inner_rows) {
            let result = self.joiner.try_to_match_inners(
                outer,
                inners,
                &mut self.output,
                NaajType::Unknown,
            )?;
            if !result.matched {
                self.joiner
                    .on_miss_match(result.has_null, outer, &mut self.output);
            }
        }
        Ok(())
    }
    /// 乱序：以内表行为驱动探测 outer_hash，最后为未匹配外表补 miss 结果。
    fn join_unordered(&mut self, task: IndexHashJoinTask) -> Result<(), String> {
        let mut matched = vec![false; task.outer_rows.len()];
        let mut has_null = vec![false; task.outer_rows.len()];
        for inner in &task.inner_rows {
            let key = extract_key(inner, &self.inner_key_columns)?;
            if let Some(indices) = task.outer_hash.get(&encode_key(&key)) {
                for index in indices {
                    let result = self.joiner.try_to_match_inners(
                        &task.outer_rows[*index],
                        std::slice::from_ref(inner),
                        &mut self.output,
                        NaajType::Unknown,
                    )?;
                    matched[*index] |= result.matched;
                    has_null[*index] |= result.has_null;
                }
            }
        }
        for (index, outer) in task.outer_rows.iter().enumerate() {
            if !matched[index] {
                self.joiner
                    .on_miss_match(has_null[index], outer, &mut self.output);
            }
        }
        Ok(())
    }
    /// 惰性执行后按 required_rows 切分输出。
    pub fn next(&mut self, required_rows: usize) -> Result<IndexHashJoinResult, String> {
        if !self.opened {
            self.open()?;
        }
        if required_rows == 0 {
            return Ok(IndexHashJoinResult::default());
        }
        if self.output.is_empty() && self.cursor == 0 {
            self.execute()?;
        }
        if self.cursor >= self.output.len() {
            return Ok(IndexHashJoinResult::default());
        }
        let end = (self.cursor + required_rows).min(self.output.len());
        let rows = self.output[self.cursor..end].to_vec();
        self.cursor = end;
        Ok(IndexHashJoinResult { rows, error: None })
    }
    /// 关闭执行器并释放输出缓冲。
    pub fn close(&mut self) {
        self.output.clear();
        self.closed = true;
        self.opened = false;
    }
}
