[package]
name = "astersql-executor-test-simpletest"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[package.metadata.porting]
go-package = "pkg/executor/test/simpletest"
legacy-tasks = ["task-1358"]

[target.'cfg(any())'.dev-dependencies]
"astersql-config" = { package = "astersql-config", path = "../../../config" }
"astersql-config-deploymode" = { package = "astersql-config-deploymode", path = "../../../config/deploymode" }
"astersql-config-kerneltype" = { package = "astersql-config-kerneltype", path = "../../../config/kerneltype" }
"astersql-parser-ast" = { package = "astersql-parser-ast", path = "../../../parser/ast" }
"astersql-parser-auth" = { package = "astersql-parser-auth", path = "../../../parser/auth" }
"astersql-parser-mysql" = { package = "astersql-parser-mysql", path = "../../../parser/mysql" }
"astersql-parser-terror" = { package = "astersql-parser-terror", path = "../../../parser/terror" }
"astersql-server" = { package = "astersql-server", path = "../../../server" }
"astersql-session" = { package = "astersql-session", path = "../../../session" }
"astersql-sessionctx" = { package = "astersql-sessionctx", path = "../../../sessionctx" }
"astersql-statistics" = { package = "astersql-statistics", path = "../../../statistics" }
"astersql-store-mockstore" = { package = "astersql-store-mockstore", path = "../../../store/mockstore" }
"astersql-testkit" = { package = "astersql-testkit", path = "../../../testkit" }
"astersql-util-dbterror-exeerrors" = { package = "astersql-util-dbterror-exeerrors", path = "../../../util/dbterror/exeerrors" }
"astersql-util-globalconn" = { package = "astersql-util-globalconn", path = "../../../util/globalconn" }
