// Copyright 2026 AsterSQL.
// Copyright 2025 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Generates the Go copy-on-write helpers for the four logical operators used by
//! `shallow_ref_generator.go`.
//!
//! Go discovers fields through reflection and the `shallow-ref:"true"` tag.
//! Rust cannot reflect over Go types, so the same tagged field/type information
//! is represented explicitly below. The recursive emitter otherwise follows the
//! Go slice, struct, scalar and unsupported-kind branches.

/// Compatibility field kinds accepted by the metadata-driven public API.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum FieldKind {
    Value,
    Pointer,
    Slice,
    Map,
    Interface,
    ShallowRef,
    Embedded,
}

/// A field supplied to [`gen_shallow_ref_for_logical_ops`].
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Field {
    pub name: String,
    pub type_name: String,
    pub kind: FieldKind,
    /// Public callers use this flag to select fields, mirroring an exported Go
    /// field carrying `shallow-ref:"true"`.
    pub exported: bool,
}

/// One logical operator supplied to the metadata-driven public API.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LogicalOperator {
    pub name: String,
    pub fields: Vec<Field>,
}

#[derive(Clone, Debug)]
enum TypeSpec {
    Scalar,
    Slice {
        go_name: String,
        element: Box<TypeSpec>,
    },
    Struct {
        fields: Vec<StructFieldSpec>,
    },
    Unsupported(&'static str),
}

#[derive(Clone, Debug)]
struct StructFieldSpec {
    name: String,
    go_name: String,
    field_type: TypeSpec,
    exported: bool,
    shallow_ref: bool,
}

#[derive(Clone, Debug)]
struct OperatorSpec {
    name: String,
    fields: Vec<StructFieldSpec>,
}

const CODE_GEN_LOGICAL_OP_COW_PREFIX: &str = r#"// Copyright 2025 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by hash64_equals_generator; DO NOT EDIT IT DIRECTLY.

package logicalop

import (
	"github.com/pingcap/tidb/pkg/expression"
	"github.com/pingcap/tidb/pkg/expression/aggregation"
	"github.com/pingcap/tidb/pkg/planner/core/base"
	"github.com/pingcap/tidb/pkg/planner/util"
)
"#;

/// Generate complete, gofmt-shaped source for explicitly described operators.
pub fn gen_shallow_ref_for_logical_ops(operators: &[LogicalOperator]) -> Result<Vec<u8>, String> {
    let mut output = String::from(
        "// Copyright 2025 PingCAP, Inc.\n// Code generated by shallow_ref_generator; DO NOT EDIT.\n\npackage logicalop\n\n",
    );
    for operator in operators {
        validate_name(&operator.name)?;
        output.push_str(&format!(
            "func (p *{}) ShallowRef() *{} {{\n",
            operator.name, operator.name
        ));
        output.push_str("\tif p == nil { return nil }\n\tr := *p\n");
        for field in &operator.fields {
            validate_name(&field.name)?;
            if !field.exported {
                continue;
            }
            match field.kind {
                FieldKind::Slice => output.push_str(&format!(
                    "\tr.{0} = append([]{1}(nil), p.{0}...)\n",
                    field.name,
                    field.type_name.trim_start_matches("[]")
                )),
                FieldKind::Map => output.push_str(&format!(
                    "\tif p.{0} != nil {{ r.{0} = maps.Clone(p.{0}) }}\n",
                    field.name
                )),
                FieldKind::ShallowRef => {
                    output.push_str(&format!("\tr.{0} = p.{0}.ShallowRef()\n", field.name));
                }
                FieldKind::Value
                | FieldKind::Pointer
                | FieldKind::Interface
                | FieldKind::Embedded => {}
            }
        }
        output.push_str("\treturn &r\n}\n\n");
    }
    Ok(output.into_bytes())
}

fn generate(operators: &[OperatorSpec]) -> Result<Vec<u8>, String> {
    let mut output = String::from(CODE_GEN_LOGICAL_OP_COW_PREFIX);
    output.push('\n');
    for operator in operators {
        write_operator(&mut output, operator)?;
    }
    if !operators.is_empty() {
        output.pop();
    }
    Ok(output.into_bytes())
}

fn write_operator(output: &mut String, operator: &OperatorSpec) -> Result<(), String> {
    validate_name(&operator.name)?;
    let function_name = format!("{}ShallowRef", operator.name);
    line(
        output,
        0,
        &format!("// {function_name} implements the copy-on-write usage."),
    );
    line(
        output,
        0,
        &format!(
            "func (op *{}) {function_name}() *{} {{",
            operator.name, operator.name
        ),
    );
    line(output, 1, "shallow := *op");
    line(output, 1, "return &shallow");
    line(output, 0, "}");
    output.push('\n');

    for field in &operator.fields {
        if is_shallow_ref_field(field) {
            write_field_method(output, operator, field)?;
        }
    }
    Ok(())
}

fn write_field_method(
    output: &mut String,
    operator: &OperatorSpec,
    field: &StructFieldSpec,
) -> Result<(), String> {
    validate_name(&field.name)?;
    let function_name = format!("{}ShallowRef", field.name);
    line(
        output,
        0,
        &format!("// {function_name} implements the copy-on-write usage."),
    );
    line(
        output,
        0,
        &format!(
            "func (op *{}) {function_name}() {} {{",
            operator.name, field.go_name
        ),
    );
    write_shallow_ref_element(output, &field.field_type, "op.", &field.name, 1)?;
    line(output, 1, &format!("return op.{}", field.name));
    line(output, 0, "}");
    output.push('\n');
    Ok(())
}

fn write_shallow_ref_element(
    output: &mut String,
    field_type: &TypeSpec,
    caller: &str,
    field_name: &str,
    indent: usize,
) -> Result<Option<String>, String> {
    match field_type {
        TypeSpec::Scalar => Ok(None),
        TypeSpec::Slice { go_name, element } => {
            let temporary = format!("{field_name}CP");
            line(
                output,
                indent,
                &format!("{temporary} := make({go_name}, 0, len({caller}{field_name}))"),
            );
            let item_name = if field_name.starts_with("one") {
                format!("{field_name}e")
            } else {
                "one".to_owned()
            };
            line(
                output,
                indent,
                &format!("for _, {item_name} := range {caller}{field_name} {{"),
            );
            let nested = write_shallow_ref_element(output, element, "", &item_name, indent + 1)?;
            let result = nested.as_deref().unwrap_or(&item_name);
            line(
                output,
                indent + 1,
                &format!("{temporary} = append({temporary}, {result})"),
            );
            line(output, indent, "}");
            if field_name.starts_with("one") {
                return Ok(Some(temporary));
            }
            line(
                output,
                indent,
                &format!("{caller}{field_name} = {temporary}"),
            );
            Ok(None)
        }
        TypeSpec::Struct { fields } => {
            let temporary = format!("{field_name}CP");
            line(
                output,
                indent,
                &format!("{temporary} := {caller}{field_name}"),
            );
            for field in fields.iter().filter(|field| field.exported) {
                write_shallow_ref_element(
                    output,
                    &field.field_type,
                    &format!("{temporary}."),
                    &field.name,
                    indent,
                )?;
            }
            if !field_name.starts_with("one") {
                line(
                    output,
                    indent,
                    &format!("{caller}{field_name} = {temporary}"),
                );
            }
            Ok(Some(temporary))
        }
        TypeSpec::Unsupported(kind) => Err(format!("doesn't support element type{kind}")),
    }
}

fn is_shallow_ref_field(field: &StructFieldSpec) -> bool {
    field.shallow_ref
}

fn line(output: &mut String, indent: usize, text: &str) {
    for _ in 0..indent {
        output.push('\t');
    }
    output.push_str(text);
    output.push('\n');
}

fn field(name: &str, go_name: &str, field_type: TypeSpec) -> StructFieldSpec {
    StructFieldSpec {
        name: name.to_owned(),
        go_name: go_name.to_owned(),
        field_type,
        exported: true,
        shallow_ref: true,
    }
}

fn scalar() -> TypeSpec {
    TypeSpec::Scalar
}

fn slice(go_name: &str, element: TypeSpec) -> TypeSpec {
    TypeSpec::Slice {
        go_name: go_name.to_owned(),
        element: Box::new(element),
    }
}

fn operator(name: &str, fields: Vec<StructFieldSpec>) -> OperatorSpec {
    OperatorSpec {
        name: name.to_owned(),
        fields,
    }
}

fn logical_operator_specs() -> Vec<OperatorSpec> {
    vec![
        operator(
            "LogicalJoin",
            vec![
                field(
                    "EqualConditions",
                    "[]*expression.ScalarFunction",
                    slice("[]*expression.ScalarFunction", scalar()),
                ),
                field(
                    "NAEQConditions",
                    "[]*expression.ScalarFunction",
                    slice("[]*expression.ScalarFunction", scalar()),
                ),
                field(
                    "LeftConditions",
                    "expression.CNFExprs",
                    slice("expression.CNFExprs", scalar()),
                ),
                field(
                    "RightConditions",
                    "expression.CNFExprs",
                    slice("expression.CNFExprs", scalar()),
                ),
                field(
                    "OtherConditions",
                    "expression.CNFExprs",
                    slice("expression.CNFExprs", scalar()),
                ),
            ],
        ),
        operator(
            "LogicalProjection",
            vec![field(
                "Exprs",
                "[]expression.Expression",
                slice("[]expression.Expression", scalar()),
            )],
        ),
        operator(
            "LogicalAggregation",
            vec![
                field(
                    "AggFuncs",
                    "[]*aggregation.AggFuncDesc",
                    slice("[]*aggregation.AggFuncDesc", scalar()),
                ),
                field(
                    "GroupByItems",
                    "[]expression.Expression",
                    slice("[]expression.Expression", scalar()),
                ),
                field(
                    "PossibleProperties",
                    "base.PossiblePropertiesInfo",
                    TypeSpec::Struct {
                        fields: vec![
                            field(
                                "Orders",
                                "[][]*expression.Column",
                                slice(
                                    "[][]*expression.Column",
                                    slice("[]*expression.Column", scalar()),
                                ),
                            ),
                            field("HasTiFlash", "bool", scalar()),
                        ],
                    },
                ),
            ],
        ),
        operator(
            "LogicalSort",
            vec![field(
                "ByItems",
                "[]*util.ByItems",
                slice("[]*util.ByItems", scalar()),
            )],
        ),
    ]
}

/// Go `refineFieldTypeName` removes only the `logicalop.` package prefix.
pub fn refine_field_type_name(name: &str) -> String {
    name.strip_prefix("logicalop.").unwrap_or(name).to_owned()
}

/// Logical operators covered by Go `GenShallowRef4LogicalOps`.
pub const SHALLOW_REF_STRUCTURES: &[&str] = &[
    "LogicalJoin",
    "LogicalProjection",
    "LogicalAggregation",
    "LogicalSort",
];

/// Generate the same source as Go `GenShallowRef4LogicalOps` for its fixed
/// `LogicalJoin`, `LogicalProjection`, `LogicalAggregation` and `LogicalSort`
/// catalog.
#[allow(non_snake_case)]
pub fn GenShallowRef4LogicalOps() -> Result<Vec<u8>, String> {
    generate(&logical_operator_specs())
}

fn validate_name(name: &str) -> Result<(), String> {
    if name.is_empty()
        || !name.chars().enumerate().all(|(index, character)| {
            character == '_'
                || character.is_ascii_alphabetic()
                || (index > 0 && character.is_ascii_digit())
        })
    {
        Err(format!("invalid Go identifier {name}"))
    } else {
        Ok(())
    }
}
