[package]
name = "astersql-br-pkg-stream-crr-config"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[package.metadata.porting]
go-package = "br/pkg/stream/crr/config"
legacy-tasks = []
kind = "library"
lane = 0

[dependencies]
"astersql-br-pkg-stream-crr-internal-checkpoint" = { package = "astersql-br-pkg-stream-crr-internal-checkpoint", path = "../internal/checkpoint" }
"astersql-br-pkg-stream-crr-service" = { package = "astersql-br-pkg-stream-crr-service", path = "../service" }
