// Copyright 2026 AsterSQL.
// Copyright 2025 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// `KSRuntimeHandle` 的 mockall 桩（对齐 Go MockGen 产物）。
//
// Go 中 KSRuntimeHandle 嵌入 Runtime；此处在同一 mock 上实现 Runtime 与
// KSRuntimeHandle，使 Store/SysSessionPool/AlterTableMode/Release 共享期望集合。

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pingcap/tidb/pkg/domain/sqlsvrapi (interfaces: KSRuntimeHandle)

use std::sync::Arc;

use crate::domain::sqlsvrapi::{
    Context, KSRuntimeHandle as KSRuntimeHandleTrait, Runtime as RuntimeTrait, SqlSvrError,
};
use crate::kv::Storage;
use crate::meta::model::AlterTableModeTarget;
use crate::util::DestroyableSessionPool;

// 中文补充：同一 mock 同时实现 Runtime 与 KSRuntimeHandle。
// KSRuntimeHandle embeds Runtime in Go. Keep both trait implementations on the
// same mock so runtime access and Release share one verified expectation set.
mockall::mock! {
    pub KSRuntimeHandle {}

    impl RuntimeTrait for KSRuntimeHandle {
        fn Store(&self) -> Arc<dyn Storage + Send + Sync>;
        fn SysSessionPool(&self) -> Arc<dyn DestroyableSessionPool>;
        fn AlterTableMode(
            &self,
            ctx: Context,
            target: AlterTableModeTarget,
        ) -> Result<(), SqlSvrError>;
    }

    impl KSRuntimeHandleTrait for KSRuntimeHandle {
        fn Release(&self);
    }
}

impl MockKSRuntimeHandle {
    /// 保留 GoMock 接口检查用的生成标记。
    /// Retains the generated GoMock marker used by interface checks.
    pub fn ISGOMOCK(&self) {}

    /// 返回 recorder；用 `expect_*` 配置调用期望。
    /// Returns the mock as its recorder; configure calls with `expect_*`.
    pub fn EXPECT(&mut self) -> &mut Self {
        self
    }
}

/// 创建空期望集的 keyspace Runtime handle mock。
/// Creates a keyspace Runtime handle mock with an empty expectation set.
pub fn NewMockKSRuntimeHandle<C: ?Sized>(_ctrl: &C) -> MockKSRuntimeHandle {
    MockKSRuntimeHandle::new()
}
