// Copyright 2026 AsterSQL.
// Copyright 2025 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// `Runtime` 的 mockall 桩（对齐 Go MockGen 产物）。
//
// 用 mockall 期望引擎替代 GoMock controller/recorder：`expect_*` 记录参数、
// 次数与返回值，生成的 Runtime 实现将每次调用分派到期望引擎。

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pingcap/tidb/pkg/domain/sqlsvrapi (interfaces: Runtime)

use std::sync::Arc;

use crate::domain::sqlsvrapi::{Context, Runtime as RuntimeTrait, SqlSvrError};
use crate::kv::Storage;
use crate::meta::model::AlterTableModeTarget;
use crate::util::DestroyableSessionPool;

// 中文补充：expect_* 记录参数/次数/返回，调用时由期望引擎分派。
// GoMock's controller/recorder pair is represented by mockall's expectation
// engine. Each expect_* method records argument, count, and return behavior;
// the generated Runtime implementation dispatches every call through it.
mockall::mock! {
    pub Runtime {}

    impl RuntimeTrait for Runtime {
        fn Store(&self) -> Arc<dyn Storage + Send + Sync>;
        fn SysSessionPool(&self) -> Arc<dyn DestroyableSessionPool>;
        fn AlterTableMode(
            &self,
            ctx: Context,
            target: AlterTableModeTarget,
        ) -> Result<(), SqlSvrError>;
    }
}

impl MockRuntime {
    /// 保留 GoMock 接口检查用的生成标记。
    /// Retains the generated GoMock marker used by interface checks.
    pub fn ISGOMOCK(&self) {}

    /// 返回 recorder；用 `expect_*` 配置调用期望。
    /// Returns the mock as its recorder; configure calls with `expect_*`.
    pub fn EXPECT(&mut self) -> &mut Self {
        self
    }
}

/// 创建空期望集的 Runtime mock。
///
/// 保留 Go 构造函数形态的 controller 参数；mockall 在 checkpoint/drop 时独立校验。
/// Creates a Runtime mock with an empty expectation set.
///
/// The controller argument preserves the generated Go constructor shape.
/// mockall verifies each instance independently on checkpoint or drop.
pub fn NewMockRuntime<C: ?Sized>(_ctrl: &C) -> MockRuntime {
    MockRuntime::new()
}
