// Copyright 2026 AsterSQL.
// Copyright 2025 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// SQL Server 接口的 mock 实现（由 MockGen/mockall 风格生成）。
//
// 对应 Go 的 `sqlsvrapi.Server` 可测替身：可配置 `GetRuntime`、
// `AcquireKSRuntime`（跨 keyspace 获取运行时句柄）、`GetDDLOwnerMgr`
// （DDL Owner 管理器，负责选主与 DDL 调度）的期望与返回值。

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pingcap/tidb/pkg/domain/sqlsvrapi (interfaces: Server)

use std::sync::Arc;

use crate::domain::sqlsvrapi::{KSRuntimeHandle, Runtime, Server as ServerTrait, SqlSvrError};
use crate::owner::Manager;

// mockall supplies the same observable contract as the generated GoMock:
// argument matching, ordered call counts, configured return values, and
// verification when checkpoint is called or the mock is dropped.
// 用 mockall 生成与 GoMock 同契约的 Server mock：参数匹配、调用次序、返回值与 drop 校验。
mockall::mock! {
    pub Server {}

    impl ServerTrait for Server {
        fn GetRuntime(&self) -> Arc<dyn Runtime>;
        fn AcquireKSRuntime(
            &self,
            targetKS: String,
            holderID: String,
        ) -> Result<Arc<dyn KSRuntimeHandle>, SqlSvrError>;
        fn GetDDLOwnerMgr(&self) -> Arc<dyn Manager>;
    }
}

/// `MockServer` 上的 GoMock 兼容辅助方法。
impl MockServer {
    /// 保留 GoMock 标记方法，供接口类型检查识别这是 mock。
    /// Retains the generated GoMock marker used by interface checks.
    pub fn ISGOMOCK(&self) {}

    /// 返回录音器自身；通过 `expect_*` 配置期望调用。
    /// Returns the mock as its recorder; configure calls with `expect_*`.
    pub fn EXPECT(&mut self) -> &mut Self {
        self
    }
}

/// 创建空期望集合的 Server mock（`_ctrl` 对齐 Go 的 gomock.Controller，此处未使用）。
/// Creates a Server mock with an empty expectation set.
pub fn NewMockServer<C: ?Sized>(_ctrl: &C) -> MockServer {
    MockServer::new()
}
