[package]
name = "astersql-ddl-testutil"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[package.metadata.porting]
go-package = "pkg/ddl/testutil"
legacy-tasks = ["task-1270"]

[dependencies]
"astersql-ddl" = { package = "astersql-ddl", path = ".." }
"astersql-ddl-logutil" = { package = "astersql-ddl-logutil", path = "../logutil" }
"astersql-domain" = { package = "astersql-domain", path = "../../domain" }
"astersql-dxf-operator" = { package = "astersql-dxf-operator", path = "../../dxf/operator" }
"astersql-kv" = { package = "astersql-kv", path = "../../kv" }
"astersql-meta" = { package = "astersql-meta", path = "../../meta" }
"astersql-meta-model" = { package = "astersql-meta-model", path = "../../meta/model" }
"astersql-parser-ast" = { package = "astersql-parser-ast", path = "../../parser/ast" }
"astersql-session" = { package = "astersql-session", path = "../../session" }
"astersql-session-sessionapi" = { package = "astersql-session-sessionapi", path = "../../session/sessionapi" }
"astersql-sessionctx" = { package = "astersql-sessionctx", path = "../../sessionctx" }
"astersql-sessiontxn" = { package = "astersql-sessiontxn", path = "../../sessiontxn" }
"astersql-table" = { package = "astersql-table", path = "../../table" }
"astersql-table-tables" = { package = "astersql-table-tables", path = "../../table/tables" }
"astersql-types" = { package = "astersql-types", path = "../../types" }
