// Copyright 2026 AsterSQL.
// Copyright 2016 PingCAP, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// 词法辅助：字符分类、运算符规则树（trie）与关键字/Hint token 映射表。
//
// `ruleTable` 按字节最长匹配分派到 `lexer.rs` 中的扫描函数；
// `isTokenIdentifier` 在标识符路径上查普通关键字、内建函数与窗口函数表。

// 在内存中识别 SQL token。
use std::sync::LazyLock as MiscLazyLock;

// ASCII 字母、数字与非 ASCII 扩展字节的分类规则和 Go 完全一致。
/// 判断 ASCII 字母。
pub fn isLetter(ch: u8) -> bool {
    ch.is_ascii_alphabetic()
}
/// 判断 ASCII 数字。
pub fn isDigit(ch: u8) -> bool {
    ch.is_ascii_digit()
}
/// 标识符允许的字节（含 `$`/`_`/扩展）。
pub fn isIdentChar(ch: u8) -> bool {
    isLetter(ch) || isDigit(ch) || ch == b'_' || ch == b'$' || isIdentExtend(ch)
}
/// 非 ASCII 扩展标识符字节。
pub fn isIdentExtend(ch: u8) -> bool {
    ch >= 0x80
}

// isInCorrectIdentifierName 保留原函数的反向命名语义：空名称或尾随空格返回 true。
/// 非法标识符名（空或尾随空格）；保留 Go 反向命名。
pub fn isInCorrectIdentifierName(name: &str) -> bool {
    name.is_empty() || name.as_bytes().last() == Some(&b' ')
}

// Go 在 init 中填充 256 项查表；Rust 用同一谓词表达，避免每次初始化可变全局状态。
/// 用户变量名允许的字符（含 `.`）。
pub fn isUserVarChar(ch: u8) -> bool {
    isLetter(ch) || isDigit(ch) || ch == b'_' || ch == b'$' || ch == b'.' || isIdentExtend(ch)
}

// trieNode 对应单字节 token trie；function 保存 lexer.rs 中的分支扫描函数。
/// 单字节 token trie 节点，可挂接扫描函数。
pub struct trieNode {
    pub childs: Vec<Option<Box<trieNode>>>,
    pub token: i32,
    pub function: Option<fn(&mut Scanner) -> (i32, Pos, String)>,
}
impl trieNode {
    /// 构造 256 子槽的空节点。
    fn new() -> Self {
        Self {
            childs: (0..256).map(|_| None).collect(),
            token: 0,
            function: None,
        }
    }
}

// initTokenByte/String/Func 对应 Go 初始化辅助函数；调用方传入局部 root 后再发布为 ruleTable。
/// 注册单字节 token。
fn initTokenByte(root: &mut trieNode, c: u8, tok: i32) {
    let node = root.childs[c as usize].get_or_insert_with(|| Box::new(trieNode::new()));
    node.token = tok;
}
/// 沿字符串路径注册多字节运算符 token。
fn initTokenString(root: &mut trieNode, text: &str, tok: i32) {
    let mut node = root;
    for c in text.bytes() {
        node = node.childs[c as usize].get_or_insert_with(|| Box::new(trieNode::new()));
    }
    node.token = tok;
}
/// 为 text 中每个首字节挂接扫描函数（Go 语义）。
fn initTokenFunc(
    root: &mut trieNode,
    text: &str,
    scanner_fn: fn(&mut Scanner) -> (i32, Pos, String),
) {
    // Go 对 text 的每个字节都从 root 挂函数，而不是构造多级路径。
    for c in text.bytes() {
        let node = root.childs[c as usize].get_or_insert_with(|| Box::new(trieNode::new()));
        node.function = Some(scanner_fn);
    }
}

// buildRuleTable 保留两个 Go init 的效果：默认 invalid、固定符号、复合运算符及分派函数。
/// 构建完整运算符/分派规则树。
pub fn buildRuleTable() -> trieNode {
    let mut root = trieNode::new();
    root.token = invalid;
    for (c, tok) in [
        (b'/', b'/' as i32),
        (b'+', b'+' as i32),
        (b'>', b'>' as i32),
        (b'<', b'<' as i32),
        (b'(', b'(' as i32),
        (b')', b')' as i32),
        (b'[', b'[' as i32),
        (b']', b']' as i32),
        (b';', b';' as i32),
        (b',', b',' as i32),
        (b'&', b'&' as i32),
        (b'%', b'%' as i32),
        (b':', b':' as i32),
        (b'|', b'|' as i32),
        (b'!', b'!' as i32),
        (b'^', b'^' as i32),
        (b'~', b'~' as i32),
        (b'\\', b'\\' as i32),
        (b'?', token::paramMarker),
        (b'=', token::eq),
        (b'{', b'{' as i32),
        (b'}', b'}' as i32),
    ] {
        initTokenByte(&mut root, c, tok);
    }
    for (text, tok) in [
        ("||", token::pipes),
        ("&&", token::andand),
        ("&^", token::andnot),
        (":=", token::assignmentEq),
        ("<=>", token::nulleq),
        (">=", token::ge),
        ("<=", token::le),
        ("!=", token::neq),
        ("<>", token::neqSynonym),
        ("<<", token::lsh),
        (">>", token::rsh),
        ("\\N", token::null),
    ] {
        initTokenString(&mut root, text, tok);
    }
    for (text, scanner_fn) in [
        ("@", startWithAt as fn(&mut Scanner) -> _),
        ("/", startWithSlash),
        ("*", startWithStar),
        ("-", startWithDash),
        ("#", startWithSharp),
        ("Xx", startWithXx),
        ("Nn", startWithNn),
        ("Bb", startWithBb),
        (".", startWithDot),
        (
            "_$ACDEFGHIJKLMOPQRSTUVWYZacdefghijklmopqrstuvwyz",
            scanIdentifier,
        ),
        ("`", scanQuotedIdent),
        ("0123456789", startWithNumber),
        ("'\"", startString),
    ] {
        initTokenFunc(&mut root, text, scanner_fn);
    }
    root
}

// ruleTable 对应 Go 包级 trie；LazyLock 保证首次扫描前只初始化一次。
/// 包级懒初始化规则树。
pub static ruleTable: MiscLazyLock<trieNode> = MiscLazyLock::new(buildRuleTable);

/// 在 (名称, token) 表中精确查找。
fn lookup_token(map: &[(&str, i32)], target_name: &str) -> i32 {
    map.iter()
        .find_map(|(name, tok)| (*name == target_name).then_some(*tok))
        .unwrap_or(0)
}

// isInTokenMap 判断规范化后的标识符是否属于 parser 已知关键字。
/// 是否为已知关键字。
pub fn isInTokenMap(target_name: &str) -> bool {
    lookup_token(tokenMap, target_name) != 0
}

// TOKEN_MAP 保持 Go tokenMap 的键和值及原有顺序，便于与 parser.y 人工核对。
/// 普通 SQL 关键字 → token 映射（顺序对齐 Go）。
pub static tokenMap: &[(&str, i32)] = &[
    ("ACCOUNT", token::account),
    ("ACTION", token::action),
    ("ADD", token::add),
    ("ADDDATE", token::addDate),
    (
        "ADD_COLUMNAR_REPLICA_ON_DEMAND",
        token::addColumnarReplicaOnDemand,
    ),
    ("ADMIN", token::admin),
    ("ADVISE", token::advise),
    ("AFFINITY", token::affinity),
    ("AFTER", token::after),
    ("AGAINST", token::against),
    ("AGO", token::ago),
    ("ALGORITHM", token::algorithm),
    ("ALL", token::all),
    ("ALTER", token::alter),
    ("ALWAYS", token::always),
    ("ANALYZE", token::analyze),
    ("AND", token::and),
    ("ANY", token::any),
    ("APPROX_COUNT_DISTINCT", token::approxCountDistinct),
    ("APPROX_PERCENTILE", token::approxPercentile),
    ("ARRAY", token::array),
    ("AS", token::r#as),
    ("ASC", token::asc),
    ("ASCII", token::ascii),
    ("APPLY", token::apply),
    ("ATTRIBUTE", token::attribute),
    ("ATTRIBUTES", token::attributes),
    ("BATCH", token::batch),
    ("BACKGROUND", token::background),
    ("STATS_OPTIONS", token::statsOptions),
    ("STATS_SAMPLE_RATE", token::statsSampleRate),
    ("STATS_COL_CHOICE", token::statsColChoice),
    ("STATS_COL_LIST", token::statsColList),
    ("AUTO_ID_CACHE", token::autoIdCache),
    ("AUTO_INCREMENT", token::autoIncrement),
    ("AUTO_RANDOM", token::autoRandom),
    ("AUTO_RANDOM_BASE", token::autoRandomBase),
    ("AUTOEXTEND_SIZE", token::autoextendSize),
    ("AVG_ROW_LENGTH", token::avgRowLength),
    ("AVG", token::avg),
    ("BACKEND", token::backend),
    ("BACKUP", token::backup),
    ("BACKUPS", token::backups),
    ("BDR", token::bdr),
    ("BEGIN", token::begin),
    ("BETWEEN", token::between),
    ("BERNOULLI", token::bernoulli),
    ("BIGINT", token::bigIntType),
    ("BINARY", token::binaryType),
    ("BINDING", token::binding),
    ("BINDING_CACHE", token::bindingCache),
    ("BINDINGS", token::bindings),
    ("BINLOG", token::binlog),
    ("BIT_AND", token::bitAnd),
    ("BIT_OR", token::bitOr),
    ("BIT_XOR", token::bitXor),
    ("BIT", token::bitType),
    ("BLOB", token::blobType),
    ("BLOCK", token::block),
    ("BOOL", token::boolType),
    ("BOOLEAN", token::booleanType),
    ("BOTH", token::both),
    ("BOUND", token::bound),
    ("BR", token::br),
    ("BRIEF", token::briefType),
    ("BTREE", token::btree),
    ("BUCKETS", token::buckets),
    ("BUILTINS", token::builtins),
    ("BURSTABLE", token::burstable),
    ("BY", token::by),
    ("BYTE", token::byteType),
    ("CACHE", token::cache),
    ("CALIBRATE", token::calibrate),
    ("CALL", token::call),
    ("CANCEL", token::cancel),
    ("CAPTURE", token::capture),
    ("CARDINALITY", token::cardinality),
    ("CASCADE", token::cascade),
    ("CASCADED", token::cascaded),
    ("CASE", token::caseKwd),
    ("CAST", token::cast),
    ("CAUSAL", token::causal),
    ("CHAIN", token::chain),
    ("CHANGE", token::change),
    ("CHAR", token::charType),
    ("CHARACTER", token::character),
    ("CHARSET", token::charsetKwd),
    ("CHECK", token::check),
    ("CHECKPOINT", token::checkpoint),
    ("CHECKSUM", token::checksum),
    ("CIPHER", token::cipher),
    ("CLEANUP", token::cleanup),
    ("CLIENT", token::client),
    ("CLIENT_ERRORS_SUMMARY", token::clientErrorsSummary),
    ("CLOSE", token::close),
    ("CLUSTER", token::cluster),
    ("CLUSTERED", token::clustered),
    ("CMSKETCH", token::cmSketch),
    ("COALESCE", token::coalesce),
    ("COLLATE", token::collate),
    ("COLLATION", token::collation),
    ("COLUMN_FORMAT", token::columnFormat),
    ("COLUMN_STATS_USAGE", token::columnStatsUsage),
    ("COLUMN", token::column),
    ("COLUMNAR", token::columnar),
    ("COLUMNS", token::columns),
    ("COMMENT", token::comment),
    ("COMMIT", token::commit),
    ("COMMITTED", token::committed),
    ("COMPACT", token::compact),
    ("COMPRESS", token::compress),
    ("COMPRESSED", token::compressed),
    ("COMPRESSION", token::compression),
    ("CONCURRENCY", token::concurrency),
    ("CONFIG", token::config),
    ("CONNECTION", token::connection),
    ("CONSISTENCY", token::consistency),
    ("CONSISTENT", token::consistent),
    ("CONSTRAINT", token::constraint),
    ("CONSTRAINTS", token::constraints),
    ("CONTEXT", token::context),
    ("CONTINUE", token::continueKwd),
    ("CONVERT", token::convert),
    ("COOLDOWN", token::cooldown),
    ("COPY", token::copyKwd),
    ("CORRELATION", token::correlation),
    ("CPU", token::cpu),
    ("CREATE", token::create),
    ("CROSS", token::cross),
    ("CSV_BACKSLASH_ESCAPE", token::csvBackslashEscape),
    ("CSV_DELIMITER", token::csvDelimiter),
    ("CSV_HEADER", token::csvHeader),
    ("CSV_NOT_NULL", token::csvNotNull),
    ("CSV_NULL", token::csvNull),
    ("CSV_SEPARATOR", token::csvSeparator),
    ("CSV_TRIM_LAST_SEPARATORS", token::csvTrimLastSeparators),
    ("WAIT_TIFLASH_READY", token::waitTiflashReady),
    ("WITH_SYS_TABLE", token::withSysTable),
    ("IGNORE_STATS", token::ignoreStats),
    ("LOAD_STATS", token::loadStats),
    ("CHECKSUM_CONCURRENCY", token::checksumConcurrency),
    ("COMPRESSION_LEVEL", token::compressionLevel),
    ("COMPRESSION_TYPE", token::compressionType),
    ("ENCRYPTION_METHOD", token::encryptionMethod),
    ("ENCRYPTION_KEYFILE", token::encryptionKeyFile),
    ("CURDATE", token::curDate),
    ("CURRENT_DATE", token::currentDate),
    ("CURRENT_ROLE", token::currentRole),
    ("CURRENT_TIME", token::currentTime),
    ("CURRENT_TIMESTAMP", token::currentTs),
    ("CURRENT_USER", token::currentUser),
    ("CURRENT", token::current),
    ("CURSOR", token::cursor),
    ("CURTIME", token::curTime),
    ("CYCLE", token::cycle),
    ("DATA", token::data),
    ("DATABASE", token::database),
    ("DATABASES", token::databases),
    ("DATE_ADD", token::dateAdd),
    ("DATE_SUB", token::dateSub),
    ("DATE", token::dateType),
    ("DATETIME", token::datetimeType),
    ("DAY_HOUR", token::dayHour),
    ("DAY_MICROSECOND", token::dayMicrosecond),
    ("DAY_MINUTE", token::dayMinute),
    ("DAY_SECOND", token::daySecond),
    ("DAY", token::day),
    ("DDL", token::ddl),
    ("DEALLOCATE", token::deallocate),
    ("DEC", token::decimalType),
    ("DECIMAL", token::decimalType),
    ("DECLARE", token::declare),
    ("DEFAULT", token::defaultKwd),
    ("DEFINED", token::defined),
    ("DEFINER", token::definer),
    ("DELAY_KEY_WRITE", token::delayKeyWrite),
    ("DELAYED", token::delayed),
    ("DELETE", token::deleteKwd),
    ("DEPENDENCY", token::dependency),
    ("DEPTH", token::depth),
    ("DESC", token::desc),
    ("DESCRIBE", token::describe),
    ("DIGEST", token::digest),
    ("DIRECTORY", token::directory),
    ("DISABLE", token::disable),
    ("DISABLED", token::disabled),
    ("DISCARD", token::discard),
    ("DISK", token::disk),
    ("DISTINCT", token::distinct),
    ("DISTINCTROW", token::distinct),
    ("DISTRIBUTE", token::distribute),
    ("DISTRIBUTION", token::distribution),
    ("DISTRIBUTIONS", token::distributions),
    ("DIV", token::div),
    ("DO", token::r#do),
    ("DOT", token::dotType),
    ("DOUBLE", token::doubleType),
    ("DROP", token::drop),
    ("DRY", token::dry),
    ("DRYRUN", token::dryRun),
    ("DUAL", token::dual),
    ("DUMP", token::dump),
    ("DUPLICATE", token::duplicate),
    ("DURATION", token::timeDuration),
    ("DYNAMIC", token::dynamic),
    ("ELSE", token::elseKwd),
    ("ELSEIF", token::elseIfKwd),
    ("ENABLE", token::enable),
    ("ENABLED", token::enabled),
    ("ENCLOSED", token::enclosed),
    ("ENCRYPTION", token::encryption),
    ("END", token::end),
    ("END_TIME", token::endTime),
    ("ENFORCED", token::enforced),
    ("ENGINE", token::engine),
    ("ENGINES", token::engines),
    ("ENGINE_ATTRIBUTE", token::engine_attribute),
    (
        "SECONDARY_ENGINE_ATTRIBUTE",
        token::secondaryEngineAttribute,
    ),
    ("ENUM", token::r#enum),
    ("ERROR", token::errorKwd),
    ("ERRORS", token::identSQLErrors),
    ("ESCAPE", token::escape),
    ("ESCAPED", token::escaped),
    ("EVENT", token::event),
    ("EVENTS", token::events),
    ("EVOLVE", token::evolve),
    ("EXACT", token::exact),
    ("EXEC_ELAPSED", token::execElapsed),
    ("EXCEPT", token::except),
    ("EXCHANGE", token::exchange),
    ("EXCLUSIVE", token::exclusive),
    ("EXECUTE", token::execute),
    ("EXISTS", token::exists),
    ("EXIT", token::exit),
    ("EXPANSION", token::expansion),
    ("EXPIRE", token::expire),
    ("EXPLAIN", token::explain),
    ("EXPR_PUSHDOWN_BLACKLIST", token::exprPushdownBlacklist),
    ("EXTENDED", token::extended),
    ("EXPLORE", token::explore),
    ("EXTRACT", token::extract),
    ("FALSE", token::falseKwd),
    ("FAULTS", token::faultsSym),
    ("FETCH", token::fetch),
    ("FIELDS", token::fields),
    ("FILE", token::file),
    ("FIRST", token::first),
    ("FIXED", token::fixed),
    ("FLASHBACK", token::flashback),
    ("FLOAT", token::floatType),
    ("FLOAT4", token::float4Type),
    ("FLOAT8", token::float8Type),
    ("FLUSH", token::flush),
    ("FOLLOWER", token::follower),
    ("FOLLOWERS", token::followers),
    ("FOLLOWER_CONSTRAINTS", token::followerConstraints),
    ("FOLLOWING", token::following),
    ("FOR", token::forKwd),
    ("FORCE", token::force),
    ("FOREIGN", token::foreign),
    ("FORMAT", token::format),
    ("FOUND", token::found),
    ("FROM", token::from),
    ("FULL", token::full),
    ("FULL_BACKUP_STORAGE", token::fullBackupStorage),
    ("FULLTEXT", token::fulltext),
    ("FUNCTION", token::function),
    ("GC_TTL", token::gcTTL),
    ("GENERAL", token::general),
    ("GENERATED", token::generated),
    ("GET_FORMAT", token::getFormat),
    ("GLOBAL", token::global),
    ("GRANT", token::grant),
    ("GRANTS", token::grants),
    ("GROUP_CONCAT", token::groupConcat),
    ("GROUP", token::group),
    ("HASH", token::hash),
    ("HANDLER", token::handler),
    ("HAVING", token::having),
    ("HELP", token::help),
    ("HIGH_PRIORITY", token::highPriority),
    ("HISTORY", token::history),
    ("HISTOGRAM", token::histogram),
    ("HNSW", token::hnsw),
    ("HOSTS", token::hosts),
    ("HOUR_MICROSECOND", token::hourMicrosecond),
    ("HOUR_MINUTE", token::hourMinute),
    ("HOUR_SECOND", token::hourSecond),
    ("HOUR", token::hour),
    ("IDENTIFIED", token::identified),
    ("IETF_QUOTES", token::ietfQuotes),
    ("IF", token::ifKwd),
    ("IGNORE", token::ignore),
    ("ILIKE", token::ilike),
    ("IMPORT", token::importKwd),
    ("IMPORTS", token::imports),
    ("IN", token::r#in),
    ("INCREMENT", token::increment),
    ("INCREMENTAL", token::incremental),
    ("INDEX", token::index),
    ("INDEXES", token::indexes),
    ("INFILE", token::infile),
    ("INNER", token::inner),
    ("INOUT", token::inout),
    ("INPLACE", token::inplace),
    ("INSERT_METHOD", token::insertMethod),
    ("INSERT", token::insert),
    ("INSTANCE", token::instance),
    ("INSTANT", token::instant),
    ("INT", token::intType),
    ("INT1", token::int1Type),
    ("INT2", token::int2Type),
    ("INT3", token::int3Type),
    ("INT4", token::int4Type),
    ("INT8", token::int8Type),
    ("INTEGER", token::integerType),
    ("INTERNAL", token::internal),
    ("INTERSECT", token::intersect),
    ("INTERVAL", token::interval),
    ("INTO", token::into),
    ("INVERTED", token::inverted),
    ("INVISIBLE", token::invisible),
    ("INVOKER", token::invoker),
    ("ITERATE", token::iterate),
    ("IO", token::io),
    ("RU_PER_SEC", token::ruRate),
    ("PRIORITY", token::priority),
    ("HIGH", token::high),
    ("MEDIUM", token::medium),
    ("LOW", token::low),
    ("IO_READ_BANDWIDTH", token::ioReadBandwidth),
    ("IO_WRITE_BANDWIDTH", token::ioWriteBandwidth),
    ("IPC", token::ipc),
    ("IS", token::is),
    ("ISOLATION", token::isolation),
    ("ISSUER", token::issuer),
    ("JOB", token::job),
    ("JOBS", token::jobs),
    ("JOIN", token::join),
    ("JSON_ARRAYAGG", token::jsonArrayagg),
    ("JSON_OBJECTAGG", token::jsonObjectAgg),
    ("JSON_SUM_CRC32", token::jsonSumCrc32),
    ("JSON", token::jsonType),
    ("KEY_BLOCK_SIZE", token::keyBlockSize),
    ("KEY", token::key),
    ("KEYS", token::keys),
    ("KILL", token::kill),
    ("LABELS", token::labels),
    ("LANGUAGE", token::language),
    ("LAST_BACKUP", token::lastBackup),
    ("LAST", token::last),
    ("LASTVAL", token::lastval),
    ("LATERAL", token::lateral),
    ("LEADER", token::leader),
    ("LEADER_CONSTRAINTS", token::leaderConstraints),
    ("LEADING", token::leading),
    ("LEARNER", token::learner),
    ("LEARNER_CONSTRAINTS", token::learnerConstraints),
    ("LEARNERS", token::learners),
    ("LEAVE", token::leave),
    ("LEFT", token::left),
    ("LESS", token::less),
    ("LEVEL", token::level),
    ("LIKE", token::like),
    ("LIMIT", token::limit),
    ("LITE", token::lite),
    ("LINEAR", token::linear),
    ("LINES", token::lines),
    ("LIST", token::list),
    ("LOAD", token::load),
    ("LOCAL", token::local),
    ("LOCALTIME", token::localTime),
    ("LOCALTIMESTAMP", token::localTs),
    ("LOCATION", token::location),
    ("LOCK", token::lock),
    ("LOCKED", token::locked),
    ("LOG", token::log),
    ("LOGS", token::logs),
    ("LONG", token::long),
    ("LONGBLOB", token::longblobType),
    ("LONGTEXT", token::longtextType),
    ("LOW_PRIORITY", token::lowPriority),
    ("MASTER", token::master),
    ("MASKING", token::masking),
    ("MATCH", token::r#match),
    ("MAX_CONNECTIONS_PER_HOUR", token::maxConnectionsPerHour),
    ("MAX_IDXNUM", token::max_idxnum),
    ("MAX_MINUTES", token::max_minutes),
    ("MAX_QUERIES_PER_HOUR", token::maxQueriesPerHour),
    ("MAX_ROWS", token::maxRows),
    ("MAX_UPDATES_PER_HOUR", token::maxUpdatesPerHour),
    ("MAX_USER_CONNECTIONS", token::maxUserConnections),
    ("MAX", token::max),
    ("MAXVALUE", token::maxValue),
    ("MB", token::mb),
    ("MEDIUMBLOB", token::mediumblobType),
    ("MEDIUMINT", token::mediumIntType),
    ("MEDIUMTEXT", token::mediumtextType),
    ("MEMORY", token::memory),
    ("MEMBER", token::member),
    ("MERGE", token::merge),
    ("METADATA", token::metadata),
    ("MICROSECOND", token::microsecond),
    ("MIDDLEINT", token::middleIntType),
    ("MIN_ROWS", token::minRows),
    ("MIN", token::min),
    ("MINUTE_MICROSECOND", token::minuteMicrosecond),
    ("MINUTE_SECOND", token::minuteSecond),
    ("MINUTE", token::minute),
    ("MINVALUE", token::minValue),
    ("MOD", token::r#mod),
    ("MODE", token::mode),
    ("MODIFY", token::modify),
    ("MONITOR", token::monitor),
    ("MONTH", token::month),
    ("NAMES", token::names),
    ("NATIONAL", token::national),
    ("NATURAL", token::natural),
    ("NCHAR", token::ncharType),
    ("NEVER", token::never),
    ("NEXT_ROW_ID", token::next_row_id),
    ("NEXT", token::next),
    ("NEXTVAL", token::nextval),
    ("NO_WRITE_TO_BINLOG", token::noWriteToBinLog),
    ("NO", token::no),
    ("NOCACHE", token::nocache),
    ("NOCYCLE", token::nocycle),
    ("NODE_ID", token::nodeID),
    ("NODE_STATE", token::nodeState),
    ("NODEGROUP", token::nodegroup),
    ("NOMAXVALUE", token::nomaxvalue),
    ("NOMINVALUE", token::nominvalue),
    ("NONCLUSTERED", token::nonclustered),
    ("NONE", token::none),
    ("NOT", token::not),
    ("NOW", token::now),
    ("NOWAIT", token::nowait),
    ("NULL", token::null),
    ("NULLS", token::nulls),
    ("NUMERIC", token::numericType),
    ("NVARCHAR", token::nvarcharType),
    ("OF", token::of),
    ("OFF", token::off),
    ("OFFSET", token::offset),
    ("OLD", token::old),
    ("OLTP_READ_ONLY", token::oltpReadOnly),
    ("OLTP_READ_WRITE", token::oltpReadWrite),
    ("OLTP_WRITE_ONLY", token::oltpWriteOnly),
    ("TPCH_10", token::tpch10),
    ("ON_DUPLICATE", token::onDuplicate),
    ("ON", token::on),
    ("ONLINE", token::online),
    ("ONLY", token::only),
    ("OPEN", token::open),
    ("OPT_RULE_BLACKLIST", token::optRuleBlacklist),
    ("OPTIMISTIC", token::optimistic),
    ("OPTIMIZE", token::optimize),
    ("OPTION", token::option),
    ("OPTIONAL", token::optional),
    ("OPTIONALLY", token::optionally),
    ("OR", token::or),
    ("ORDER", token::order),
    ("OUT", token::out),
    ("OUTER", token::outer),
    ("OUTFILE", token::outfile),
    ("PACK_KEYS", token::packKeys),
    ("PAGE", token::pageSym),
    ("PAGE_CHECKSUM", token::pageChecksum),
    ("PAGE_COMPRESSED", token::pageCompressed),
    ("PAGE_COMPRESSION_LEVEL", token::pageCompressionLevel),
    ("PARSER", token::parser),
    ("PARTIAL", token::partial),
    ("PARTITION", token::partition),
    ("PARTITIONING", token::partitioning),
    ("PARTITIONS", token::partitions),
    ("PASSWORD", token::password),
    ("PAUSE", token::pause),
    ("PERCENT", token::percent),
    ("PER_DB", token::per_db),
    ("PER_TABLE", token::per_table),
    ("PESSIMISTIC", token::pessimistic),
    ("PLACEMENT", token::placement),
    ("PLAN", token::plan),
    ("PLAN_CACHE", token::planCache),
    ("PLUGINS", token::plugins),
    ("POINT", token::point),
    ("POLICIES", token::policies),
    ("POLICY", token::policy),
    ("POSITION", token::position),
    ("PRE_SPLIT_REGIONS", token::preSplitRegions),
    ("PRECEDING", token::preceding),
    ("PREDICATE", token::predicate),
    ("PRECISION", token::precisionType),
    ("PREPARE", token::prepare),
    ("PRESERVE", token::preserve),
    ("PRIMARY", token::primary),
    ("PRIMARY_REGION", token::primaryRegion),
    ("PRIVILEGES", token::privileges),
    ("PROCEDURE", token::procedure),
    ("PROCESS", token::process),
    ("PROCESSED_KEYS", token::processedKeys),
    ("PROCESSLIST", token::processlist),
    ("PROFILE", token::profile),
    ("PROFILES", token::profiles),
    ("PROXY", token::proxy),
    ("PURGE", token::purge),
    ("QUARTER", token::quarter),
    ("QUERIES", token::queries),
    ("QUERY", token::query),
    ("QUERY_LIMIT", token::queryLimit),
    ("QUICK", token::quick),
    ("RANGE", token::rangeKwd),
    ("RATE_LIMIT", token::rateLimit),
    ("RAW", token::raw),
    ("READ", token::read),
    ("READ_ONLY", token::readOnly),
    ("REAL", token::realType),
    ("REBUILD", token::rebuild),
    ("RECENT", token::recent),
    ("RECOMMEND", token::recommend),
    ("RECOVER", token::recover),
    ("RECURSIVE", token::recursive),
    ("REDUNDANT", token::redundant),
    ("REFERENCES", token::references),
    ("REFRESH", token::refresh),
    ("REGEXP", token::regexpKwd),
    ("REGION", token::region),
    ("REGIONS", token::regions),
    ("RELEASE", token::release),
    ("RELOAD", token::reload),
    ("REMOVE", token::remove),
    ("RENAME", token::rename),
    ("REORGANIZE", token::reorganize),
    ("REPAIR", token::repair),
    ("REPEAT", token::repeat),
    ("REPEATABLE", token::repeatable),
    ("REPLACE", token::replace),
    ("REPLAY", token::replay),
    ("REPLAYER", token::replayer),
    ("REPLICA", token::replica),
    ("REPLICAS", token::replicas),
    ("REPLICATION", token::replication),
    ("RU", token::ru),
    ("RULE", token::rule),
    ("REQUIRE", token::require),
    ("REQUIRED", token::required),
    ("RESET", token::reset),
    ("RESOURCE", token::resource),
    ("RESPECT", token::respect),
    ("RESTART", token::restart),
    ("RESTORE", token::restore),
    ("RESTORES", token::restores),
    ("RESTORED_TS", token::restoredTS),
    ("RESTRICT", token::restrict),
    ("RETAIN", token::retain),
    ("RETURNING", token::returning),
    ("REVERSE", token::reverse),
    ("REVOKE", token::revoke),
    ("RIGHT", token::right),
    ("RLIKE", token::rlike),
    ("ROLE", token::role),
    ("ROLLBACK", token::rollback),
    ("ROLLUP", token::rollup),
    ("ROUTINE", token::routine),
    ("ROW_COUNT", token::rowCount),
    ("ROW_FORMAT", token::rowFormat),
    ("ROW", token::row),
    ("ROWS", token::rows),
    ("RTREE", token::rtree),
    ("HYPO", token::hypo),
    ("RESUME", token::resume),
    ("RUN", token::run),
    ("RUNNING", token::running),
    ("S3", token::s3),
    ("NDVRATE", token::ndvRate),
    ("SAMPLES", token::samples),
    ("SAMPLERATE", token::sampleRate),
    ("SAN", token::san),
    ("SAVEPOINT", token::savepoint),
    ("SCHEDULE", token::schedule),
    ("SCHEMA", token::database),
    ("SCHEMAS", token::databases),
    ("SECOND_MICROSECOND", token::secondMicrosecond),
    ("SECOND", token::second),
    ("SECONDARY", token::secondary),
    ("SECONDARY_ENGINE", token::secondaryEngine),
    ("SECONDARY_LOAD", token::secondaryLoad),
    ("SECONDARY_UNLOAD", token::secondaryUnload),
    ("SECURITY", token::security),
    ("SELECT", token::selectKwd),
    ("SEND_CREDENTIALS_TO_TIKV", token::sendCredentialsToTiKV),
    ("SEPARATOR", token::separator),
    ("SEQUENCE", token::sequence),
    ("SERIAL", token::serial),
    ("SERIALIZABLE", token::serializable),
    ("SESSION", token::session),
    ("SESSION_STATES", token::sessionStates),
    ("SET", token::set),
    ("SETVAL", token::setval),
    ("SHARD_ROW_ID_BITS", token::shardRowIDBits),
    ("SHARE", token::share),
    ("SHARED", token::shared),
    ("SHOW", token::show),
    ("SHUTDOWN", token::shutdown),
    ("SIGNED", token::signed),
    ("SIMILAR", token::similar),
    ("SIMPLE", token::simple),
    ("SKIP", token::skip),
    ("SKIP_SCHEMA_FILES", token::skipSchemaFiles),
    ("SLAVE", token::slave),
    ("SLOW", token::slow),
    ("SMALLINT", token::smallIntType),
    ("SNAPSHOT", token::snapshot),
    ("SOME", token::some),
    ("SOURCE", token::source),
    ("SPATIAL", token::spatial),
    ("SPEED", token::speed),
    ("SPLIT", token::split),
    ("SQL_BIG_RESULT", token::sqlBigResult),
    ("SQL_BUFFER_RESULT", token::sqlBufferResult),
    ("SQL_CACHE", token::sqlCache),
    ("SQL_CALC_FOUND_ROWS", token::sqlCalcFoundRows),
    ("SQL_NO_CACHE", token::sqlNoCache),
    ("SQL_SMALL_RESULT", token::sqlSmallResult),
    ("SQL_TSI_DAY", token::sqlTsiDay),
    ("SQL_TSI_HOUR", token::sqlTsiHour),
    ("SQL_TSI_MINUTE", token::sqlTsiMinute),
    ("SQL_TSI_MONTH", token::sqlTsiMonth),
    ("SQL_TSI_QUARTER", token::sqlTsiQuarter),
    ("SQL_TSI_SECOND", token::sqlTsiSecond),
    ("SQL_TSI_WEEK", token::sqlTsiWeek),
    ("SQL_TSI_YEAR", token::sqlTsiYear),
    ("SQL", token::sql),
    ("SQLEXCEPTION", token::sqlexception),
    ("SQLSTATE", token::sqlstate),
    ("SQLWARNING", token::sqlwarning),
    ("SSL", token::ssl),
    ("STALENESS", token::staleness),
    ("START", token::start),
    ("START_TIME", token::startTime),
    ("START_TS", token::startTS),
    ("STARTING", token::starting),
    ("STATISTICS", token::statistics),
    ("STATS_AUTO_RECALC", token::statsAutoRecalc),
    ("STATS_BUCKETS", token::statsBuckets),
    ("STATS_DELTA", token::statsDelta),
    ("STATS_EXTENDED", token::statsExtended),
    ("STATS_HEALTHY", token::statsHealthy),
    ("STATS_HISTOGRAMS", token::statsHistograms),
    ("STATS_TOPN", token::statsTopN),
    ("STATS_META", token::statsMeta),
    ("STATS_LOCKED", token::statsLocked),
    ("HISTOGRAMS_IN_FLIGHT", token::histogramsInFlight),
    ("STATS_PERSISTENT", token::statsPersistent),
    ("STATS_SAMPLE_PAGES", token::statsSamplePages),
    ("STATS", token::stats),
    ("STATUS", token::status),
    ("STD", token::stddevPop),
    ("STDDEV_POP", token::stddevPop),
    ("STDDEV_SAMP", token::stddevSamp),
    ("STDDEV", token::stddevPop),
    ("STOP", token::stop),
    ("STORAGE", token::storage),
    ("STORED", token::stored),
    ("STRAIGHT_JOIN", token::straightJoin),
    ("STRICT", token::strict),
    ("STRICT_FORMAT", token::strictFormat),
    ("STRONG", token::strong),
    ("SUBDATE", token::subDate),
    ("SUBJECT", token::subject),
    ("SUBPARTITION", token::subpartition),
    ("SUBPARTITIONS", token::subpartitions),
    ("SUBSTR", token::substring),
    ("SUBSTRING", token::substring),
    ("SUM", token::sum),
    ("SUPER", token::superToken),
    ("SURVIVAL_PREFERENCES", token::survivalPreferences),
    ("SWAPS", token::swaps),
    ("SWITCHES", token::switchesSym),
    ("SWITCH_GROUP", token::switchGroup),
    ("SYSTEM", token::system),
    ("SYSTEM_TIME", token::systemTime),
    ("TARGET", token::target),
    ("TASK_TYPES", token::taskTypes),
    ("TABLE_CHECKSUM", token::tableChecksum),
    ("TABLE", token::tableKwd),
    ("TABLES", token::tables),
    ("TABLESAMPLE", token::tableSample),
    ("TABLESPACE", token::tablespace),
    ("TEMPORARY", token::temporary),
    ("TEMPTABLE", token::temptable),
    ("TERMINATED", token::terminated),
    ("TEXT", token::textType),
    ("THAN", token::than),
    ("THEN", token::then),
    ("TIDB", token::tidb),
    ("TIDB_CURRENT_TSO", token::tidbCurrentTSO),
    ("TIDB_JSON", token::tidbJson),
    ("TIFLASH", token::tiFlash),
    ("TIKV_IMPORTER", token::tikvImporter),
    ("TIME", token::timeType),
    ("TIMESTAMP", token::timestampType),
    ("TIMESTAMPADD", token::timestampAdd),
    ("TIMESTAMPDIFF", token::timestampDiff),
    ("TIMEOUT", token::timeout),
    ("TINYBLOB", token::tinyblobType),
    ("TINYINT", token::tinyIntType),
    ("TINYTEXT", token::tinytextType),
    ("TLS", token::tls),
    ("TO", token::to),
    ("TOKEN_ISSUER", token::tokenIssuer),
    ("TOKUDB_DEFAULT", token::tokudbDefault),
    ("TOKUDB_FAST", token::tokudbFast),
    ("TOKUDB_LZMA", token::tokudbLzma),
    ("TOKUDB_QUICKLZ", token::tokudbQuickLZ),
    ("TOKUDB_SMALL", token::tokudbSmall),
    ("TOKUDB_SNAPPY", token::tokudbSnappy),
    ("TOKUDB_UNCOMPRESSED", token::tokudbUncompressed),
    ("TOKUDB_ZLIB", token::tokudbZlib),
    ("TOKUDB_ZSTD", token::tokudbZstd),
    ("TOP", token::top),
    ("TOPN", token::topn),
    ("TPCC", token::tpcc),
    ("TRACE", token::trace),
    ("TRADITIONAL", token::traditional),
    ("TRAFFIC", token::traffic),
    ("TRAILING", token::trailing),
    ("TRANSACTION", token::transaction),
    ("TRANSACTIONAL", token::transactional),
    ("TRIGGER", token::trigger),
    ("TRIGGERS", token::triggers),
    ("TRIM", token::trim),
    ("TRUE", token::trueKwd),
    ("TRUNCATE", token::truncate),
    ("TRUE_CARD_COST", token::trueCardCost),
    ("TSO", token::tsoType),
    ("TTL", token::ttl),
    ("TTL_ENABLE", token::ttlEnable),
    ("TTL_JOB_INTERVAL", token::ttlJobInterval),
    ("TYPE", token::tp),
    ("UNBOUNDED", token::unbounded),
    ("UNCOMMITTED", token::uncommitted),
    ("UNDEFINED", token::undefined),
    ("UNICODE", token::unicodeSym),
    ("UNION", token::union),
    ("UNIQUE", token::unique),
    ("UNKNOWN", token::unknown),
    ("UNLOCK", token::unlock),
    ("UNLIMITED", token::unlimited),
    ("MODERATED", token::moderated),
    ("UNSET", token::unset),
    ("UNSIGNED", token::unsigned),
    ("UNTIL", token::until),
    ("UNTIL_TS", token::untilTS),
    ("UPDATE", token::update),
    ("USAGE", token::usage),
    ("USE", token::r#use),
    ("USER", token::user),
    ("USING", token::using),
    ("UTC_DATE", token::utcDate),
    ("UTC_TIME", token::utcTime),
    ("UTC_TIMESTAMP", token::utcTimestamp),
    ("UTILIZATION_LIMIT", token::utilizationLimit),
    ("UUID", token::uuid),
    ("VALIDATION", token::validation),
    ("VALUE", token::value),
    ("VALUES", token::values),
    ("VAR_POP", token::varPop),
    ("VAR_SAMP", token::varSamp),
    ("VARBINARY", token::varbinaryType),
    ("VARCHAR", token::varcharType),
    ("VARCHARACTER", token::varcharacter),
    ("VARIABLES", token::variables),
    ("VARIANCE", token::varPop),
    ("VARYING", token::varying),
    ("VECTOR", token::vectorType),
    ("VERBOSE", token::verboseType),
    ("VOTER", token::voter),
    ("VOTER_CONSTRAINTS", token::voterConstraints),
    ("VOTERS", token::voters),
    ("VIEW", token::view),
    ("VIRTUAL", token::r#virtual),
    ("VISIBLE", token::visible),
    ("WARNINGS", token::warnings),
    ("WATCH", token::watch),
    ("WEEK", token::week),
    ("WEIGHT_STRING", token::weightString),
    ("WHEN", token::when),
    ("WHERE", token::r#where),
    ("WHILE", token::r#while),
    ("WIDTH", token::width),
    ("WITH", token::with),
    ("WITHOUT", token::without),
    ("WRITE", token::write),
    ("WORKLOAD", token::workload),
    ("X509", token::x509),
    ("XOR", token::xor),
    ("YEAR_MONTH", token::yearMonth),
    ("YEAR", token::yearType),
    ("ZEROFILL", token::zerofill),
    ("WAIT", token::wait),
    ("FAILED_LOGIN_ATTEMPTS", token::failedLoginAttempts),
    ("PASSWORD_LOCK_TIME", token::passwordLockTime),
    ("REUSE", token::reuse),
];

// 内建函数只有在后面紧跟左括号时才采用专用 token。
/// 需紧跟 `(` 才生效的内建函数 token。
pub static btFuncTokenMap: &[(&str, i32)] = &[
    ("BIT_AND", token::builtinBitAnd),
    ("BIT_OR", token::builtinBitOr),
    ("BIT_XOR", token::builtinBitXor),
    ("CAST", token::builtinCast),
    ("COUNT", token::builtinCount),
    ("APPROX_COUNT_DISTINCT", token::builtinApproxCountDistinct),
    ("APPROX_PERCENTILE", token::builtinApproxPercentile),
    ("CURDATE", token::builtinCurDate),
    ("CURTIME", token::builtinCurTime),
    ("DATE_ADD", token::builtinDateAdd),
    ("DATE_SUB", token::builtinDateSub),
    ("EXTRACT", token::builtinExtract),
    ("GROUP_CONCAT", token::builtinGroupConcat),
    ("MAX", token::builtinMax),
    ("MID", token::builtinSubstring),
    ("MIN", token::builtinMin),
    ("NOW", token::builtinNow),
    ("POSITION", token::builtinPosition),
    ("STD", token::builtinStddevPop),
    ("STDDEV", token::builtinStddevPop),
    ("STDDEV_POP", token::builtinStddevPop),
    ("STDDEV_SAMP", token::builtinStddevSamp),
    ("SUBSTR", token::builtinSubstring),
    ("SUBSTRING", token::builtinSubstring),
    ("SUM", token::builtinSum),
    ("SUM_INT", token::builtinSumInt),
    ("SYSDATE", token::builtinSysDate),
    ("TRANSLATE", token::builtinTranslate),
    ("TRIM", token::builtinTrim),
    ("VARIANCE", token::builtinVarPop),
    ("VAR_POP", token::builtinVarPop),
    ("VAR_SAMP", token::builtinVarSamp),
];

// 窗口函数关键字由 Scanner.supportWindowFunc 控制启用。
/// 窗口函数关键字（由开关启用）。
pub static windowFuncTokenMap: &[(&str, i32)] = &[
    ("CUME_DIST", token::cumeDist),
    ("DENSE_RANK", token::denseRank),
    ("FIRST_VALUE", token::firstValue),
    ("GROUPS", token::groups),
    ("LAG", token::lag),
    ("LAST_VALUE", token::lastValue),
    ("LEAD", token::lead),
    ("NTH_VALUE", token::nthValue),
    ("NTILE", token::ntile),
    ("OVER", token::over),
    ("PERCENT_RANK", token::percentRank),
    ("RANK", token::rank),
    ("ROW_NUMBER", token::rowNumber),
    ("WINDOW", token::window),
];

// ALIASES 让同义拼写共享同一个 token。
/// 关键字别名到规范名。
pub static aliases: &[(&str, &str)] = &[
    ("SCHEMA", "DATABASE"),
    ("SCHEMAS", "DATABASES"),
    ("DEC", "DECIMAL"),
    ("SUBSTR", "SUBSTRING"),
];

// HINTED_TOKENS 限定哪些语句关键字后可以出现优化器 hint。
/// 允许后接优化器 Hint 的语句关键字。
pub static hintedTokens: &[i32] = &[
    token::selectKwd,
    token::insert,
    token::replace,
    token::update,
    token::deleteKwd,
    token::create,
    token::partition,
];

// HINT_TOKEN_MAP 同时保留 MySQL、TiDB hint 名称、别名和参数关键字。
/// Hint 名称/别名/参数关键字映射。
pub static hintTokenMap: &[(&str, i32)] = &[
    // MySQL 8.0 hint names
    ("JOIN_FIXED_ORDER", hintJoinFixedOrder),
    ("JOIN_ORDER", hintJoinOrder),
    ("JOIN_PREFIX", hintJoinPrefix),
    ("JOIN_SUFFIX", hintJoinSuffix),
    ("BKA", hintBKA),
    ("NO_BKA", hintNoBKA),
    ("BNL", hintBNL),
    ("NO_BNL", hintNoBNL),
    ("HASH_JOIN", hintHashJoin),
    ("HASH_JOIN_BUILD", hintHashJoinBuild),
    ("HASH_JOIN_PROBE", hintHashJoinProbe),
    ("NO_HASH_JOIN", hintNoHashJoin),
    ("MERGE", hintMerge),
    ("NO_MERGE", hintNoMerge),
    ("INDEX_MERGE", hintIndexMerge),
    ("NO_INDEX_MERGE", hintNoIndexMerge),
    ("MRR", hintMRR),
    ("NO_MRR", hintNoMRR),
    ("NO_ICP", hintNoICP),
    ("NO_RANGE_OPTIMIZATION", hintNoRangeOptimization),
    ("SKIP_SCAN", hintSkipScan),
    ("NO_SKIP_SCAN", hintNoSkipScan),
    ("SEMIJOIN", hintSemijoin),
    ("NO_SEMIJOIN", hintNoSemijoin),
    ("MAX_EXECUTION_TIME", hintMaxExecutionTime),
    ("SET_VAR", hintSetVar),
    ("RESOURCE_GROUP", hintResourceGroup),
    ("QB_NAME", hintQBName),
    ("HYPO_INDEX", hintHypoIndex),
    // TiDB hint names
    ("AGG_TO_COP", hintAggToCop),
    ("LIMIT_TO_COP", hintLimitToCop),
    ("IGNORE_PLAN_CACHE", hintIgnorePlanCache),
    ("WRITE_SLOW_LOG", hintWriteSlowLog),
    ("HASH_AGG", hintHashAgg),
    ("MPP_1PHASE_AGG", hintMpp1PhaseAgg),
    ("MPP_2PHASE_AGG", hintMpp2PhaseAgg),
    ("IGNORE_INDEX", hintIgnoreIndex),
    ("INL_HASH_JOIN", hintInlHashJoin),
    ("INDEX_HASH_JOIN", hintIndexHashJoin),
    ("NO_INDEX_HASH_JOIN", hintNoIndexHashJoin),
    ("INL_JOIN", hintInlJoin),
    ("INDEX_JOIN", hintIndexJoin),
    ("NO_INDEX_JOIN", hintNoIndexJoin),
    ("INL_MERGE_JOIN", hintInlMergeJoin),
    ("INDEX_MERGE_JOIN", hintIndexMergeJoin),
    ("NO_INDEX_MERGE_JOIN", hintNoIndexMergeJoin),
    ("MEMORY_QUOTA", hintMemoryQuota),
    ("NO_SWAP_JOIN_INPUTS", hintNoSwapJoinInputs),
    ("QUERY_TYPE", hintQueryType),
    ("READ_CONSISTENT_REPLICA", hintReadConsistentReplica),
    ("READ_FROM_STORAGE", hintReadFromStorage),
    ("BROADCAST_JOIN", hintBCJoin),
    ("SHUFFLE_JOIN", hintShuffleJoin),
    ("MERGE_JOIN", hintSMJoin),
    ("NO_MERGE_JOIN", hintNoSMJoin),
    ("STREAM_AGG", hintStreamAgg),
    ("SWAP_JOIN_INPUTS", hintSwapJoinInputs),
    ("USE_INDEX_MERGE", hintUseIndexMerge),
    ("USE_INDEX", hintUseIndex),
    ("ORDER_INDEX", hintOrderIndex),
    ("NO_ORDER_INDEX", hintNoOrderIndex),
    ("INDEX_LOOKUP_PUSHDOWN", hintIndexLookUpPushDown),
    ("NO_INDEX_LOOKUP_PUSHDOWN", hintNoIndexLookUpPushDown),
    ("USE_PLAN_CACHE", hintUsePlanCache),
    ("USE_TOJA", hintUseToja),
    ("TIME_RANGE", hintTimeRange),
    ("USE_CASCADES", hintUseCascades),
    ("NTH_PLAN", hintNthPlan),
    ("FORCE_INDEX", hintForceIndex),
    ("STRAIGHT_JOIN", hintStraightJoin),
    ("LEADING", hintLeading),
    ("SEMI_JOIN_REWRITE", hintSemiJoinRewrite),
    ("NO_DECORRELATE", hintNoDecorrelate),
    // TiDB hint aliases
    ("TIDB_HJ", hintHashJoin),
    ("TIDB_INLJ", hintInlJoin),
    ("TIDB_SMJ", hintSMJoin),
    // Other keywords
    ("OLAP", hintOLAP),
    ("OLTP", hintOLTP),
    ("TIKV", hintTiKV),
    ("TIFLASH", hintTiFlash),
    ("PARTITION", hintPartition),
    ("FALSE", hintFalse),
    ("TRUE", hintTrue),
    ("MB", hintMB),
    ("GB", hintGB),
    ("DUPSWEEDOUT", hintDupsWeedOut),
    ("FIRSTMATCH", hintFirstMatch),
    ("LOOSESCAN", hintLooseScan),
    ("MATERIALIZATION", hintMaterialization),
];

impl Scanner {
    // isTokenIdentifier 先排除限定名，再做 ASCII 大写化与函数/普通/窗口关键字三级查表。
    /// 将标识符解析为关键字/内建/窗口函数 token，排除限定名。
    pub fn isTokenIdentifier(&mut self, lit: &str, token_offset: i32) -> i32 {
        // 点号两侧的词属于 qualified identifier，不能解释为 SQL 关键字。
        if self.r.peek() == b'.' {
            return 0;
        }
        let bytes = self.r.s.as_bytes();
        let mut idx = token_offset - 1;
        while idx >= 0 {
            match bytes[idx as usize] {
                b' ' => idx -= 1,
                b'.' => return 0,
                _ => break,
            }
        }
        self.buf.clear();
        self.buf.reserve(lit.len());
        self.buf.extend(lit.bytes().map(|c| {
            if c.is_ascii_lowercase() {
                c.to_ascii_uppercase()
            } else {
                c
            }
        }));
        let normalized = String::from_utf8_lossy(&self.buf).into_owned();

        // IGNORE_SPACE 模式允许函数名与左括号之间存在空白；skipWhitespace 会推进 reader，沿用 Go 行为。
        let mut builtin_call = self.r.peek() == b'(';
        if !builtin_call && self.sqlMode.HasIgnoreSpaceMode() {
            self.skipWhitespace();
            builtin_call = self.r.peek() == b'(';
        }
        if builtin_call {
            let tok = lookup_token(btFuncTokenMap, &normalized);
            if tok != 0 {
                return tok;
            }
        }
        let tok = lookup_token(tokenMap, &normalized);
        if tok == 0 && self.supportWindowFunc {
            lookup_token(windowFuncTokenMap, &normalized)
        } else {
            tok
        }
    }
}
