// Code generated by goyacc DO NOT EDIT.

// Copyright 2026 AsterSQL.

// Copyright 2013 The ql Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSES/QL-LICENSE file.

// Copyright 2015 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

// Initial yacc source generated by ebnf2y[1]
// at 2013-10-04 23:10:47.861401015 +0200 CEST
//
//  $ ebnf2y -o ql.y -oe ql.ebnf -start StatementList -pkg ql -p _
//
//   [1]: http://github.com/cznic/ebnf2y

// goyacc 生成的 SQL LALR(1) 解析器核心。
//
// 对应 Go `parser.go` / goyacc 输出：包含语义值类型、token 常量、
// 稀疏动作表，以及 `yyParse` 移进/规约状态机。LALR 是自底向上语法分析，
// 语义动作在规约时构造 AST（抽象语法树）节点。

// ast、auth、charset、duration、mysql、opcode、types 和 Parser 均为跨文件依赖，模块连线留待后续统一处理。

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
/// 语法错误定位：(state, 期望符号)。
pub struct yyXError {
    state: isize,
    xsym: isize,
}

pub use token::account;

/// Pure Rust parsergen uses zero as the end-of-input token.
const yyEOFCode: isize = 0;

fn generated_main_symbol(token: isize) -> Option<usize> {
    GENERATED_MAIN_XLAT
        .binary_search_by_key(&token, |(number, _)| *number)
        .ok()
        .map(|index| GENERATED_MAIN_XLAT[index].1)
}

fn generated_main_action(state: usize, symbol: usize) -> i32 {
    GENERATED_MAIN_PARSE_TABLE
        .get(state)
        .and_then(|row| {
            row.binary_search_by_key(&symbol, |(column, _)| *column)
                .ok()
                .map(|index| row[index].1)
        })
        .unwrap_or(0)
}

// 词元、符号、归约与状态表由 parsergen 生成并在 crate 入口 include。

/// goyacc 调试级别；>=3 时打印词法细节。
static mut yyDebug: isize = 0;

// yyLexer 对应 goyacc 词法器接口：产生 token，并把错误/警告回传给调用方。
/// goyacc 词法器接口：取 token 并回传错误/警告。
pub trait yyLexer {
    fn Lex(&mut self, lval: &mut yySymType) -> isize;
    fn Errorf(&self, format: &str, args: &[&dyn Any]) -> ParserError;
    fn AppendError(&mut self, err: ParserError);
    fn AppendWarn(&mut self, err: ParserError);
    fn LastErrorAsWarn(&mut self) {}
    fn Errors(&self) -> (Vec<ParserError>, Vec<ParserError>);
    // Go's optional stmtTexter contract: only real scanners own source slices.
    fn statement_text(&mut self) -> Option<(charset::encoding::EncodingRef, String)> {
        None
    }
    fn sql_mode_bits(&self) -> i64 {
        0
    }
    fn hint_position(&self) -> Pos {
        Pos::default()
    }
    fn as_extended(&mut self) -> Option<&mut dyn yyLexerEx> {
        None
    }
    fn skip_position_recording(&self) -> bool {
        false
    }
}

// yyLexerEx 保留规约完成回调；返回 true 时，Go 解析器会提前停止当前规约流程。
/// 扩展词法器：规约完成回调 Reduced。
pub trait yyLexerEx: yyLexer {
    fn Reduced(&mut self, rule: isize, state: isize, lval: &mut yySymType) -> bool;
}

// yySymName 先查生成的 token 翻译表，未知 token 则按十进制编号显示。
/// token 编号转可读名称；未知则输出十进制。
pub fn yySymName(c: isize) -> String {
    generated_main_symbol(c)
        .map(|symbol_index| GENERATED_MAIN_SYMBOL_NAMES[symbol_index].to_owned())
        .unwrap_or_else(|| c.to_string())
}

// yylex1 对应 Go 的词法入口；非正 token 统一折叠为 EOF，并保留调试输出位置。
/// 词法入口包装：非正 token 折叠为 EOF。
pub fn yylex1(yylex: &mut dyn yyLexer, lval: &mut yySymType) -> isize {
    let mut token = yylex.Lex(lval);
    if token <= 0 {
        token = yyEOFCode;
    }
    if unsafe { yyDebug } >= 3 {
        eprintln!(
            "lex {}({:#x} {}), lval offset: {}",
            yySymName(token),
            token,
            token,
            lval.offset
        );
    }
    token
}

// yyParse 对应 goyacc 生成的 LALR 状态机；下方完整保留移进、规约、恢复和全部语义动作。
/// LALR 状态机入口：移进、规约、错误恢复与语义动作。
pub fn yyParse(yylex: &mut dyn yyLexer, parser_state: &mut Parser) -> isize {
    // Go keeps the state and semantic value in one cached yySymType slice.
    // Reuse Parser.cache across calls so long statements do not allocate two
    // parallel stacks on every parse.
    let mut values = std::mem::take(&mut parser_state.cache);
    values.clear();
    values.push(yySymType::default());
    let mut lookahead = -1isize;
    let mut error_flag = 0u8;

    let result = (|| -> isize {
        loop {
            let state = values
                .last()
                .expect("goyacc state stack is never empty")
                .yys as usize;
            if lookahead < 0 {
                parser_state.yylval = yySymType::default();
                lookahead = yylex1(yylex, &mut parser_state.yylval);
            }
            let symbol =
                generated_main_symbol(lookahead).unwrap_or(GENERATED_MAIN_SYMBOL_NAMES.len());
            let action = generated_main_action(state, symbol);

            if action == GENERATED_MAIN_ACCEPT {
                return 0;
            }

            if action > 0 {
                let mut shifted_value = std::mem::take(&mut parser_state.yylval);
                shifted_value.yys = (action - 1) as isize;
                values.push(shifted_value);
                lookahead = -1;
                if error_flag > 0 {
                    error_flag -= 1;
                }
                continue;
            }
            if action < 0 {
                let previous_state = state as isize;
                let generated_reduction = (-action - 1) as usize;
                let Some(&(reduction_symbol, reduction_components)) =
                    GENERATED_MAIN_REDUCTIONS.get(generated_reduction)
                else {
                    yylex.AppendError(yylex.Errorf("invalid parser reduction", &[]));
                    return 1;
                };
                let Some(&reduction_index) = GENERATED_MAIN_LEGACY_RULES.get(generated_reduction)
                else {
                    yylex.AppendError(yylex.Errorf("invalid parser rule mapping", &[]));
                    return 1;
                };
                let Some(&rule_id) = RULE_IDS_BY_REDUCTION.get(generated_reduction) else {
                    yylex.AppendError(yylex.Errorf("invalid parser RuleId mapping", &[]));
                    return 1;
                };
                let pop_count = reduction_components;
                if pop_count >= values.len() {
                    yylex.AppendError(yylex.Errorf("invalid parser stack", &[]));
                    return 1;
                }
                let value_start = values.len() - pop_count;
                let rhs_semantic_complete = values[value_start..]
                    .iter()
                    .all(|value| value.semantic_complete);
                // goyacc defaults $$ to $1. Move that value instead of cloning it:
                // semantic values contain dynamic AST nodes and are intentionally
                // non-Clone.
                let mut reduced_value = yySymType::default();
                reduced_value.semantic_complete = rhs_semantic_complete;
                if pop_count > 0 {
                    reduced_value.offset = values[value_start].offset;
                    reduced_value.ident = values[value_start].ident.clone();
                }
                let handled = match parser_actions::apply(
                    rule_id,
                    Rhs::new(&mut values[value_start..]),
                    parser_actions::Context::new(&mut reduced_value, parser_state, yylex),
                ) {
                    Ok(handled) => handled,
                    Err(status) => return status,
                };
                if !handled && pop_count > 0 {
                    reduced_value = Rhs::new(&mut values[value_start..]).take_default();
                    reduced_value.semantic_complete =
                        rhs_semantic_complete && !parser_actions::has_semantic_action(rule_id);
                } else if !handled {
                    reduced_value.semantic_complete = !parser_actions::has_semantic_action(rule_id);
                }
                values.truncate(values.len() - pop_count);
                let base_state = values.last().expect("reduction leaves a base state").yys as usize;
                let encoded_goto = generated_main_action(base_state, reduction_symbol);
                if encoded_goto <= 0 {
                    yylex.AppendError(yylex.Errorf("invalid parser goto", &[]));
                    return 1;
                }
                let next_state = (encoded_goto - 1) as isize;
                if !yylex.skip_position_recording() {
                    let offset = reduced_value.offset;
                    yySetOffset(&mut reduced_value, offset);
                }
                reduced_value.yys = next_state;
                if let Some(extended) = yylex.as_extended() {
                    if extended.Reduced(
                        reduction_index as isize,
                        previous_state,
                        &mut reduced_value,
                    ) {
                        return -1;
                    }
                }
                values.push(reduced_value);
                continue;
            }

            // Match goyacc's three-stage recovery. Report a new error once, then
            // pop to a state that can shift the synthetic error symbol. If three
            // normal tokens have not shifted yet, discard the current lookahead.
            if error_flag == 0 {
                // TiDB intentionally ignores goyacc's generated message; Scanner
                // derives the exact line/column/near text from its current state.
                yylex.AppendError(yylex.Errorf("", &[]));
            }
            if error_flag < 3 {
                error_flag = 3;
                let mut recovery_state = None;
                while let Some(value) = values.last() {
                    let state = value.yys as usize;
                    if let Some(error_symbol) = GENERATED_MAIN_SYMBOL_NAMES
                        .iter()
                        .position(|name| *name == "error")
                    {
                        let encoded = generated_main_action(state, error_symbol);
                        if encoded > 0 {
                            recovery_state = Some((encoded - 1) as isize);
                            break;
                        }
                    }
                    values.pop();
                }
                let Some(error_shift) = recovery_state else {
                    return 1;
                };
                let mut error_value = yySymType::default();
                error_value.yys = error_shift;
                values.push(error_value);
                continue;
            }
            if lookahead == yyEOFCode {
                return 1;
            }
            lookahead = -1;
        }
    })();

    values.clear();
    parser_state.cache = values;
    result
}
