// Code generated by goyacc DO NOT EDIT.

// Copyright 2026 AsterSQL.

// Copyright 2013 The ql Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSES/QL-LICENSE file.

// Copyright 2015 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.
/// goyacc 语义值联合体：状态、偏移、标识符、表达式与语句。
pub struct yySymType {
    yys: isize,
    offset: i32, // offset
    item: Option<Box<dyn Any>>,
    ident: String,
    expr: Option<parser_ast::ExprNode>,
    statement: Option<Box<dyn parser_ast::Node>>,
    semantic_complete: bool,
}

impl Default for yySymType {
    fn default() -> Self {
        Self {
            yys: 0,
            offset: 0,
            item: None,
            ident: String::new(),
            expr: None,
            statement: None,
            semantic_complete: true,
        }
    }
}

/// 一次规约的右部语义值，使用 `$1..$n` 的一基、从左到右索引。
pub(crate) struct Rhs<'a> {
    values: &'a mut [yySymType],
}

impl<'a> Rhs<'a> {
    pub(crate) fn new(values: &'a mut [yySymType]) -> Self {
        Self { values }
    }

    pub(crate) fn len(&self) -> usize {
        self.values.len()
    }

    pub(crate) fn borrow(&self, position: usize) -> Option<&yySymType> {
        self.values.get(position.checked_sub(1)?)
    }

    pub(crate) fn borrow_mut(&mut self, position: usize) -> Option<&mut yySymType> {
        self.values.get_mut(position.checked_sub(1)?)
    }

    pub(crate) fn take(&mut self, position: usize) -> Option<yySymType> {
        self.values
            .get_mut(position.checked_sub(1)?)
            .map(std::mem::take)
    }

    pub(crate) fn take_default(mut self) -> yySymType {
        self.take(1).unwrap_or_default()
    }

    pub(crate) fn as_mut_slice(&mut self) -> &mut [yySymType] {
        self.values
    }
}
