// Code generated by goyacc DO NOT EDIT.

// Copyright 2026 AsterSQL.

// Copyright 2013 The ql Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSES/QL-LICENSE file.

// Copyright 2015 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

// Initial yacc source generated by ebnf2y[1]
// at 2013-10-04 23:10:47.861401015 +0200 CEST
//
//  $ ebnf2y -o ql.y -oe ql.ebnf -start StatementList -pkg ql -p _
//
//   [1]: http://github.com/cznic/ebnf2y

// goyacc 生成的 SQL LALR(1) 解析器核心。
//
// 对应 Go `parser.go` / goyacc 输出：包含语义值类型、token 常量、
// 稀疏动作表，以及 `yyParse` 移进/规约状态机。LALR 是自底向上语法分析，
// 语义动作在规约时构造 AST（抽象语法树）节点。

// ast、auth、charset、duration、mysql、opcode、types 和 Parser 均为跨文件依赖，模块连线留待后续统一处理。

use std::any::Any;
use std::sync::LazyLock;

/// LIKE/ESCAPE 子句的转义字符说明。
pub struct likeEscapeSpec {
    escape: String,
    explicit: bool,
}

/// INSERT ... AS row_alias(col...) 的行别名语义。
pub struct insertRowAlias {
    rowAlias: ast::CIStr,
    columnAliases: Vec<ast::CIStr>,
}

#[derive(Clone, Default)]
/// CREATE TABLE 列与约束列表的规约中间结果。
struct CreateTableElementsSemantic {
    columns: Vec<parser_ast::ColumnDef>,
    constraints: Vec<parser_ast::Constraint>,
    complete: bool,
}

#[derive(Default)]
/// CREATE TABLE 整句语义值，complete 标记规约是否完成。
struct CreateTableSemantic {
    statement: parser_ast::CreateTableStmt,
    complete: bool,
}

#[derive(Clone, Copy, Default)]
/// 数值类型 UNSIGNED / ZEROFILL 选项。
struct TypeOptSemantic {
    unsigned: bool,
    zerofill: bool,
}

#[derive(Clone, Copy)]
/// FLOAT/DOUBLE 精度：flen 与 decimal。
struct FloatOptSemantic {
    flen: isize,
    decimal: isize,
}

#[derive(Clone, Default)]
/// BINARY 属性与可选字符集。
struct OptBinarySemantic {
    binary: bool,
    charset: String,
}

#[derive(Clone, Copy, Default)]
/// VECTOR 元素类型语义。
struct VectorElementTypeSemantic {
    tp: u8,
}

#[derive(Clone, Default)]
/// 索引名与索引类型（BTREE/HASH 等）。
struct IndexNameAndTypeSemantic {
    name: parser_ast::NullString,
    index_type: Option<parser_ast::IndexType>,
}

/// 子查询节点包装。
struct SubquerySemantic {
    query: parser_ast::NodeRef,
}

#[derive(Clone, Default)]
/// GROUP BY items plus its trailing WITH ROLLUP modifier.
struct GroupBySemantic {
    items: Vec<parser_ast::ByItem>,
    rollup: bool,
}

#[derive(Clone)]
/// 角色、权限元素或动态权限名。
enum RoleOrPrivSemantic {
    Priv(parser_ast::PrivElem),
    Role(auth::RoleIdentity),
    Dynamic(String),
}

#[derive(Clone, Default)]
/// 文本串字面量及其 binary 标记。
struct TextStringSemantic {
    value: String,
    binary: bool,
}

#[derive(Default)]
/// 集合运算（UNION/INTERSECT/EXCEPT）中间语义。
struct SetOprSemantic {
    nodes: Vec<Box<dyn parser_ast::Node>>,
    operators: Vec<Option<parser_ast::SetOprType>>,
}

#[derive(Clone)]
struct ShowLikeSemantic(parser_ast::ExprNode);

/// 从嵌套集合运算语句取出 SelectList。
fn nested_set_op_list(
    statement: Box<dyn parser_ast::Node>,
    retain_select_with: bool,
) -> Option<parser_ast::SetOprSelectList> {
    match statement.into_any().downcast::<parser_ast::SelectStmt>() {
        Ok(select) => {
            let with = if retain_select_with {
                select.With.clone()
            } else {
                None
            };
            let mut list = parser_ast::SetOprSelectList::new(vec![select]);
            list.With = with;
            Some(list)
        }
        Err(statement) => match statement.downcast::<parser_ast::SetOprStmt>() {
            Ok(set_op) => {
                let parser_ast::SetOprStmt {
                    select_list,
                    OrderBy,
                    Limit,
                    With,
                    ..
                } = *set_op;
                Some(parser_ast::SetOprSelectList {
                    node_text: Default::default(),
                    selects: select_list.selects,
                    operators: select_list.operators,
                    With,
                    OrderBy,
                    Limit,
                    AfterSetOperator: None,
                })
            }
            Err(_) => None,
        },
    }
}

/// 从语义值中取出子查询语句节点。
fn take_subquery_statement(value: &mut yySymType) -> Option<Box<dyn parser_ast::Node>> {
    value
        .item
        .take()?
        .downcast::<SubquerySemantic>()
        .ok()?
        .query
        .take()
}

/// 校验是否为合法 Go duration 字面量形式。
fn validate_go_duration(value: &str) -> Result<(), String> {
    // time.quote escapes every non-ASCII/control byte rather than Unicode scalars.
    let quote = |value: &str| {
        let mut result = String::from("\"");
        for byte in value.bytes() {
            match byte {
                b'"' | b'\\' => {
                    result.push('\\');
                    result.push(byte as char);
                }
                0..=31 | 128..=255 => result.push_str(&format!("\\x{byte:02x}")),
                _ => result.push(byte as char),
            }
        }
        result.push('"');
        result
    };
    let original = quote(value);
    let invalid_duration = || format!("time: invalid duration {original}");
    // Match time.ParseDuration, including its signed int64 nanosecond range
    // and bounded fractional accumulation.
    let negative = value.starts_with('-');
    let value = value.strip_prefix(['+', '-']).unwrap_or(value);
    if value == "0" {
        return Ok(());
    }
    let bytes = value.as_bytes();
    let mut index = 0;
    let mut total = 0u64;
    const LIMIT: u64 = 1 << 63;
    while index < bytes.len() {
        let start = index;
        let mut integer = 0u64;
        while index < bytes.len() && bytes[index].is_ascii_digit() {
            let digit = u64::from(bytes[index] - b'0');
            if integer > (LIMIT - digit) / 10 {
                return Err(invalid_duration());
            }
            integer = integer * 10 + digit;
            index += 1;
        }
        let pre = index > start;
        let mut fraction = 0u64;
        let mut scale = 1.0f64;
        let mut post = false;
        if index < bytes.len() && bytes[index] == b'.' {
            index += 1;
            let mut overflow = false;
            while index < bytes.len() && bytes[index].is_ascii_digit() {
                post = true;
                if !overflow {
                    let digit = u64::from(bytes[index] - b'0');
                    if fraction > (LIMIT - 1) / 10 || fraction * 10 + digit > LIMIT {
                        overflow = true;
                    } else {
                        fraction = fraction * 10 + digit;
                        scale *= 10.0;
                    }
                }
                index += 1;
            }
        }
        if !pre && !post {
            return Err(invalid_duration());
        }
        let unit_start = index;
        while index < bytes.len() && bytes[index] != b'.' && !bytes[index].is_ascii_digit() {
            index += 1;
        }
        let unit = match &value[unit_start..index] {
            "ns" => 1,
            "us" | "µs" | "μs" => 1_000,
            "ms" => 1_000_000,
            "s" => 1_000_000_000,
            "m" => 60_000_000_000,
            "h" => 3_600_000_000_000,
            "" => return Err(format!("time: missing unit in duration {original}")),
            unit => {
                return Err(format!(
                    "time: unknown unit {} in duration {original}",
                    quote(unit)
                ));
            }
        };
        if integer > LIMIT / unit {
            return Err(invalid_duration());
        }
        let term = integer * unit + (fraction as f64 * (unit as f64 / scale)) as u64;
        if term > LIMIT || total > LIMIT - term {
            return Err(invalid_duration());
        }
        total += term;
    }
    if !value.is_empty() && (negative || total < LIMIT) {
        Ok(())
    } else {
        Err(invalid_duration())
    }
}

static AST_ERR_WRONG_USAGE: LazyLock<Box<terror::Error>> =
    LazyLock::new(|| terror::ClassDDL.NewStd(terror::ErrCode(mysql::ErrWrongUsage as isize)));
static AST_ERR_UNKNOWN_CHARACTER_SET: LazyLock<Box<terror::Error>> = LazyLock::new(|| {
    terror::ClassDDL.NewStd(terror::ErrCode(mysql::ErrUnknownCharacterSet as isize))
});

/// 校验列定义合法性（生成列选项等）。
fn validate_column_def(column: &parser_ast::ColumnDef) -> Result<(), errors::Error> {
    let generated = column
        .Options
        .iter()
        .any(|option| option.Tp == parser_ast::ColumnOptionType::Generated);
    if !generated {
        return Ok(());
    }
    let illegal = column
        .Options
        .iter()
        .rev()
        .find_map(|option| match option.Tp {
            parser_ast::ColumnOptionType::AutoIncrement => Some("AUTO_INCREMENT"),
            parser_ast::ColumnOptionType::OnUpdate => Some("ON UPDATE"),
            parser_ast::ColumnOptionType::DefaultValue => Some("DEFAULT"),
            _ => None,
        });
    match illegal {
        Some(illegal) => {
            Err(AST_ERR_WRONG_USAGE
                .GenWithStackByArgs(&[illegal.into(), "generated column".into()]))
        }
        None => Ok(()),
    }
}

/// 校验分区定义子句与分区方法是否匹配。
fn validate_partition_clause(
    clause: &parser_ast::PartitionDefinitionClause,
    partition_type: parser_ast::PartitionType,
    columns: usize,
) -> Result<(), errors::Error> {
    use parser_ast::{PartitionDefinitionClause as Clause, PartitionType as Type};
    let validation_error = |code: u16, args: &[&str]| {
        Err(terror::ClassDDL
            .NewStd(terror::ErrCode(code as isize))
            .GenWithStackByArgs(&args.iter().map(|value| (*value).into()).collect::<Vec<_>>()))
    };
    match clause {
        Clause::None => match partition_type {
            Type::Range => {
                validation_error(mysql::ErrPartitionRequiresValues, &["RANGE", "LESS THAN"])
            }
            Type::List => validation_error(mysql::ErrPartitionRequiresValues, &["LIST", "IN"]),
            Type::SystemTime => validation_error(mysql::ErrSystemVersioningWrongPartitions, &[]),
            _ => Ok(()),
        },
        Clause::LessThan(expressions) => {
            if !matches!(partition_type, Type::Range | Type::None) {
                return validation_error(mysql::ErrPartitionWrongValues, &["RANGE", "LESS THAN"]);
            }
            if columns == 0 && expressions.len() != 1 {
                return validation_error(mysql::ErrTooManyValues, &["RANGE"]);
            }
            if columns > 0 && expressions.len() != columns {
                return validation_error(mysql::ErrPartitionColumnList, &[]);
            }
            Ok(())
        }
        Clause::In(values) => {
            if !matches!(partition_type, Type::List | Type::None) {
                return validation_error(mysql::ErrPartitionWrongValues, &["LIST", "IN"]);
            }
            if values.is_empty() {
                return Ok(());
            }
            let mut expected = values[0].len();
            let mut start = 1;
            if expected == 1 && matches!(values[0][0].Kind, parser_ast::ExprKind::DefaultValue) {
                if values.len() == 1 {
                    return Ok(());
                }
                expected = values[1].len();
                start = 2;
            }
            for value in &values[start..] {
                if value.len() != expected
                    && !(value.len() == 1
                        && matches!(value[0].Kind, parser_ast::ExprKind::DefaultValue))
                {
                    return validation_error(mysql::ErrPartitionColumnList, &[]);
                }
            }
            if columns == 0 && expected != 1 {
                return validation_error(mysql::ErrRowSinglePartitionField, &[]);
            }
            if columns > 0 && expected != columns {
                return validation_error(mysql::ErrPartitionColumnList, &[]);
            }
            Ok(())
        }
        Clause::History { .. } if !matches!(partition_type, Type::SystemTime | Type::None) => {
            validation_error(mysql::ErrWrongPartitionTypeExpectedSystemTime, &[])
        }
        Clause::History { .. } => Ok(()),
    }
}

/// 校验并规范化整表分区选项。
fn validate_partition_options(
    options: &mut parser_ast::PartitionOptions,
) -> Result<(), errors::Error> {
    use parser_ast::PartitionType as Type;
    let validation_error = |code: u16, args: &[&str]| {
        Err(terror::ClassDDL
            .NewStd(terror::ErrCode(code as isize))
            .GenWithStackByArgs(&args.iter().map(|value| (*value).into()).collect::<Vec<_>>()))
    };
    if options.PartitionMethod.Num != 0
        && !options.Definitions.is_empty()
        && options.PartitionMethod.Num != options.Definitions.len() as u64
    {
        return validation_error(mysql::ErrPartitionWrongNoPart, &[]);
    }
    if let Some(first) = options.Definitions.first() {
        options.PartitionMethod.Num = options.Definitions.len() as u64;
        let sub_count = first.Sub.len();
        if options
            .Definitions
            .iter()
            .skip(1)
            .any(|definition| definition.Sub.len() != sub_count)
        {
            return validation_error(mysql::ErrPartitionWrongNoSubpart, &[]);
        }
        if let Some(sub) = options.Sub.as_mut() {
            if sub.Num != 0 && sub_count != 0 && sub.Num != sub_count as u64 {
                return validation_error(mysql::ErrPartitionWrongNoSubpart, &[]);
            }
            if sub_count != 0 {
                sub.Num = sub_count as u64;
            }
        } else if sub_count != 0 {
            return validation_error(mysql::ErrSubpartition, &[]);
        }
    }
    match options.PartitionMethod.Tp {
        Type::Hash | Type::Key if options.PartitionMethod.Num == 0 => {
            options.PartitionMethod.Num = 1
        }
        Type::Range | Type::List
            if options.PartitionMethod.Interval.is_none() && options.Definitions.is_empty() =>
        {
            return validation_error(
                mysql::ErrPartitionsMustBeDefined,
                &[if options.PartitionMethod.Tp == Type::Range {
                    "RANGE"
                } else {
                    "LIST"
                }],
            );
        }
        Type::SystemTime if options.Definitions.len() < 2 => {
            return validation_error(mysql::ErrSystemVersioningWrongPartitions, &[]);
        }
        _ => {}
    }
    for definition in &options.Definitions {
        validate_partition_clause(
            &definition.Clause,
            options.PartitionMethod.Tp,
            options.PartitionMethod.ColumnNames.len(),
        )?;
    }
    Ok(())
}

/// 按名称解析数据脱敏策略限制操作；未知返回 (None, false)。
pub fn getMaskingPolicyRestrictOp(name: &str) -> (ast::MaskingPolicyRestrictOps, bool) {
    // Go 先把名称转成大写再匹配四种限制操作；未知名称显式返回 None/false。
    match name.to_uppercase().as_str() {
        ast::MaskingPolicyRestrictNameInsertIntoSelect => {
            (ast::MaskingPolicyRestrictOpInsertIntoSelect, true)
        }
        ast::MaskingPolicyRestrictNameUpdateSelect => {
            (ast::MaskingPolicyRestrictOpUpdateSelect, true)
        }
        ast::MaskingPolicyRestrictNameDeleteSelect => {
            (ast::MaskingPolicyRestrictOpDeleteSelect, true)
        }
        ast::MaskingPolicyRestrictNameCTAS => (ast::MaskingPolicyRestrictOpCTAS, true),
        _ => (ast::MaskingPolicyRestrictOpNone, false),
    }
}

fn semantic_value_text(value: &dyn Any) -> String {
    if let Some(value) = value.downcast_ref::<i64>() {
        value.to_string()
    } else if let Some(value) = value.downcast_ref::<u64>() {
        value.to_string()
    } else if let Some(value) = value.downcast_ref::<f64>() {
        value.to_string()
    } else if let Some(value) = value.downcast_ref::<String>() {
        value.clone()
    } else if let Some(value) = value.downcast_ref::<bool>() {
        value.to_string()
    } else if let Some(value) = value.downcast_ref::<Value>() {
        match value {
            Value::Null => "NULL".to_owned(),
            Value::String(value) => value.clone(),
        }
    } else if let Some(value) = value.downcast_ref::<parser_test_driver::MyDecimal>() {
        value.String()
    } else if let Some(value) = value.downcast_ref::<parser_test_driver::HexLiteral>() {
        format!(
            "0x{}",
            value
                .0
                .iter()
                .map(|byte| format!("{byte:02x}"))
                .collect::<String>()
        )
    } else if let Some(value) = value.downcast_ref::<parser_test_driver::BitLiteral>() {
        format!(
            "0b{}",
            value
                .0
                .iter()
                .map(|byte| format!("{byte:08b}"))
                .collect::<String>()
        )
    } else {
        "<value>".to_owned()
    }
}

/// Convert lexer semantic values without erasing their SQL datum kind. This is
/// the Rust counterpart of test_driver.newValueExpr + DefaultTypeForValue.
fn semantic_value_expr(
    value: &dyn Any,
    charset_name: &str,
    collation: &str,
) -> parser_ast::ExprNode {
    if value.is::<()>() {
        parser_ast::ExprNode::NullValue()
    } else if let Some(value) = value.downcast_ref::<bool>() {
        parser_ast::ExprNode::BoolValue(*value)
    } else if let Some(value) = value.downcast_ref::<i32>() {
        parser_ast::ExprNode::IntValue(*value as i64)
    } else if let Some(value) = value.downcast_ref::<i64>() {
        parser_ast::ExprNode::IntValue(*value)
    } else if let Some(value) = value.downcast_ref::<u64>() {
        parser_ast::ExprNode::UintValue(*value)
    } else if let Some(value) = value.downcast_ref::<f32>() {
        parser_ast::ExprNode::Float32Value(*value)
    } else if let Some(value) = value.downcast_ref::<f64>() {
        parser_ast::ExprNode::FloatValue(*value)
    } else if let Some(value) = value.downcast_ref::<String>() {
        parser_ast::ExprNode::StringValue(value.clone(), charset_name, collation)
    } else if let Some(value) = value.downcast_ref::<Value>() {
        match value {
            Value::Null => parser_ast::ExprNode::NullValue(),
            Value::String(value) => {
                parser_ast::ExprNode::StringValue(value.clone(), charset_name, collation)
            }
        }
    } else if let Some(value) = value.downcast_ref::<parser_test_driver::MyDecimal>() {
        parser_ast::ExprNode::DecimalValue(value.String())
    } else if let Some(value) = value.downcast_ref::<parser_test_driver::HexLiteral>() {
        parser_ast::ExprNode::HexValue(value.0.clone(), charset_name, collation)
    } else if let Some(value) = value.downcast_ref::<parser_test_driver::BitLiteral>() {
        parser_ast::ExprNode::BitValue(value.0.clone(), charset_name, collation)
    } else {
        panic!("unsupported lexer literal semantic type")
    }
}

fn semantic_numeric_isize(value: &dyn Any) -> Option<isize> {
    if let Some(value) = value.downcast_ref::<u64>() {
        Some(*value as isize)
    } else if let Some(value) = value.downcast_ref::<i64>() {
        Some(*value as isize)
    } else if let Some(value) = value.downcast_ref::<isize>() {
        Some(*value)
    } else if let Some(value) = value.downcast_ref::<usize>() {
        Some(*value as isize)
    } else {
        semantic_value_text(value).parse().ok()
    }
}

fn result_set_from_item(item: &dyn Any) -> Option<parser_ast::ResultSetNode> {
    if let Some(source) = item.downcast_ref::<parser_ast::TableSource>() {
        Some(parser_ast::ResultSetNode::TableSource(source.clone()))
    } else {
        item.downcast_ref::<parser_ast::Join>()
            .cloned()
            .map(|join| parser_ast::ResultSetNode::Join(Box::new(join)))
    }
}
