// Code generated by goyacc DO NOT EDIT.

// Copyright 2026 AsterSQL.

// Copyright 2013 The ql Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSES/QL-LICENSE file.

// Copyright 2015 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// See the License for the specific language governing permissions and
// limitations under the License.

// Initial yacc source generated by ebnf2y[1]
// at 2013-10-04 23:10:47.861401015 +0200 CEST
//
//  $ ebnf2y -o ql.y -oe ql.ebnf -start StatementList -pkg ql -p _
//
//   [1]: http://github.com/cznic/ebnf2y

// goyacc 生成的 SQL LALR(1) 解析器核心。
//
// 对应 Go `parser.go` / goyacc 输出：包含语义值类型、token 常量、
// 稀疏动作表，以及 `yyParse` 移进/规约状态机。LALR 是自底向上语法分析，
// 语义动作在规约时构造 AST（抽象语法树）节点。

// ast、auth、charset、duration、mysql、opcode、types 和 Parser 均为跨文件依赖，模块连线留待后续统一处理。

// 主解析器按稳定边界组装：语义值、共享辅助、动作调度与 LR runtime。
include!("parser_value.rs");
include!("parser_semantic_support.rs");
mod parser_actions;
include!("parser_runtime.rs");
