[package]
name = "astersql-ddl-tests-metadatalock"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[package.metadata.porting]
go-package = "pkg/ddl/tests/metadatalock"
legacy-tasks = ["task-1546", "task-1547"]

[dev-dependencies]
"astersql-config" = { package = "astersql-config", path = "../../../config" }
"astersql-config-kerneltype" = { package = "astersql-config-kerneltype", path = "../../../config/kerneltype" }
"astersql-ddl" = { package = "astersql-ddl", path = "../.." }
"astersql-ddl-ingest-testutil" = { package = "astersql-ddl-ingest-testutil", path = "../../ingest/testutil" }
"astersql-errno" = { package = "astersql-errno", path = "../../../errno" }
"astersql-meta-model" = { package = "astersql-meta-model", path = "../../../meta/model" }
"astersql-server" = { package = "astersql-server", path = "../../../server" }
"astersql-testkit" = { package = "astersql-testkit", path = "../../../testkit" }
"astersql-testkit-testfailpoint" = { package = "astersql-testkit-testfailpoint", path = "../../../testkit/testfailpoint" }
"astersql-testkit-testsetup" = { package = "astersql-testkit-testsetup", path = "../../../testkit/testsetup" }
