[package]
name = "astersql-util-topsql-collector-mock"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[dependencies]
collector = { package = "astersql-util-topsql-collector", path = ".." }
logutil = { package = "astersql-util-logutil", path = "../../../logutil" }
parser = { package = "astersql-parser", path = "../../../../parser" }
stmtstats = { package = "astersql-util-topsql-stmtstats", path = "../../stmtstats" }

[package.metadata.porting]
go-package = "pkg/util/topsql/collector/mock"
legacy-tasks = ["task-589"]
