// Copyright 2026 AsterSQL.
// Copyright 2026 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and

// StepExecutor 的 mockall 替身（对齐 GoMock 生成物）。
//
// 为 DXF 步骤执行器（StepExecutor）提供可控 mock：可对 Init/RunSubtask/Cleanup
// 及框架信息访问器设置期望（expectation），供单元测试验证参数派发与错误返回。
// 子任务（subtask）是任务在某一步（Step）上切分出的可并行执行单元。
// limitations under the License.

// Source: github.com/pingcap/tidb/pkg/dxf/framework/taskexecutor/execute
// (interfaces: StepExecutor)

#![allow(non_snake_case)]

use anyhow::Result;
use execute::{
    CheckpointGetFunc, CheckpointUpdateFunc, Context, FrameworkInfo, StepExecFrameworkInfo,
    StepExecutor as StepExecutorTrait, SubtaskSummary,
};
use proto::step::Step;
use proto::subtask::{StepResource, Subtask};
use std::sync::Arc;

// Go 侧由 GoMock 生成；Rust 侧用 mockall 提供同等期望引擎。
// The Go source is generated by GoMock. `mockall` provides the corresponding
// production-grade Rust expectation engine: each `expect_*` method records a
// call contract, and the generated trait implementation dispatches arguments
// and configured return values through that contract.
// 同时实现 StepExecFrameworkInfo 与 StepExecutor trait。
mockall::mock! {
    pub StepExecutor {}

    impl StepExecFrameworkInfo for StepExecutor {
        fn restricted(&self);
        fn GetStep(&self) -> Step;
        fn GetResource(&self) -> Option<Arc<StepResource>>;
        fn SetResource(&self, resource: Arc<StepResource>);
        fn GetMeterRecorder(&self) -> Option<Arc<metering::Recorder>>;
        fn GetCheckpointUpdateFunc(&self) -> Option<CheckpointUpdateFunc>;
        fn GetCheckpointFunc(&self) -> Option<CheckpointGetFunc>;
    }

    impl StepExecutorTrait for StepExecutor {
        fn Init(&mut self, ctx: Context) -> Result<()>;
        fn RunSubtask(&mut self, ctx: Context, subtask: &mut Subtask) -> Result<()>;
        fn RealtimeSummary(&mut self) -> Option<&'static SubtaskSummary>;
        fn ResetSummary(&mut self);
        fn Cleanup(&mut self, ctx: Context) -> Result<()>;
        fn TaskMetaModified(&mut self, ctx: Context, new_meta: Vec<u8>) -> Result<()>;
        fn ResourceModified(&mut self, ctx: Context, new_resource: &StepResource) -> Result<()>;
        fn SetFrameworkInfo(&mut self, info: FrameworkInfo);
    }
}

/// mockall 生成的 `MockStepExecutor` 辅助方法（对齐 GoMock API）。
impl MockStepExecutor {
    /// 保留 GoMock 标记，供生成接口检查识别。
    /// Retains the GoMock marker used by generated-interface checks.
    pub fn ISGOMOCK(&self) {}

    /// 返回自身作为期望记录器（调用方可链式 `expect_*`）。
    /// Returns the mock itself as the expectation recorder.
    ///
    /// Rust callers configure individual calls with `expect_Init`,
    /// `expect_RunSubtask`, and the other generated `expect_*` methods.
    pub fn EXPECT(&mut self) -> &mut Self {
        self
    }
}

/// 创建空期望集合的新 mock 实例。
/// Creates a new mock instance with an empty expectation set.
pub fn NewMockStepExecutor() -> MockStepExecutor {
    MockStepExecutor::new()
}
