// Copyright 2025 PingCAP, Inc.
// Copyright 2026 AsterSQL.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// PrefixClient 的 mockall 生成替身（对齐 Go MockGen 产物）。
//
// 保留 Go 接口方法名与签名，便于测试侧用 EXPECT 配置返回值与调用次数。
// 源接口见 `s3like::PrefixClient`。

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pingcap/tidb/pkg/objstore/s3like (interfaces: PrefixClient)
// Generated by: mockgen -package mock github.com/pingcap/tidb/pkg/objstore/s3like PrefixClient

use anyhow::Result;
use s3like::{CopyInput, GetResp, HeadObjectResp, ListResp, PrefixClient, Uploader};
use storeapi::Context;

// Mockall provides the Rust equivalent of GoMock's controller, recorder, argument
// matcher, return action, and call-count verification behavior. Keep the Go
// interface's method names and signatures so callers can configure the same API.
// mockall 提供与 GoMock 控制器/录制器/参数匹配/返回动作/调用次数校验对等的能力。
mockall::mock! {
    pub PrefixClient {}

    impl PrefixClient for PrefixClient {
        fn CheckBucketExistence(&self, ctx: &Context) -> Result<()>;
        fn CheckGetObject(&self, ctx: &Context) -> Result<()>;
        fn CheckListObjects(&self, ctx: &Context) -> Result<()>;
        fn CheckPutAndDeleteObject(&self, ctx: &Context) -> Result<()>;
        fn CopyObject(&self, ctx: &Context, input: &CopyInput) -> Result<()>;
        fn DeleteObject(&self, ctx: &Context, name: &str) -> Result<()>;
        fn DeleteObjects(&self, ctx: &Context, names: &[String]) -> Result<()>;
        fn GetObject(
            &self,
            ctx: &Context,
            name: &str,
            start_offset: i64,
            end_offset: i64,
        ) -> Result<Option<GetResp>>;
        fn HeadObject(&self, ctx: &Context, name: &str) -> Result<Option<HeadObjectResp>>;
        fn IsObjectExists(&self, ctx: &Context, name: &str) -> Result<bool>;
        fn ListObjects<'a>(
            &self,
            ctx: &Context,
            extra_prefix: &str,
            start_after: &str,
            continuation_token: Option<&'a str>,
            max_keys: isize,
        ) -> Result<Option<ListResp>>;
        fn MultipartUploader(
            &self,
            name: &str,
            part_size: i64,
            concurrency: i32,
        ) -> Option<Box<dyn Uploader>>;
        fn MultipartWriter(&self, ctx: &Context, name: &str)
            -> Result<Option<Box<dyn objectio::Writer>>>;
        fn PutObject(&self, ctx: &Context, name: &str, data: &[u8]) -> Result<()>;
    }
}

/// NewMockPrefixClient creates a fresh mock, matching Go's constructor role.
/// 创建新的 PrefixClient mock，对应 Go 侧构造函数角色。
pub fn NewMockPrefixClient() -> MockPrefixClient {
    MockPrefixClient::new()
}

impl MockPrefixClient {
    /// EXPECT returns the mock so callers can configure generated expectations.
    /// 返回自身以便链式配置期望（对齐 Go EXPECT()）。
    pub fn EXPECT(&mut self) -> &mut Self {
        self
    }

    /// ISGOMOCK retains the generated Go marker method as a zero-value operation.
    /// 保留 Go 生成代码的 ISGOMOCK 标记方法，空实现。
    pub fn ISGOMOCK(&self) {}
}
