[package]
name = "astersql-util-topsql"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[features]
failpoints = ["dep:fail", "fail/failpoints"]

[dependencies]
collector = { package = "astersql-util-topsql-collector", path = "collector" }
fail = { version = "0.5", optional = true }
log = "0.4"
parser = { package = "astersql-parser", path = "../../parser" }
plancodec = { package = "astersql-util-plancodec", path = "../plancodec" }
stmtstats = { package = "astersql-util-topsql-stmtstats", path = "stmtstats" }
topsql_state = { package = "astersql-util-topsql-state", path = "state" }
topsql_reporter = { package = "astersql-util-topsql-reporter", path = "reporter" }

[dev-dependencies]
astersql-testkit-testsetup = { path = "../../testkit/testsetup" }
anyhow = "1"
cpuprofile = { package = "astersql-util-cpuprofile", path = "../cpuprofile" }
protobuf = "=2.8.0"
serial_test = "3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
topsql_mock = { package = "astersql-util-topsql-reporter-mock", path = "reporter/mock" }

[package.metadata.porting]
go-package = "pkg/util/topsql"
legacy-tasks = ["task-588", "task-590"]
