[package]
name = "astersql-executor"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[features]
nextgen = ["astersql-dxf-importinto/nextgen"]

[package.metadata.porting]
go-package = "pkg/executor"
legacy-tasks = ["task-1219", "task-1220", "task-1221", "task-1222", "task-1223", "task-1224", "task-1225", "task-1226", "task-1227", "task-1228", "task-1229", "task-1230", "task-1231", "task-1232", "task-1233", "task-1234", "task-1235", "task-1236", "task-1237", "task-1238", "task-1239", "task-1240", "task-1241", "task-1242", "task-1243", "task-1244", "task-1245", "task-1246", "task-1247", "task-1248", "task-1249", "task-1250", "task-1251", "task-1252", "task-1254", "task-1569", "task-1570", "task-1571", "task-1572", "task-1573", "task-1574", "task-1575", "task-1576", "task-1577", "task-1578", "task-1579", "task-1580", "task-1581", "task-1582", "task-1583", "task-1584", "task-1585", "task-1586", "task-1587", "task-1588", "task-1589", "task-1590", "task-1591", "task-1592", "task-1593"]

[dependencies]
"astersql-errors" = { package = "astersql-errors", path = "../errors" }
"astersql-bindinfo" = { package = "astersql-bindinfo", path = "../bindinfo" }
"astersql-config" = { package = "astersql-config", path = "../config" }
"astersql-config-deploymode" = { package = "astersql-config-deploymode", path = "../config/deploymode" }
"astersql-config-kerneltype" = { package = "astersql-config-kerneltype", path = "../config/kerneltype" }
"astersql-ddl" = { package = "astersql-ddl", path = "../ddl" }
"astersql-ddl-label" = { package = "astersql-ddl-label", path = "../ddl/label" }
"astersql-ddl-placement" = { package = "astersql-ddl-placement", path = "../ddl/placement" }
"astersql-ddl-schematracker" = { package = "astersql-ddl-schematracker", path = "../ddl/schematracker" }
"astersql-ddl-session" = { package = "astersql-ddl-session", path = "../ddl/session" }
"astersql-ddl-util" = { package = "astersql-ddl-util", path = "../ddl/util" }
"astersql-distsql" = { package = "astersql-distsql", path = "../distsql" }
"astersql-distsql-context" = { package = "astersql-distsql-context", path = "../distsql/context" }
"astersql-domain" = { package = "astersql-domain", path = "../domain" }
"astersql-domain-affinity" = { package = "astersql-domain-affinity", path = "../domain/affinity" }
"astersql-domain-infosync" = { package = "astersql-domain-infosync", path = "../domain/infosync" }
"astersql-domain-serverinfo" = { package = "astersql-domain-serverinfo", path = "../domain/serverinfo" }
"astersql-dxf-framework-handle" = { package = "astersql-dxf-framework-handle", path = "../dxf/framework/handle" }
"astersql-dxf-framework-proto" = { package = "astersql-dxf-framework-proto", path = "../dxf/framework/proto" }
"astersql-dxf-framework-storage" = { package = "astersql-dxf-framework-storage", path = "../dxf/framework/storage" }
"astersql-dxf-importinto" = { package = "astersql-dxf-importinto", path = "../dxf/importinto" }
"astersql-dxf-operator" = { package = "astersql-dxf-operator", path = "../dxf/operator" }
"astersql-errctx" = { package = "astersql-errctx", path = "../errctx" }
"astersql-errno" = { package = "astersql-errno", path = "../errno" }
"astersql-executor-aggfuncs" = { package = "astersql-executor-aggfuncs", path = "aggfuncs" }
"astersql-executor-aggregate" = { package = "astersql-executor-aggregate", path = "aggregate" }
"astersql-executor-importer" = { package = "astersql-executor-importer", path = "importer" }
"astersql-executor-internal-applycache" = { package = "astersql-executor-internal-applycache", path = "internal/applycache" }
"astersql-executor-internal-builder" = { package = "astersql-executor-internal-builder", path = "internal/builder" }
"astersql-executor-internal-calibrateresource" = { package = "astersql-executor-internal-calibrateresource", path = "internal/calibrateresource" }
"astersql-executor-internal-exec" = { package = "astersql-executor-internal-exec", path = "internal/exec" }
"astersql-executor-internal-mpp" = { package = "astersql-executor-internal-mpp", path = "internal/mpp" }
"astersql-executor-internal-pdhelper" = { package = "astersql-executor-internal-pdhelper", path = "internal/pdhelper" }
"astersql-executor-internal-querywatch" = { package = "astersql-executor-internal-querywatch", path = "internal/querywatch" }
"astersql-executor-internal-testutil" = { package = "astersql-executor-internal-testutil", path = "internal/testutil" }
"astersql-executor-internal-util" = { package = "astersql-executor-internal-util", path = "internal/util" }
"astersql-executor-internal-vecgroupchecker" = { package = "astersql-executor-internal-vecgroupchecker", path = "internal/vecgroupchecker" }
"astersql-executor-join" = { package = "astersql-executor-join", path = "join" }
"astersql-executor-join-joinversion" = { package = "astersql-executor-join-joinversion", path = "join/joinversion" }
"astersql-executor-lockstats" = { package = "astersql-executor-lockstats", path = "lockstats" }
"astersql-executor-metrics" = { package = "astersql-executor-metrics", path = "metrics" }
"astersql-executor-sortexec" = { package = "astersql-executor-sortexec", path = "sortexec" }
"astersql-executor-staticrecordset" = { package = "astersql-executor-staticrecordset", path = "staticrecordset" }
"astersql-executor-unionexec" = { package = "astersql-executor-unionexec", path = "unionexec" }
"astersql-executor-windows" = { package = "astersql-executor-windows", path = "windows" }
"astersql-expression" = { package = "astersql-expression", path = "../expression" }
"astersql-expression-aggregation" = { package = "astersql-expression-aggregation", path = "../expression/aggregation" }
"astersql-expression-exprctx" = { package = "astersql-expression-exprctx", path = "../expression/exprctx" }
"astersql-expression-sessionexpr" = { package = "astersql-expression-sessionexpr", path = "../expression/sessionexpr" }
"astersql-extension" = { package = "astersql-extension", path = "../extension" }
"astersql-infoschema" = { package = "astersql-infoschema", path = "../infoschema" }
"astersql-infoschema-context" = { package = "astersql-infoschema-context", path = "../infoschema/context" }
"astersql-keyspace" = { package = "astersql-keyspace", path = "../keyspace" }
"astersql-kv" = { package = "astersql-kv", path = "../kv" }
"astersql-lightning-backend-encode" = { package = "astersql-lightning-backend-encode", path = "../lightning/backend/encode" }
"astersql-lightning-backend-kv" = { package = "astersql-lightning-backend-kv", path = "../lightning/backend/kv" }
"astersql-lightning-log" = { package = "astersql-lightning-log", path = "../lightning/log" }
"astersql-lightning-mydump" = { package = "astersql-lightning-mydump", path = "../lightning/mydump" }
"astersql-meta" = { package = "astersql-meta", path = "../meta" }
"astersql-meta-autoid" = { package = "astersql-meta-autoid", path = "../meta/autoid" }
"astersql-meta-metadef" = { package = "astersql-meta-metadef", path = "../meta/metadef" }
"astersql-meta-model" = { package = "astersql-meta-model", path = "../meta/model" }
"astersql-metrics" = { package = "astersql-metrics", path = "../metrics" }
"astersql-objstore" = { package = "astersql-objstore", path = "../objstore" }
"astersql-objstore-compressedio" = { package = "astersql-objstore-compressedio", path = "../objstore/compressedio" }
"astersql-objstore-storeapi" = { package = "astersql-objstore-storeapi", path = "../objstore/storeapi" }
"astersql-parser" = { package = "astersql-parser", path = "../parser" }
"astersql-parser-ast" = { package = "astersql-parser-ast", path = "../parser/ast" }
"astersql-parser-auth" = { package = "astersql-parser-auth", path = "../parser/auth" }
"astersql-parser-charset" = { package = "astersql-parser-charset", path = "../parser/charset" }
"astersql-parser-format" = { package = "astersql-parser-format", path = "../parser/format" }
"astersql-parser-mysql" = { package = "astersql-parser-mysql", path = "../parser/mysql" }
"astersql-parser-terror" = { package = "astersql-parser-terror", path = "../parser/terror" }
"astersql-parser-tidb" = { package = "astersql-parser-tidb", path = "../parser/tidb" }
"astersql-parser-types" = { package = "astersql-parser-types", path = "../parser/types" }
"astersql-planner" = { package = "astersql-planner", path = "../planner" }
"astersql-planner-cardinality" = { package = "astersql-planner-cardinality", path = "../planner/cardinality" }
"astersql-planner-core" = { package = "astersql-planner-core", path = "../planner/core" }
"astersql-planner-core-base" = { package = "astersql-planner-core-base", path = "../planner/core/base" }
"astersql-planner-core-operator-logicalop" = { package = "astersql-planner-core-operator-logicalop", path = "../planner/core/operator/logicalop" }
"astersql-planner-core-operator-physicalop" = { package = "astersql-planner-core-operator-physicalop", path = "../planner/core/operator/physicalop" }
"astersql-planner-core-resolve" = { package = "astersql-planner-core-resolve", path = "../planner/core/resolve" }
"astersql-planner-core-rule" = { package = "astersql-planner-core-rule", path = "../planner/core/rule" }
"astersql-planner-extstore" = { package = "astersql-planner-extstore", path = "../planner/extstore" }
"astersql-planner-indexadvisor" = { package = "astersql-planner-indexadvisor", path = "../planner/indexadvisor" }
"astersql-planner-planctx" = { package = "astersql-planner-planctx", path = "../planner/planctx" }
"astersql-planner-util" = { package = "astersql-planner-util", path = "../planner/util" }
"astersql-planner-util-coreusage" = { package = "astersql-planner-util-coreusage", path = "../planner/util/coreusage" }
"astersql-planner-util-fixcontrol" = { package = "astersql-planner-util-fixcontrol", path = "../planner/util/fixcontrol" }
"astersql-planner-util-partitionpruning" = { package = "astersql-planner-util-partitionpruning", path = "../planner/util/partitionpruning" }
"astersql-plugin" = { package = "astersql-plugin", path = "../plugin" }
"astersql-privilege" = { package = "astersql-privilege", path = "../privilege" }
"astersql-privilege-privileges" = { package = "astersql-privilege-privileges", path = "../privilege/privileges" }
"astersql-resourcegroup" = { package = "astersql-resourcegroup", path = "../resourcegroup" }
"astersql-resourcegroup-runaway" = { package = "astersql-resourcegroup-runaway", path = "../resourcegroup/runaway" }
"astersql-resourcemanager-pool-workerpool" = { package = "astersql-resourcemanager-pool-workerpool", path = "../resourcemanager/pool/workerpool" }
"astersql-resourcemanager-util" = { package = "astersql-resourcemanager-util", path = "../resourcemanager/util" }
"astersql-session-sessmgr" = { package = "astersql-session-sessmgr", path = "../session/sessmgr" }
"astersql-session-txninfo" = { package = "astersql-session-txninfo", path = "../session/txninfo" }
"astersql-sessionctx" = { package = "astersql-sessionctx", path = "../sessionctx" }
"astersql-sessionctx-sessionstates" = { package = "astersql-sessionctx-sessionstates", path = "../sessionctx/sessionstates" }
"astersql-sessionctx-slowlogrule" = { package = "astersql-sessionctx-slowlogrule", path = "../sessionctx/slowlogrule" }
"astersql-sessionctx-stmtctx" = { package = "astersql-sessionctx-stmtctx", path = "../sessionctx/stmtctx" }
"astersql-sessionctx-vardef" = { package = "astersql-sessionctx-vardef", path = "../sessionctx/vardef" }
"astersql-sessionctx-variable" = { package = "astersql-sessionctx-variable", path = "../sessionctx/variable" }
"astersql-sessiontxn" = { package = "astersql-sessiontxn", path = "../sessiontxn" }
"astersql-sessiontxn-staleread" = { package = "astersql-sessiontxn-staleread", path = "../sessiontxn/staleread" }
"astersql-statistics" = { package = "astersql-statistics", path = "../statistics" }
"astersql-statistics-handle" = { package = "astersql-statistics-handle", path = "../statistics/handle" }
"astersql-statistics-handle-cache" = { package = "astersql-statistics-handle-cache", path = "../statistics/handle/cache" }
"astersql-statistics-handle-logutil" = { package = "astersql-statistics-handle-logutil", path = "../statistics/handle/logutil" }
"astersql-statistics-handle-storage" = { package = "astersql-statistics-handle-storage", path = "../statistics/handle/storage" }
"astersql-statistics-handle-types" = { package = "astersql-statistics-handle-types", path = "../statistics/handle/types" }
"astersql-statistics-handle-util" = { package = "astersql-statistics-handle-util", path = "../statistics/handle/util" }
"astersql-statistics-util" = { package = "astersql-statistics-util", path = "../statistics/util" }
"astersql-store-driver-backoff" = { package = "astersql-store-driver-backoff", path = "../store/driver/backoff" }
"astersql-store-driver-txn" = { package = "astersql-store-driver-txn", path = "../store/driver/txn" }
"astersql-store-helper" = { package = "astersql-store-helper", path = "../store/helper" }
"astersql-table" = { package = "astersql-table", path = "../table" }
"astersql-table-tables" = { package = "astersql-table-tables", path = "../table/tables" }
"astersql-table-temptable" = { package = "astersql-table-temptable", path = "../table/temptable" }
"astersql-tablecodec" = { package = "astersql-tablecodec", path = "../tablecodec" }
"astersql-types" = { package = "astersql-types", path = "../types" }
"astersql-types-parser_driver" = { package = "astersql-types-parser_driver", path = "../types/parser_driver" }
"astersql-util" = { package = "astersql-util", path = "../util" }
"astersql-util-admin" = { package = "astersql-util-admin", path = "../util/admin" }
"astersql-util-breakpoint" = { package = "astersql-util-breakpoint", path = "../util/breakpoint" }
"astersql-util-channel" = { package = "astersql-util-channel", path = "../util/channel" }
"astersql-util-chunk" = { package = "astersql-util-chunk", path = "../util/chunk" }
"astersql-util-codec" = { package = "astersql-util-codec", path = "../util/codec" }
"astersql-util-collate" = { package = "astersql-util-collate", path = "../util/collate" }
"astersql-util-config" = { package = "astersql-util-config", path = "../util/config" }
"astersql-util-context" = { package = "astersql-util-context", path = "../util/context" }
"astersql-util-cteutil" = { package = "astersql-util-cteutil", path = "../util/cteutil" }
"astersql-util-dbterror" = { package = "astersql-util-dbterror", path = "../util/dbterror" }
"astersql-util-dbterror-exeerrors" = { package = "astersql-util-dbterror-exeerrors", path = "../util/dbterror/exeerrors" }
"astersql-util-dbterror-plannererrors" = { package = "astersql-util-dbterror-plannererrors", path = "../util/dbterror/plannererrors" }
"astersql-util-deadlockhistory" = { package = "astersql-util-deadlockhistory", path = "../util/deadlockhistory" }
"astersql-util-disk" = { package = "astersql-util-disk", path = "../util/disk" }
"astersql-util-disttask" = { package = "astersql-util-disttask", path = "../util/disttask" }
"astersql-util-execdetails" = { package = "astersql-util-execdetails", path = "../util/execdetails" }
"astersql-util-format" = { package = "astersql-util-format", path = "../util/format" }
"astersql-util-gcutil" = { package = "astersql-util-gcutil", path = "../util/gcutil" }
"astersql-util-globalconn" = { package = "astersql-util-globalconn", path = "../util/globalconn" }
"astersql-util-hack" = { package = "astersql-util-hack", path = "../util/hack" }
"astersql-util-hint" = { package = "astersql-util-hint", path = "../util/hint" }
"astersql-util-intest" = { package = "astersql-util-intest", path = "../util/intest" }
"astersql-util-keydecoder" = { package = "astersql-util-keydecoder", path = "../util/keydecoder" }
"astersql-util-logutil" = { package = "astersql-util-logutil", path = "../util/logutil" }
"astersql-util-logutil-consistency" = { package = "astersql-util-logutil-consistency", path = "../util/logutil/consistency" }
"astersql-util-mathutil" = { package = "astersql-util-mathutil", path = "../util/mathutil" }
"astersql-util-memory" = { package = "astersql-util-memory", path = "../util/memory" }
"astersql-util-parser" = { package = "astersql-util-parser", path = "../util/parser" }
"astersql-util-password-validation" = { package = "astersql-util-password-validation", path = "../util/password-validation" }
"astersql-util-plancodec" = { package = "astersql-util-plancodec", path = "../util/plancodec" }
"astersql-util-printer" = { package = "astersql-util-printer", path = "../util/printer" }
"astersql-util-ranger" = { package = "astersql-util-ranger", path = "../util/ranger" }
"astersql-util-ranger-context" = { package = "astersql-util-ranger-context", path = "../util/ranger/context" }
"astersql-util-redact" = { package = "astersql-util-redact", path = "../util/redact" }
"astersql-util-regionsplit" = { package = "astersql-util-regionsplit", path = "../util/regionsplit" }
"astersql-util-replayer" = { package = "astersql-util-replayer", path = "../util/replayer" }
"astersql-util-resourcegrouptag" = { package = "astersql-util-resourcegrouptag", path = "../util/resourcegrouptag" }
"astersql-util-rowDecoder" = { package = "astersql-util-rowDecoder", path = "../util/rowDecoder" }
"astersql-util-rowcodec" = { package = "astersql-util-rowcodec", path = "../util/rowcodec" }
"astersql-util-sem" = { package = "astersql-util-sem", path = "../util/sem" }
"astersql-util-sem-compat" = { package = "astersql-util-sem-compat", path = "../util/sem/compat" }
"astersql-util-sem-v2" = { package = "astersql-util-sem-v2", path = "../util/sem/v2" }
"astersql-util-servermemorylimit" = { package = "astersql-util-servermemorylimit", path = "../util/servermemorylimit" }
"astersql-util-set" = { package = "astersql-util-set", path = "../util/set" }
"astersql-util-size" = { package = "astersql-util-size", path = "../util/size" }
"astersql-util-sqlescape" = { package = "astersql-util-sqlescape", path = "../util/sqlescape" }
"astersql-util-sqlexec" = { package = "astersql-util-sqlexec", path = "../util/sqlexec" }
"astersql-util-sqlkiller" = { package = "astersql-util-sqlkiller", path = "../util/sqlkiller" }
"astersql-util-stmtsummary" = { package = "astersql-util-stmtsummary", path = "../util/stmtsummary" }
"astersql-util-stmtsummary-v2" = { package = "astersql-util-stmtsummary-v2", path = "../util/stmtsummary/v2" }
"astersql-util-stringutil" = { package = "astersql-util-stringutil", path = "../util/stringutil" }
"astersql-util-syncutil" = { package = "astersql-util-syncutil", path = "../util/syncutil" }
"astersql-util-table-filter" = { package = "astersql-util-table-filter", path = "../util/table-filter" }
"astersql-util-tiflash" = { package = "astersql-util-tiflash", path = "../util/tiflash" }
"astersql-util-timeutil" = { package = "astersql-util-timeutil", path = "../util/timeutil" }
"astersql-util-tls" = { package = "astersql-util-tls", path = "../util/tls" }
"astersql-util-topsql" = { package = "astersql-util-topsql", path = "../util/topsql" }
"astersql-util-topsql-state" = { package = "astersql-util-topsql-state", path = "../util/topsql/state" }
"astersql-util-topsql-stmtstats" = { package = "astersql-util-topsql-stmtstats", path = "../util/topsql/stmtstats" }
"astersql-util-traceevent" = { package = "astersql-util-traceevent", path = "../util/traceevent" }
"astersql-util-tracing" = { package = "astersql-util-tracing", path = "../util/tracing" }
fail = { version = "0.5.1", features = ["failpoints"] }

[dev-dependencies]
"astersql-expression-exprstatic" = { package = "astersql-expression-exprstatic", path = "../expression/exprstatic" }
"astersql-objstore-s3like" = { package = "astersql-objstore-s3like", path = "../objstore/s3like" }
"astersql-planner-property" = { package = "astersql-planner-property", path = "../planner/property" }
"astersql-planner-util-coretestsdk" = { package = "astersql-planner-util-coretestsdk", path = "../planner/util/coretestsdk" }
"astersql-server" = { package = "astersql-server", path = "../server" }
"astersql-session" = { package = "astersql-session", path = "../session" }
"astersql-session-sessionapi" = { package = "astersql-session-sessionapi", path = "../session/sessionapi" }
"astersql-store-copr" = { package = "astersql-store-copr", path = "../store/copr" }
"astersql-store-driver-error" = { package = "astersql-store-driver-error", path = "../store/driver/error" }
"astersql-store-mockstore" = { package = "astersql-store-mockstore", path = "../store/mockstore" }
"astersql-store-mockstore-unistore" = { package = "astersql-store-mockstore-unistore", path = "../store/mockstore/unistore" }
"astersql-testkit" = { package = "astersql-testkit", path = "../testkit" }
"astersql-testkit-external" = { package = "astersql-testkit-external", path = "../testkit/external" }
"astersql-testkit-testfailpoint" = { package = "astersql-testkit-testfailpoint", path = "../testkit/testfailpoint" }
"astersql-testkit-testmain" = { package = "astersql-testkit-testmain", path = "../testkit/testmain" }
"astersql-testkit-testsetup" = { package = "astersql-testkit-testsetup", path = "../testkit/testsetup" }
"astersql-testkit-testutil" = { package = "astersql-testkit-testutil", path = "../testkit/testutil" }
"astersql-util-benchdaily" = { package = "astersql-util-benchdaily", path = "../util/benchdaily" }
"astersql-util-mock" = { package = "astersql-util-mock", path = "../util/mock" }
"astersql-util-paging" = { package = "astersql-util-paging", path = "../util/paging" }
"astersql-util-tableutil" = { package = "astersql-util-tableutil", path = "../util/tableutil" }
"astersql-util-topsql-collector-mock" = { package = "astersql-util-topsql-collector-mock", path = "../util/topsql/collector/mock" }
