[package]
name = "astersql-executor-test-splittest"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[package.metadata.porting]
go-package = "pkg/executor/test/splittest"
legacy-tasks = ["task-1600"]

[dev-dependencies]
"astersql-ddl" = { package = "astersql-ddl", path = "../../../ddl" }
"astersql-domain-infosync" = { package = "astersql-domain-infosync", path = "../../../domain/infosync" }
"astersql-executor" = { package = "astersql-executor", path = "../.." }
"astersql-kv" = { package = "astersql-kv", path = "../../../kv" }
"astersql-parser-terror" = { package = "astersql-parser-terror", path = "../../../parser/terror" }
"astersql-sessionctx-vardef" = { package = "astersql-sessionctx-vardef", path = "../../../sessionctx/vardef" }
"astersql-store-copr" = { package = "astersql-store-copr", path = "../../../store/copr" }
"astersql-store-driver-backoff" = { package = "astersql-store-driver-backoff", path = "../../../store/driver/backoff" }
"astersql-store-helper" = { package = "astersql-store-helper", path = "../../../store/helper" }
"astersql-table" = { package = "astersql-table", path = "../../../table" }
"astersql-testkit" = { package = "astersql-testkit", path = "../../../testkit" }
"astersql-testkit-external" = { package = "astersql-testkit-external", path = "../../../testkit/external" }
"astersql-util-benchdaily" = { package = "astersql-util-benchdaily", path = "../../../util/benchdaily" }
"astersql-util-dbterror" = { package = "astersql-util-dbterror", path = "../../../util/dbterror" }
"astersql-util-dbterror-plannererrors" = { package = "astersql-util-dbterror-plannererrors", path = "../../../util/dbterror/plannererrors" }
"astersql-util-regionsplit" = { package = "astersql-util-regionsplit", path = "../../../util/regionsplit" }
