[package]
name = "astersql-planner-core-casetest-hint"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[package.metadata.porting]
go-package = "pkg/planner/core/casetest/hint"
legacy-tasks = ["task-1408"]

[dev-dependencies]
"astersql-config" = { package = "astersql-config", path = "../../../../config" }
"astersql-domain" = { package = "astersql-domain", path = "../../../../domain" }
"astersql-domain-infosync" = { package = "astersql-domain-infosync", path = "../../../../domain/infosync" }
"astersql-meta-model" = { package = "astersql-meta-model", path = "../../../../meta/model" }
"astersql-parser" = { package = "astersql-parser", path = "../../../../parser" }
"astersql-parser-ast" = { package = "astersql-parser-ast", path = "../../../../parser/ast" }
"astersql-sessionctx-variable" = { package = "astersql-sessionctx-variable", path = "../../../../sessionctx/variable" }
"astersql-store-mockstore" = { package = "astersql-store-mockstore", path = "../../../../store/mockstore" }
"astersql-testkit" = { package = "astersql-testkit", path = "../../../../testkit" }
"astersql-util-hint" = { package = "astersql-util-hint", path = "../../../../util/hint" }
"astersql-testkit-testfailpoint" = { package = "astersql-testkit-testfailpoint", path = "../../../../testkit/testfailpoint" }
"astersql-testkit-testmain" = { package = "astersql-testkit-testmain", path = "../../../../testkit/testmain" }
"astersql-testkit-testsetup" = { package = "astersql-testkit-testsetup", path = "../../../../testkit/testsetup" }
