[package]
name = "astersql-objstore-s3like"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[dependencies]
anyhow = "1"
fail = { version = "0.5.1", features = ["failpoints"] }
metricscommon = { package = "astersql-metrics-common", path = "../../metrics/common" }
mockall = "0.13"
objectio = { package = "astersql-objstore-objectio", path = "../objectio" }
os_pipe = "1"
prefetch = { package = "astersql-util-prefetch", path = "../../util/prefetch" }
prometheus = "0.14"
regex = "1"
storeapi = { package = "astersql-objstore-storeapi", path = "../storeapi" }
tracing = "0.1"
url = "2"

[dev-dependencies]
s3like_mock = { package = "astersql-objstore-s3like-mock", path = "mock" }

[[test]]
name = "permission_test"
path = "permission_test.rs"

[package.metadata.porting]
go-package = "pkg/objstore/s3like"
legacy-tasks = ["task-481"]
