[package]
name = "astersql-planner-core-casetest-planstats"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[package.metadata.porting]
go-package = "pkg/planner/core/casetest/planstats"
legacy-tasks = ["task-1421"]

[dev-dependencies]
"astersql-config" = { package = "astersql-config", path = "../../../../config" }
"astersql-domain" = { package = "astersql-domain", path = "../../../../domain" }
"astersql-executor" = { package = "astersql-executor", path = "../../../../executor" }
"astersql-meta-model" = { package = "astersql-meta-model", path = "../../../../meta/model" }
"astersql-parser" = { package = "astersql-parser", path = "../../../../parser" }
"astersql-parser-ast" = { package = "astersql-parser-ast", path = "../../../../parser/ast" }
"astersql-planner" = { package = "astersql-planner", path = "../../.." }
"astersql-planner-core-base" = { package = "astersql-planner-core-base", path = "../../base" }
"astersql-planner-core-operator-physicalop" = { package = "astersql-planner-core-operator-physicalop", path = "../../operator/physicalop" }
"astersql-planner-core-resolve" = { package = "astersql-planner-core-resolve", path = "../../resolve" }
"astersql-planner-core-rule" = { package = "astersql-planner-core-rule", path = "../../rule" }
"astersql-sessionctx" = { package = "astersql-sessionctx", path = "../../../../sessionctx" }
"astersql-sessionctx-stmtctx" = { package = "astersql-sessionctx-stmtctx", path = "../../../../sessionctx/stmtctx" }
"astersql-sessionctx-vardef" = { package = "astersql-sessionctx-vardef", path = "../../../../sessionctx/vardef" }
"astersql-statistics" = { package = "astersql-statistics", path = "../../../../statistics" }
"astersql-statistics-asyncload" = { package = "astersql-statistics-asyncload", path = "../../../../statistics/asyncload" }
"astersql-statistics-handle" = { package = "astersql-statistics-handle", path = "../../../../statistics/handle" }
"astersql-statistics-handle-ddl-testutil" = { package = "astersql-statistics-handle-ddl-testutil", path = "../../../../statistics/handle/ddl/testutil" }
"astersql-statistics-handle-types" = { package = "astersql-statistics-handle-types", path = "../../../../statistics/handle/types" }
"astersql-testkit" = { package = "astersql-testkit", path = "../../../../testkit" }
"astersql-testkit-testfailpoint" = { package = "astersql-testkit-testfailpoint", path = "../../../../testkit/testfailpoint" }
"astersql-testkit-testmain" = { package = "astersql-testkit-testmain", path = "../../../../testkit/testmain" }
"astersql-testkit-testsetup" = { package = "astersql-testkit-testsetup", path = "../../../../testkit/testsetup" }
"astersql-util-dbutil" = { package = "astersql-util-dbutil", path = "../../../../util/dbutil" }
