[package]
name = "astersql-statistics-handle-handletest-analyze"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[package.metadata.porting]
go-package = "pkg/statistics/handle/handletest/analyze"
legacy-tasks = ["task-1631"]

[dev-dependencies]
"astersql-domain" = { package = "astersql-domain", path = "../../../../domain" }
"astersql-statistics" = { package = "astersql-statistics", path = "../../.." }
"astersql-testkit" = { package = "astersql-testkit", path = "../../../../testkit" }
"astersql-testkit-testsetup" = { package = "astersql-testkit-testsetup", path = "../../../../testkit/testsetup" }
