[package]
name = "astersql-planner-cardinality"
version.workspace = true
edition.workspace = true
publish.workspace = true
autotests = false

[lib]
path = "lib.rs"
doctest = false

[dependencies]
chrono-tz = "0.10"
fail = { version = "0.5", features = ["failpoints"] }
chunk-dependency = { package = "astersql-util-chunk", path = "../../util/chunk" }
codec-dependency = { package = "astersql-util-codec", path = "../../util/codec" }
collate-dependency = { package = "astersql-util-collate", path = "../../util/collate" }
cost-dependency = { package = "astersql-planner-core-cost", path = "../core/cost" }
expression-dependency = { package = "astersql-expression", path = "../../expression" }
kv-dependency = { package = "astersql-kv", path = "../../kv" }
logutil-dependency = { package = "astersql-util-logutil", path = "../../util/logutil" }
mathutil-dependency = { package = "astersql-util-mathutil", path = "../../util/mathutil" }
model-dependency = { package = "astersql-meta-model", path = "../../meta/model" }
mysql-dependency = { package = "astersql-parser-mysql", path = "../../parser/mysql" }
parser-ast-dependency = { package = "astersql-parser-ast", path = "../../parser/ast" }
planctx-dependency = { package = "astersql-planner-planctx", path = "../planctx" }
planutil-dependency = { package = "astersql-planner-util", path = "../util" }
property-dependency = { package = "astersql-planner-property", path = "../property" }
ranger-dependency = { package = "astersql-util-ranger", path = "../../util/ranger" }
stmtctx-dependency = { package = "astersql-sessionctx-stmtctx", path = "../../sessionctx/stmtctx" }
statistics-dependency = { package = "astersql-statistics", path = "../../statistics" }
tablecodec-dependency = { package = "astersql-tablecodec", path = "../../tablecodec" }
types-dependency = { package = "astersql-types", path = "../../types" }
vardef-dependency = { package = "astersql-sessionctx-vardef", path = "../../sessionctx/vardef" }
variable-dependency = { package = "astersql-sessionctx-variable", path = "../../sessionctx/variable" }

[dev-dependencies]
exprstatic = { package = "astersql-expression-exprstatic", path = "../../expression/exprstatic" }
testsetup = { package = "astersql-testkit-testsetup", path = "../../testkit/testsetup" }

[package.metadata.porting]
go-package = "pkg/planner/cardinality"
