[package]
name = "astersql-dxf-framework-taskexecutor"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[package.metadata.porting]
go-package = "pkg/dxf/framework/taskexecutor"
legacy-tasks = ["task-844", "task-848", "task-1565"]

[dependencies]
"astersql-lightning-log" = { package = "astersql-lightning-log", path = "../../../lightning/log" }

[target.'cfg(any())'.dependencies]
"astersql-config" = { package = "astersql-config", path = "../../../config" }
"astersql-domain-sqlsvrapi" = { package = "astersql-domain-sqlsvrapi", path = "../../../domain/sqlsvrapi" }
"astersql-dxf-framework-dxfmetric" = { package = "astersql-dxf-framework-dxfmetric", path = "../dxfmetric" }
"astersql-dxf-framework-dxfutil" = { package = "astersql-dxf-framework-dxfutil", path = "../dxfutil" }
"astersql-dxf-framework-handle" = { package = "astersql-dxf-framework-handle", path = "../handle" }
"astersql-dxf-framework-metering" = { package = "astersql-dxf-framework-metering", path = "../metering" }
"astersql-dxf-framework-proto" = { package = "astersql-dxf-framework-proto", path = "../proto" }
"astersql-dxf-framework-scheduler" = { package = "astersql-dxf-framework-scheduler", path = "../scheduler" }
"astersql-dxf-framework-storage" = { package = "astersql-dxf-framework-storage", path = "../storage" }
"astersql-dxf-framework-taskexecutor-execute" = { package = "astersql-dxf-framework-taskexecutor-execute", path = "execute" }
"astersql-kv" = { package = "astersql-kv", path = "../../../kv" }
"astersql-metrics" = { package = "astersql-metrics", path = "../../../metrics" }
"astersql-objstore" = { package = "astersql-objstore", path = "../../../objstore" }
"astersql-sessionctx" = { package = "astersql-sessionctx", path = "../../../sessionctx" }
"astersql-sessionctx-vardef" = { package = "astersql-sessionctx-vardef", path = "../../../sessionctx/vardef" }
"astersql-util" = { package = "astersql-util", path = "../../../util" }
"astersql-util-backoff" = { package = "astersql-util-backoff", path = "../../../util/backoff" }
"astersql-util-gctuner" = { package = "astersql-util-gctuner", path = "../../../util/gctuner" }
"astersql-util-injectfailpoint" = { package = "astersql-util-injectfailpoint", path = "../../../util/injectfailpoint" }
"astersql-util-intest" = { package = "astersql-util-intest", path = "../../../util/intest" }
"astersql-util-logutil" = { package = "astersql-util-logutil", path = "../../../util/logutil" }
"astersql-util-memory" = { package = "astersql-util-memory", path = "../../../util/memory" }
"astersql-util-traceevent" = { package = "astersql-util-traceevent", path = "../../../util/traceevent" }
"astersql-util-tracing" = { package = "astersql-util-tracing", path = "../../../util/tracing" }

[target.'cfg(any())'.dev-dependencies]
"astersql-domain-sqlsvrapi-mock" = { package = "astersql-domain-sqlsvrapi-mock", path = "../../../domain/sqlsvrapi/mock" }
"astersql-dxf-framework-mock" = { package = "astersql-dxf-framework-mock", path = "../mock" }
"astersql-dxf-framework-mock-execute" = { package = "astersql-dxf-framework-mock-execute", path = "../mock/execute" }
"astersql-dxf-framework-testutil" = { package = "astersql-dxf-framework-testutil", path = "../testutil" }
"astersql-testkit" = { package = "astersql-testkit", path = "../../../testkit" }
"astersql-testkit-testfailpoint" = { package = "astersql-testkit-testfailpoint", path = "../../../testkit/testfailpoint" }
"astersql-testkit-testsetup" = { package = "astersql-testkit-testsetup", path = "../../../testkit/testsetup" }
"astersql-util-mock" = { package = "astersql-util-mock", path = "../../../util/mock" }
