[package]
name = "astersql-statistics-handle-autoanalyze-priorityqueue"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"
doctest = false

[dependencies]
astersql-statistics-handle-logutil = { path = "../../logutil" }

[package.metadata.porting]
go-package = "pkg/statistics/handle/autoanalyze/priorityqueue"
legacy-tasks = ["task-942", "task-943", "task-946", "task-1480", "task-1481", "task-1482"]
