[package]
name = "astersql-statistics-util"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[dependencies]
protobuf = "=2.8.0"
tipb = { git = "https://github.com/pingcap/tipb.git", rev = "07f0ea6b6bffa9d8ac100d81ee51dbbfe4dda3bf", default-features = false, features = ["protobuf-codec"] }

[package.metadata.porting]
go-package = "pkg/statistics/util"
legacy-tasks = ["task-44"]
