[package]
name = "astersql-planner-core-tests-analyze"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[package.metadata.porting]
go-package = "pkg/planner/core/tests/analyze"
legacy-tasks = ["task-1435"]

[dev-dependencies]
"astersql-parser-ast" = { package = "astersql-parser-ast", path = "../../../../parser/ast" }
"astersql-statistics" = { package = "astersql-statistics", path = "../../../../statistics" }
"astersql-testkit" = { package = "astersql-testkit", path = "../../../../testkit" }
"astersql-testkit-testsetup" = { package = "astersql-testkit-testsetup", path = "../../../../testkit/testsetup" }
