// Copyright 2023 PingCAP, Inc.
// Copyright 2026 AsterSQL.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Unicode 9.0.0 accent-insensitive / case-insensitive（ai_ci）Collator 生成代码。
//
// 由 `util/collate/ucaimpl` 生成以保障内联。ai_ci 表示不区分重音与大小写；
// UCA 9.0.0 权重表由 `unicode0900Impl` 提供。对应 Go 生成的同名 collator。

// Code generated by "util/collate/ucaimpl"; DO NOT EDIT.
// These codes are generated rather than using other polymorphism method (e.g. generics, interfaces, if/else...) to make
// sure every call to the `GetWeight` and `Preprocess` is inlined. The function inlining can affect 20%~50% performance.

// Rust 的 &str 已保证 UTF-8 合法；这里在解码辅助函数旁记录 Go 对非法字节返回 0/当前 key 的语义。

#![allow(dead_code)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use std::any::Any;

use crate::unicode_0900_ai_ci_impl::unicode0900Impl;
use crate::{Collator, WildcardPattern, decodeRune};

// unicode0900AICICollator implements UCA. see http://unicode.org/reports/tr10/
/// Unicode 9.0.0 ai_ci Collator；`impl_` 承载权重与 pattern 实现。
// unicode0900AICICollator 对应 Go 生成的 collator，impl 字段承载 UCA 9.0.0 ai_ci 的权重实现。
#[derive(Default)]
pub struct unicode0900AICICollator {
    impl_: unicode0900Impl,
}

/// 将固有方法转发到 `Collator` trait。
impl Collator for unicode0900AICICollator {
    fn Compare(&self, a: &str, b: &str) -> i32 {
        unicode0900AICICollator::Compare(self, a, b)
    }

    fn CompareBytes(&self, a: &[u8], b: &[u8]) -> i32 {
        unicode0900AICICollator::CompareBytes(self, a, b)
    }

    fn Key(&self, value: &str) -> Vec<u8> {
        unicode0900AICICollator::Key(self, value)
    }

    fn KeyBytes(&self, value: &[u8]) -> Vec<u8> {
        unicode0900AICICollator::KeyBytes(self, value)
    }

    fn ImmutableKey(&self, value: &str) -> Vec<u8> {
        unicode0900AICICollator::ImmutableKey(self, value)
    }

    fn KeyWithoutTrimRightSpace(&self, value: &str) -> Vec<u8> {
        unicode0900AICICollator::KeyWithoutTrimRightSpace(self, value)
    }

    fn Pattern(&self) -> Box<dyn WildcardPattern> {
        unicode0900AICICollator::Pattern(self)
    }

    fn Clone(&self) -> Box<dyn Collator> {
        self.Clone()
    }

    fn MaxKeyLen(&self, value: &str) -> i32 {
        unicode0900AICICollator::MaxKeyLen(self, value) as i32
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
}
impl unicode0900AICICollator {
    // Clone implements Collator interface.
    // Clone 对应 Go 的 Collator.Clone，复制内部 impl 并返回新的 collator。
    pub fn Clone(&self) -> Box<unicode0900AICICollator> {
        Box::new(unicode0900AICICollator {
            impl_: self.impl_.Clone(),
        })
    }

    // Compare implements Collator interface.
    // Compare 对应 Go 生成代码的主比较循环：先预处理，再按最多两段 u64 权重逐 16bit 比较。
    pub fn Compare(&self, a: &str, b: &str) -> i32 {
        let a = self.impl_.Preprocess(a);
        let b = self.impl_.Preprocess(b);
        self.CompareBytes(a.as_bytes(), b.as_bytes())
    }

    /// Go string 的原始字节比较入口；非法 UTF-8 与生成的 Go 实现一样立即返回 0。
    pub fn CompareBytes(&self, a: &[u8], b: &[u8]) -> i32 {
        // weight of a, b. weight in unicode_ci may have 8 uint16s. xn indicate first 4 u16s, xs indicate last 4 u16s
        let mut an: u64 = 0;
        let mut bn: u64 = 0;
        let mut as_: u64 = 0;
        let mut bs: u64 = 0;
        // decode index of a, b
        let mut ai: usize = 0;
        let mut bi: usize = 0;

        loop {
            if an == 0 {
                if as_ == 0 {
                    while an == 0 && ai < a.len() {
                        let (ar, invalid) = decodeRune(a, &mut ai);
                        if invalid {
                            return 0;
                        }
                        let (first, second) = self.impl_.GetWeight(ar);
                        an = first;
                        as_ = second;
                    }
                } else {
                    // Go 把第二段权重提升为当前权重继续比较。
                    an = as_;
                    as_ = 0;
                }
            }

            if bn == 0 {
                if bs == 0 {
                    while bn == 0 && bi < b.len() {
                        let (br, invalid) = decodeRune(b, &mut bi);
                        if invalid {
                            return 0;
                        }
                        let (first, second) = self.impl_.GetWeight(br);
                        bn = first;
                        bs = second;
                    }
                } else {
                    bn = bs;
                    bs = 0;
                }
            }

            if an == 0 || bn == 0 {
                // 任一字符串耗尽时，Go 用 sign(int(an)-int(bn)) 决定长度/剩余权重关系。
                return sign(an as i64 - bn as i64);
            }

            if an == bn {
                an = 0;
                bn = 0;
                continue;
            }

            while an != 0 && bn != 0 {
                if (an ^ bn) & 0xFFFF != 0 {
                    return sign((an & 0xFFFF) as i64 - (bn & 0xFFFF) as i64);
                }
                an >>= 16;
                bn >>= 16;
            }
        }
    }

    // Key implements Collator interface.
    // Key 先执行 impl.Preprocess，再转给 KeyWithoutTrimRightSpace 生成可比较字节序列。
    pub fn Key(&self, str_: &str) -> Vec<u8> {
        self.KeyWithoutTrimRightSpace(&self.impl_.Preprocess(str_))
    }

    /// Go string 的原始字节 key 入口；非法 UTF-8 前返回已生成的前缀。
    pub fn KeyBytes(&self, value: &[u8]) -> Vec<u8> {
        let mut result = Vec::with_capacity(value.len() * 2);
        let mut index = 0;
        while index < value.len() {
            let (rune, invalid) = decodeRune(value, &mut index);
            if invalid {
                return result;
            }
            let (mut first, mut second) = self.impl_.GetWeight(rune);
            while first != 0 {
                result.push(((first & 0xFF00) >> 8) as u8);
                result.push(first as u8);
                first >>= 16;
            }
            while second != 0 {
                result.push(((second & 0xFF00) >> 8) as u8);
                result.push(second as u8);
                second >>= 16;
            }
        }
        result
    }

    // ImmutableKey implements Collator interface.
    // Go 中 ImmutableKey 与 Key 对该 collator 相同；保留同样调用链。
    pub fn ImmutableKey(&self, str_: &str) -> Vec<u8> {
        self.KeyWithoutTrimRightSpace(&self.impl_.Preprocess(str_))
    }

    // KeyWithoutTrimRightSpace implements Collator interface.
    // KeyWithoutTrimRightSpace 对应 Go 的 key 构造：把每个非零 16bit 权重按大端追加到 buf。
    pub fn KeyWithoutTrimRightSpace(&self, str_: &str) -> Vec<u8> {
        let mut buf: Vec<u8> = Vec::with_capacity(str_.len() * 2);
        let mut si: usize = 0;

        while si < str_.len() {
            let (r, invalid) = decode_next_rune(str_, &mut si);
            if invalid {
                // Go 遇到非法 UTF-8 时返回当前已生成的 buf。
                return buf;
            }

            let (mut sn, mut ss) = self.impl_.GetWeight(r);
            while sn != 0 {
                buf.push(((sn & 0xFF00) >> 8) as u8);
                buf.push(sn as u8);
                sn >>= 16;
            }
            while ss != 0 {
                buf.push(((ss & 0xFF00) >> 8) as u8);
                buf.push(ss as u8);
                ss >>= 16;
            }
        }
        buf
    }

    // Pattern implements Collator interface.
    // Pattern 直接委托给 impl，保持 Go 中 generated collator 与 impl 的职责拆分。
    pub fn Pattern(&self) -> Box<dyn WildcardPattern> {
        self.impl_.Pattern()
    }

    // MaxKeyLen implements Collator interface.
    // MaxKeyLen 对应 Go 的 utf8.RuneCountInString(s) * 16；每个 rune 最多贡献 8 个 uint16 权重。
    pub fn MaxKeyLen(&self, s: &str) -> usize {
        s.chars().count() * 16
    }
}

/// 按字节下标解码下一个 rune；对齐 Go `utf8.DecodeRuneInString` 调用点。
// decode_next_rune 迁移 Go 的 utf8.DecodeRuneInString 调用点。
// Rust &str 已完成 UTF-8 校验，因此 invalid 恒为 false；保留返回位是为了让 Compare/Key 分支与 Go 对齐。
fn decode_next_rune(s: &str, idx: &mut usize) -> (char, bool) {
    if *idx >= s.len() {
        return ('\0', false);
    }
    let mut chars = s[*idx..].chars();
    match chars.next() {
        Some(ch) => {
            *idx += ch.len_utf8();
            (ch, false)
        }
        None => ('\0', false),
    }
}

/// 将比较差值压缩为 -1 / 0 / 1，对齐 Go `sign`。
// sign 对应 collate 包中 Go 的 sign 辅助语义：负数、零、正数压缩为 -1/0/1。
fn sign(v: i64) -> i32 {
    if v < 0 {
        -1
    } else if v > 0 {
        1
    } else {
        0
    }
}
