// Copyright 2023 PingCAP, Inc.
// Copyright 2026 AsterSQL.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Unicode 4.0.0 case-insensitive（ci）Collator 的生成代码。
//
// 由 `util/collate/ucaimpl` 生成，刻意展开而非多态，以保证 `GetWeight` /
// `Preprocess` 可内联（影响约 20%~50% 性能）。UCA（Unicode Collation
// Algorithm）按权重逐段比较字符串，用于 SQL 排序规则。

// Code generated by "util/collate/ucaimpl"; DO NOT EDIT.
// These codes are generated rather than using other polymorphism method (e.g. generics, interfaces, if/else...) to make
// sure every call to the `GetWeight` and `Preprocess` is inlined. The function inlining can affect 20%~50% performance.

// unicodeCICollator 如何通过 unicode0400Impl 进行 UCA 预处理、权重比较和排序 key 生成。

use std::any::Any;

use crate::unicode_0400_ci_impl::unicode0400Impl;
use crate::{Collator, WildcardPattern, decodeRune, sign, truncateTailingSpaceBytes};

// unicodeCICollator implements UCA. see http://unicode.org/reports/tr10/
/// Unicode 4.0.0 ci Collator：内嵌 `unicode0400Impl` 做预处理与权重查询。
// Go 字段名 impl 是 Rust 关键字，这里用 raw identifier r#impl 保留原字段含义。
#[derive(Default)]
pub struct unicodeCICollator {
    pub r#impl: unicode0400Impl,
}

impl unicodeCICollator {
    // Clone implements Collator interface.
    // Go 会调用内嵌 unicode0400Impl.Clone，再放回新的 unicodeCICollator。
    pub fn Clone(&self) -> Box<dyn Collator> {
        Box::new(unicodeCICollator {
            r#impl: self.r#impl.Clone(),
        })
    }

    // Compare implements Collator interface.
    // 先对两边字符串做 UCA 预处理，再按 uint64 中打包的多个 uint16 权重逐段比较。
    pub fn Compare(&self, a: &str, b: &str) -> i32 {
        self.CompareBytes(a.as_bytes(), b.as_bytes())
    }

    /// Go string 的原始字节比较入口；非法 UTF-8 与生成的 Go 实现一样立即返回 0。
    pub fn CompareBytes(&self, a: &[u8], b: &[u8]) -> i32 {
        let a = truncateTailingSpaceBytes(a);
        let b = truncateTailingSpaceBytes(b);

        // weight of a, b. weight in unicode_ci may have 8 uint16s. xn indicate first 4 u16s, xs indicate last 4 u16s
        let mut an: u64 = 0;
        let mut bn: u64 = 0;
        let mut a_s: u64 = 0;
        let mut b_s: u64 = 0;
        let mut ai = 0;
        let mut bi = 0;

        loop {
            if an == 0 {
                if a_s == 0 {
                    while an == 0 && ai < a.len() {
                        let (ar, invalid) = decodeRune(a, &mut ai);
                        if invalid {
                            return 0;
                        }
                        let (next_an, next_as) = self.r#impl.GetWeight(ar);
                        an = next_an;
                        a_s = next_as;
                    }
                } else {
                    an = a_s;
                    a_s = 0;
                }
            }

            if bn == 0 {
                if b_s == 0 {
                    while bn == 0 && bi < b.len() {
                        let (br, invalid) = decodeRune(b, &mut bi);
                        if invalid {
                            return 0;
                        }
                        let (next_bn, next_bs) = self.r#impl.GetWeight(br);
                        bn = next_bn;
                        b_s = next_bs;
                    }
                } else {
                    bn = b_s;
                    b_s = 0;
                }
            }

            if an == 0 || bn == 0 {
                return sign(an as isize - bn as isize);
            }

            if an == bn {
                an = 0;
                bn = 0;
                continue;
            }

            // Go 从低 16 位开始比较打包权重；相等则右移继续比较下一段。
            while an != 0 && bn != 0 {
                if (an ^ bn) & 0xFFFF != 0 {
                    return sign((an & 0xFFFF) as isize - (bn & 0xFFFF) as isize);
                }
                an >>= 16;
                bn >>= 16;
            }
        }
    }

    // Key implements Collator interface.
    // Go 先 Preprocess，再交给不裁空格版本输出权重 key。
    pub fn Key(&self, str_: &str) -> Vec<u8> {
        self.KeyWithoutTrimRightSpace(&self.r#impl.Preprocess(str_))
    }

    /// Go string 的原始字节 key 入口；非法 UTF-8 前返回已生成的前缀。
    pub fn KeyBytes(&self, value: &[u8]) -> Vec<u8> {
        self.key_bytes_without_trim(truncateTailingSpaceBytes(value))
    }

    fn key_bytes_without_trim(&self, value: &[u8]) -> Vec<u8> {
        let mut result = Vec::with_capacity(value.len() * 2);
        let mut index = 0;
        while index < value.len() {
            let (rune, invalid) = decodeRune(value, &mut index);
            if invalid {
                return result;
            }
            let (mut first, mut second) = self.r#impl.GetWeight(rune);
            while first != 0 {
                result.push(((first & 0xFF00) >> 8) as u8);
                result.push(first as u8);
                first >>= 16;
            }
            while second != 0 {
                result.push(((second & 0xFF00) >> 8) as u8);
                result.push(second as u8);
                second >>= 16;
            }
        }
        result
    }

    // ImmutableKey implements Collator interface.
    // Go 版本与 Key 相同；这里保留调用关系，不引入缓存或所有权优化。
    pub fn ImmutableKey(&self, str_: &str) -> Vec<u8> {
        self.KeyWithoutTrimRightSpace(&self.r#impl.Preprocess(str_))
    }

    // KeyWithoutTrimRightSpace implements Collator interface.
    // 每个 rune 的前四段权重在 sn，后四段在 ss，逐个 uint16 写入高低字节。
    pub fn KeyWithoutTrimRightSpace(&self, str_: &str) -> Vec<u8> {
        let mut buf = Vec::with_capacity(str_.len() * 2);
        for r in str_.chars() {
            let (mut sn, mut ss) = self.r#impl.GetWeight(r);

            // Go 对 sn 和 ss 分别循环；0 权重表示没有更多 collation element。
            while sn != 0 {
                buf.push(((sn & 0xFF00) >> 8) as u8);
                buf.push(sn as u8);
                sn >>= 16;
            }
            while ss != 0 {
                buf.push(((ss & 0xFF00) >> 8) as u8);
                buf.push(ss as u8);
                ss >>= 16;
            }
        }
        buf
    }

    // Pattern implements Collator interface.
    // 通配符模式由具体 unicode0400Impl 提供，保持 Go 的委托关系。
    pub fn Pattern(&self) -> Box<dyn WildcardPattern> {
        self.r#impl.Pattern()
    }

    // MaxKeyLen implements Collator interface.
    // unicode_ci 每个 rune 最多 8 个 uint16 权重，因此最多 16 字节。
    pub fn MaxKeyLen(&self, s: &str) -> usize {
        s.chars().count() * 16
    }
}

/// 将固有方法转发到 `Collator` trait，支持动态分派。
impl Collator for unicodeCICollator {
    fn Compare(&self, a: &str, b: &str) -> i32 {
        unicodeCICollator::Compare(self, a, b)
    }

    fn CompareBytes(&self, a: &[u8], b: &[u8]) -> i32 {
        unicodeCICollator::CompareBytes(self, a, b)
    }

    fn Key(&self, value: &str) -> Vec<u8> {
        unicodeCICollator::Key(self, value)
    }

    fn KeyBytes(&self, value: &[u8]) -> Vec<u8> {
        unicodeCICollator::KeyBytes(self, value)
    }

    fn ImmutableKey(&self, value: &str) -> Vec<u8> {
        unicodeCICollator::ImmutableKey(self, value)
    }

    fn KeyWithoutTrimRightSpace(&self, value: &str) -> Vec<u8> {
        unicodeCICollator::KeyWithoutTrimRightSpace(self, value)
    }

    fn Pattern(&self) -> Box<dyn WildcardPattern> {
        unicodeCICollator::Pattern(self)
    }

    fn Clone(&self) -> Box<dyn Collator> {
        unicodeCICollator::Clone(self)
    }

    fn MaxKeyLen(&self, value: &str) -> i32 {
        unicodeCICollator::MaxKeyLen(self, value) as i32
    }

    fn as_any(&self) -> &dyn Any {
        self
    }
}
