[package]
name = "astersql-types-json-binary"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[dependencies]
base64 = "0.22"
serde_json = { version = "1", features = ["arbitrary_precision"] }
thiserror = "2"
dbterror = { package = "astersql-util-dbterror", path = "../../../util/dbterror" }
