// Copyright 2026 AsterSQL.
// Copyright 2019 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go generate in expression/generator; DO NOT EDIT.

// 由 expression/generator 生成的时间向量化签名实现（ADDTIME/SUBTIME/TIMEDIFF）。
//
// 对应 Go `builtin_time_vec_generated.go`。按参数类型组合派发日期时间加减与时差，
// 处理字符串时长/日期时间解析、NULL 填充签名，以及严格/警告模式下的截断错误。
// 向量化指一次对 Chunk 整列求值。

use regex::Regex;
pub use std::rc::Rc;
use std::sync::{Arc, LazyLock, Mutex};

pub use crate::mysql;
use types_time::{Duration, MaxFsp, MinFsp, Time, TimeError};

/// 最小 Chunk：仅携带行数，供生成式向量路径按行迭代。
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct Chunk {
    rows: usize,
}

impl Chunk {
    pub fn new(rows: usize) -> Self {
        Self { rows }
    }

    pub fn NumRows(&self) -> usize {
        self.rows
    }
}

/// 结果/参数列：时间、时长（微秒）或字符串三种形态。
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub enum Column {
    #[default]
    Empty,
    Times(Vec<Option<Time>>),
    Durations(Vec<Option<i64>>),
    Strings(Vec<Option<String>>),
}

impl Column {
    fn times(&self) -> EvalResult<&[Option<Time>]> {
        match self {
            Self::Times(values) => Ok(values),
            _ => Err(EvalError::Message("expected a time column".to_owned())),
        }
    }

    fn durations(&self) -> EvalResult<&[Option<i64>]> {
        match self {
            Self::Durations(values) => Ok(values),
            _ => Err(EvalError::Message("expected a duration column".to_owned())),
        }
    }

    fn strings(&self) -> EvalResult<&[Option<String>]> {
        match self {
            Self::Strings(values) => Ok(values),
            _ => Err(EvalError::Message("expected a string column".to_owned())),
        }
    }
}

/// 简化 FieldType：携带小数精度（FSP）与是否 binary。
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct FieldType {
    pub decimal: i32,
    pub binary: bool,
}

impl FieldType {
    pub fn new(decimal: i32) -> Self {
        Self {
            decimal,
            binary: false,
        }
    }

    pub fn binary(decimal: i32) -> Self {
        Self {
            decimal,
            binary: true,
        }
    }
}

/// 向量化求值错误：通用消息或时间类型错误。
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum EvalError {
    Message(String),
    Time(String),
}

impl std::fmt::Display for EvalError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Message(message) | Self::Time(message) => formatter.write_str(message),
        }
    }
}

impl std::error::Error for EvalError {}

impl From<TimeError> for EvalError {
    fn from(error: TimeError) -> Self {
        Self::Time(error.to_string())
    }
}

/// 生成式时间向量路径的统一 Result 别名。
pub type EvalResult<T = ()> = Result<T, EvalError>;

/// 求值上下文：收集警告，并实现 `types_time::TimeContext`。
#[derive(Clone, Debug)]
pub struct EvalContext {
    warnings: Arc<Mutex<Vec<String>>>,
    pub truncate_as_warning: bool,
}

impl Default for EvalContext {
    fn default() -> Self {
        Self {
            warnings: Arc::new(Mutex::new(Vec::new())),
            truncate_as_warning: true,
        }
    }
}

impl EvalContext {
    pub fn append_warning(&self, warning: impl ToString) {
        self.warnings
            .lock()
            .expect("time-vector warning mutex poisoned")
            .push(warning.to_string());
    }

    pub fn warnings(&self) -> Vec<String> {
        self.warnings
            .lock()
            .expect("time-vector warning mutex poisoned")
            .clone()
    }
}

impl types_time::TimeContext for EvalContext {
    fn append_warning(&self, warning: TimeError) {
        EvalContext::append_warning(self, warning);
    }
}

pub trait Expression {
    fn VecEvalTime(&self, _ctx: &EvalContext, _input: &Chunk, _result: &mut Column) -> EvalResult {
        Err(EvalError::Message(
            "time evaluation is not supported".to_owned(),
        ))
    }

    fn VecEvalDuration(
        &self,
        _ctx: &EvalContext,
        _input: &Chunk,
        _result: &mut Column,
    ) -> EvalResult {
        Err(EvalError::Message(
            "duration evaluation is not supported".to_owned(),
        ))
    }

    fn VecEvalString(
        &self,
        _ctx: &EvalContext,
        _input: &Chunk,
        _result: &mut Column,
    ) -> EvalResult {
        Err(EvalError::Message(
            "string evaluation is not supported".to_owned(),
        ))
    }

    fn GetType(&self, ctx: &EvalContext) -> FieldType;
}

/// 字面量表达式：直接持有列值，用于单测构造参数。
#[derive(Clone, Debug)]
pub struct LiteralExpression {
    values: Column,
    field_type: FieldType,
}

impl LiteralExpression {
    pub fn new(values: Column, field_type: FieldType) -> Self {
        Self { values, field_type }
    }
}

impl Expression for LiteralExpression {
    fn VecEvalTime(&self, _ctx: &EvalContext, _input: &Chunk, result: &mut Column) -> EvalResult {
        self.values.times()?;
        *result = self.values.clone();
        Ok(())
    }

    fn VecEvalDuration(
        &self,
        _ctx: &EvalContext,
        _input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        self.values.durations()?;
        *result = self.values.clone();
        Ok(())
    }

    fn VecEvalString(&self, _ctx: &EvalContext, _input: &Chunk, result: &mut Column) -> EvalResult {
        self.values.strings()?;
        *result = self.values.clone();
        Ok(())
    }

    fn GetType(&self, _ctx: &EvalContext) -> FieldType {
        self.field_type
    }
}

/// 双参数内置函数基座：左右表达式与返回 FieldType。
pub struct BuiltinBase {
    args: [Rc<dyn Expression>; 2],
    tp: FieldType,
}

impl BuiltinBase {
    pub fn new(lhs: Rc<dyn Expression>, rhs: Rc<dyn Expression>, tp: FieldType) -> Self {
        Self {
            args: [lhs, rhs],
            tp,
        }
    }
}

// 批量定义 ADDTIME/SUBTIME/TIMEDIFF 各类型组合的签名结构体。
macro_rules! define_signatures {
    ($($signature:ident),+ $(,)?) => {
        $(
            pub struct $signature {
                base: BuiltinBase,
            }

            impl $signature {
                pub fn new(base: BuiltinBase) -> Self {
                    Self { base }
                }
            }
        )+
    };
}

define_signatures!(
    builtinAddDatetimeAndDurationSig,
    builtinAddDatetimeAndStringSig,
    builtinAddDurationAndDurationSig,
    builtinAddDurationAndStringSig,
    builtinAddStringAndDurationSig,
    builtinAddStringAndStringSig,
    builtinAddDateAndDurationSig,
    builtinAddDateAndStringSig,
    builtinAddTimeDateTimeNullSig,
    builtinAddTimeStringNullSig,
    builtinAddTimeDurationNullSig,
    builtinSubDatetimeAndDurationSig,
    builtinSubDatetimeAndStringSig,
    builtinSubDurationAndDurationSig,
    builtinSubDurationAndStringSig,
    builtinSubStringAndDurationSig,
    builtinSubStringAndStringSig,
    builtinSubDateAndDurationSig,
    builtinSubDateAndStringSig,
    builtinSubTimeDateTimeNullSig,
    builtinSubTimeStringNullSig,
    builtinSubTimeDurationNullSig,
    builtinNullTimeDiffSig,
    builtinTimeStringTimeDiffSig,
    builtinDurationStringTimeDiffSig,
    builtinDurationDurationTimeDiffSig,
    builtinStringTimeTimeDiffSig,
    builtinStringDurationTimeDiffSig,
    builtinStringStringTimeDiffSig,
    builtinTimeTimeTimeDiffSig,
);

static DURATION_PATTERN: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"^\s*[-]?(((\d{1,2}\s+)?0*\d{0,3}(:0*\d{1,2}){0,2})|(\d{1,7}))?(\.\d*)?\s*$")
        .expect("the ADDTIME/SUBTIME duration pattern is valid")
});

/// 向量化求值第 index 个时间为列。
fn eval_time_arg(
    base: &BuiltinBase,
    index: usize,
    ctx: &EvalContext,
    input: &Chunk,
) -> EvalResult<Column> {
    let mut column = Column::default();
    base.args[index].VecEvalTime(ctx, input, &mut column)?;
    validate_column_rows(&column, input.NumRows(), "time")?;
    Ok(column)
}

/// 向量化求值第 index 个时长为列。
fn eval_duration_arg(
    base: &BuiltinBase,
    index: usize,
    ctx: &EvalContext,
    input: &Chunk,
) -> EvalResult<Column> {
    let mut column = Column::default();
    base.args[index].VecEvalDuration(ctx, input, &mut column)?;
    validate_column_rows(&column, input.NumRows(), "duration")?;
    Ok(column)
}

/// 向量化求值第 index 个字符串为列。
fn eval_string_arg(
    base: &BuiltinBase,
    index: usize,
    ctx: &EvalContext,
    input: &Chunk,
) -> EvalResult<Column> {
    let mut column = Column::default();
    base.args[index].VecEvalString(ctx, input, &mut column)?;
    validate_column_rows(&column, input.NumRows(), "string")?;
    Ok(column)
}

/// Go's generated loops index every row in the input chunk. Preserve that contract explicitly in
/// the standalone Rust column facade instead of allowing iterator `zip` to truncate malformed
/// expression output silently.
fn validate_column_rows(column: &Column, expected: usize, kind: &str) -> EvalResult {
    let actual = match column {
        Column::Times(values) => values.len(),
        Column::Durations(values) => values.len(),
        Column::Strings(values) => values.len(),
        Column::Empty => 0,
    };
    if actual != expected {
        return Err(EvalError::Message(format!(
            "{kind} column has {actual} rows, expected {expected}"
        )));
    }
    Ok(())
}

/// 判断字符串是否像 MySQL duration 词法形式。
fn is_duration(value: &str) -> bool {
    DURATION_PATTERN.is_match(value)
}

/// ADDTIME/SUBTIME 字符串操作数的分数秒精度：无小数或全 0 用 MinFsp，否则 MaxFsp。
fn get_fsp_for_time_add_sub(value: &str) -> i32 {
    match value.split_once('.') {
        None => MinFsp,
        Some((_, fraction)) if fraction.chars().all(|character| character == '0') => MinFsp,
        Some(_) => MaxFsp,
    }
}

/// 解析 duration 字符串；解析为 NULL 时转为截断类 TimeError。
fn parse_duration(ctx: &EvalContext, value: &str, fsp: i32) -> Result<Duration, TimeError> {
    let (duration, is_null) = types_time::ParseDuration(ctx, value, fsp)?;
    if is_null {
        Err(TimeError(format!(
            "truncated incorrect time value: {value}"
        )))
    } else {
        Ok(duration)
    }
}

/// 生成路径用：解析失败记警告并返回 None（SQL NULL）。
fn parse_duration_for_generated_path(ctx: &EvalContext, value: &str, fsp: i32) -> Option<Duration> {
    if !is_duration(value) {
        return None;
    }
    match parse_duration(ctx, value, fsp) {
        Ok(duration) => Some(duration),
        Err(error) => {
            ctx.append_warning(error);
            None
        }
    }
}

/// 时长微秒与 Duration 做加/减。
fn duration_op(lhs: i64, rhs: Duration, add: bool) -> EvalResult<i64> {
    let lhs = Duration {
        Duration: lhs,
        Fsp: rhs.Fsp,
    };
    let result = if add { lhs.Add(rhs) } else { lhs.Sub(rhs) }?;
    Ok(result.Duration)
}

/// 日期时间与 Duration 做加/减。
fn time_op(ctx: &EvalContext, lhs: Time, rhs: Duration, add: bool) -> EvalResult<Time> {
    let rhs = if add { rhs } else { rhs.Neg() };
    Ok(lhs.Add(ctx, rhs)?)
}

/// 字符串操作数与 Duration：按时长或日期时间语义分流。
fn string_duration_op(
    ctx: &EvalContext,
    lhs: &str,
    rhs: Duration,
    add: bool,
) -> EvalResult<Option<String>> {
    if is_duration(lhs) {
        let lhs = match parse_duration(ctx, lhs, MaxFsp) {
            Ok(value) => value,
            Err(error) => {
                ctx.append_warning(error);
                return Ok(None);
            }
        };
        let mut value = if add { lhs.Add(rhs) } else { lhs.Sub(rhs) }?;
        value.Fsp = if value.MicroSecond() == 0 {
            MinFsp
        } else {
            MaxFsp
        };
        return Ok(Some(value.String()));
    }

    let lhs = match types_time::ParseTimeWithString(ctx, lhs, mysql::TypeDatetime, MaxFsp) {
        Ok(value) => value,
        Err(error) => {
            // MySQL emits a warning for malformed datetime strings regardless of SQL mode.
            ctx.append_warning(error);
            return Ok(None);
        }
    };
    let mut value = time_op(ctx, lhs, rhs, add)?;
    value.SetFsp(if value.Microsecond() == 0 {
        MinFsp
    } else {
        MaxFsp
    });
    Ok(Some(value.String()))
}

/// DATETIME ± DURATION 的列式求值。
fn eval_datetime_duration(
    base: &BuiltinBase,
    ctx: &EvalContext,
    input: &Chunk,
    result: &mut Column,
    add: bool,
) -> EvalResult {
    let lhs = eval_time_arg(base, 0, ctx, input)?;
    let rhs = eval_duration_arg(base, 1, ctx, input)?;
    let lhs = lhs.times()?;
    let rhs = rhs.durations()?;
    let mut output = Vec::with_capacity(input.NumRows());
    for (lhs, rhs) in lhs.iter().zip(rhs) {
        // 仅时长-时长或时间-时间可做 TIMEDIFF；混合类型结果为 NULL。
        let value = match (lhs, rhs) {
            (Some(lhs), Some(rhs)) if !lhs.IsZero() => Some(time_op(
                ctx,
                *lhs,
                Duration {
                    Duration: *rhs,
                    Fsp: -1,
                },
                add,
            )?),
            _ => None,
        };
        output.push(value);
    }
    *result = Column::Times(output);
    Ok(())
}

/// DATETIME ± STRING(时长) 的列式求值。
fn eval_datetime_string(
    base: &BuiltinBase,
    ctx: &EvalContext,
    input: &Chunk,
    result: &mut Column,
    add: bool,
) -> EvalResult {
    let lhs = eval_time_arg(base, 0, ctx, input)?;
    let rhs = eval_string_arg(base, 1, ctx, input)?;
    let lhs = lhs.times()?;
    let rhs = rhs.strings()?;
    let mut output = Vec::with_capacity(input.NumRows());
    for (lhs, rhs) in lhs.iter().zip(rhs) {
        let value = match (lhs, rhs) {
            (Some(lhs), Some(rhs)) if !lhs.IsZero() => {
                match parse_duration_for_generated_path(ctx, rhs, types_time::GetFsp(rhs)) {
                    Some(rhs) => Some(time_op(ctx, *lhs, rhs, add)?),
                    None => None,
                }
            }
            _ => None,
        };
        output.push(value);
    }
    *result = Column::Times(output);
    Ok(())
}

/// DURATION ± DURATION 的列式求值。
fn eval_duration_duration(
    base: &BuiltinBase,
    ctx: &EvalContext,
    input: &Chunk,
    result: &mut Column,
    add: bool,
) -> EvalResult {
    let lhs = eval_duration_arg(base, 0, ctx, input)?;
    let rhs = eval_duration_arg(base, 1, ctx, input)?;
    let lhs = lhs.durations()?;
    let rhs = rhs.durations()?;
    let mut output = Vec::with_capacity(input.NumRows());
    for (lhs, rhs) in lhs.iter().zip(rhs) {
        output.push(match (lhs, rhs) {
            (Some(lhs), Some(rhs)) => Some(duration_op(
                *lhs,
                Duration {
                    Duration: *rhs,
                    Fsp: -1,
                },
                add,
            )?),
            _ => None,
        });
    }
    *result = Column::Durations(output);
    Ok(())
}

/// DURATION ± STRING 的列式求值。
fn eval_duration_string(
    base: &BuiltinBase,
    ctx: &EvalContext,
    input: &Chunk,
    result: &mut Column,
    add: bool,
) -> EvalResult {
    let lhs = eval_duration_arg(base, 0, ctx, input)?;
    let rhs = eval_string_arg(base, 1, ctx, input)?;
    let lhs = lhs.durations()?;
    let rhs = rhs.strings()?;
    let mut output = Vec::with_capacity(input.NumRows());
    for (lhs, rhs) in lhs.iter().zip(rhs) {
        output.push(match (lhs, rhs) {
            (Some(lhs), Some(rhs)) => {
                match parse_duration_for_generated_path(ctx, rhs, types_time::GetFsp(rhs)) {
                    Some(rhs) => Some(duration_op(*lhs, rhs, add)?),
                    None => None,
                }
            }
            _ => None,
        });
    }
    *result = Column::Durations(output);
    Ok(())
}

/// STRING ± DURATION：结果写回字符串列。
fn eval_string_duration(
    base: &BuiltinBase,
    ctx: &EvalContext,
    input: &Chunk,
    result: &mut Column,
    add: bool,
) -> EvalResult {
    let lhs = eval_string_arg(base, 0, ctx, input)?;
    let rhs = eval_duration_arg(base, 1, ctx, input)?;
    let rhs_fsp = base.args[1].GetType(ctx).decimal;
    let lhs = lhs.strings()?;
    let rhs = rhs.durations()?;
    let mut output = Vec::with_capacity(input.NumRows());
    for (lhs, rhs) in lhs.iter().zip(rhs) {
        output.push(match (lhs, rhs) {
            (Some(lhs), Some(rhs)) => string_duration_op(
                ctx,
                lhs,
                Duration {
                    Duration: *rhs,
                    Fsp: rhs_fsp,
                },
                add,
            )?,
            _ => None,
        });
    }
    *result = Column::Strings(output);
    Ok(())
}

/// STRING ± STRING：右操作数先判是否 duration。
fn eval_string_string(
    base: &BuiltinBase,
    ctx: &EvalContext,
    input: &Chunk,
    result: &mut Column,
    add: bool,
) -> EvalResult {
    let lhs = eval_string_arg(base, 0, ctx, input)?;
    // The Go implementation checks the binary flag before evaluating arg 1.
    if base.args[1].GetType(ctx).binary {
        *result = Column::Strings(vec![None; input.NumRows()]);
        return Ok(());
    }
    let rhs = eval_string_arg(base, 1, ctx, input)?;
    let lhs = lhs.strings()?;
    let rhs = rhs.strings()?;
    let mut output = Vec::with_capacity(input.NumRows());
    for (lhs, rhs) in lhs.iter().zip(rhs) {
        output.push(match (lhs, rhs) {
            (Some(lhs), Some(rhs)) => {
                match parse_duration_for_generated_path(ctx, rhs, get_fsp_for_time_add_sub(rhs)) {
                    Some(rhs) => string_duration_op(ctx, lhs, rhs, add)?,
                    None => None,
                }
            }
            _ => None,
        });
    }
    *result = Column::Strings(output);
    Ok(())
}

/// DATE ± DURATION：结果格式化为字符串。
fn eval_date_duration(
    base: &BuiltinBase,
    ctx: &EvalContext,
    input: &Chunk,
    result: &mut Column,
    add: bool,
) -> EvalResult {
    let lhs = eval_time_arg(base, 0, ctx, input)?;
    let rhs = eval_duration_arg(base, 1, ctx, input)?;
    let rhs_fsp = base.args[1].GetType(ctx).decimal;
    let lhs = lhs.times()?;
    let rhs = rhs.durations()?;
    let mut output = Vec::with_capacity(input.NumRows());
    for (lhs, rhs) in lhs.iter().zip(rhs) {
        let value = match (lhs, rhs) {
            (Some(lhs), Some(rhs)) if !lhs.IsZero() => {
                let mut lhs = *lhs;
                lhs.SetType(mysql::TypeDatetime);
                match time_op(
                    ctx,
                    lhs,
                    Duration {
                        Duration: *rhs,
                        Fsp: rhs_fsp,
                    },
                    add,
                ) {
                    Ok(value) => Some(value.String()),
                    Err(error) => {
                        ctx.append_warning(&error);
                        None
                    }
                }
            }
            _ => None,
        };
        output.push(value);
    }
    *result = Column::Strings(output);
    Ok(())
}

/// DATE ± STRING：结果格式化为字符串。
fn eval_date_string(
    base: &BuiltinBase,
    ctx: &EvalContext,
    input: &Chunk,
    result: &mut Column,
    add: bool,
) -> EvalResult {
    let lhs = eval_time_arg(base, 0, ctx, input)?;
    let rhs = eval_string_arg(base, 1, ctx, input)?;
    let lhs = lhs.times()?;
    let rhs = rhs.strings()?;
    let mut output = Vec::with_capacity(input.NumRows());
    for (lhs, rhs) in lhs.iter().zip(rhs) {
        let value = match (lhs, rhs) {
            (Some(lhs), Some(rhs)) if !lhs.IsZero() => {
                match parse_duration_for_generated_path(ctx, rhs, get_fsp_for_time_add_sub(rhs)) {
                    Some(rhs) => {
                        let mut lhs = *lhs;
                        lhs.SetType(mysql::TypeDatetime);
                        match time_op(ctx, lhs, rhs, add) {
                            Ok(value) => Some(value.String()),
                            Err(error) => {
                                ctx.append_warning(&error);
                                None
                            }
                        }
                    }
                    None => None,
                }
            }
            _ => None,
        };
        output.push(value);
    }
    *result = Column::Strings(output);
    Ok(())
}

/// 常 NULL 时间签名：按行数填充全 NULL 时间列。
fn fill_null_time(input: &Chunk, result: &mut Column) -> EvalResult {
    *result = Column::Times(vec![None; input.NumRows()]);
    Ok(())
}

/// 常 NULL 时长签名：按行数填充全 NULL 时长列。
fn fill_null_duration(input: &Chunk, result: &mut Column) -> EvalResult {
    *result = Column::Durations(vec![None; input.NumRows()]);
    Ok(())
}

/// 常 NULL 字符串签名：按行数填充全 NULL 字符串列。
fn fill_null_string(input: &Chunk, result: &mut Column) -> EvalResult {
    *result = Column::Strings(vec![None; input.NumRows()]);
    Ok(())
}

/// 字符串解析后的时间形态：时长或日期时间。
enum StringTemporal {
    Duration(Duration),
    Time(Time),
}

/// 将字符串转为时长或日期时间；失败记警告并返回 None。
fn convert_string_to_temporal(
    ctx: &EvalContext,
    value: &str,
    mut fsp: i32,
) -> EvalResult<StringTemporal> {
    if let Some((_, fraction)) = value.split_once('.')
        && fraction.len() <= MaxFsp as usize
    {
        fsp = fsp.max(fraction.len() as i32);
    }

    let trimmed = value.trim();
    let unsigned = trimmed.strip_prefix('-').unwrap_or(trimmed);
    let integral_len = unsigned
        .split_once('.')
        .map_or(unsigned.len(), |(head, _)| head.len());
    if integral_len >= 12
        && let Ok(time) = types_time::ParseTimeWithString(ctx, trimmed, mysql::TypeDatetime, fsp)
    {
        return Ok(StringTemporal::Time(time));
    }
    Ok(StringTemporal::Duration(parse_duration(ctx, trimmed, fsp)?))
}

/// 处理 TIMEDIFF 截断：超范围时按上下文警告或报错，并返回钳位值/NULL。
fn handle_truncated_difference(ctx: &EvalContext, value: i64) -> EvalResult<Option<i64>> {
    if (types_time::MinTime..=types_time::MaxTime).contains(&value) {
        return Ok(Some(value));
    }
    let error = EvalError::Time(format!("truncated incorrect time value: {value}"));
    if ctx.truncate_as_warning {
        ctx.append_warning(&error);
        Ok(Some(value.clamp(types_time::MinTime, types_time::MaxTime)))
    } else {
        Err(error)
    }
}

/// 计算两个 Time 的时差（微秒）。
fn calculate_time_diff(ctx: &EvalContext, lhs: Time, rhs: Time) -> EvalResult<Option<i64>> {
    handle_truncated_difference(ctx, lhs.Sub(ctx, rhs).Duration)
}

/// 计算两个 Duration 的时差（微秒）。
fn calculate_duration_time_diff(
    ctx: &EvalContext,
    lhs: Duration,
    rhs: Duration,
) -> EvalResult<Option<i64>> {
    let value = lhs.Sub(rhs)?.Duration;
    handle_truncated_difference(ctx, value)
}

/// TIMEDIFF(time, string) 列式求值。
fn eval_time_string_timediff(
    base: &BuiltinBase,
    ctx: &EvalContext,
    input: &Chunk,
    result: &mut Column,
) -> EvalResult {
    let lhs = eval_time_arg(base, 0, ctx, input)?;
    let rhs = eval_string_arg(base, 1, ctx, input)?;
    let lhs = lhs.times()?;
    let rhs = rhs.strings()?;
    let mut output = Vec::with_capacity(input.NumRows());
    for (lhs, rhs) in lhs.iter().zip(rhs) {
        output.push(match (lhs, rhs) {
            (Some(lhs), Some(rhs)) => {
                match convert_string_to_temporal(ctx, rhs, base.tp.decimal)? {
                    StringTemporal::Time(rhs) => calculate_time_diff(ctx, *lhs, rhs)?,
                    StringTemporal::Duration(_) => None,
                }
            }
            _ => None,
        });
    }
    *result = Column::Durations(output);
    Ok(())
}

/// TIMEDIFF(duration, string) 列式求值。
fn eval_duration_string_timediff(
    base: &BuiltinBase,
    ctx: &EvalContext,
    input: &Chunk,
    result: &mut Column,
) -> EvalResult {
    let lhs = eval_duration_arg(base, 0, ctx, input)?;
    let rhs = eval_string_arg(base, 1, ctx, input)?;
    let lhs = lhs.durations()?;
    let rhs = rhs.strings()?;
    let mut output = Vec::with_capacity(input.NumRows());
    for (lhs, rhs) in lhs.iter().zip(rhs) {
        output.push(match (lhs, rhs) {
            (Some(lhs), Some(rhs)) => {
                match convert_string_to_temporal(ctx, rhs, base.tp.decimal)? {
                    StringTemporal::Duration(rhs) => calculate_duration_time_diff(
                        ctx,
                        Duration {
                            Duration: *lhs,
                            Fsp: base.tp.decimal,
                        },
                        rhs,
                    )?,
                    StringTemporal::Time(_) => None,
                }
            }
            _ => None,
        });
    }
    *result = Column::Durations(output);
    Ok(())
}

/// TIMEDIFF(duration, duration) 列式求值。
fn eval_duration_duration_timediff(
    base: &BuiltinBase,
    ctx: &EvalContext,
    input: &Chunk,
    result: &mut Column,
) -> EvalResult {
    let lhs = eval_duration_arg(base, 0, ctx, input)?;
    let rhs = eval_duration_arg(base, 1, ctx, input)?;
    let lhs = lhs.durations()?;
    let rhs = rhs.durations()?;
    let mut output = Vec::with_capacity(input.NumRows());
    for (lhs, rhs) in lhs.iter().zip(rhs) {
        output.push(match (lhs, rhs) {
            (Some(lhs), Some(rhs)) => calculate_duration_time_diff(
                ctx,
                Duration {
                    Duration: *lhs,
                    Fsp: base.tp.decimal,
                },
                Duration {
                    Duration: *rhs,
                    Fsp: base.tp.decimal,
                },
            )?,
            _ => None,
        });
    }
    *result = Column::Durations(output);
    Ok(())
}

/// TIMEDIFF(string, time) 列式求值。
fn eval_string_time_timediff(
    base: &BuiltinBase,
    ctx: &EvalContext,
    input: &Chunk,
    result: &mut Column,
) -> EvalResult {
    let lhs = eval_string_arg(base, 0, ctx, input)?;
    let rhs = eval_time_arg(base, 1, ctx, input)?;
    let lhs = lhs.strings()?;
    let rhs = rhs.times()?;
    let mut output = Vec::with_capacity(input.NumRows());
    for (lhs, rhs) in lhs.iter().zip(rhs) {
        output.push(match (lhs, rhs) {
            (Some(lhs), Some(rhs)) => {
                match convert_string_to_temporal(ctx, lhs, base.tp.decimal)? {
                    StringTemporal::Time(lhs) => calculate_time_diff(ctx, lhs, *rhs)?,
                    StringTemporal::Duration(_) => None,
                }
            }
            _ => None,
        });
    }
    *result = Column::Durations(output);
    Ok(())
}

/// TIMEDIFF(string, duration) 列式求值。
fn eval_string_duration_timediff(
    base: &BuiltinBase,
    ctx: &EvalContext,
    input: &Chunk,
    result: &mut Column,
) -> EvalResult {
    let lhs = eval_string_arg(base, 0, ctx, input)?;
    let rhs = eval_duration_arg(base, 1, ctx, input)?;
    let lhs = lhs.strings()?;
    let rhs = rhs.durations()?;
    let mut output = Vec::with_capacity(input.NumRows());
    for (lhs, rhs) in lhs.iter().zip(rhs) {
        output.push(match (lhs, rhs) {
            (Some(lhs), Some(rhs)) => {
                match convert_string_to_temporal(ctx, lhs, base.tp.decimal)? {
                    StringTemporal::Duration(lhs) => calculate_duration_time_diff(
                        ctx,
                        lhs,
                        Duration {
                            Duration: *rhs,
                            Fsp: base.tp.decimal,
                        },
                    )?,
                    StringTemporal::Time(_) => None,
                }
            }
            _ => None,
        });
    }
    *result = Column::Durations(output);
    Ok(())
}

/// TIMEDIFF(string, string)：仅同类可减，混合类型得 NULL。
fn eval_string_string_timediff(
    base: &BuiltinBase,
    ctx: &EvalContext,
    input: &Chunk,
    result: &mut Column,
) -> EvalResult {
    let lhs = eval_string_arg(base, 0, ctx, input)?;
    let rhs = eval_string_arg(base, 1, ctx, input)?;
    let lhs = lhs.strings()?;
    let rhs = rhs.strings()?;
    let mut output = Vec::with_capacity(input.NumRows());
    for (lhs, rhs) in lhs.iter().zip(rhs) {
        output.push(match (lhs, rhs) {
            (Some(lhs), Some(rhs)) => {
                let lhs = convert_string_to_temporal(ctx, lhs, base.tp.decimal)?;
                let rhs = convert_string_to_temporal(ctx, rhs, base.tp.decimal)?;
                match (lhs, rhs) {
                    (StringTemporal::Duration(lhs), StringTemporal::Duration(rhs)) => {
                        calculate_duration_time_diff(ctx, lhs, rhs)?
                    }
                    (StringTemporal::Time(lhs), StringTemporal::Time(rhs)) => {
                        calculate_time_diff(ctx, lhs, rhs)?
                    }
                    _ => None,
                }
            }
            _ => None,
        });
    }
    *result = Column::Durations(output);
    Ok(())
}

/// TIMEDIFF(time, time) 列式求值。
fn eval_time_time_timediff(
    base: &BuiltinBase,
    ctx: &EvalContext,
    input: &Chunk,
    result: &mut Column,
) -> EvalResult {
    let lhs = eval_time_arg(base, 0, ctx, input)?;
    let rhs = eval_time_arg(base, 1, ctx, input)?;
    let lhs = lhs.times()?;
    let rhs = rhs.times()?;
    let mut output = Vec::with_capacity(input.NumRows());
    for (lhs, rhs) in lhs.iter().zip(rhs) {
        output.push(match (lhs, rhs) {
            (Some(lhs), Some(rhs)) => calculate_time_diff(ctx, *lhs, *rhs)?,
            _ => None,
        });
    }
    *result = Column::Durations(output);
    Ok(())
}

// 为所有生成签名声明 vectorized() == true，供优化器选择列式路径。
macro_rules! impl_vectorized {
    ($($signature:ident),+ $(,)?) => {
        $(
            impl $signature {
                pub fn vectorized(&self) -> bool {
                    true
                }
            }
        )+
    };
}

/// ADDTIME(datetime, duration) 向量化入口。
impl builtinAddDatetimeAndDurationSig {
    pub fn vecEvalTime(&self, ctx: &EvalContext, input: &Chunk, result: &mut Column) -> EvalResult {
        eval_datetime_duration(&self.base, ctx, input, result, true)
    }
}
/// ADDTIME(datetime, string) 向量化入口。
impl builtinAddDatetimeAndStringSig {
    pub fn vecEvalTime(&self, ctx: &EvalContext, input: &Chunk, result: &mut Column) -> EvalResult {
        eval_datetime_string(&self.base, ctx, input, result, true)
    }
}
/// ADDTIME(duration, duration) 向量化入口。
impl builtinAddDurationAndDurationSig {
    pub fn vecEvalDuration(
        &self,
        ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        eval_duration_duration(&self.base, ctx, input, result, true)
    }
}
/// ADDTIME(duration, string) 向量化入口。
impl builtinAddDurationAndStringSig {
    pub fn vecEvalDuration(
        &self,
        ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        eval_duration_string(&self.base, ctx, input, result, true)
    }
}
/// ADDTIME(string, duration) 向量化入口。
impl builtinAddStringAndDurationSig {
    pub fn vecEvalString(
        &self,
        ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        eval_string_duration(&self.base, ctx, input, result, true)
    }
}
/// ADDTIME(string, string) 向量化入口。
impl builtinAddStringAndStringSig {
    pub fn vecEvalString(
        &self,
        ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        eval_string_string(&self.base, ctx, input, result, true)
    }
}
/// ADDTIME(date, duration) 向量化入口（结果为字符串）。
impl builtinAddDateAndDurationSig {
    pub fn vecEvalString(
        &self,
        ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        eval_date_duration(&self.base, ctx, input, result, true)
    }
}
/// ADDTIME(date, string) 向量化入口（结果为字符串）。
impl builtinAddDateAndStringSig {
    pub fn vecEvalString(
        &self,
        ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        eval_date_string(&self.base, ctx, input, result, true)
    }
}
/// ADDTIME 常 NULL（时间结果）向量化入口。
impl builtinAddTimeDateTimeNullSig {
    pub fn vecEvalTime(
        &self,
        _ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        fill_null_time(input, result)
    }
}
/// ADDTIME 常 NULL（字符串结果）向量化入口。
impl builtinAddTimeStringNullSig {
    pub fn vecEvalString(
        &self,
        _ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        fill_null_string(input, result)
    }
}
/// ADDTIME 常 NULL（时长结果）向量化入口。
impl builtinAddTimeDurationNullSig {
    pub fn vecEvalDuration(
        &self,
        _ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        fill_null_duration(input, result)
    }
}
/// SUBTIME(datetime, duration) 向量化入口。
impl builtinSubDatetimeAndDurationSig {
    pub fn vecEvalTime(&self, ctx: &EvalContext, input: &Chunk, result: &mut Column) -> EvalResult {
        eval_datetime_duration(&self.base, ctx, input, result, false)
    }
}
/// SUBTIME(datetime, string) 向量化入口。
impl builtinSubDatetimeAndStringSig {
    pub fn vecEvalTime(&self, ctx: &EvalContext, input: &Chunk, result: &mut Column) -> EvalResult {
        eval_datetime_string(&self.base, ctx, input, result, false)
    }
}
/// SUBTIME(duration, duration) 向量化入口。
impl builtinSubDurationAndDurationSig {
    pub fn vecEvalDuration(
        &self,
        ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        eval_duration_duration(&self.base, ctx, input, result, false)
    }
}
/// SUBTIME(duration, string) 向量化入口。
impl builtinSubDurationAndStringSig {
    pub fn vecEvalDuration(
        &self,
        ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        eval_duration_string(&self.base, ctx, input, result, false)
    }
}
/// SUBTIME(string, duration) 向量化入口。
impl builtinSubStringAndDurationSig {
    pub fn vecEvalString(
        &self,
        ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        eval_string_duration(&self.base, ctx, input, result, false)
    }
}
/// SUBTIME(string, string) 向量化入口。
impl builtinSubStringAndStringSig {
    pub fn vecEvalString(
        &self,
        ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        eval_string_string(&self.base, ctx, input, result, false)
    }
}
/// SUBTIME(date, duration) 向量化入口。
impl builtinSubDateAndDurationSig {
    pub fn vecEvalString(
        &self,
        ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        eval_date_duration(&self.base, ctx, input, result, false)
    }
}
/// SUBTIME(date, string) 向量化入口。
impl builtinSubDateAndStringSig {
    pub fn vecEvalString(
        &self,
        ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        eval_date_string(&self.base, ctx, input, result, false)
    }
}
/// SUBTIME 常 NULL（时间结果）向量化入口。
impl builtinSubTimeDateTimeNullSig {
    pub fn vecEvalTime(
        &self,
        _ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        fill_null_time(input, result)
    }
}
/// SUBTIME 常 NULL（字符串结果）向量化入口。
impl builtinSubTimeStringNullSig {
    pub fn vecEvalString(
        &self,
        _ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        fill_null_string(input, result)
    }
}
/// SUBTIME 常 NULL（时长结果）向量化入口。
impl builtinSubTimeDurationNullSig {
    pub fn vecEvalDuration(
        &self,
        _ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        fill_null_duration(input, result)
    }
}
/// TIMEDIFF 常 NULL 向量化入口。
impl builtinNullTimeDiffSig {
    pub fn vecEvalDuration(
        &self,
        _ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        fill_null_duration(input, result)
    }
}
/// TIMEDIFF(time, string) 向量化入口。
impl builtinTimeStringTimeDiffSig {
    pub fn vecEvalDuration(
        &self,
        ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        eval_time_string_timediff(&self.base, ctx, input, result)
    }
}
/// TIMEDIFF(duration, string) 向量化入口。
impl builtinDurationStringTimeDiffSig {
    pub fn vecEvalDuration(
        &self,
        ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        eval_duration_string_timediff(&self.base, ctx, input, result)
    }
}
/// TIMEDIFF(duration, duration) 向量化入口。
impl builtinDurationDurationTimeDiffSig {
    pub fn vecEvalDuration(
        &self,
        ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        eval_duration_duration_timediff(&self.base, ctx, input, result)
    }
}
/// TIMEDIFF(string, time) 向量化入口。
impl builtinStringTimeTimeDiffSig {
    pub fn vecEvalDuration(
        &self,
        ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        eval_string_time_timediff(&self.base, ctx, input, result)
    }
}
/// TIMEDIFF(string, duration) 向量化入口。
impl builtinStringDurationTimeDiffSig {
    pub fn vecEvalDuration(
        &self,
        ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        eval_string_duration_timediff(&self.base, ctx, input, result)
    }
}
/// TIMEDIFF(string, string) 向量化入口。
impl builtinStringStringTimeDiffSig {
    pub fn vecEvalDuration(
        &self,
        ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        eval_string_string_timediff(&self.base, ctx, input, result)
    }
}
/// TIMEDIFF(time, time) 向量化入口。
impl builtinTimeTimeTimeDiffSig {
    pub fn vecEvalDuration(
        &self,
        ctx: &EvalContext,
        input: &Chunk,
        result: &mut Column,
    ) -> EvalResult {
        eval_time_time_timediff(&self.base, ctx, input, result)
    }
}

impl_vectorized!(
    builtinAddDatetimeAndDurationSig,
    builtinAddDatetimeAndStringSig,
    builtinAddDurationAndDurationSig,
    builtinAddDurationAndStringSig,
    builtinAddStringAndDurationSig,
    builtinAddStringAndStringSig,
    builtinAddDateAndDurationSig,
    builtinAddDateAndStringSig,
    builtinAddTimeDateTimeNullSig,
    builtinAddTimeStringNullSig,
    builtinAddTimeDurationNullSig,
    builtinSubDatetimeAndDurationSig,
    builtinSubDatetimeAndStringSig,
    builtinSubDurationAndDurationSig,
    builtinSubDurationAndStringSig,
    builtinSubStringAndDurationSig,
    builtinSubStringAndStringSig,
    builtinSubDateAndDurationSig,
    builtinSubDateAndStringSig,
    builtinSubTimeDateTimeNullSig,
    builtinSubTimeStringNullSig,
    builtinSubTimeDurationNullSig,
    builtinNullTimeDiffSig,
    builtinTimeStringTimeDiffSig,
    builtinDurationStringTimeDiffSig,
    builtinDurationDurationTimeDiffSig,
    builtinStringTimeTimeDiffSig,
    builtinStringDurationTimeDiffSig,
    builtinStringStringTimeDiffSig,
    builtinTimeTimeTimeDiffSig,
);
