// Copyright 2026 AsterSQL.
// Copyright 2021 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go generate in expression/generator; DO NOT EDIT.

// 由 expression/generator 生成的向量化 FIELD 实现。
//
// FIELD(search, ...) 返回 search 在候选列表中首次匹配的 1-based 位置；
// 未匹配为 0。SQL NULL 永不与任何值相等；实数路径保留 IEEE NaN≠NaN。
// 字符串比较器由调用方注入，以对接 TiDB 各签名的 collation。

use thiserror::Error;

#[derive(Clone, Debug, Error, PartialEq, Eq)]
/// FIELD 向量求值前的列长度校验错误。
pub enum FieldVectorError {
    #[error("FIELD vector columns have different row counts")]
    RowCountMismatch,
}

/// 校验 search 与各候选列行数一致。
fn validate_lengths<T>(
    search: &[Option<T>],
    candidates: &[Vec<Option<T>>],
) -> Result<(), FieldVectorError> {
    if candidates.iter().any(|column| column.len() != search.len()) {
        return Err(FieldVectorError::RowCountMismatch);
    }
    Ok(())
}

/// 通用 FIELD 内核：按行扫描候选，首个相等者写入 1-based 下标。
fn field_by<T, F>(
    search: &[Option<T>],
    candidates: &[Vec<Option<T>>],
    mut equal: F,
) -> Result<Vec<i64>, FieldVectorError>
where
    F: FnMut(&T, &T) -> bool,
{
    validate_lengths(search, candidates)?;
    let mut result = vec![0_i64; search.len()];
    for (candidate_index, candidate) in candidates.iter().enumerate() {
        for row in 0..search.len() {
            if result[row] > 0 {
                continue;
            }
            let (Some(left), Some(right)) = (&search[row], &candidate[row]) else {
                continue;
            };
            if equal(left, right) {
                result[row] = (candidate_index + 1) as i64;
            }
        }
    }
    Ok(result)
}

/// Vectorized FIELD for integer arguments. The first matching candidate wins;
/// NULL never compares equal and unmatched rows remain zero.
/// 整型参数的向量化 FIELD；首匹配胜出，NULL 不相等，未匹配为 0。
pub fn field_int(
    search: &[Option<i64>],
    candidates: &[Vec<Option<i64>>],
) -> Result<Vec<i64>, FieldVectorError> {
    field_by(search, candidates, |left, right| left == right)
}

/// Vectorized FIELD for real arguments. Direct IEEE equality intentionally
/// keeps NaN unequal to itself, matching the generated Go implementation.
/// 实数参数的向量化 FIELD；直接 IEEE 相等，故 NaN 不等于自身。
pub fn field_real(
    search: &[Option<f64>],
    candidates: &[Vec<Option<f64>>],
) -> Result<Vec<i64>, FieldVectorError> {
    field_by(search, candidates, |left, right| left == right)
}

/// Vectorized FIELD for strings. The supplied comparator is the Rust boundary
/// for TiDB's signature-specific collator.
/// 字符串参数的向量化 FIELD；比较器对接签名相关 collation。
pub fn field_string<'a, F>(
    search: &[Option<&'a str>],
    candidates: &[Vec<Option<&'a str>>],
    mut equal: F,
) -> Result<Vec<i64>, FieldVectorError>
where
    F: FnMut(&str, &str) -> bool,
{
    field_by(search, candidates, |left, right| equal(left, right))
}

/// 声明整型 FIELD 已向量化。
pub const fn field_int_vectorized() -> bool {
    true
}

/// 声明实数 FIELD 已向量化。
pub const fn field_real_vectorized() -> bool {
    true
}

/// 声明字符串 FIELD 已向量化。
pub const fn field_string_vectorized() -> bool {
    true
}
