// Copyright 2026 AsterSQL.
// Copyright 2019 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go generate in expression/generator; DO NOT EDIT.

// 向量化控制流（CASE WHEN / IFNULL / IF）生成代码。
//
// 由 `expression/generator` 的 Go generate 产出；七种求值类型各一套签名。
// 向量路径投机求值各分支；若出错或新增警告则回滚警告并逐行标量回退。
// 条件/首参的向量错误为强制错误，不隐藏于回退。
use std::error::Error;
use std::fmt::{self, Display, Formatter};

pub type Decimal = rust_decimal::Decimal;
pub type Time = chrono::NaiveDateTime;
pub type Duration = chrono::Duration;
pub type BinaryJSON = serde_json::Value;

/// Error returned while evaluating a control expression.
/// 控制表达式求值错误。
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EvalError {
    message: String,
}

impl EvalError {
    /// 由消息构造求值错误。
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

impl Display for EvalError {
    fn fmt(&self, formatter: &mut Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.message)
    }
}

impl Error for EvalError {}

/// Observable evaluation state used by the warning rollback path.
/// 可观测求值上下文：支持警告回滚路径。
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct EvalContext {
    warnings: Vec<String>,
}

impl EvalContext {
    /// 追加警告。
    pub fn append_warning(&mut self, warning: impl Into<String>) {
        self.warnings.push(warning.into());
    }

    /// 当前警告条数。
    pub fn warning_count(&self) -> usize {
        self.warnings.len()
    }

    /// 截断警告到指定条数（回滚投机警告）。
    pub fn truncate_warnings(&mut self, count: usize) {
        self.warnings.truncate(count);
    }

    /// 只读访问警告列表。
    pub fn warnings(&self) -> &[String] {
        &self.warnings
    }
}

/// The expression surface needed by generated control builtins.
///
/// Implementations may override `vec_eval` with a vectorized implementation.
/// The default deliberately evaluates rows in order, which is also the scalar
/// fallback order used by the Go implementation.
/// 生成式控制内建所需的表达式接口；默认 `vec_eval` 按行顺序求值。
pub trait VectorExpression<T>: Send + Sync {
    /// 单行标量求值。
    fn eval_row(&self, ctx: &mut EvalContext, row: usize) -> Result<Option<T>, EvalError>;

    /// 向量求值；默认实现逐行调用 `eval_row`。
    fn vec_eval(&self, ctx: &mut EvalContext, rows: usize) -> Result<Vec<Option<T>>, EvalError> {
        (0..rows).map(|row| self.eval_row(ctx, row)).collect()
    }
}

/// CASE 的一支：`(WHEN 条件列, THEN 结果列)`。
pub type CaseBranch<T> = (Box<dyn VectorExpression<i64>>, Box<dyn VectorExpression<T>>);

/// 校验向量结果行数是否与期望一致。
fn check_column_len<T>(column: &[Option<T>], rows: usize) -> Result<(), EvalError> {
    if column.len() == rows {
        Ok(())
    } else {
        Err(EvalError::new(format!(
            "vector expression returned {} rows, expected {rows}",
            column.len()
        )))
    }
}

/// 若求值期间新增了警告，则截断回滚到求值前条数。
fn rollback_speculative_warnings(ctx: &mut EvalContext, before_warnings: usize) {
    if ctx.warning_count() > before_warnings {
        ctx.truncate_warnings(before_warnings);
    }
}

/// Shared implementation for the seven generated CASE WHEN signatures.
/// 七种生成式 CASE WHEN 签名的共享实现。
pub struct BuiltinCaseWhen<T> {
    branches: Vec<CaseBranch<T>>,
    else_expr: Option<Box<dyn VectorExpression<T>>>,
}

impl<T> BuiltinCaseWhen<T>
where
    T: Clone + Send + Sync + 'static,
{
    /// 由 WHEN/THEN 分支与可选 ELSE 构造。
    pub fn new(
        branches: Vec<CaseBranch<T>>,
        else_expr: Option<Box<dyn VectorExpression<T>>>,
    ) -> Self {
        Self {
            branches,
            else_expr,
        }
    }

    /// 逐行标量回退求值。
    pub fn fallback_eval(
        &self,
        ctx: &mut EvalContext,
        rows: usize,
    ) -> Result<Vec<Option<T>>, EvalError> {
        let mut result = Vec::with_capacity(rows);
        for row in 0..rows {
            let mut matched = false;
            for (when, then) in &self.branches {
                if matches!(when.eval_row(ctx, row)?, Some(value) if value != 0) {
                    result.push(then.eval_row(ctx, row)?);
                    matched = true;
                    break;
                }
            }
            if !matched {
                result.push(match &self.else_expr {
                    Some(else_expr) => else_expr.eval_row(ctx, row)?,
                    None => None,
                });
            }
        }
        Ok(result)
    }

    /// 向量求值：先投机求各分支列，失败则回退；再按行选首个真 WHEN。
    pub fn vec_eval(
        &self,
        ctx: &mut EvalContext,
        rows: usize,
    ) -> Result<Vec<Option<T>>, EvalError> {
        // 记录警告水位，便于投机失败时回滚。
        let before_warnings = ctx.warning_count();
        let mut branch_columns = Vec::with_capacity(self.branches.len());

        for (when, then) in &self.branches {
            let when_column = match when.vec_eval(ctx, rows) {
                Ok(column) if check_column_len(&column, rows).is_ok() => column,
                Ok(_) | Err(_) => {
                    rollback_speculative_warnings(ctx, before_warnings);
                    return self.fallback_eval(ctx, rows);
                }
            };
            if ctx.warning_count() > before_warnings {
                rollback_speculative_warnings(ctx, before_warnings);
                return self.fallback_eval(ctx, rows);
            }

            let then_column = match then.vec_eval(ctx, rows) {
                Ok(column) if check_column_len(&column, rows).is_ok() => column,
                Ok(_) | Err(_) => {
                    rollback_speculative_warnings(ctx, before_warnings);
                    return self.fallback_eval(ctx, rows);
                }
            };
            if ctx.warning_count() > before_warnings {
                rollback_speculative_warnings(ctx, before_warnings);
                return self.fallback_eval(ctx, rows);
            }
            branch_columns.push((when_column, then_column));
        }

        let else_column = match &self.else_expr {
            Some(else_expr) => {
                let column = match else_expr.vec_eval(ctx, rows) {
                    Ok(column) if check_column_len(&column, rows).is_ok() => column,
                    Ok(_) | Err(_) => {
                        rollback_speculative_warnings(ctx, before_warnings);
                        return self.fallback_eval(ctx, rows);
                    }
                };
                if ctx.warning_count() > before_warnings {
                    rollback_speculative_warnings(ctx, before_warnings);
                    return self.fallback_eval(ctx, rows);
                }
                Some(column)
            }
            None => None,
        };

        // 按行选取：首个非零 WHEN 取对应 THEN，否则 ELSE（无 ELSE 则为 NULL）。
        let mut result = Vec::with_capacity(rows);
        for row in 0..rows {
            let mut value = None;
            let mut matched = false;
            for (when, then) in &branch_columns {
                if matches!(when[row], Some(condition) if condition != 0) {
                    value = then[row].clone();
                    matched = true;
                    break;
                }
            }
            if !matched && let Some(else_column) = &else_column {
                value = else_column[row].clone();
            }
            result.push(value);
        }
        Ok(result)
    }

    /// 声明本签名支持向量化执行。
    pub const fn vectorized(&self) -> bool {
        true
    }
}

/// Shared implementation for the seven generated IFNULL signatures.
/// 七种生成式 IFNULL 签名的共享实现。
pub struct BuiltinIfNull<T> {
    lhs: Box<dyn VectorExpression<T>>,
    rhs: Box<dyn VectorExpression<T>>,
}

impl<T> BuiltinIfNull<T>
where
    T: Clone + Send + Sync + 'static,
{
    /// 由条件与真/假分支构造 IF。
    /// 由左右表达式构造 IFNULL。
    pub fn new(lhs: Box<dyn VectorExpression<T>>, rhs: Box<dyn VectorExpression<T>>) -> Self {
        Self { lhs, rhs }
    }

    /// 逐行按条件选择真/假分支。
    /// 逐行：左非 NULL 取左，否则取右。
    pub fn fallback_eval(
        &self,
        ctx: &mut EvalContext,
        rows: usize,
    ) -> Result<Vec<Option<T>>, EvalError> {
        let mut result = Vec::with_capacity(rows);
        for row in 0..rows {
            match self.lhs.eval_row(ctx, row)? {
                Some(value) => result.push(Some(value)),
                None => result.push(self.rhs.eval_row(ctx, row)?),
            }
        }
        Ok(result)
    }

    /// 向量 IF：条件强制求值；真/假分支可回退。
    /// 向量 IFNULL：左列强制求值；右列可回退。
    pub fn vec_eval(
        &self,
        ctx: &mut EvalContext,
        rows: usize,
    ) -> Result<Vec<Option<T>>, EvalError> {
        // Go returns an error from arg0 directly because every row needs it.
        let lhs = self.lhs.vec_eval(ctx, rows)?;
        check_column_len(&lhs, rows)?;

        let before_warnings = ctx.warning_count();
        let rhs = match self.rhs.vec_eval(ctx, rows) {
            Ok(column) if check_column_len(&column, rows).is_ok() => column,
            Ok(_) | Err(_) => {
                rollback_speculative_warnings(ctx, before_warnings);
                return self.fallback_eval(ctx, rows);
            }
        };
        if ctx.warning_count() > before_warnings {
            rollback_speculative_warnings(ctx, before_warnings);
            return self.fallback_eval(ctx, rows);
        }

        Ok(lhs
            .into_iter()
            .zip(rhs)
            .map(|(lhs, rhs)| lhs.or(rhs))
            .collect())
    }

    /// 声明支持向量化。
    /// 声明支持向量化。
    pub const fn vectorized(&self) -> bool {
        true
    }
}

/// Shared implementation for the seven generated IF signatures.
/// 七种生成式 IF 签名的共享实现。
pub struct BuiltinIf<T> {
    condition: Box<dyn VectorExpression<i64>>,
    if_true: Box<dyn VectorExpression<T>>,
    if_false: Box<dyn VectorExpression<T>>,
}

impl<T> BuiltinIf<T>
where
    T: Clone + Send + Sync + 'static,
{
    pub fn new(
        condition: Box<dyn VectorExpression<i64>>,
        if_true: Box<dyn VectorExpression<T>>,
        if_false: Box<dyn VectorExpression<T>>,
    ) -> Self {
        Self {
            condition,
            if_true,
            if_false,
        }
    }

    pub fn fallback_eval(
        &self,
        ctx: &mut EvalContext,
        rows: usize,
    ) -> Result<Vec<Option<T>>, EvalError> {
        let mut result = Vec::with_capacity(rows);
        for row in 0..rows {
            let condition = self.condition.eval_row(ctx, row)?;
            if matches!(condition, Some(value) if value != 0) {
                result.push(self.if_true.eval_row(ctx, row)?);
            } else {
                result.push(self.if_false.eval_row(ctx, row)?);
            }
        }
        Ok(result)
    }

    pub fn vec_eval(
        &self,
        ctx: &mut EvalContext,
        rows: usize,
    ) -> Result<Vec<Option<T>>, EvalError> {
        // As in Go, a condition vector error is mandatory and propagates.
        let condition = self.condition.vec_eval(ctx, rows)?;
        check_column_len(&condition, rows)?;
        let before_warnings = ctx.warning_count();

        let if_true = match self.if_true.vec_eval(ctx, rows) {
            Ok(column) if check_column_len(&column, rows).is_ok() => column,
            Ok(_) | Err(_) => {
                rollback_speculative_warnings(ctx, before_warnings);
                return self.fallback_eval(ctx, rows);
            }
        };
        if ctx.warning_count() > before_warnings {
            rollback_speculative_warnings(ctx, before_warnings);
            return self.fallback_eval(ctx, rows);
        }

        let if_false = match self.if_false.vec_eval(ctx, rows) {
            Ok(column) if check_column_len(&column, rows).is_ok() => column,
            Ok(_) | Err(_) => {
                rollback_speculative_warnings(ctx, before_warnings);
                return self.fallback_eval(ctx, rows);
            }
        };
        if ctx.warning_count() > before_warnings {
            rollback_speculative_warnings(ctx, before_warnings);
            return self.fallback_eval(ctx, rows);
        }

        Ok((0..rows)
            .map(|row| {
                if matches!(condition[row], Some(value) if value != 0) {
                    if_true[row].clone()
                } else {
                    if_false[row].clone()
                }
            })
            .collect())
    }

    pub const fn vectorized(&self) -> bool {
        true
    }
}

/// 为指定求值类型生成 CASE WHEN 签名包装类型。
macro_rules! case_when_signature {
    ($name:ident, $value:ty, $fallback:ident, $vector:ident) => {
        #[allow(non_camel_case_types)]
        pub struct $name(BuiltinCaseWhen<$value>);

        #[allow(non_snake_case)]
        impl $name {
            pub fn new(
                branches: Vec<CaseBranch<$value>>,
                else_expr: Option<Box<dyn VectorExpression<$value>>>,
            ) -> Self {
                Self(BuiltinCaseWhen::new(branches, else_expr))
            }

            pub fn $fallback(
                &mut self,
                ctx: &mut EvalContext,
                rows: usize,
            ) -> Result<Vec<Option<$value>>, EvalError> {
                self.0.fallback_eval(ctx, rows)
            }

            pub fn $vector(
                &mut self,
                ctx: &mut EvalContext,
                rows: usize,
            ) -> Result<Vec<Option<$value>>, EvalError> {
                self.0.vec_eval(ctx, rows)
            }

            pub const fn vectorized(&self) -> bool {
                self.0.vectorized()
            }
        }
    };
}

/// 为指定求值类型生成 IFNULL 签名包装类型。
macro_rules! if_null_signature {
    ($name:ident, $value:ty, $fallback:ident, $vector:ident) => {
        #[allow(non_camel_case_types)]
        pub struct $name(BuiltinIfNull<$value>);

        #[allow(non_snake_case)]
        impl $name {
            pub fn new(
                lhs: Box<dyn VectorExpression<$value>>,
                rhs: Box<dyn VectorExpression<$value>>,
            ) -> Self {
                Self(BuiltinIfNull::new(lhs, rhs))
            }

            pub fn $fallback(
                &mut self,
                ctx: &mut EvalContext,
                rows: usize,
            ) -> Result<Vec<Option<$value>>, EvalError> {
                self.0.fallback_eval(ctx, rows)
            }

            pub fn $vector(
                &mut self,
                ctx: &mut EvalContext,
                rows: usize,
            ) -> Result<Vec<Option<$value>>, EvalError> {
                self.0.vec_eval(ctx, rows)
            }

            pub const fn vectorized(&self) -> bool {
                self.0.vectorized()
            }
        }
    };
}

/// 为指定求值类型生成 IF 签名包装类型。
macro_rules! if_signature {
    ($name:ident, $value:ty, $fallback:ident, $vector:ident) => {
        #[allow(non_camel_case_types)]
        pub struct $name(BuiltinIf<$value>);

        #[allow(non_snake_case)]
        impl $name {
            pub fn new(
                condition: Box<dyn VectorExpression<i64>>,
                if_true: Box<dyn VectorExpression<$value>>,
                if_false: Box<dyn VectorExpression<$value>>,
            ) -> Self {
                Self(BuiltinIf::new(condition, if_true, if_false))
            }

            pub fn $fallback(
                &mut self,
                ctx: &mut EvalContext,
                rows: usize,
            ) -> Result<Vec<Option<$value>>, EvalError> {
                self.0.fallback_eval(ctx, rows)
            }

            pub fn $vector(
                &mut self,
                ctx: &mut EvalContext,
                rows: usize,
            ) -> Result<Vec<Option<$value>>, EvalError> {
                self.0.vec_eval(ctx, rows)
            }

            pub const fn vectorized(&self) -> bool {
                self.0.vectorized()
            }
        }
    };
}

// 七种求值类型 × CASE / IFNULL / IF = 21 个 Go 签名包装。
case_when_signature!(builtinCaseWhenIntSig, i64, fallbackEvalInt, vecEvalInt);
case_when_signature!(builtinCaseWhenRealSig, f64, fallbackEvalReal, vecEvalReal);
case_when_signature!(
    builtinCaseWhenDecimalSig,
    Decimal,
    fallbackEvalDecimal,
    vecEvalDecimal
);
case_when_signature!(
    builtinCaseWhenStringSig,
    String,
    fallbackEvalString,
    vecEvalString
);
case_when_signature!(builtinCaseWhenTimeSig, Time, fallbackEvalTime, vecEvalTime);
case_when_signature!(
    builtinCaseWhenDurationSig,
    Duration,
    fallbackEvalDuration,
    vecEvalDuration
);
case_when_signature!(
    builtinCaseWhenJSONSig,
    BinaryJSON,
    fallbackEvalJSON,
    vecEvalJSON
);

if_null_signature!(builtinIfNullIntSig, i64, fallbackEvalInt, vecEvalInt);
if_null_signature!(builtinIfNullRealSig, f64, fallbackEvalReal, vecEvalReal);
if_null_signature!(
    builtinIfNullDecimalSig,
    Decimal,
    fallbackEvalDecimal,
    vecEvalDecimal
);
if_null_signature!(
    builtinIfNullStringSig,
    String,
    fallbackEvalString,
    vecEvalString
);
if_null_signature!(builtinIfNullTimeSig, Time, fallbackEvalTime, vecEvalTime);
if_null_signature!(
    builtinIfNullDurationSig,
    Duration,
    fallbackEvalDuration,
    vecEvalDuration
);
if_null_signature!(
    builtinIfNullJSONSig,
    BinaryJSON,
    fallbackEvalJSON,
    vecEvalJSON
);

if_signature!(builtinIfIntSig, i64, fallbackEvalInt, vecEvalInt);
if_signature!(builtinIfRealSig, f64, fallbackEvalReal, vecEvalReal);
if_signature!(
    builtinIfDecimalSig,
    Decimal,
    fallbackEvalDecimal,
    vecEvalDecimal
);
if_signature!(
    builtinIfStringSig,
    String,
    fallbackEvalString,
    vecEvalString
);
if_signature!(builtinIfTimeSig, Time, fallbackEvalTime, vecEvalTime);
if_signature!(
    builtinIfDurationSig,
    Duration,
    fallbackEvalDuration,
    vecEvalDuration
);
if_signature!(builtinIfJSONSig, BinaryJSON, fallbackEvalJSON, vecEvalJSON);
