// Copyright 2026 AsterSQL.
// Copyright 2019 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// 由 generator 生成的向量化 IN 谓词签名实现。
//
// 对应 Go `builtin_other_vec_generated.go`：共享 `evaluate_in` 内核实现
// 哈希常量快路径 + 非常量参数逐列比较，并按 SQL 三值逻辑写出 0/1/NULL。
// 各类型签名（Int/String/Decimal/Real/Time/Duration/Json）仅注入求值与相等回调。

// Code generated by go generate in expression/generator; DO NOT EDIT.

use std::collections::{HashMap, HashSet};

use crate::builtin_other_vec_kernel::{
    EvalContext, EvalError, EvalResult, VectorExpression, write_int_options,
};
use crate::{chunk, collate, types};

/// 向量化表达式参数列表别名。
type Expressions = Vec<Box<dyn VectorExpression>>;

/// IN 向量求值共享内核：先求左列，再哈希匹配，再扫非常量右列，最后写 0/1/NULL。
///
/// `hash_match`/`equal` 由各类型签名注入，以保留有符号、collation、NaN 等语义。
fn evaluate_in<T, Evaluate, Read, HashMatch, Equal>(
    context: &EvalContext,
    input: &chunk::Chunk,
    result: &mut chunk::Column,
    args: &[Box<dyn VectorExpression>],
    hash_present: bool,
    non_const_args_idx: &[usize],
    constant_has_null: bool,
    evaluate: Evaluate,
    read: Read,
    hash_match: HashMatch,
    equal: Equal,
) -> EvalResult<()>
where
    T: Clone,
    Evaluate: Fn(
        &dyn VectorExpression,
        &EvalContext,
        &chunk::Chunk,
        &mut chunk::Column,
    ) -> EvalResult<()>,
    Read: Fn(&chunk::Column, usize) -> T,
    HashMatch: Fn(&T) -> EvalResult<bool>,
    Equal: Fn(&T, &T, usize) -> bool,
{
    let Some(first) = args.first() else {
        return Err(EvalError::Message(
            "IN requires at least one argument".to_owned(),
        ));
    };

    let row_count = input.NumRows();
    let mut left = chunk::Column::default();
    evaluate(first.as_ref(), context, input, &mut left)?;
    if left.length != row_count {
        return Err(EvalError::Message(format!(
            "IN left argument produced {} rows, expected {row_count}",
            left.length
        )));
    }

    // 初始结果全为 NULL；仅在命中时置 1，或证明无 NULL 参与比较后置 0。
    // Go starts with a NULL result column and only clears a row on a match or
    // after proving that no compared argument was NULL.
    let mut output = vec![None; row_count];
    let mut has_null = vec![constant_has_null; row_count];
    if hash_present {
        for row in 0..row_count {
            if left.IsNull(row) {
                has_null[row] = true;
                continue;
            }
            if hash_match(&read(&left, row))? {
                output[row] = Some(1);
            }
        }
    }

    // 有哈希时只扫非常量下标；否则从参数 1 起全部作为动态右值。
    let dynamic_indexes = if hash_present {
        non_const_args_idx.to_vec()
    } else {
        (1..args.len()).collect()
    };
    let mut right = chunk::Column::default();
    for arg_index in dynamic_indexes {
        let Some(arg) = args.get(arg_index) else {
            return Err(EvalError::Message(format!(
                "IN non-constant argument index {arg_index} is out of range"
            )));
        };
        evaluate(arg.as_ref(), context, input, &mut right)?;
        if right.length != row_count {
            return Err(EvalError::Message(format!(
                "IN argument {arg_index} produced {} rows, expected {row_count}",
                right.length
            )));
        }
        for row in 0..row_count {
            if output[row] == Some(1) {
                continue;
            }
            if left.IsNull(row) || right.IsNull(row) {
                has_null[row] = true;
                continue;
            }
            if equal(&read(&left, row), &read(&right, row), arg_index) {
                output[row] = Some(1);
            }
        }
    }

    // 未命中且全程无 NULL → false(0)；否则保持 NULL。
    for row in 0..row_count {
        if output[row].is_none() && !has_null[row] {
            output[row] = Some(0);
        }
    }
    write_int_options(result, &output);
    Ok(())
}

/// 整数相等：同号直接比；跨有符号/无符号时仅非负才可能相等（对齐 Go）。
fn int_equal(left: i64, left_unsigned: bool, right: i64, right_unsigned: bool) -> bool {
    match (left_unsigned, right_unsigned) {
        (true, true) | (false, false) => left == right,
        (false, true) => left >= 0 && left == right,
        (true, false) => right >= 0 && left == right,
    }
}

/// 整数 IN 向量签名：常量进入 `hash_set`（附带是否无符号），非常量走动态比较。
pub struct BuiltinInIntSig {
    args: Expressions,
    hash_set: HashMap<i64, bool>,
    has_null: bool,
    non_const_args_idx: Vec<usize>,
}

impl BuiltinInIntSig {
    pub fn new(
        args: Expressions,
        hash_values: impl IntoIterator<Item = (i64, bool)>,
        has_null: bool,
        non_const_args_idx: Vec<usize>,
    ) -> Self {
        Self {
            args,
            hash_set: hash_values.into_iter().collect(),
            has_null,
            non_const_args_idx,
        }
    }

    pub fn vectorized(&self) -> bool {
        true
    }

    pub fn vec_eval_int(
        &self,
        context: &EvalContext,
        input: &chunk::Chunk,
        result: &mut chunk::Column,
    ) -> EvalResult<()> {
        let left_unsigned = self
            .args
            .first()
            .is_some_and(|expression| expression.is_unsigned());
        evaluate_in(
            context,
            input,
            result,
            &self.args,
            !self.hash_set.is_empty(),
            &self.non_const_args_idx,
            self.has_null,
            |expression, context, input, result| expression.vec_eval_int(context, input, result),
            |column, row| column.GetInt64(row),
            |value| {
                Ok(self.hash_set.get(value).is_some_and(|constant_unsigned| {
                    int_equal(*value, left_unsigned, *value, *constant_unsigned)
                }))
            },
            |left, right, arg_index| {
                int_equal(
                    *left,
                    left_unsigned,
                    *right,
                    self.args[arg_index].is_unsigned(),
                )
            },
        )
    }
}

/// 字符串 IN：常量按 collation 生成排序键后入哈希；比较亦走 collator。
pub struct BuiltinInStringSig {
    args: Expressions,
    hash_set: HashSet<Vec<u8>>,
    has_null: bool,
    non_const_args_idx: Vec<usize>,
    collation: String,
}

impl BuiltinInStringSig {
    pub fn new<I, S>(
        args: Expressions,
        hash_values: I,
        has_null: bool,
        non_const_args_idx: Vec<usize>,
        collation: impl Into<String>,
    ) -> Self
    where
        I: IntoIterator<Item = S>,
        S: AsRef<str>,
    {
        let collation = collation.into();
        let collator = collate::GetCollator(&collation);
        Self {
            args,
            hash_set: hash_values
                .into_iter()
                .map(|value| collator.Key(value.as_ref()))
                .collect(),
            has_null,
            non_const_args_idx,
            collation,
        }
    }

    pub fn vectorized(&self) -> bool {
        true
    }

    pub fn vec_eval_int(
        &self,
        context: &EvalContext,
        input: &chunk::Chunk,
        result: &mut chunk::Column,
    ) -> EvalResult<()> {
        let collator = collate::GetCollator(&self.collation);
        evaluate_in(
            context,
            input,
            result,
            &self.args,
            !self.hash_set.is_empty(),
            &self.non_const_args_idx,
            self.has_null,
            |expression, context, input, result| expression.vec_eval_string(context, input, result),
            |column, row| column.GetString(row),
            |value| Ok(self.hash_set.contains(&collator.Key(value))),
            |left, right, _| collator.Compare(left, right) == 0,
        )
    }
}

/// Decimal IN：常量 ToHashKey；哈希构建失败会推迟到求值时返回错误。
pub struct BuiltinInDecimalSig {
    args: Expressions,
    hash_set: HashSet<Vec<u8>>,
    hash_error: Option<String>,
    has_null: bool,
    non_const_args_idx: Vec<usize>,
}

impl BuiltinInDecimalSig {
    pub fn new(
        args: Expressions,
        hash_values: impl IntoIterator<Item = types::MyDecimal>,
        has_null: bool,
        non_const_args_idx: Vec<usize>,
    ) -> Self {
        let mut hash_set = HashSet::new();
        let mut hash_error = None;
        for value in hash_values {
            match value.ToHashKey() {
                Ok(key) => {
                    hash_set.insert(key);
                }
                Err(error) => {
                    hash_error = Some(error.to_string());
                    break;
                }
            }
        }
        Self {
            args,
            hash_set,
            hash_error,
            has_null,
            non_const_args_idx,
        }
    }

    pub fn vectorized(&self) -> bool {
        true
    }

    pub fn vec_eval_int(
        &self,
        context: &EvalContext,
        input: &chunk::Chunk,
        result: &mut chunk::Column,
    ) -> EvalResult<()> {
        if let Some(error) = &self.hash_error {
            return Err(EvalError::Message(error.clone()));
        }
        evaluate_in(
            context,
            input,
            result,
            &self.args,
            !self.hash_set.is_empty(),
            &self.non_const_args_idx,
            self.has_null,
            |expression, context, input, result| {
                expression.vec_eval_decimal(context, input, result)
            },
            |column, row| column.GetDecimal(row),
            |value| {
                value
                    .ToHashKey()
                    .map(|key| self.hash_set.contains(&key))
                    .map_err(|error| EvalError::Message(error.to_string()))
            },
            |left, right, _| left.Compare(right) == 0,
        )
    }
}

/// 实数 IN：用 Vec 保留 Go map[float64] 语义（NaN 不自等，±0 相等）。
pub struct BuiltinInRealSig {
    args: Expressions,
    // A Vec intentionally preserves Go map[float64] lookup semantics: NaN
    // never hashes equal to itself, while +0 and -0 compare equal.
    hash_values: Vec<f64>,
    has_null: bool,
    non_const_args_idx: Vec<usize>,
}

impl BuiltinInRealSig {
    pub fn new(
        args: Expressions,
        hash_values: impl IntoIterator<Item = f64>,
        has_null: bool,
        non_const_args_idx: Vec<usize>,
    ) -> Self {
        Self {
            args,
            hash_values: hash_values.into_iter().collect(),
            has_null,
            non_const_args_idx,
        }
    }

    pub fn vectorized(&self) -> bool {
        true
    }

    pub fn vec_eval_int(
        &self,
        context: &EvalContext,
        input: &chunk::Chunk,
        result: &mut chunk::Column,
    ) -> EvalResult<()> {
        evaluate_in(
            context,
            input,
            result,
            &self.args,
            !self.hash_values.is_empty(),
            &self.non_const_args_idx,
            self.has_null,
            |expression, context, input, result| expression.vec_eval_real(context, input, result),
            |column, row| column.GetFloat64(row),
            |value| Ok(self.hash_values.iter().any(|constant| constant == value)),
            |left, right, _| left == right || left.is_nan() && right.is_nan(),
        )
    }
}

/// 时间 IN：以 CoreTime 编码作为哈希键。
pub struct BuiltinInTimeSig {
    args: Expressions,
    hash_set: HashSet<u64>,
    has_null: bool,
    non_const_args_idx: Vec<usize>,
}

impl BuiltinInTimeSig {
    pub fn new(
        args: Expressions,
        hash_values: impl IntoIterator<Item = types::Time>,
        has_null: bool,
        non_const_args_idx: Vec<usize>,
    ) -> Self {
        Self {
            args,
            hash_set: hash_values
                .into_iter()
                .map(|value| value.CoreTime().0)
                .collect(),
            has_null,
            non_const_args_idx,
        }
    }

    pub fn vectorized(&self) -> bool {
        true
    }

    pub fn vec_eval_int(
        &self,
        context: &EvalContext,
        input: &chunk::Chunk,
        result: &mut chunk::Column,
    ) -> EvalResult<()> {
        evaluate_in(
            context,
            input,
            result,
            &self.args,
            !self.hash_set.is_empty(),
            &self.non_const_args_idx,
            self.has_null,
            |expression, context, input, result| expression.vec_eval_time(context, input, result),
            |column, row| column.GetTime(row),
            |value| Ok(self.hash_set.contains(&value.CoreTime().0)),
            |left, right, _| left.Compare(*right) == 0,
        )
    }
}

/// Duration IN：以 i64 时长值作为哈希键。
pub struct BuiltinInDurationSig {
    args: Expressions,
    hash_set: HashSet<i64>,
    has_null: bool,
    non_const_args_idx: Vec<usize>,
}

impl BuiltinInDurationSig {
    pub fn new(
        args: Expressions,
        hash_values: impl IntoIterator<Item = i64>,
        has_null: bool,
        non_const_args_idx: Vec<usize>,
    ) -> Self {
        Self {
            args,
            hash_set: hash_values.into_iter().collect(),
            has_null,
            non_const_args_idx,
        }
    }

    pub fn vectorized(&self) -> bool {
        true
    }

    pub fn vec_eval_int(
        &self,
        context: &EvalContext,
        input: &chunk::Chunk,
        result: &mut chunk::Column,
    ) -> EvalResult<()> {
        evaluate_in(
            context,
            input,
            result,
            &self.args,
            !self.hash_set.is_empty(),
            &self.non_const_args_idx,
            self.has_null,
            |expression, context, input, result| {
                expression.vec_eval_duration(context, input, result)
            },
            |column, row| column.GetInt64(row),
            |value| Ok(self.hash_set.contains(value)),
            |left, right, _| left == right,
        )
    }
}

/// JSON IN：不建哈希，仅逐参数 CompareBinaryJSON。
pub struct BuiltinInJsonSig {
    args: Expressions,
}

impl BuiltinInJsonSig {
    pub fn new(args: Expressions) -> Self {
        Self { args }
    }

    pub fn vectorized(&self) -> bool {
        true
    }

    pub fn vec_eval_int(
        &self,
        context: &EvalContext,
        input: &chunk::Chunk,
        result: &mut chunk::Column,
    ) -> EvalResult<()> {
        evaluate_in(
            context,
            input,
            result,
            &self.args,
            false,
            &[],
            false,
            |expression, context, input, result| expression.vec_eval_json(context, input, result),
            |column, row| column.GetJSON(row),
            |_| Ok(false),
            |left, right, _| types::CompareBinaryJSON(left, right) == 0,
        )
    }
}

/// 与 Go 命名对齐的 JSON 签名别名。
pub type BuiltinInJSONSig = BuiltinInJsonSig;
