// Copyright 2026 AsterSQL.
// Copyright 2024 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go generate in expression/generator; DO NOT EDIT.
//
// These signatures are session-sensitive in Go and must always return false.
// Rust's formal runtime collapses Go's concrete signature structs, so this
// complete inventory is the authoritative classification used by dispatch.

// 生成的非线程安全（会话敏感）内建签名清单。
//
// 对应 Go generator：这些签名依赖会话状态或可变上下文，
// `SafeToShareAcrossSession` 必须恒为 false，由分发层据此分类。

pub const GENERATED_THREADUNSAFE_SIGNATURES: &[&str] = &[
    "builtinArithmeticMultiplyRealSig",
    "builtinGreatestCmpStringAsTimeSig",
    "builtinGreatestTimeSig",
    "builtinLeastCmpStringAsTimeSig",
    "builtinLeastTimeSig",
    "builtinIntervalIntSig",
    "builtinIntervalRealSig",
    "builtinInternalFromBinarySig",
    "builtinAesDecryptSig",
    "builtinAesDecryptIVSig",
    "builtinAesEncryptSig",
    "builtinAesEncryptIVSig",
    "builtinValidatePasswordStrengthSig",
    "builtinFtsMysqlMatchAgainstSig",
    "builtinIlikeSig",
    "builtinFoundRowsSig",
    "builtinCurrentUserSig",
    "builtinCurrentRoleSig",
    "builtinCurrentResourceGroupSig",
    "builtinUserSig",
    "builtinConnectionIDSig",
    "builtinLastInsertIDSig",
    "builtinLastInsertIDWithIDSig",
    "builtinTiDBIsDDLOwnerSig",
    "builtinBenchmarkSig",
    "builtinRowCountSig",
    "builtinTiDBMVCCInfoSig",
    "builtinTiDBEncodeRecordKeySig",
    "builtinTiDBEncodeIndexKeySig",
    "builtinTiDBDecodeKeySig",
    "builtinTiDBDecodeSQLDigestsSig",
    "builtinNextValSig",
    "builtinLastValSig",
    "builtinSetValSig",
    "builtinJSONSchemaValidSig",
    "builtinLikeSig",
    "builtinRandSig",
    "builtinSleepSig",
    "builtinLockSig",
    "builtinReleaseLockSig",
    "builtinFreeLockSig",
    "builtinUsedLockSig",
    "builtinReleaseAllLocksSig",
    "builtinVectorFloat32IsTrueSig",
    "builtinVectorFloat32IsFalseSig",
    "builtinUnaryMinusDecimalSig",
    "builtinSetStringVarSig",
    "builtinSetRealVarSig",
    "builtinSetDecimalVarSig",
    "builtinSetIntVarSig",
    "builtinSetTimeVarSig",
    "builtinValuesIntSig",
    "builtinValuesRealSig",
    "builtinValuesDecimalSig",
    "builtinValuesStringSig",
    "builtinValuesTimeSig",
    "builtinValuesDurationSig",
    "builtinValuesJSONSig",
    "builtinValuesVectorFloat32Sig",
    "builtinRegexpLikeFuncSig",
    "builtinRegexpSubstrFuncSig",
    "builtinRegexpInStrFuncSig",
    "builtinRegexpReplaceFuncSig",
    "builtinConcatSig",
    "builtinConcatWSSig",
    "builtinRepeatSig",
    "builtinSpaceSig",
    "builtinLpadSig",
    "builtinLpadUTF8Sig",
    "builtinRpadSig",
    "builtinRpadUTF8Sig",
    "builtinFindInSetSig",
    "builtinFromBase64Sig",
    "builtinToBase64Sig",
    "builtinInsertSig",
    "builtinInsertUTF8Sig",
    "builtinWeightStringSig",
    "builtinDateLiteralSig",
    "builtinTimeLiteralSig",
    "builtinAddSubDateAsStringSig",
    "builtinAddSubDateDatetimeAnySig",
    "builtinAddSubDateDurationAnySig",
    "builtinTimestamp1ArgSig",
    "builtinTimestamp2ArgsSig",
    "builtinTimestampLiteralSig",
    "builtinConvertTzSig",
    "builtinTiDBBoundedStalenessSig",
    "builtinTiDBCurrentTsoSig",
];

/// 非线程安全签名数量。
pub const GENERATED_SIGNATURE_COUNT: usize = GENERATED_THREADUNSAFE_SIGNATURES.len();

/// 判断签名名是否属于非线程安全生成清单。
pub fn IsGeneratedThreadunsafeSignature(name: &str) -> bool {
    GENERATED_THREADUNSAFE_SIGNATURES.contains(&name)
}
