[package]
name = "astersql-timer"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[package.metadata.porting]
go-package = "pkg/timer"
legacy-tasks = ["task-1498"]

[dev-dependencies]
"astersql-kv" = { package = "astersql-kv", path = "../kv" }
"astersql-meta-metadef" = { package = "astersql-meta-metadef", path = "../meta/metadef" }
"astersql-session-syssession" = { package = "astersql-session-syssession", path = "../session/syssession" }
"astersql-testkit" = { package = "astersql-testkit", path = "../testkit" }
"astersql-testkit-testsetup" = { package = "astersql-testkit-testsetup", path = "../testkit/testsetup" }
"astersql-timer-api" = { package = "astersql-timer-api", path = "api" }
"astersql-timer-runtime" = { package = "astersql-timer-runtime", path = "runtime" }
"astersql-timer-tablestore" = { package = "astersql-timer-tablestore", path = "tablestore" }
"astersql-util-timeutil" = { package = "astersql-util-timeutil", path = "../util/timeutil" }
