// Copyright 2026 AsterSQL.
// Copyright 2024 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Plan Cache 用物理计划克隆（由 plan_clone_generator 生成逻辑迁移）。
//
// 前半为 Go 参考实现注释；后半 `CloneForPlanCache` trait 与 `CachePlan`
// 枚举提供可编译的 Rust 接线骨架。Plan Cache 复用已编译计划，避免重复优化。

// 本 Rust 文件仅用于人工审阅。
// Go 的 interface、指针、slice、map、defer、goroutine、context 及第三方类型保留为后续 Rust 模块接线点。
// 下面的中文说明对应主要迁移边界；完整 Go 语义按原文件逐行保留，避免用空泛 TODO 替代实现。
//
// Go imports 与外部依赖仅记录在原始代码段中，待后续 crate 接线。
//
// 主要声明清单：
// 类型：无
// 函数/方法：CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache, CloneForPlanCache
// 常量/变量：见原始代码段
//
// 迁移提示：
// - plan/physical plan 的接口调用保留 Go 的动态分发形状，Rust 接线时需选择 trait object 或泛型。
// - nil、错误返回、可变 slice/map 和 defer 的生命周期语义不能在本批次擅自改写。
//
// /*
//  * 以下为按声明顺序保留的 Go 实现参考。它不是运行时代码；Rust 迁移阶段以此逐段替换，
//  * 每个函数边界和关键分支均保留，便于和来源文件做一比一审查。
//  */
//
// Copyright 2024 PingCAP, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by plan_clone_generator; DO NOT EDIT IT DIRECTLY.
//
// package physicalop
//
// import (
//     "github.com/pingcap/tidb/pkg/expression"
//     "github.com/pingcap/tidb/pkg/planner/core/base"
//     "github.com/pingcap/tidb/pkg/planner/util"
//     "github.com/pingcap/tidb/pkg/planner/util/utilfuncp"
//     sliceutil "github.com/pingcap/tidb/pkg/util/slice"
// )
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *Update) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(Update)
//     *cloned = *op
//     cloned.SimpleSchemaProducer = *op.SimpleSchemaProducer.CloneSelfForPlanCache(newCtx)
//     cloned.OrderedList = util.CloneAssignments(op.OrderedList)
//     if op.SelectPlan != nil {
//         SelectPlan, ok := op.SelectPlan.CloneForPlanCache(newCtx)
//         if !ok {
//             return nil, false
//         }
//         cloned.SelectPlan = SelectPlan.(base.PhysicalPlan)
//     }
//     if op.FKChecks != nil {
//         return nil, false
//     }
//     if op.FKCascades != nil {
//         return nil, false
//     }
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *Delete) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(Delete)
//     *cloned = *op
//     cloned.SimpleSchemaProducer = *op.SimpleSchemaProducer.CloneSelfForPlanCache(newCtx)
//     if op.SelectPlan != nil {
//         SelectPlan, ok := op.SelectPlan.CloneForPlanCache(newCtx)
//         if !ok {
//             return nil, false
//         }
//         cloned.SelectPlan = SelectPlan.(base.PhysicalPlan)
//     }
//     if op.FKChecks != nil {
//         return nil, false
//     }
//     if op.FKCascades != nil {
//         return nil, false
//     }
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *Insert) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(Insert)
//     *cloned = *op
//     cloned.SimpleSchemaProducer = *op.SimpleSchemaProducer.CloneSelfForPlanCache(newCtx)
//     cloned.Lists = utilfuncp.CloneExpression2DForPlanCache(op.Lists)
//     cloned.OnDuplicate = util.CloneAssignments(op.OnDuplicate)
//     cloned.GenCols = op.GenCols.cloneForPlanCache()
//     if op.SelectPlan != nil {
//         SelectPlan, ok := op.SelectPlan.CloneForPlanCache(newCtx)
//         if !ok {
//             return nil, false
//         }
//         cloned.SelectPlan = SelectPlan.(base.PhysicalPlan)
//     }
//     if op.FKChecks != nil {
//         return nil, false
//     }
//     if op.FKCascades != nil {
//         return nil, false
//     }
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalTableScan) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalTableScan)
//     *cloned = *op
//     basePlan, baseOK := op.PhysicalSchemaProducer.CloneForPlanCacheWithSelf(newCtx, cloned)
//     if !baseOK {
//         return nil, false
//     }
//     cloned.PhysicalSchemaProducer = *basePlan
//     cloned.AccessCondition = utilfuncp.CloneExpressionsForPlanCache(op.AccessCondition, nil)
//     cloned.FilterCondition = utilfuncp.CloneExpressionsForPlanCache(op.FilterCondition, nil)
//     cloned.LateMaterializationFilterCondition = utilfuncp.CloneExpressionsForPlanCache(op.LateMaterializationFilterCondition, nil)
//     cloned.HandleIdx = make([]int, len(op.HandleIdx))
//     copy(cloned.HandleIdx, op.HandleIdx)
//     if op.HandleCols != nil {
//         cloned.HandleCols = op.HandleCols.Clone()
//     }
//     cloned.ByItems = sliceutil.DeepClone(op.ByItems)
//     cloned.PlanPartInfo = op.PlanPartInfo.CloneForPlanCache()
//     if op.SampleInfo != nil {
//         return nil, false
//     }
//     cloned.constColsByCond = make([]bool, len(op.constColsByCond))
//     copy(cloned.constColsByCond, op.constColsByCond)
//     if op.runtimeFilterList != nil {
//         return nil, false
//     }
//     if op.UsedColumnarIndexes != nil {
//         return nil, false
//     }
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalIndexScan) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalIndexScan)
//     *cloned = *op
//     basePlan, baseOK := op.PhysicalSchemaProducer.CloneForPlanCacheWithSelf(newCtx, cloned)
//     if !baseOK {
//         return nil, false
//     }
//     cloned.PhysicalSchemaProducer = *basePlan
//     cloned.AccessCondition = utilfuncp.CloneExpressionsForPlanCache(op.AccessCondition, nil)
//     cloned.IdxCols = utilfuncp.CloneColumnsForPlanCache(op.IdxCols, nil)
//     cloned.IdxColLens = make([]int, len(op.IdxColLens))
//     copy(cloned.IdxColLens, op.IdxColLens)
//     if op.GenExprs != nil {
//         return nil, false
//     }
//     cloned.ByItems = sliceutil.DeepClone(op.ByItems)
//     if op.PkIsHandleCol != nil {
//         if op.PkIsHandleCol.SafeToShareAcrossSession() {
//             cloned.PkIsHandleCol = op.PkIsHandleCol
//         } else {
//             cloned.PkIsHandleCol = op.PkIsHandleCol.Clone().(*expression.Column)
//         }
//     }
//     cloned.ConstColsByCond = make([]bool, len(op.ConstColsByCond))
//     copy(cloned.ConstColsByCond, op.ConstColsByCond)
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalSelection) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalSelection)
//     *cloned = *op
//     basePlan, baseOK := op.BasePhysicalPlan.CloneForPlanCacheWithSelf(newCtx, cloned)
//     if !baseOK {
//         return nil, false
//     }
//     cloned.BasePhysicalPlan = *basePlan
//     cloned.Conditions = utilfuncp.CloneExpressionsForPlanCache(op.Conditions, nil)
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalProjection) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalProjection)
//     *cloned = *op
//     basePlan, baseOK := op.PhysicalSchemaProducer.CloneForPlanCacheWithSelf(newCtx, cloned)
//     if !baseOK {
//         return nil, false
//     }
//     cloned.PhysicalSchemaProducer = *basePlan
//     cloned.Exprs = utilfuncp.CloneExpressionsForPlanCache(op.Exprs, nil)
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalTopN) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalTopN)
//     *cloned = *op
//     basePlan, baseOK := op.PhysicalSchemaProducer.CloneForPlanCacheWithSelf(newCtx, cloned)
//     if !baseOK {
//         return nil, false
//     }
//     cloned.PhysicalSchemaProducer = *basePlan
//     cloned.ByItems = sliceutil.DeepClone(op.ByItems)
//     cloned.PartitionBy = sliceutil.DeepClone(op.PartitionBy)
//     if op.PrefixCol != nil {
//         if op.PrefixCol.SafeToShareAcrossSession() {
//             cloned.PrefixCol = op.PrefixCol
//         } else {
//             cloned.PrefixCol = op.PrefixCol.Clone().(*expression.Column)
//         }
//     }
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalLimit) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalLimit)
//     *cloned = *op
//     basePlan, baseOK := op.PhysicalSchemaProducer.CloneForPlanCacheWithSelf(newCtx, cloned)
//     if !baseOK {
//         return nil, false
//     }
//     cloned.PhysicalSchemaProducer = *basePlan
//     cloned.PartitionBy = sliceutil.DeepClone(op.PartitionBy)
//     if op.PrefixCol != nil {
//         if op.PrefixCol.SafeToShareAcrossSession() {
//             cloned.PrefixCol = op.PrefixCol
//         } else {
//             cloned.PrefixCol = op.PrefixCol.Clone().(*expression.Column)
//         }
//     }
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalStreamAgg) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalStreamAgg)
//     *cloned = *op
//     basePlan, baseOK := op.BasePhysicalAgg.CloneForPlanCacheWithSelf(newCtx, cloned)
//     if !baseOK {
//         return nil, false
//     }
//     cloned.BasePhysicalAgg = *basePlan
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalHashAgg) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalHashAgg)
//     *cloned = *op
//     basePlan, baseOK := op.BasePhysicalAgg.CloneForPlanCacheWithSelf(newCtx, cloned)
//     if !baseOK {
//         return nil, false
//     }
//     cloned.BasePhysicalAgg = *basePlan
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalHashJoin) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalHashJoin)
//     *cloned = *op
//     basePlan, baseOK := op.BasePhysicalJoin.CloneForPlanCacheWithSelf(newCtx, cloned)
//     if !baseOK {
//         return nil, false
//     }
//     cloned.BasePhysicalJoin = *basePlan
//     cloned.EqualConditions = utilfuncp.CloneScalarFunctionsForPlanCache(op.EqualConditions, nil)
//     cloned.NAEqualConditions = utilfuncp.CloneScalarFunctionsForPlanCache(op.NAEqualConditions, nil)
//     if op.runtimeFilterList != nil {
//         return nil, false
//     }
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalMergeJoin) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalMergeJoin)
//     *cloned = *op
//     basePlan, baseOK := op.BasePhysicalJoin.CloneForPlanCacheWithSelf(newCtx, cloned)
//     if !baseOK {
//         return nil, false
//     }
//     cloned.BasePhysicalJoin = *basePlan
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalIndexJoin) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalIndexJoin)
//     *cloned = *op
//     basePlan, baseOK := op.BasePhysicalJoin.CloneForPlanCacheWithSelf(newCtx, cloned)
//     if !baseOK {
//         return nil, false
//     }
//     cloned.BasePhysicalJoin = *basePlan
//     if op.InnerPlan != nil {
//         InnerPlan, ok := op.InnerPlan.CloneForPlanCache(newCtx)
//         if !ok {
//             return nil, false
//         }
//         cloned.InnerPlan = InnerPlan.(base.PhysicalPlan)
//     }
//     cloned.Ranges = op.Ranges.CloneForPlanCache()
//     cloned.KeyOff2IdxOff = make([]int, len(op.KeyOff2IdxOff))
//     copy(cloned.KeyOff2IdxOff, op.KeyOff2IdxOff)
//     cloned.IdxColLens = make([]int, len(op.IdxColLens))
//     copy(cloned.IdxColLens, op.IdxColLens)
//     cloned.CompareFilters = op.CompareFilters.cloneForPlanCache()
//     cloned.OuterHashKeys = utilfuncp.CloneColumnsForPlanCache(op.OuterHashKeys, nil)
//     cloned.InnerHashKeys = utilfuncp.CloneColumnsForPlanCache(op.InnerHashKeys, nil)
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalIndexHashJoin) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalIndexHashJoin)
//     *cloned = *op
//     inlj, ok := op.PhysicalIndexJoin.CloneForPlanCache(newCtx)
//     if !ok {
//         return nil, false
//     }
//     cloned.PhysicalIndexJoin = *inlj.(*PhysicalIndexJoin)
//     cloned.Self = cloned
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalIndexReader) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalIndexReader)
//     *cloned = *op
//     basePlan, baseOK := op.PhysicalSchemaProducer.CloneForPlanCacheWithSelf(newCtx, cloned)
//     if !baseOK {
//         return nil, false
//     }
//     cloned.PhysicalSchemaProducer = *basePlan
//     if op.IndexPlan != nil {
//         IndexPlan, ok := op.IndexPlan.CloneForPlanCache(newCtx)
//         if !ok {
//             return nil, false
//         }
//         cloned.IndexPlan = IndexPlan.(base.PhysicalPlan)
//     }
//     cloned.IndexPlans = FlattenListPushDownPlan(cloned.IndexPlan)
//     cloned.OutputColumns = utilfuncp.CloneColumnsForPlanCache(op.OutputColumns, nil)
//     cloned.PlanPartInfo = op.PlanPartInfo.CloneForPlanCache()
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalTableReader) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalTableReader)
//     *cloned = *op
//     basePlan, baseOK := op.PhysicalSchemaProducer.CloneForPlanCacheWithSelf(newCtx, cloned)
//     if !baseOK {
//         return nil, false
//     }
//     cloned.PhysicalSchemaProducer = *basePlan
//     if op.TablePlan != nil {
//         TablePlan, ok := op.TablePlan.CloneForPlanCache(newCtx)
//         if !ok {
//             return nil, false
//         }
//         cloned.TablePlan = TablePlan.(base.PhysicalPlan)
//     }
//     cloned.TablePlans = FlattenListPushDownPlan(cloned.TablePlan)
//     cloned.PlanPartInfo = op.PlanPartInfo.CloneForPlanCache()
//     if op.TableScanAndPartitionInfos != nil {
//         return nil, false
//     }
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalIndexMergeReader) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalIndexMergeReader)
//     *cloned = *op
//     basePlan, baseOK := op.PhysicalSchemaProducer.CloneForPlanCacheWithSelf(newCtx, cloned)
//     if !baseOK {
//         return nil, false
//     }
//     cloned.PhysicalSchemaProducer = *basePlan
//     cloned.PushedLimit = op.PushedLimit.Clone()
//     cloned.ByItems = sliceutil.DeepClone(op.ByItems)
//     PartialPlansRaw, ok := ClonePhysicalPlansForPlanCache(newCtx, op.PartialPlansRaw)
//     if !ok {
//         return nil, false
//     }
//     cloned.PartialPlansRaw = PartialPlansRaw
//     if op.TablePlan != nil {
//         TablePlan, ok := op.TablePlan.CloneForPlanCache(newCtx)
//         if !ok {
//             return nil, false
//         }
//         cloned.TablePlan = TablePlan.(base.PhysicalPlan)
//     }
//     cloned.PartialPlans = make([][]base.PhysicalPlan, len(op.PartialPlans))
//     for i, plan := range cloned.PartialPlansRaw {
//         cloned.PartialPlans[i] = FlattenListPushDownPlan(plan)
//     }
//     cloned.TablePlans = FlattenListPushDownPlan(cloned.TablePlan)
//     cloned.PlanPartInfo = op.PlanPartInfo.CloneForPlanCache()
//     if op.HandleCols != nil {
//         cloned.HandleCols = op.HandleCols.Clone()
//     }
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalIndexLookUpReader) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalIndexLookUpReader)
//     *cloned = *op
//     basePlan, baseOK := op.PhysicalSchemaProducer.CloneForPlanCacheWithSelf(newCtx, cloned)
//     if !baseOK {
//         return nil, false
//     }
//     cloned.PhysicalSchemaProducer = *basePlan
//     if op.IndexPlan != nil {
//         IndexPlan, ok := op.IndexPlan.CloneForPlanCache(newCtx)
//         if !ok {
//             return nil, false
//         }
//         cloned.IndexPlan = IndexPlan.(base.PhysicalPlan)
//     }
//     if op.TablePlan != nil {
//         TablePlan, ok := op.TablePlan.CloneForPlanCache(newCtx)
//         if !ok {
//             return nil, false
//         }
//         cloned.TablePlan = TablePlan.(base.PhysicalPlan)
//     }
//     if cloned.IndexLookUpPushDown {
//         cloned.IndexPlans, cloned.IndexPlansUnNatureOrders = FlattenTreePushDownPlan(cloned.IndexPlan)
//     } else {
//         cloned.IndexPlans = FlattenListPushDownPlan(cloned.IndexPlan)
//     }
//     if op.IndexPlansUnNatureOrders != nil {
//         cloned.IndexPlansUnNatureOrders = make(map[int]int, len(op.IndexPlansUnNatureOrders))
//         for k, v := range op.IndexPlansUnNatureOrders {
//             cloned.IndexPlansUnNatureOrders[k] = v
//         }
//     }
//     cloned.TablePlans = FlattenListPushDownPlan(cloned.TablePlan)
//     if op.ExtraHandleCol != nil {
//         if op.ExtraHandleCol.SafeToShareAcrossSession() {
//             cloned.ExtraHandleCol = op.ExtraHandleCol
//         } else {
//             cloned.ExtraHandleCol = op.ExtraHandleCol.Clone().(*expression.Column)
//         }
//     }
//     cloned.PushedLimit = op.PushedLimit.Clone()
//     cloned.CommonHandleCols = utilfuncp.CloneColumnsForPlanCache(op.CommonHandleCols, nil)
//     cloned.PlanPartInfo = op.PlanPartInfo.CloneForPlanCache()
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalLocalIndexLookUp) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalLocalIndexLookUp)
//     *cloned = *op
//     basePlan, baseOK := op.PhysicalSchemaProducer.CloneForPlanCacheWithSelf(newCtx, cloned)
//     if !baseOK {
//         return nil, false
//     }
//     cloned.PhysicalSchemaProducer = *basePlan
//     cloned.IndexHandleOffsets = make([]uint32, len(op.IndexHandleOffsets))
//     copy(cloned.IndexHandleOffsets, op.IndexHandleOffsets)
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *BatchPointGetPlan) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(BatchPointGetPlan)
//     *cloned = *op
//     cloned.SimpleSchemaProducer = *op.SimpleSchemaProducer.CloneSelfForPlanCache(newCtx)
//     ProbeParents, ok := ClonePhysicalPlansForPlanCache(newCtx, op.ProbeParents)
//     if !ok {
//         return nil, false
//     }
//     cloned.ProbeParents = ProbeParents
//     cloned.ctx = newCtx
//     cloned.Handles = util.CloneHandles(op.Handles)
//     cloned.HandleParams = utilfuncp.CloneConstantsForPlanCache(op.HandleParams, nil)
//     cloned.IndexValues = util.CloneDatum2D(op.IndexValues)
//     cloned.IndexValueParams = CloneConstant2DForPlanCache(op.IndexValueParams)
//     cloned.AccessConditions = utilfuncp.CloneExpressionsForPlanCache(op.AccessConditions, nil)
//     cloned.IdxCols = utilfuncp.CloneColumnsForPlanCache(op.IdxCols, nil)
//     cloned.IdxColLens = make([]int, len(op.IdxColLens))
//     copy(cloned.IdxColLens, op.IdxColLens)
//     cloned.PartitionIdxs = make([]int, len(op.PartitionIdxs))
//     copy(cloned.PartitionIdxs, op.PartitionIdxs)
//     cloned.accessCols = utilfuncp.CloneColumnsForPlanCache(op.accessCols, nil)
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PointGetPlan) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PointGetPlan)
//     *cloned = *op
//     cloned.Plan = *op.Plan.CloneWithNewCtx(newCtx)
//     if op.PartitionIdx != nil {
//         cloned.PartitionIdx = new(int)
//         *cloned.PartitionIdx = *op.PartitionIdx
//     }
//     if op.Handle != nil {
//         cloned.Handle = op.Handle.Copy()
//     }
//     if op.HandleConstant != nil {
//         if op.HandleConstant.SafeToShareAcrossSession() {
//             cloned.HandleConstant = op.HandleConstant
//         } else {
//             cloned.HandleConstant = op.HandleConstant.Clone().(*expression.Constant)
//         }
//     }
//     cloned.IndexValues = util.CloneDatums(op.IndexValues)
//     cloned.IndexConstants = utilfuncp.CloneConstantsForPlanCache(op.IndexConstants, nil)
//     cloned.IdxCols = utilfuncp.CloneColumnsForPlanCache(op.IdxCols, nil)
//     cloned.IdxColLens = make([]int, len(op.IdxColLens))
//     copy(cloned.IdxColLens, op.IdxColLens)
//     cloned.AccessConditions = utilfuncp.CloneExpressionsForPlanCache(op.AccessConditions, nil)
//     cloned.accessCols = utilfuncp.CloneColumnsForPlanCache(op.accessCols, nil)
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalUnionScan) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalUnionScan)
//     *cloned = *op
//     basePlan, baseOK := op.BasePhysicalPlan.CloneForPlanCacheWithSelf(newCtx, cloned)
//     if !baseOK {
//         return nil, false
//     }
//     cloned.BasePhysicalPlan = *basePlan
//     cloned.Conditions = utilfuncp.CloneExpressionsForPlanCache(op.Conditions, nil)
//     if op.HandleCols != nil {
//         cloned.HandleCols = op.HandleCols.Clone()
//     }
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalUnionAll) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalUnionAll)
//     *cloned = *op
//     basePlan, baseOK := op.PhysicalSchemaProducer.CloneForPlanCacheWithSelf(newCtx, cloned)
//     if !baseOK {
//         return nil, false
//     }
//     cloned.PhysicalSchemaProducer = *basePlan
//     return cloned, true
// }
//
// CloneForPlanCache implements the base.Plan interface.
// func (op *PhysicalTableDual) CloneForPlanCache(newCtx base.PlanContext) (base.Plan, bool) {
//     cloned := new(PhysicalTableDual)
//     *cloned = *op
//     basePlan, baseOK := op.PhysicalSchemaProducer.CloneForPlanCacheWithSelf(newCtx, cloned)
//     if !baseOK {
//         return nil, false
//     }
//     cloned.PhysicalSchemaProducer = *basePlan
//     cloned.names = util.CloneFieldNames(op.names)
//     return cloned, true
// }
//
// */
// 文件尾：以上完整保留 Go 来源实现，未删除或修改来源文件。

// ---- 以下为可执行的 Rust 克隆接线 ----

use crate::physical_common_plans::{Delete, Insert, PhysicalPlanNode, Update};
use crate::physical_index_hash_join::LegacyPhysicalIndexHashJoin;
use crate::physical_index_merge_join::LegacyPhysicalIndexMergeJoin;
use crate::physical_indexlookup::PhysicalLocalIndexLookup;
use crate::{PhysicalHashJoin, PhysicalIndexJoin, PhysicalMergeJoin};

/// Plan Cache 克隆：成功返回副本，失败（不可缓存字段）返回 None。
pub trait CloneForPlanCache: Sized {
    /// 尝试克隆自身供缓存复用。
    fn clone_for_plan_cache(&self) -> Option<Self>;
}
/// 递归克隆通用物理计划节点及其 children。
impl CloneForPlanCache for PhysicalPlanNode {
    fn clone_for_plan_cache(&self) -> Option<Self> {
        let mut cloned = self.clone();
        cloned.children = self
            .children
            .iter()
            .map(CloneForPlanCache::clone_for_plan_cache)
            .collect::<Option<Vec<_>>>()?;
        Some(cloned)
    }
}
impl CloneForPlanCache for PhysicalHashJoin {
    fn clone_for_plan_cache(&self) -> Option<Self> {
        if !self.RuntimeFilterList.is_empty() {
            return None;
        }
        Some(Self {
            BasePhysicalJoin: self.BasePhysicalJoin.CloneForPlanCacheWithSelf(
                self.BasePhysicalJoin
                    .PhysicalSchemaProducer
                    .BasePhysicalPlan
                    .Plan
                    .SCtx()
                    .clone(),
            )?,
            Concurrency: self.Concurrency,
            EqualConditions: self
                .EqualConditions
                .iter()
                .map(expression::ScalarFunction::clone_scalar)
                .collect(),
            NAEqualConditions: self
                .NAEqualConditions
                .iter()
                .map(expression::ScalarFunction::clone_scalar)
                .collect(),
            UseOuterToBuild: self.UseOuterToBuild,
            StoreTp: self.StoreTp,
            MppShuffleJoin: self.MppShuffleJoin,
            FromHashJoinHint: self.FromHashJoinHint,
            HasTableAlias: self.HasTableAlias,
            RuntimeFilterList: Vec::new(),
            RuntimeFilterTypes: self.RuntimeFilterTypes.clone(),
        })
    }
}
impl CloneForPlanCache for PhysicalMergeJoin {
    fn clone_for_plan_cache(&self) -> Option<Self> {
        Some(Self {
            BasePhysicalJoin: self.BasePhysicalJoin.CloneForPlanCacheWithSelf(
                self.BasePhysicalJoin
                    .PhysicalSchemaProducer
                    .BasePhysicalPlan
                    .Plan
                    .SCtx()
                    .clone(),
            )?,
            Desc: self.Desc,
            CompareFuncs: self.CompareFuncs.clone(),
        })
    }
}
impl CloneForPlanCache for PhysicalIndexJoin {
    fn clone_for_plan_cache(&self) -> Option<Self> {
        let context = self
            .BasePhysicalJoin
            .PhysicalSchemaProducer
            .BasePhysicalPlan
            .Plan
            .SCtx()
            .clone();
        Some(Self {
            BasePhysicalJoin: self
                .BasePhysicalJoin
                .CloneForPlanCacheWithSelf(context.clone())?,
            InnerPlan: self
                .InnerPlan
                .as_ref()
                .map(|plan| plan.clone_physical(context))
                .transpose()
                .ok()?,
            Ranges: self.Ranges.clone(),
            KeyOff2IdxOff: self.KeyOff2IdxOff.clone(),
            IdxColLens: self.IdxColLens.clone(),
            CompareFilters: self
                .CompareFilters
                .as_ref()
                .map(crate::physical_index_join::ColWithCmpFuncManager::cloneForPlanCache),
            OuterHashKeys: self
                .OuterHashKeys
                .iter()
                .map(expression::Column::Clone)
                .collect(),
            InnerHashKeys: self
                .InnerHashKeys
                .iter()
                .map(expression::Column::Clone)
                .collect(),
            EqualConditions: self
                .EqualConditions
                .iter()
                .map(expression::ScalarFunction::clone_scalar)
                .collect(),
            FromDecorrelatedApply: self.FromDecorrelatedApply,
        })
    }
}
/// 克隆 Insert；SelectPlan 不可缓存时整体失败。
impl CloneForPlanCache for Insert {
    fn clone_for_plan_cache(&self) -> Option<Self> {
        if !self.fk_checks.is_empty() || !self.fk_cascades.is_empty() {
            return None;
        }
        let mut cloned = self.clone();
        cloned.select_plan = self
            .select_plan
            .as_ref()
            .map(CloneForPlanCache::clone_for_plan_cache)
            .transpose_option()?;
        Some(cloned)
    }
}
/// 外键元数据存在时拒绝缓存；否则克隆 Update。
impl CloneForPlanCache for Update {
    fn clone_for_plan_cache(&self) -> Option<Self> {
        if !self.fk_checks.is_empty() || !self.fk_cascades.is_empty() {
            return None;
        }
        Some(self.clone())
    }
}
/// 外键元数据存在时拒绝缓存；否则克隆 Delete。
impl CloneForPlanCache for Delete {
    fn clone_for_plan_cache(&self) -> Option<Self> {
        if !self.fk_checks.is_empty() || !self.fk_cascades.is_empty() {
            return None;
        }
        Some(self.clone())
    }
}
/// 分别克隆 outer/inner 子计划。
impl CloneForPlanCache for LegacyPhysicalIndexHashJoin {
    fn clone_for_plan_cache(&self) -> Option<Self> {
        Some(Self {
            outer: self.outer.clone_for_plan_cache()?,
            inner: self.inner.clone_for_plan_cache()?,
            ..self.clone()
        })
    }
}
/// 分别克隆 outer/inner 子计划。
impl CloneForPlanCache for LegacyPhysicalIndexMergeJoin {
    fn clone_for_plan_cache(&self) -> Option<Self> {
        Some(Self {
            outer: self.outer.clone_for_plan_cache()?,
            inner: self.inner.clone_for_plan_cache()?,
            ..self.clone()
        })
    }
}
/// 分别克隆 index_plan 与 table_plan。
impl CloneForPlanCache for PhysicalLocalIndexLookup {
    fn clone_for_plan_cache(&self) -> Option<Self> {
        Some(Self {
            index_plan: self.index_plan.clone_for_plan_cache()?,
            table_plan: self.table_plan.clone_for_plan_cache()?,
            ..self.clone()
        })
    }
}

/// 将 `Option<Option<T>>` 展平为缓存语义：内层 None 表示克隆失败。
trait TransposeOption<T> {
    fn transpose_option(self) -> Option<Option<T>>;
}
impl<T> TransposeOption<T> for Option<Option<T>> {
    fn transpose_option(self) -> Option<Option<T>> {
        match self {
            Some(Some(value)) => Some(Some(value)),
            Some(None) => None,
            None => Some(None),
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
/// 可缓存物理计划变体集合（覆盖常见算子与 DML）。
pub enum CachePlan {
    Update(Update),
    Delete(Delete),
    Insert(Insert),
    TableScan(PhysicalPlanNode),
    IndexScan(PhysicalPlanNode),
    Selection(PhysicalPlanNode),
    Projection(PhysicalPlanNode),
    TopN(PhysicalPlanNode),
    Limit(PhysicalPlanNode),
    StreamAgg(PhysicalPlanNode),
    HashAgg(PhysicalPlanNode),
    HashJoin(PhysicalPlanNode),
    MergeJoin(PhysicalPlanNode),
    IndexJoin(PhysicalPlanNode),
    IndexHashJoin(LegacyPhysicalIndexHashJoin),
    IndexReader(PhysicalPlanNode),
    TableReader(PhysicalPlanNode),
    IndexMergeReader(PhysicalPlanNode),
    IndexLookupReader(PhysicalPlanNode),
    LocalIndexLookup(PhysicalLocalIndexLookup),
    BatchPointGet(PhysicalPlanNode),
    PointGet(PhysicalPlanNode),
    UnionScan(PhysicalPlanNode),
    UnionAll(PhysicalPlanNode),
    TableDual(PhysicalPlanNode),
}
/// 按变体分发到具体类型的 clone_for_plan_cache。
impl CloneForPlanCache for CachePlan {
    fn clone_for_plan_cache(&self) -> Option<Self> {
        Some(match self {
            Self::Update(value) => Self::Update(value.clone_for_plan_cache()?),
            Self::Delete(value) => Self::Delete(value.clone_for_plan_cache()?),
            Self::Insert(value) => Self::Insert(value.clone_for_plan_cache()?),
            Self::IndexHashJoin(value) => Self::IndexHashJoin(value.clone_for_plan_cache()?),
            Self::LocalIndexLookup(value) => Self::LocalIndexLookup(value.clone_for_plan_cache()?),
            Self::TableScan(value) => Self::TableScan(value.clone_for_plan_cache()?),
            Self::IndexScan(value) => Self::IndexScan(value.clone_for_plan_cache()?),
            Self::Selection(value) => Self::Selection(value.clone_for_plan_cache()?),
            Self::Projection(value) => Self::Projection(value.clone_for_plan_cache()?),
            Self::TopN(value) => Self::TopN(value.clone_for_plan_cache()?),
            Self::Limit(value) => Self::Limit(value.clone_for_plan_cache()?),
            Self::StreamAgg(value) => Self::StreamAgg(value.clone_for_plan_cache()?),
            Self::HashAgg(value) => Self::HashAgg(value.clone_for_plan_cache()?),
            Self::HashJoin(value) => Self::HashJoin(value.clone_for_plan_cache()?),
            Self::MergeJoin(value) => Self::MergeJoin(value.clone_for_plan_cache()?),
            Self::IndexJoin(value) => Self::IndexJoin(value.clone_for_plan_cache()?),
            Self::IndexReader(value) => Self::IndexReader(value.clone_for_plan_cache()?),
            Self::TableReader(value) => Self::TableReader(value.clone_for_plan_cache()?),
            Self::IndexMergeReader(value) => Self::IndexMergeReader(value.clone_for_plan_cache()?),
            Self::IndexLookupReader(value) => {
                Self::IndexLookupReader(value.clone_for_plan_cache()?)
            }
            Self::BatchPointGet(value) => Self::BatchPointGet(value.clone_for_plan_cache()?),
            Self::PointGet(value) => Self::PointGet(value.clone_for_plan_cache()?),
            Self::UnionScan(value) => Self::UnionScan(value.clone_for_plan_cache()?),
            Self::UnionAll(value) => Self::UnionAll(value.clone_for_plan_cache()?),
            Self::TableDual(value) => Self::TableDual(value.clone_for_plan_cache()?),
        })
    }
}
