[package]
name = "astersql-util-memory"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[features]
default = []
mem-arbitrator = []

[dependencies]
astersql-errno = { path = "../../errno" }
config_crate = { package = "astersql-config", path = "../../config" }
cgroup_crate = { package = "astersql-util-cgroup", path = "../cgroup" }
chrono = "0.4"
crossbeam-utils = "0.8"
logutil_crate = { package = "astersql-util-logutil", path = "../logutil" }
memory-stats = "1"
serde_json = "1"
rpprof = { git = "https://github.com/mingley/pprof-rs", tag = "v0.18.1" }
sqlkiller_crate = { package = "astersql-util-sqlkiller", path = "../sqlkiller" }
sysinfo = "0.33"
tempfile = "3"

[dev-dependencies]
rand = "0.9"

[package.metadata.porting]
go-package = "pkg/util/memory"
legacy-tasks = ["task-337", "task-344", "task-354", "task-355", "task-362"]
