[package]
name = "astersql-lightning-backend-encode"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[dependencies]
verification = { package = "astersql-lightning-verification", path = "../../verification" }

[package.metadata.porting]
go-package = "pkg/lightning/backend/encode"
