[package]
name = "astersql-types-field"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[dependencies]
collate = { package = "astersql-util-collate", path = "../../../util/collate" }
dbterror = { package = "astersql-util-dbterror", path = "../../../util/dbterror" }
mathutil = { package = "astersql-util-mathutil", path = "../../../util/mathutil" }
parser-types = { package = "astersql-parser-types", path = "../../../parser/types" }
