// Copyright 2026 AsterSQL.
// Copyright 2019 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// 比较类内置函数的向量化 Go 代码生成器，对应 `compare_vec.go`。
//
// 按比较算子（LT/LE/GT/GE/EQ/NE/NullEQ/Coalesce）× EvalType 矩阵展开
// `vecEval*` / `vectorized` 方法及基准测试用例；Int 的普通比较与 NullEQ
// 保留手写实现故跳过。模板用显式占位符替换，格式化留给接线层。

// Generates comparison vector Go source and tests.
// Go 的 text/template 用显式上下文替换保留生成语义；gofmt 负责等价的语法校验与格式化，最终 IO 留在接线边界。

use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

/// 生成文件公共版权头与 package 声明。
pub const HEADER: &str = r#"// Copyright 2019 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go generate in expression/generator; DO NOT EDIT.

package expression
"#;

/// 换行常量，便于与 Go 生成器拼接风格一致。
pub const NEW_LINE: &str = "\n";

/// 比较向量化实现所需的 import 块。
pub const BUILTIN_COMPARE_IMPORTS: &str = r#"import (
	"cmp"
	"github.com/pingcap/tidb/pkg/types"
	"github.com/pingcap/tidb/pkg/util/chunk"
)
"#;

/// 对应 helper.TypeContext；字符串字段仍使用 Go 模板中的类型拼写。
#[derive(Clone, Copy)]
pub struct TypeContext {
    pub et_name: &'static str,
    pub type_name: &'static str,
    pub type_name_in_column: &'static str,
    pub type_name_go: &'static str,
    pub fixed: bool,
}

/// Int EvalType 模板上下文。
pub const TYPE_INT: TypeContext = TypeContext {
    et_name: "Int",
    type_name: "Int",
    type_name_in_column: "Int64",
    type_name_go: "int64",
    fixed: true,
};
/// Real EvalType 模板上下文。
pub const TYPE_REAL: TypeContext = TypeContext {
    et_name: "Real",
    type_name: "Real",
    type_name_in_column: "Float64",
    type_name_go: "float64",
    fixed: true,
};
/// Decimal EvalType 模板上下文。
pub const TYPE_DECIMAL: TypeContext = TypeContext {
    et_name: "Decimal",
    type_name: "Decimal",
    type_name_in_column: "Decimal",
    type_name_go: "types.MyDecimal",
    fixed: true,
};
/// String EvalType 模板上下文（变长列）。
pub const TYPE_STRING: TypeContext = TypeContext {
    et_name: "String",
    type_name: "String",
    type_name_in_column: "String",
    type_name_go: "string",
    fixed: false,
};
/// Datetime/Time EvalType 模板上下文。
pub const TYPE_DATETIME: TypeContext = TypeContext {
    et_name: "Datetime",
    type_name: "Time",
    type_name_in_column: "Time",
    type_name_go: "types.Time",
    fixed: true,
};
/// Duration EvalType 模板上下文。
pub const TYPE_DURATION: TypeContext = TypeContext {
    et_name: "Duration",
    type_name: "Duration",
    type_name_in_column: "GoDuration",
    type_name_go: "time.Duration",
    fixed: true,
};
/// JSON EvalType 模板上下文（变长列）。
pub const TYPE_JSON: TypeContext = TypeContext {
    et_name: "Json",
    type_name: "JSON",
    type_name_in_column: "JSON",
    type_name_go: "json.BinaryJSON",
    fixed: false,
};

/// 对应 CompareContext，保存生成方法名片段与和零比较时使用的运算符。
#[derive(Clone, Copy)]
pub struct CompareContext {
    pub compare_name: &'static str,
    pub operator: &'static str,
}

/// 全部比较算子表（含 NullEQ、Coalesce）。
pub const COMPARES_MAP: &[CompareContext] = &[
    CompareContext {
        compare_name: "LT",
        operator: "<",
    },
    CompareContext {
        compare_name: "LE",
        operator: "<=",
    },
    CompareContext {
        compare_name: "GT",
        operator: ">",
    },
    CompareContext {
        compare_name: "GE",
        operator: ">=",
    },
    CompareContext {
        compare_name: "EQ",
        operator: "==",
    },
    CompareContext {
        compare_name: "NE",
        operator: "!=",
    },
    CompareContext {
        compare_name: "NullEQ",
        operator: "",
    },
    CompareContext {
        compare_name: "Coalesce",
        operator: "",
    },
];

/// 参与生成的 EvalType 列表。
pub const TYPES_MAP: &[TypeContext] = &[
    TYPE_INT,
    TYPE_REAL,
    TYPE_DECIMAL,
    TYPE_STRING,
    TYPE_DATETIME,
    TYPE_DURATION,
    TYPE_JSON,
];

/// 普通比较模板的稳定骨架。类型专用取值表达式由 compare_expression 补入。
const BUILTIN_COMPARE_VEC_TEMPLATE: &str = r#"
func (b *builtin{CompareName}{TypeName}Sig) vecEvalInt(ctx EvalContext, input *chunk.Chunk, result *chunk.Column) error {
	n := input.NumRows()
	buf0, err := b.bufAllocator.get()
	if err != nil { return err }
	defer b.bufAllocator.put(buf0)
	if err := b.args[0].VecEval{TypeName}(ctx, input, buf0); err != nil { return err }
	buf1, err := b.bufAllocator.get()
	if err != nil { return err }
	defer b.bufAllocator.put(buf1)
	if err := b.args[1].VecEval{TypeName}(ctx, input, buf1); err != nil { return err }
	{FixedArgs}
	result.ResizeInt64(n, false)
	result.MergeNulls(buf0, buf1)
	i64s := result.Int64s()
	for i := 0; i < n; i++ {
		if result.IsNull(i) { continue }
		val := {CompareExpression}
		i64s[i] = boolToInt64(val {Operator} 0)
	}
	return nil
}

func (b *builtin{CompareName}{TypeName}Sig) vectorized() bool { return true }
"#;

/// NullEQ 单独处理两个 NULL：双 NULL 为真，单 NULL 为假，其余再做类型比较。
const BUILTIN_NULL_EQ_COMPARE_VEC_TEMPLATE: &str = r#"
func (b *builtinNullEQ{TypeName}Sig) vecEvalInt(ctx EvalContext, input *chunk.Chunk, result *chunk.Column) error {
	n := input.NumRows()
	buf0, err := b.bufAllocator.get()
	if err != nil { return err }
	defer b.bufAllocator.put(buf0)
	if err := b.args[0].VecEval{TypeName}(ctx, input, buf0); err != nil { return err }
	buf1, err := b.bufAllocator.get()
	if err != nil { return err }
	defer b.bufAllocator.put(buf1)
	if err := b.args[1].VecEval{TypeName}(ctx, input, buf1); err != nil { return err }
	{FixedArgs}
	result.ResizeInt64(n, false)
	i64s := result.Int64s()
	for i := 0; i < n; i++ {
		isNull0, isNull1 := buf0.IsNull(i), buf1.IsNull(i)
		switch {
		case isNull0 && isNull1: i64s[i] = 1
		case isNull0 != isNull1: i64s[i] = 0
		case {CompareExpression} == 0: i64s[i] = 1
		}
	}
	return nil
}

func (b *builtinNullEQ{TypeName}Sig) vectorized() bool { return true }
"#;

/// 测试文件 map 字面量头部。
const BUILTIN_COMPARE_VEC_TEST_HEADER: &str = r#"import (
	"testing"
	"github.com/pingcap/tidb/pkg/parser/ast"
	"github.com/pingcap/tidb/pkg/types"
)

var vecGeneratedBuiltinCompareCases = map[string][]vecExprBenchCase{
"#;

/// 测试与 benchmark 入口函数尾部。
const BUILTIN_COMPARE_VEC_TEST_TAIL: &str = r#"}

func TestVectorizedGeneratedBuiltinCompareEvalOneVec(t *testing.T) { testVectorizedEvalOneVec(t, vecGeneratedBuiltinCompareCases) }
func TestVectorizedGeneratedBuiltinCompareFunc(t *testing.T) { testVectorizedBuiltinFunc(t, vecGeneratedBuiltinCompareCases) }
func BenchmarkVectorizedGeneratedBuiltinCompareEvalOneVec(b *testing.B) { benchmarkVectorizedEvalOneVec(b, vecGeneratedBuiltinCompareCases) }
func BenchmarkVectorizedGeneratedBuiltinCompareFunc(b *testing.B) { benchmarkVectorizedBuiltinFunc(b, vecGeneratedBuiltinCompareCases) }
"#;

/// 根据 EvalType 生成与 Go 模板相同的比较表达式。
fn compare_expression(t: TypeContext) -> &'static str {
    match t.et_name {
        "Json" => "types.CompareBinaryJSON(buf0.GetJSON(i), buf1.GetJSON(i))",
        "Real" | "Duration" => "cmp.Compare(arg0[i], arg1[i])",
        "String" => "types.CompareString(buf0.GetString(i), buf1.GetString(i), b.collation)",
        "Datetime" => "arg0[i].Compare(arg1[i])",
        "Decimal" => "arg0[i].Compare(&arg1[i])",
        _ => "cmp.Compare(arg0[i], arg1[i])",
    }
}

/// 只替换本使用的确定占位符，避免把 Go text/template 的控制语义误译为 Rust 宏。
fn render(mut template: String, compare: CompareContext, t: TypeContext) -> String {
    let fixed_args = if t.fixed {
        format!(
            "arg0 := buf0.{}s()\n\targ1 := buf1.{}s()",
            t.type_name_in_column, t.type_name_in_column
        )
    } else {
        String::new()
    };
    for (key, value) in [
        ("{CompareName}", compare.compare_name),
        ("{TypeName}", t.type_name),
        ("{Operator}", compare.operator),
        ("{CompareExpression}", compare_expression(t)),
        ("{FixedArgs}", fixed_args.as_str()),
    ] {
        template = template.replace(key, value);
    }
    template
}

fn render_coalesce(t: TypeContext) -> String {
    let fallback_store = match t.type_name {
        "Decimal" => "x[i] = *res".to_owned(),
        "Duration" => "x[i] = res.Duration".to_owned(),
        _ => "x[i] = res".to_owned(),
    };
    let fallback = if t.fixed {
        format!(
            r#"func (b *builtinCoalesce{0}Sig) fallbackEval{0}(ctx EvalContext, input *chunk.Chunk, result *chunk.Column) error {{
	n := input.NumRows()
	x := result.{1}s()
	for i := 0; i < n; i++ {{
		res, isNull, err := b.eval{0}(ctx, input.GetRow(i))
		if err != nil {{ return err }}
		result.SetNull(i, isNull)
		if isNull {{ continue }}
		{2}
	}}
	return nil
}}
"#,
            t.type_name, t.type_name_in_column, fallback_store
        )
    } else {
        format!(
            r#"func (b *builtinCoalesce{0}Sig) fallbackEval{0}(ctx EvalContext, input *chunk.Chunk, result *chunk.Column) error {{
	n := input.NumRows()
	result.Reserve{1}(n)
	for i := 0; i < n; i++ {{
		res, isNull, err := b.eval{0}(ctx, input.GetRow(i))
		if err != nil {{ return err }}
		if isNull {{ result.AppendNull(); continue }}
		result.Append{1}(res)
	}}
	return nil
}}
"#,
            t.type_name, t.type_name_in_column
        )
    };

    let vector = if t.fixed {
        let fsp = if t.type_name == "Time" {
            "\n\t\tfsp := b.tp.GetDecimal()"
        } else {
            ""
        };
        let set_fsp = if t.type_name == "Time" {
            "\n\t\t\t\ti64s[i].SetFsp(fsp)"
        } else {
            ""
        };
        format!(
            r#"func (b *builtinCoalesce{0}Sig) vecEval{0}(ctx EvalContext, input *chunk.Chunk, result *chunk.Column) error {{
	n := input.NumRows()
	result.Resize{1}(n, true)
	i64s := result.{1}s()
	buf1, err := b.bufAllocator.get()
	if err != nil {{ return err }}
	defer b.bufAllocator.put(buf1)
	beforeWarns := warningCount(ctx)
	for j := 0; j < len(b.args); j++ {{
		err := b.args[j].VecEval{0}(ctx, input, buf1){2}
		afterWarns := warningCount(ctx)
		if err != nil || afterWarns > beforeWarns {{
			if afterWarns > beforeWarns {{ truncateWarnings(ctx, beforeWarns) }}
			return b.fallbackEval{0}(ctx, input, result)
		}}
		args := buf1.{1}s()
		for i := 0; i < n; i++ {{
			if !buf1.IsNull(i) && result.IsNull(i) {{
				i64s[i] = args[i]{3}
				result.SetNull(i, false)
			}}
		}}
	}}
	return nil
}}
"#,
            t.type_name, t.type_name_in_column, fsp, set_fsp
        )
    } else {
        format!(
            r#"func (b *builtinCoalesce{0}Sig) vecEval{0}(ctx EvalContext, input *chunk.Chunk, result *chunk.Column) error {{
	n := input.NumRows()
	argLen := len(b.args)
	bufs := make([]*chunk.Column, argLen)
	beforeWarns := warningCount(ctx)
	for i := 0; i < argLen; i++ {{
		buf, err := b.bufAllocator.get()
		if err != nil {{ return err }}
		defer b.bufAllocator.put(buf)
		err = b.args[i].VecEval{0}(ctx, input, buf)
		afterWarns := warningCount(ctx)
		if err != nil || afterWarns > beforeWarns {{
			if afterWarns > beforeWarns {{ truncateWarnings(ctx, beforeWarns) }}
			return b.fallbackEval{0}(ctx, input, result)
		}}
		bufs[i] = buf
	}}
	result.Reserve{0}(n)
	for i := 0; i < n; i++ {{
		for j := 0; j < argLen; j++ {{
			if !bufs[j].IsNull(i) {{ result.Append{0}(bufs[j].Get{0}(i)); break }}
			if j == argLen-1 && bufs[j].IsNull(i) {{ result.AppendNull() }}
		}}
	}}
	return nil
}}
"#,
            t.type_name
        )
    };
    format!(
        "\n// NOTE: Coalesce just return the first non-null item, but vectorization do each item, which would incur additional errors. If this case happen,\n// the vectorization falls back to the scalar execution.\n{fallback}\n{vector}\nfunc (b *builtinCoalesce{}Sig) vectorized() bool {{ return true }}\n",
        t.type_name
    )
}

/// 使用 gofmt 提供与 Go `format.Source` 相同的语法校验和格式化边界。
fn format_go_source(source: &[u8]) -> Result<Vec<u8>, String> {
    let mut child = Command::new("gofmt")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|err| err.to_string())?;
    child
        .stdin
        .take()
        .ok_or_else(|| "gofmt stdin was not piped".to_owned())?
        .write_all(source)
        .map_err(|err| err.to_string())?;
    let output = child.wait_with_output().map_err(|err| err.to_string())?;
    if output.status.success() {
        return Ok(output.stdout);
    }
    // 与 Go format.Source 失败分支一致：记录警告，并保留原文供调试。
    eprintln!(
        "[Warn] gofmt failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    Ok(source.to_vec())
}

/// 对应 generateDotGo：普通比较跳过 Int（已有手写实现），NullEQ 同样跳过 Int，Coalesce 覆盖全部类型。
pub fn generate_dot_go(
    compares: &[CompareContext],
    types: &[TypeContext],
) -> Result<Vec<u8>, String> {
    let mut out = String::from(HEADER);
    out.push_str(NEW_LINE);
    out.push_str(BUILTIN_COMPARE_IMPORTS);
    for &compare in compares {
        for &t in types {
            let template = match compare.compare_name {
                "NullEQ" if t.type_name == TYPE_INT.type_name => continue,
                "NullEQ" => BUILTIN_NULL_EQ_COMPARE_VEC_TEMPLATE,
                "Coalesce" => {
                    out.push_str(&render_coalesce(t));
                    continue;
                }
                _ if t.type_name == TYPE_INT.type_name => continue,
                _ => BUILTIN_COMPARE_VEC_TEMPLATE,
            };
            out.push_str(&render(template.to_owned(), compare, t));
        }
    }
    format_go_source(out.as_bytes())
}

/// 对应 generateTestDotGo：按函数分组生成基准用例，Coalesce 每种类型生成三参数用例。
pub fn generate_test_dot_go(
    compares: &[CompareContext],
    types: &[TypeContext],
) -> Result<Vec<u8>, String> {
    let mut out = format!("{}{}", HEADER, BUILTIN_COMPARE_VEC_TEST_HEADER);
    for compare in compares {
        out.push_str(&format!("\tast.{}: {{\n", compare.compare_name));
        for t in types {
            if compare.compare_name != "Coalesce" && t.type_name == TYPE_INT.type_name {
                continue;
            }
            if compare.compare_name == "Coalesce" {
                out.push_str(&format!("\t\t{{\n\t\t\tretEvalType: types.ET{},\n\t\t\tchildrenTypes: []types.EvalType{{types.ET{}, types.ET{}, types.ET{}}},\n\t\t\tgeners: []dataGenerator{{\n\t\t\t\tgener{{*newDefaultGener(0.2, types.ET{})}},\n\t\t\t\tgener{{*newDefaultGener(0.2, types.ET{})}},\n\t\t\t\tgener{{*newDefaultGener(0.2, types.ET{})}},\n\t\t\t}},\n\t\t}},\n", t.et_name, t.et_name, t.et_name, t.et_name, t.et_name, t.et_name, t.et_name));
            } else {
                out.push_str(&format!("\t\t{{retEvalType: types.ETInt, childrenTypes: []types.EvalType{{types.ET{}, types.ET{}}}}},\n", t.et_name, t.et_name));
            }
        }
        out.push_str("\t},\n");
    }
    out.push_str(BUILTIN_COMPARE_VEC_TEST_TAIL);
    format_go_source(out.as_bytes())
}

/// 对应 generateOneFile：返回主文件和测试文件的路径/内容，不在这里执行写盘 IO。
pub fn generate_one_file(
    prefix: &Path,
    compares: &[CompareContext],
    types: &[TypeContext],
) -> Result<[(PathBuf, Vec<u8>); 2], String> {
    Ok([
        (
            prefix.with_extension("go"),
            generate_dot_go(compares, types)?,
        ),
        (
            PathBuf::from(format!("{}_test.go", prefix.display())),
            generate_test_dot_go(compares, types)?,
        ),
    ])
}

/// 对应 Go main 的默认输出位置。
pub fn default_outputs() -> Result<[(PathBuf, Vec<u8>); 2], String> {
    generate_one_file(
        Path::new("./builtin_compare_vec_generated"),
        COMPARES_MAP,
        TYPES_MAP,
    )
}
