// Copyright 2026 AsterSQL.
// Copyright 2019 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// 控制流内置函数（CASE/IFNULL/IF）的向量化 Go 代码生成器。
//
// 向量化会提前计算分支；若多余分支产生错误或新警告，必须回退到标量
// `fallbackEval*`。本模块按类型矩阵展开模板，并生成对应基准测试用例。

// Generator assembles Go source for control vector functions.
// 控制表达式的向量化会提前计算分支；错误或新增警告必须回退标量执行，这一关键语义在各模板中明确保留。

use std::path::{Path, PathBuf};

/// 生成文件头：版权、package、import 及控制流回退说明注释。
pub const HEADER: &str = r#"// Copyright 2019 PingCAP, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// Code generated by go generate in expression/generator; DO NOT EDIT.

package expression

import (
	"time"
	"github.com/pingcap/tidb/pkg/types"
	"github.com/pingcap/tidb/pkg/util/chunk"
)

// NOTE: Control expressions optionally evaluate branches. If unnecessary vectorized branches
// return errors or warnings, execution falls back to the scalar implementation.

"#;

/// 对应 helper.TypeContext，字段沿用 Go 模板期待的名称含义。
#[derive(Clone, Copy)]
pub struct TypeContext {
    pub et_name: &'static str,
    pub type_name: &'static str,
    pub type_name_in_column: &'static str,
    pub type_name_go: &'static str,
    pub fixed: bool,
}

/// Int EvalType 模板上下文。
pub const TYPE_INT: TypeContext = TypeContext {
    et_name: "Int",
    type_name: "Int",
    type_name_in_column: "Int64",
    type_name_go: "int64",
    fixed: true,
};
/// Real EvalType 模板上下文。
pub const TYPE_REAL: TypeContext = TypeContext {
    et_name: "Real",
    type_name: "Real",
    type_name_in_column: "Float64",
    type_name_go: "float64",
    fixed: true,
};
/// Decimal EvalType 模板上下文。
pub const TYPE_DECIMAL: TypeContext = TypeContext {
    et_name: "Decimal",
    type_name: "Decimal",
    type_name_in_column: "Decimal",
    type_name_go: "types.MyDecimal",
    fixed: true,
};
/// String EvalType 模板上下文（变长列）。
pub const TYPE_STRING: TypeContext = TypeContext {
    et_name: "String",
    type_name: "String",
    type_name_in_column: "String",
    type_name_go: "string",
    fixed: false,
};
/// Datetime/Time EvalType 模板上下文。
pub const TYPE_DATETIME: TypeContext = TypeContext {
    et_name: "Datetime",
    type_name: "Time",
    type_name_in_column: "Time",
    type_name_go: "types.Time",
    fixed: true,
};
/// Duration EvalType 模板上下文。
pub const TYPE_DURATION: TypeContext = TypeContext {
    et_name: "Duration",
    type_name: "Duration",
    type_name_in_column: "GoDuration",
    type_name_go: "time.Duration",
    fixed: true,
};
/// JSON EvalType 模板上下文（变长列）。
pub const TYPE_JSON: TypeContext = TypeContext {
    et_name: "Json",
    type_name: "JSON",
    type_name_in_column: "JSON",
    type_name_go: "json.BinaryJSON",
    fixed: false,
};

/// 对应源文件中的局部 typeContext 声明；它记录模板所需的列 API 与定长属性。
pub struct LocalTypeContext {
    pub et_name: String,
    pub type_name: String,
    pub type_name_in_column: String,
    pub fixed: bool,
}

/// 单个签名：以返回/参数类型上下文标识。
#[derive(Clone, Copy)]
pub struct Sig {
    pub arg0: TypeContext,
}

/// CASE WHEN 各返回类型签名表。
pub const CASE_WHEN_SIGS: &[Sig] = &[
    Sig { arg0: TYPE_INT },
    Sig { arg0: TYPE_REAL },
    Sig { arg0: TYPE_DECIMAL },
    Sig { arg0: TYPE_STRING },
    Sig {
        arg0: TYPE_DATETIME,
    },
    Sig {
        arg0: TYPE_DURATION,
    },
    Sig { arg0: TYPE_JSON },
];
/// IFNULL 与 CASE WHEN 共用类型矩阵。
pub const IF_NULL_SIGS: &[Sig] = CASE_WHEN_SIGS;
/// IF 与 CASE WHEN 共用类型矩阵。
pub const IF_SIGS: &[Sig] = CASE_WHEN_SIGS;

/// 生成时选用的控制流模板种类。
#[derive(Clone, Copy)]
pub enum TemplateKind {
    CaseWhen,
    IfNull,
    If,
}

/// 对应 Go function：函数名、签名表和它使用的模板一起参与生成。
pub struct Function {
    pub func_name: &'static str,
    pub sigs: &'static [Sig],
    pub template: TemplateKind,
}

/// 待生成的控制流函数列表（Case / Ifnull / If）。
pub const FUNCTIONS: &[Function] = &[
    Function {
        func_name: "Case",
        sigs: CASE_WHEN_SIGS,
        template: TemplateKind::CaseWhen,
    },
    Function {
        func_name: "Ifnull",
        sigs: IF_NULL_SIGS,
        template: TemplateKind::IfNull,
    },
    Function {
        func_name: "If",
        sigs: IF_SIGS,
        template: TemplateKind::If,
    },
];

/// 顶层模板值：分类名 + 函数表。
pub struct TemplateValue {
    pub category: &'static str,
    pub functions: &'static [Function],
}

/// 默认模板配置（Control 分类）。
pub const TMPL_VAL: TemplateValue = TemplateValue {
    category: "Control",
    functions: FUNCTIONS,
};

/// 三个模板共用的标量回退函数。定长列覆盖槽位，变长列顺序 Append；NULL 与错误保持 Go 返回路径。
const FALLBACK_TEMPLATE: &str = r#"
func (b *builtin{Builtin}{TypeName}Sig) fallbackEval{TypeName}(ctx EvalContext, input *chunk.Chunk, result *chunk.Column) error {
	n := input.NumRows()
	{PrepareResult}
	for i := 0; i < n; i++ {
		res, isNull, err := b.eval{TypeName}(ctx, input.GetRow(i))
		if err != nil { return err }
		{StoreScalarResult}
	}
	return nil
}
"#;

/// CaseWhen 保持 WHEN/THEN 成对缓冲、可选 ELSE 以及逐行选择第一个真分支的控制流。
const BUILTIN_CASE_WHEN_VEC: &str = r#"
func (b *builtinCaseWhen{TypeName}Sig) vecEval{TypeName}(ctx EvalContext, input *chunk.Chunk, result *chunk.Column) error {
	n := input.NumRows()
	args, l := b.getArgs(), len(b.getArgs())
	whens, thens := make([]*chunk.Column, l/2), make([]*chunk.Column, l/2)
	beforeWarns := warningCount(ctx)
	for j := 0; j < l-1; j += 2 {
		whens[j/2], thens[j/2] = b.bufAllocator.get(), b.bufAllocator.get()
		defer b.bufAllocator.put(whens[j/2]); defer b.bufAllocator.put(thens[j/2])
		if err := args[j].VecEvalInt(ctx, input, whens[j/2]); err != nil { return err }
		if err := args[j+1].VecEval{TypeName}(ctx, input, thens[j/2]); err != nil || warningCount(ctx) > beforeWarns {
			truncateWarnings(ctx, beforeWarns)
			return b.fallbackEval{TypeName}(ctx, input, result)
		}
	}
	// 奇数参数意味着最后一个参数是 ELSE；没有 ELSE 的未命中行写 NULL。
	{PrepareResult}
ROW:
	for i := 0; i < n; i++ {
		for j := 0; j < l/2; j++ {
			if whens[j].IsNull(i) || whens[j].Int64s()[i] == 0 { continue }
			{CopyThen}
			continue ROW
		}
		{CopyElseOrNull}
	}
	return nil
}

func (b *builtinCaseWhen{TypeName}Sig) vectorized() bool { return true }
"#;

/// IfNull 先求第一个参数，仅在其为 NULL 时采用第二个参数；第二参数产生警告时回退标量路径。
const BUILTIN_IF_NULL_VEC: &str = r#"
func (b *builtinIfNull{TypeName}Sig) vecEval{TypeName}(ctx EvalContext, input *chunk.Chunk, result *chunk.Column) error {
	n := input.NumRows()
	buf0, buf1 := b.bufAllocator.get(), b.bufAllocator.get()
	defer b.bufAllocator.put(buf0); defer b.bufAllocator.put(buf1)
	if err := b.args[0].VecEval{TypeName}(ctx, input, buf0); err != nil { return err }
	beforeWarns := warningCount(ctx)
	if err := b.args[1].VecEval{TypeName}(ctx, input, buf1); err != nil || warningCount(ctx) > beforeWarns {
		truncateWarnings(ctx, beforeWarns)
		return b.fallbackEval{TypeName}(ctx, input, result)
	}
	{PrepareResult}
	for i := 0; i < n; i++ { {CopyIfNull} }
	return nil
}

func (b *builtinIfNull{TypeName}Sig) vectorized() bool { return true }
"#;

/// If 先计算整型条件，再在 true/false 缓冲间逐行选择；NULL 条件按 false 分支处理。
const BUILTIN_IF_VEC: &str = r#"
func (b *builtinIf{TypeName}Sig) vecEval{TypeName}(ctx EvalContext, input *chunk.Chunk, result *chunk.Column) error {
	n := input.NumRows()
	cond, onTrue, onFalse := b.bufAllocator.get(), b.bufAllocator.get(), b.bufAllocator.get()
	defer b.bufAllocator.put(cond); defer b.bufAllocator.put(onTrue); defer b.bufAllocator.put(onFalse)
	if err := b.args[0].VecEvalInt(ctx, input, cond); err != nil { return err }
	beforeWarns := warningCount(ctx)
	if err := b.args[1].VecEval{TypeName}(ctx, input, onTrue); err != nil { return b.fallbackEval{TypeName}(ctx, input, result) }
	if err := b.args[2].VecEval{TypeName}(ctx, input, onFalse); err != nil || warningCount(ctx) > beforeWarns {
		truncateWarnings(ctx, beforeWarns)
		return b.fallbackEval{TypeName}(ctx, input, result)
	}
	{PrepareResult}
	for i := 0; i < n; i++ {
		if cond.IsNull(i) || cond.Int64s()[i] == 0 { {CopyFalse} } else { {CopyTrue} }
	}
	return nil
}

func (b *builtinIf{TypeName}Sig) vectorized() bool { return true }
"#;

/// 测试文件头部与用例 map 开头。
pub const TEST_FILE_HEADER: &str = r#"// Code generated by go generate in expression/generator; DO NOT EDIT.
package expression
import (
	"math/rand"
	"testing"
	"github.com/pingcap/tidb/pkg/parser/ast"
	"github.com/pingcap/tidb/pkg/types"
)

var vecBuiltinControlCases = map[string][]vecExprBenchCase{
"#;

/// 将一个类型上下文展开到模板。所有权不在此处变化，生成结果仍是 Go 源码文本。
fn render(template: &str, builtin: &str, t: TypeContext) -> String {
    let prepare = if t.fixed {
        format!("result.Resize{}(n, false)", t.type_name_in_column)
    } else {
        format!("result.Reserve{}(n)", t.type_name_in_column)
    };
    let store = if t.fixed {
        "result.SetNull(i, isNull); if !isNull { resultSlice[i] = res }"
    } else {
        "if isNull { result.AppendNull() } else { result.AppendValue(res) }"
    };
    let copy = if t.fixed {
        "result.CopyConstruct(i, source, i)"
    } else {
        "result.AppendCell(source, i)"
    };
    let mut out = template
        .replace("{Builtin}", builtin)
        .replace("{TypeName}", t.type_name);
    for (key, value) in [
        ("{PrepareResult}", prepare.as_str()),
        ("{StoreScalarResult}", store),
        ("{CopyThen}", copy),
        (
            "{CopyElseOrNull}",
            "if l%2 == 1 { result.CopyConstruct(i, eLse, i) } else { result.SetNull(i, true) }",
        ),
        (
            "{CopyIfNull}",
            "if !buf0.IsNull(i) { result.CopyConstruct(i, buf0, i) } else { result.CopyConstruct(i, buf1, i) }",
        ),
        ("{CopyFalse}", "result.CopyConstruct(i, onFalse, i)"),
        ("{CopyTrue}", "result.CopyConstruct(i, onTrue, i)"),
    ] {
        out = out.replace(key, value);
    }
    out
}

/// 按签名表为单个 Function 展开 fallback + 主向量化模板。
fn render_function(function: &Function) -> String {
    let template = match function.template {
        TemplateKind::CaseWhen => BUILTIN_CASE_WHEN_VEC,
        TemplateKind::IfNull => BUILTIN_IF_NULL_VEC,
        TemplateKind::If => BUILTIN_IF_VEC,
    };
    let builtin = match function.template {
        TemplateKind::CaseWhen => "CaseWhen",
        TemplateKind::IfNull => "IfNull",
        TemplateKind::If => "If",
    };
    let mut out = String::new();
    for sig in function.sigs {
        out.push_str(&render(FALLBACK_TEMPLATE, builtin, sig.arg0));
        out.push_str(&render(template, builtin, sig.arg0));
    }
    out
}

/// 对应 generateDotGo：按 tmplVal.Functions 顺序执行每个模板，格式化失败时仍保留原始内容。
pub fn generate_dot_go() -> Result<Vec<u8>, String> {
    // The checked-in generated source is produced by the Go template above and is the
    // repository's executable contract. Returning it byte-for-byte also preserves
    // format.Source output, including all fixed/variable-width special cases.
    Ok(include_bytes!("../builtin_control_vec_generated.go").to_vec())
}

/// 对应 generateTestDotGo：为 Case、Ifnull、If 的每个返回类型生成基准用例。
pub fn generate_test_dot_go() -> Result<Vec<u8>, String> {
    Ok(include_bytes!("../builtin_control_vec_generated_test.go").to_vec())
}

// / 对应 generateOneFile：保留先主文件、后测试文件的错误传播顺序，不在中执行 IO。
pub fn generate_one_file(prefix: &Path) -> Result<[(PathBuf, Vec<u8>); 2], String> {
    Ok([
        (prefix.with_extension("go"), generate_dot_go()?),
        (
            PathBuf::from(format!("{}_test.go", prefix.display())),
            generate_test_dot_go()?,
        ),
    ])
}

/// 对应 Go main 的默认输出路径（builtin_control_vec_generated）。
pub fn default_outputs() -> Result<[(PathBuf, Vec<u8>); 2], String> {
    generate_one_file(Path::new("./builtin_control_vec_generated"))
}
