// Copyright 2026 AsterSQL.
// Copyright 2019 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Other 类向量化内置函数（当前为 SQL `IN`）的 Go 源码生成器。
//
// 对应 Go `expression/generator/other_vec.go`：按类型签名展开 `vecEvalInt`，
// 保留常量哈希快路径、动态参数逐列比较、NULL/UNKNOWN 传播及无符号整数与排序规则分支。

// Assembles Go source for IN vector functions.
// 哈希常量快路径、动态参数逐列比较、NULL 传播、无符号整数与排序规则等不直观语义均在模板分支中保留。

use std::path::{Path, PathBuf};

/// 生成实现文件的版权头与 `package expression` 声明。
pub const HEADER: &str = r#"// Copyright 2019 PingCAP, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// Code generated by go generate in expression/generator; DO NOT EDIT.

package expression
"#;

/// 生成源码中的换行分隔符。
pub const NEW_LINE: &str = "\n";

/// IN 实现文件所需的 Go import 块（比较、类型、chunk、排序规则）。
pub const BUILTIN_OTHER_IMPORTS: &str = r#"import (
	"cmp"
	"github.com/pingcap/tidb/pkg/parser/mysql"
	"github.com/pingcap/tidb/pkg/types"
	"github.com/pingcap/tidb/pkg/util/chunk"
	"github.com/pingcap/tidb/pkg/util/collate"
)
"#;

/// 模板展开时使用的 EvalType 上下文（命名片段与固定长标志）。
#[derive(Clone, Copy)]
pub struct TypeContext {
    /// 对应 `types.ET{{name}}` 的名称片段。
    pub et_name: &'static str,
    /// 对应 `VecEval{{name}}` 的名称片段。
    pub type_name: &'static str,
    /// 对应 chunk.Column 切片访问器名称片段。
    pub type_name_in_column: &'static str,
    /// 生成 Go 代码中的具体类型名。
    pub type_name_go: &'static str,
    /// true 表示可用固定长切片批量读写。
    pub fixed: bool,
}

/// 整数 EvalType 上下文。
pub const TYPE_INT: TypeContext = TypeContext {
    et_name: "Int",
    type_name: "Int",
    type_name_in_column: "Int64",
    type_name_go: "int64",
    fixed: true,
};
/// 浮点 EvalType 上下文。
pub const TYPE_REAL: TypeContext = TypeContext {
    et_name: "Real",
    type_name: "Real",
    type_name_in_column: "Float64",
    type_name_go: "float64",
    fixed: true,
};
/// Decimal EvalType 上下文。
pub const TYPE_DECIMAL: TypeContext = TypeContext {
    et_name: "Decimal",
    type_name: "Decimal",
    type_name_in_column: "Decimal",
    type_name_go: "types.MyDecimal",
    fixed: true,
};
/// 字符串 EvalType 上下文（变长列）。
pub const TYPE_STRING: TypeContext = TypeContext {
    et_name: "String",
    type_name: "String",
    type_name_in_column: "String",
    type_name_go: "string",
    fixed: false,
};
/// 日期时间 EvalType 上下文（VecEval/chunk 侧名为 Time）。
pub const TYPE_DATETIME: TypeContext = TypeContext {
    et_name: "Datetime",
    type_name: "Time",
    type_name_in_column: "Time",
    type_name_go: "types.Time",
    fixed: true,
};
/// Duration EvalType 上下文。
pub const TYPE_DURATION: TypeContext = TypeContext {
    et_name: "Duration",
    type_name: "Duration",
    type_name_in_column: "GoDuration",
    type_name_go: "time.Duration",
    fixed: true,
};
/// JSON EvalType 上下文（变长 BinaryJSON）。
pub const TYPE_JSON: TypeContext = TypeContext {
    et_name: "Json",
    type_name: "JSON",
    type_name_in_column: "JSON",
    type_name_go: "json.BinaryJSON",
    fixed: false,
};

/// 对应 Go sig：一个生成签名包含具体 builtin 类型名、输入类型和输出类型。
#[derive(Clone, Copy)]
pub struct Sig {
    /// 生成的 Go 接收者类型名，如 `builtinInIntSig`。
    pub sig_name: &'static str,
    /// 左值与列表元素的 EvalType 上下文。
    pub input: TypeContext,
    /// 向量化结果列类型（IN 恒为 Int/布尔语义）。
    pub output: TypeContext,
}

/// IN 各类型签名表，顺序与 Go `inSigsTmpl` 一致。
pub const IN_SIGS_TMPL: &[Sig] = &[
    Sig {
        sig_name: "builtinInIntSig",
        input: TYPE_INT,
        output: TYPE_INT,
    },
    Sig {
        sig_name: "builtinInStringSig",
        input: TYPE_STRING,
        output: TYPE_INT,
    },
    Sig {
        sig_name: "builtinInDecimalSig",
        input: TYPE_DECIMAL,
        output: TYPE_INT,
    },
    Sig {
        sig_name: "builtinInRealSig",
        input: TYPE_REAL,
        output: TYPE_INT,
    },
    Sig {
        sig_name: "builtinInTimeSig",
        input: TYPE_DATETIME,
        output: TYPE_INT,
    },
    Sig {
        sig_name: "builtinInDurationSig",
        input: TYPE_DURATION,
        output: TYPE_INT,
    },
    Sig {
        sig_name: "builtinInJSONSig",
        input: TYPE_JSON,
        output: TYPE_INT,
    },
];

/// 一类可生成函数及其签名列表（Other 类目前仅含 In）。
pub struct Function {
    /// AST/函数名片段，如 `"In"`。
    pub func_name: &'static str,
    /// 该函数下全部类型特化签名。
    pub sigs: &'static [Sig],
}

/// Other 类函数表。
pub const FUNCTIONS: &[Function] = &[Function {
    func_name: "In",
    sigs: IN_SIGS_TMPL,
}];

/// 顶层模板输入：分类名 + 函数列表。
pub struct TemplateValue {
    /// 生成物类别标签，如 `"Other"`。
    pub category: &'static str,
    /// 本文件覆盖的函数集合。
    pub functions: &'static [Function],
}

/// Other 生成器的默认模板输入。
pub const TMPL_VAL: TemplateValue = TemplateValue {
    category: "Other",
    functions: FUNCTIONS,
};

/// IN 模板的公共主体。类型相关的读取、哈希键和比较表达式由 render_in_sig 注入。
const BUILTIN_IN_TEMPLATE: &str = r#"
func (b *{SigName}) vecEvalInt(ctx EvalContext, input *chunk.Chunk, result *chunk.Column) error {
	n := input.NumRows()
	buf0, err := b.bufAllocator.get()
	if err != nil { return err }
	defer b.bufAllocator.put(buf0)
	if err := b.args[0].VecEval{InputType}(ctx, input, buf0); err != nil { return err }
	buf1, err := b.bufAllocator.get()
	if err != nil { return err }
	defer b.bufAllocator.put(buf1)

	result.ResizeInt64(n, true)
	r64s := result.Int64s()
	hasNull := make([]bool, n)
	{InitializeHasNull}
	args := b.args[1:]

	// 常量参数已由构造阶段写入 hashSet；命中后可以跳过后续动态参数比较。
	if len(b.hashSet) != 0 {
		{PrepareHashLookup}
		for i := 0; i < n; i++ {
			if buf0.IsNull(i) { hasNull[i] = true; continue }
			arg0 := {ReadArg0}
				{HashLookup}
		}
		args = make([]Expression, 0, len(b.nonConstArgsIdx))
		for _, i := range b.nonConstArgsIdx { args = append(args, b.args[i]) }
	}

	for j := 0; j < len(args); j++ {
		if err := args[j].VecEval{InputType}(ctx, input, buf1); err != nil { return err }
		{PrepareDynamicCompare}
		for i := 0; i < n; i++ {
			if r64s[i] != 0 { continue }
			if buf1.IsNull(i) || buf0.IsNull(i) { hasNull[i] = true; continue }
			arg0, arg1 := {ReadArg0}, {ReadArg1}
			compareResult := {CompareExpression}
			if compareResult == 0 { result.SetNull(i, false); r64s[i] = 1 }
		}
	}

	// 只有尚未命中的行才继承 hasNull；SQL IN 的 UNKNOWN 语义不能覆盖已经为真的结果。
	for i := 0; i < n; i++ { if result.IsNull(i) { result.SetNull(i, hasNull[i]) } }
	return nil
}

func (b *{SigName}) vectorized() bool { return true }
"#;

/// 为类型选择常量哈希键。Decimal/JSON 使用 ToHashKey，字符串使用排序规则键，时间使用 CoreTime。
fn hash_lookup(t: TypeContext) -> &'static str {
    match t.type_name {
        "Int" => {
            "if isUnsigned, ok := b.hashSet[arg0]; ok && ((isUnsigned0 && isUnsigned) || (!isUnsigned0 && !isUnsigned) || arg0 >= 0) { r64s[i] = 1; result.SetNull(i, false) }"
        }
        "Decimal" | "JSON" => {
            "key, err := arg0.ToHashKey()\n\t\t\tif err != nil {\n\t\t\t\treturn err\n\t\t\t}\n\t\t\tif _, ok := b.hashSet[string(key)]; ok { r64s[i] = 1; result.SetNull(i, false) }"
        }
        "String" => {
            "if _, ok := b.hashSet[string(collator.Key(arg0))]; ok { r64s[i] = 1; result.SetNull(i, false) }"
        }
        "Time" => {
            "if _, ok := b.hashSet[arg0.CoreTime()]; ok { r64s[i] = 1; result.SetNull(i, false) }"
        }
        _ => "if _, ok := b.hashSet[arg0]; ok { r64s[i] = 1; result.SetNull(i, false) }",
    }
}

/// 为动态参数选择与 Go 模板相同的比较规则。
fn compare_expression(t: TypeContext) -> &'static str {
    match t.type_name {
        "Int" => "compareSignedAndUnsignedInts(arg0, arg1, isUnsigned0, isUnsigned)",
        "Decimal" => "arg0.Compare(&arg1)",
        "Time" => "arg0.Compare(arg1)",
        "Duration" | "Real" => "cmp.Compare(arg0, arg1)",
        "JSON" => "types.CompareBinaryJSON(arg0, arg1)",
        "String" => "types.CompareString(arg0, arg1, b.collation)",
        _ => "types.CompareValue(arg0, arg1)",
    }
}

/// 展开单个 IN 签名，保留固定长切片与变长 Get 方法的差异。
fn render_in_sig(sig: Sig) -> String {
    let t = sig.input;
    let read0 = if t.fixed {
        "buf0Values[i]".to_owned()
    } else {
        format!("buf0.Get{}(i)", t.type_name)
    };
    let read1 = if t.fixed {
        "buf1Values[i]".to_owned()
    } else {
        format!("buf1.Get{}(i)", t.type_name)
    };
    let init_null = if t.type_name == "JSON" {
        ""
    } else {
        "if b.hasNull { for i := 0; i < n; i++ { hasNull[i] = true } }"
    };
    let prepare_hash = match t.type_name {
        "String" => "collator := collate.GetCollator(b.collation)",
        "Int" => "isUnsigned0 := mysql.HasUnsignedFlag(b.args[0].GetType(ctx).GetFlag())",
        _ => "",
    };
    let mut prepare_compare = if t.fixed {
        format!(
            "buf0Values := buf0.{}s(); buf1Values := buf1.{}s(); buf1.MergeNulls(buf0)",
            t.type_name_in_column, t.type_name_in_column
        )
    } else {
        String::new()
    };
    if t.type_name == "Int" {
        prepare_compare
            .push_str("; isUnsigned := mysql.HasUnsignedFlag(args[j].GetType(ctx).GetFlag())");
    }

    let mut out = BUILTIN_IN_TEMPLATE.to_owned();
    // 按占位符注入类型相关的读取、哈希与比较表达式。
    for (key, value) in [
        ("{SigName}", sig.sig_name),
        ("{InputType}", t.type_name),
        ("{InitializeHasNull}", init_null),
        ("{PrepareHashLookup}", prepare_hash),
        ("{ReadArg0}", read0.as_str()),
        ("{ReadArg1}", read1.as_str()),
        ("{HashLookup}", hash_lookup(t)),
        ("{PrepareDynamicCompare}", prepare_compare.as_str()),
        ("{CompareExpression}", compare_expression(t)),
    ] {
        out = out.replace(key, value);
    }
    if t.type_name == "JSON" {
        let start = out.find("\tif len(b.hashSet) != 0 {").unwrap();
        let end_marker = "\t}\n\n\tfor j := 0; j < len(args); j++ {";
        let end = out[start..].find(end_marker).unwrap() + start;
        out.replace_range(start..end + 3, "");
    }
    out
}

/// 生成测试文件头：含 `inGener` 与用例 map 开头。
pub const TEST_FILE_HEADER: &str = r#"// Copyright 2019 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go generate in expression/generator; DO NOT EDIT.
package expression
import (
	"fmt"
	"math/rand"
	"strconv"
	"testing"
	"time"
	"github.com/pingcap/tidb/pkg/parser/ast"
	"github.com/pingcap/tidb/pkg/parser/mysql"
	"github.com/pingcap/tidb/pkg/types"
)

type inGener struct { defaultGener }

func (g inGener) gen() any {
	if rand.Float64() < g.nullRation { return nil }
	randNum := rand.Int63n(10)
	switch g.eType {
	case types.ETInt: if rand.Float64() < 0.5 { return -randNum }; return randNum
	case types.ETReal: if rand.Float64() < 0.5 { return -float64(randNum) }; return float64(randNum)
	case types.ETDecimal: d := new(types.MyDecimal); f := float64(randNum * 100000); if err := d.FromFloat64(f); err != nil { panic(err) }; return d
	case types.ETDatetime, types.ETTimestamp: return types.NewTime(types.FromDate(2019, 11, 2, 22, 0, int(randNum), rand.Intn(1000000)), convertETType(g.eType), 0)
	case types.ETDuration: return types.Duration{Duration: time.Duration(randNum)}
	case types.ETJson: j := new(types.BinaryJSON); jsonStr := fmt.Sprintf("{\"key\":%v}", randNum); if err := j.UnmarshalJSON([]byte(jsonStr)); err != nil { panic(err) }; return *j
	case types.ETString: return strconv.FormatInt(randNum, 10)
	}
	return randNum
}

var vecBuiltinOtherGeneratedCases = map[string][]vecExprBenchCase{
"#;

/// 对应 generateDotGo：写入文件头、导入，再按 inSigsTmpl 顺序展开模板。
pub fn generate_dot_go() -> Result<Vec<u8>, String> {
    let mut out = format!("{}{}{}", HEADER, NEW_LINE, BUILTIN_OTHER_IMPORTS);
    for &sig in IN_SIGS_TMPL {
        out.push_str(&render_in_sig(sig));
    }
    Ok(out.into_bytes())
}

/// 对应 generateTestDotGo：每个类型同时生成全动态参数与两个常量参数的测试用例。
pub fn generate_test_dot_go() -> Result<Vec<u8>, String> {
    let mut out = format!("{}\tast.In: {{\n", TEST_FILE_HEADER);
    for sig in IN_SIGS_TMPL {
        let et = sig.input.et_name;
        out.push_str(&format!("\t\t// {}\n\t\t{{retEvalType: types.ET{}, childrenTypes: []types.EvalType{{types.ET{}, types.ET{}, types.ET{}, types.ET{}}}, geners: []dataGenerator{{inGener{{*newDefaultGener(0.2, types.ET{})}}, inGener{{*newDefaultGener(0.2, types.ET{})}}, inGener{{*newDefaultGener(0.2, types.ET{})}}, inGener{{*newDefaultGener(0.2, types.ET{})}}}}}},\n", sig.sig_name, sig.output.et_name, et, et, et, et, et, et, et, et));
        let constants = match et {
            "Int" => {
                "{Value: types.NewDatum(1), RetType: types.NewFieldType(mysql.TypeInt24)}, {Value: types.NewDatum(2), RetType: types.NewFieldType(mysql.TypeInt24)}"
            }
            "String" => {
                "{Value: types.NewStringDatum(\"aaaa\"), RetType: types.NewFieldType(mysql.TypeString)}, {Value: types.NewStringDatum(\"bbbb\"), RetType: types.NewFieldType(mysql.TypeString)}"
            }
            "Datetime" => {
                "{Value: types.NewTimeDatum(dateTimeFromString(\"2019-01-01\")), RetType: types.NewFieldType(mysql.TypeDatetime)}, {Value: types.NewTimeDatum(dateTimeFromString(\"2019-01-01\")), RetType: types.NewFieldType(mysql.TypeDatetime)}"
            }
            "Json" => {
                "{Value: types.NewJSONDatum(types.CreateBinaryJSON(\"aaaa\")), RetType: types.NewFieldType(mysql.TypeJSON)}, {Value: types.NewJSONDatum(types.CreateBinaryJSON(\"bbbb\")), RetType: types.NewFieldType(mysql.TypeJSON)}"
            }
            "Duration" => {
                "{Value: types.NewDurationDatum(types.Duration{Duration: time.Duration(1000)}), RetType: types.NewFieldType(mysql.TypeDuration)}, {Value: types.NewDurationDatum(types.Duration{Duration: time.Duration(2000)}), RetType: types.NewFieldType(mysql.TypeDuration)}"
            }
            "Real" => {
                "{Value: types.NewFloat64Datum(0.1), RetType: types.NewFieldType(mysql.TypeFloat)}, {Value: types.NewFloat64Datum(0.2), RetType: types.NewFieldType(mysql.TypeFloat)}"
            }
            "Decimal" => {
                "{Value: types.NewDecimalDatum(types.NewDecFromInt(10)), RetType: types.NewFieldType(mysql.TypeNewDecimal)}, {Value: types.NewDecimalDatum(types.NewDecFromInt(20)), RetType: types.NewFieldType(mysql.TypeNewDecimal)}"
            }
            _ => return Err(format!("unsupported IN EvalType: {et}")),
        };
        out.push_str(&format!("\t\t// {} with const arguments\n\t\t{{retEvalType: types.ET{}, childrenTypes: []types.EvalType{{types.ET{}, types.ET{}, types.ET{}}}, constants: []*Constant{{nil, {constants}}}}},\n", sig.sig_name, sig.output.et_name, et, et, et));
    }
    out.push_str("\t},\n}\n");
    out.push_str("func TestVectorizedBuiltinOtherEvalOneVecGenerated(t *testing.T) { testVectorizedEvalOneVec(t, vecBuiltinOtherGeneratedCases) }\n");
    out.push_str("func TestVectorizedBuiltinOtherFuncGenerated(t *testing.T) { testVectorizedBuiltinFunc(t, vecBuiltinOtherGeneratedCases) }\n");
    out.push_str("func BenchmarkVectorizedBuiltinOtherEvalOneVecGenerated(b *testing.B) { benchmarkVectorizedEvalOneVec(b, vecBuiltinOtherGeneratedCases) }\n");
    out.push_str("func BenchmarkVectorizedBuiltinOtherFuncGenerated(b *testing.B) { benchmarkVectorizedBuiltinFunc(b, vecBuiltinOtherGeneratedCases) }\n");
    Ok(out.into_bytes())
}

/// 对应 generateOneFile：先生成主文件，成功后生成测试文件；这里只返回待写内容以避免意外 IO。
pub fn generate_one_file(prefix: &Path) -> Result<[(PathBuf, Vec<u8>); 2], String> {
    Ok([
        (prefix.with_extension("go"), generate_dot_go()?),
        (
            PathBuf::from(format!("{}_test.go", prefix.display())),
            generate_test_dot_go()?,
        ),
    ])
}

/// 使用默认前缀 `./builtin_other_vec_generated` 生成实现与测试内容对。
pub fn default_outputs() -> Result<[(PathBuf, Vec<u8>); 2], String> {
    generate_one_file(Path::new("./builtin_other_vec_generated"))
}
