// Copyright 2026 AsterSQL.
// Copyright 2019 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// String 类向量化内置函数（当前为 SQL `FIELD`）的 Go 源码生成器。
//
// 对应 Go `expression/generator/string_vec.go`：按 Int/Real/String 类型展开
// `builtinField*Sig.vecEvalInt`，固定长走切片相等比较，字符串走排序规则比较器。

// Generates FIELD string vector functions and tests；公开入口可返回内存产物或按 Go 顺序写出文件。

use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

/// FIELD 模板展开使用的 EvalType 上下文。
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TypeContext {
    /// 对应 `types.ET{{name}}` 名称片段。
    pub et_name: &'static str,
    /// 对应 `VecEval{{name}}` / `builtinField{{name}}Sig` 名称片段。
    pub type_name: &'static str,
    /// 对应 chunk 固定长切片访问器名称。
    pub type_name_in_column: &'static str,
    /// true 表示可用固定长切片批量比较。
    pub fixed: bool,
}

/// 整数类型上下文。
pub const TYPE_INT: TypeContext = TypeContext {
    et_name: "Int",
    type_name: "Int",
    type_name_in_column: "Int64",
    fixed: true,
};
/// 浮点类型上下文。
pub const TYPE_REAL: TypeContext = TypeContext {
    et_name: "Real",
    type_name: "Real",
    type_name_in_column: "Float64",
    fixed: true,
};
/// 字符串类型上下文（变长，使用 collator 比较）。
pub const TYPE_STRING: TypeContext = TypeContext {
    et_name: "String",
    type_name: "String",
    type_name_in_column: "String",
    fixed: false,
};

/// header 对应生成文件的固定版权头与 package expression 声明。
const HEADER: &str = r#"// Copyright 2021 PingCAP, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go generate in expression/generator; DO NOT EDIT.

package expression
"#;

/// 生成源码中的换行分隔符。
const NEW_LINE: &str = "\n";

/// builtinStringImports 对应生成的实现文件唯一需要补入的 Go import 块。
const BUILTIN_STRING_IMPORTS: &str = r#"import (
	"github.com/pingcap/tidb/pkg/util/chunk"
)
"#;

/// builtinStringVecTpl 保留 Go text/template 正文；字段名与条件分支由 TypeContext 驱动。
#[allow(dead_code)]
const BUILTIN_STRING_VEC_TPL: &str = r#"
// vecEvalInt evals FIELD(str,str1,str2,str3,...).
// See https://dev.mysql.com/doc/refman/5.7/en/string-functions.html#function_field
func (b *builtinField{{ .TypeName }}Sig) vecEvalInt(ctx EvalContext, input *chunk.Chunk, result *chunk.Column) error {
	n := input.NumRows()
	buf0, err := b.bufAllocator.get()
	if err != nil {
		return err
	}
	defer b.bufAllocator.put(buf0)
	if err := b.args[0].VecEval{{ .TypeName }}(ctx, input, buf0); err != nil {
		return err
	}
	buf1, err := b.bufAllocator.get()
	if err != nil {
		return err
	}
	defer b.bufAllocator.put(buf1)
{{ if .Fixed }}
	arg0 := buf0.{{ .TypeNameInColumn }}s()
{{ end }}
	result.ResizeInt64(n, false)
	i64s := result.Int64s()
	for i := 0; i < n; i++ {
		i64s[i] = 0
	}
	for i := 1; i < len(b.args); i++ {
		if err := b.args[i].VecEval{{ .TypeName }}(ctx, input, buf1); err != nil {
			return err
		}
{{ if .Fixed }}
		arg1 := buf1.{{ .TypeNameInColumn }}s()
{{ end }}
		for j := 0; j < n; j++ {
			if i64s[j] > 0 || buf0.IsNull(j) || buf1.IsNull(j) {
				continue
			}
{{ if .Fixed }}
			if arg0[j] == arg1[j] {
{{ else }}
	{{ if eq .TypeName "String" }}
			if b.ctor.Compare(buf0.GetString(j), buf1.GetString(j)) == 0 {
	{{ else }}
			if buf0.Get{{ .TypeName }}(j) == buf1.Get{{ .TypeName }}(j) {
	{{ end }}
{{ end }}
				i64s[j] = int64(i)
			}
		}
	}
	return nil
}

func (b *builtinField{{ .TypeName }}Sig) vectorized() bool {
	return true
}
"#;

/// builtinStringVecTestTpl 对应生成测试文件的用例表、单元测试与基准入口。
#[allow(dead_code)]
const BUILTIN_STRING_VEC_TEST_TPL: &str = r#"
import (
	"testing"

	"github.com/pingcap/tidb/pkg/parser/ast"
	"github.com/pingcap/tidb/pkg/types"
)

var vecGeneratedBuiltinStringCases = map[string][]vecExprBenchCase{
	ast.Field: {
{{ range . }}
		{retEvalType: types.ETInt, childrenTypes: []types.EvalType{types.ET{{ .ETName }}, types.ET{{ .ETName }}, types.ET{{ .ETName }}, types.ET{{ .ETName }}}},
{{ end }}
	},
}

func TestVectorizedGeneratedBuiltinStringEvalOneVec(t *testing.T) {
	testVectorizedEvalOneVec(t, vecGeneratedBuiltinStringCases)
}

func TestVectorizedGeneratedBuiltinStringFunc(t *testing.T) {
	testVectorizedBuiltinFunc(t, vecGeneratedBuiltinStringCases)
}

func BenchmarkVectorizedGeneratedBuiltinStringEvalOneVec(b *testing.B) {
	benchmarkVectorizedEvalOneVec(b, vecGeneratedBuiltinStringCases)
}

func BenchmarkVectorizedGeneratedBuiltinStringFunc(b *testing.B) {
	benchmarkVectorizedBuiltinFunc(b, vecGeneratedBuiltinStringCases)
}
"#;

/// typesMap 与 Go 切片顺序一致，依次为 Int、Real、String。
fn types_map() -> [TypeContext; 3] {
    [TYPE_INT, TYPE_REAL, TYPE_STRING]
}

/// 按 TypeContext 展开单个 `builtinField*Sig` 的 vecEvalInt/vectorized 实现。
fn render_string_vec(t: TypeContext) -> String {
    let values0 = t
        .fixed
        .then(|| format!("\targ0 := buf0.{}s()\n", t.type_name_in_column))
        .unwrap_or_default();
    let values1 = t
        .fixed
        .then(|| format!("\t\targ1 := buf1.{}s()\n", t.type_name_in_column))
        .unwrap_or_default();
    let compare = if t.fixed {
        "arg0[j] == arg1[j]".to_owned()
    } else if t.type_name == "String" {
        "b.ctor.Compare(buf0.GetString(j), buf1.GetString(j)) == 0".to_owned()
    } else {
        format!("buf0.Get{}(j) == buf1.Get{}(j)", t.type_name, t.type_name)
    };
    format!(
        r#"
// vecEvalInt evals FIELD(str,str1,str2,str3,...).
// See https://dev.mysql.com/doc/refman/5.7/en/string-functions.html#function_field
func (b *builtinField{ty}Sig) vecEvalInt(ctx EvalContext, input *chunk.Chunk, result *chunk.Column) error {{
	n := input.NumRows()
	buf0, err := b.bufAllocator.get()
	if err != nil {{ return err }}
	defer b.bufAllocator.put(buf0)
	if err := b.args[0].VecEval{ty}(ctx, input, buf0); err != nil {{ return err }}
	buf1, err := b.bufAllocator.get()
	if err != nil {{ return err }}
	defer b.bufAllocator.put(buf1)
{values0}	result.ResizeInt64(n, false)
	i64s := result.Int64s()
	for i := 0; i < n; i++ {{ i64s[i] = 0 }}
	for i := 1; i < len(b.args); i++ {{
		if err := b.args[i].VecEval{ty}(ctx, input, buf1); err != nil {{ return err }}
{values1}		for j := 0; j < n; j++ {{
			if i64s[j] > 0 || buf0.IsNull(j) || buf1.IsNull(j) {{ continue }}
			if {compare} {{ i64s[j] = int64(i) }}
		}}
	}}
	return nil
}}

func (b *builtinField{ty}Sig) vectorized() bool {{ return true }}
"#,
        ty = t.type_name
    )
}

/// 对应 generateDotGo：写出头、导入，再按 typesMap 顺序展开 FIELD 实现。
pub fn generate_dot_go() -> Result<Vec<u8>, String> {
    let mut source = format!("{HEADER}{NEW_LINE}{BUILTIN_STRING_IMPORTS}");
    for type_ctx in types_map() {
        source.push_str(&render_string_vec(type_ctx));
    }
    Ok(format_go_source(source.as_bytes()).unwrap_or_else(|_| source.into_bytes()))
}

/// 对应 generateTestDotGo：为每种类型生成 FIELD 基准/单元测试用例表。
pub fn generate_test_dot_go() -> Result<Vec<u8>, String> {
    let mut cases = String::new();
    for t in types_map() {
        cases.push_str(&format!("\t\t{{retEvalType: types.ETInt, childrenTypes: []types.EvalType{{types.ET{0}, types.ET{0}, types.ET{0}, types.ET{0}}}}},\n", t.et_name));
    }
    let source = format!(
        r#"{HEADER}{NEW_LINE}
import (
	"testing"
	"github.com/pingcap/tidb/pkg/parser/ast"
	"github.com/pingcap/tidb/pkg/types"
)

var vecGeneratedBuiltinStringCases = map[string][]vecExprBenchCase{{
	ast.Field: {{
{cases}	}},
}}

func TestVectorizedGeneratedBuiltinStringEvalOneVec(t *testing.T) {{
	testVectorizedEvalOneVec(t, vecGeneratedBuiltinStringCases)
}}

func TestVectorizedGeneratedBuiltinStringFunc(t *testing.T) {{
	testVectorizedBuiltinFunc(t, vecGeneratedBuiltinStringCases)
}}

func BenchmarkVectorizedGeneratedBuiltinStringEvalOneVec(b *testing.B) {{
	benchmarkVectorizedEvalOneVec(b, vecGeneratedBuiltinStringCases)
}}

func BenchmarkVectorizedGeneratedBuiltinStringFunc(b *testing.B) {{
	benchmarkVectorizedBuiltinFunc(b, vecGeneratedBuiltinStringCases)
}}
"#
    );
    Ok(format_go_source(source.as_bytes()).unwrap_or_else(|_| source.into_bytes()))
}

/// 对应 go/format.Source；不可用或格式化失败时由调用方保留原始源码。
fn format_go_source(source: &[u8]) -> io::Result<Vec<u8>> {
    let mut child = Command::new("gofmt")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()?;
    child
        .stdin
        .take()
        .expect("piped gofmt stdin")
        .write_all(source)?;
    let output = child.wait_with_output()?;
    if output.status.success() {
        Ok(output.stdout)
    } else {
        Err(io::Error::new(
            io::ErrorKind::InvalidData,
            String::from_utf8_lossy(&output.stderr).into_owned(),
        ))
    }
}

/// 对应 generateOneFile：先写实现，再写关联测试；实现失败时短路。
pub fn generate_one_file(prefix: &Path) -> io::Result<()> {
    fs::write(
        prefix.with_extension("go"),
        generate_dot_go().map_err(io::Error::other)?,
    )?;
    fs::write(
        PathBuf::from(format!("{}_test.go", prefix.display())),
        generate_test_dot_go().map_err(io::Error::other)?,
    )
}

/// 使用默认前缀返回生成内容对，供审查和不落盘调用者使用。
pub fn default_outputs() -> Result<[(PathBuf, Vec<u8>); 2], String> {
    let prefix = Path::new("./builtin_string_vec_generated");
    Ok([
        (prefix.with_extension("go"), generate_dot_go()?),
        (
            PathBuf::from(format!("{}_test.go", prefix.display())),
            generate_test_dot_go()?,
        ),
    ])
}
