// Copyright 2026 AsterSQL.
// Copyright 2019 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// 时间类向量化内置函数的 Go 源码生成器。
//
// 对应 Go `expression/generator/time_vec.go`：用 text/template 展开
// ADDTIME/SUBTIME/TIMEDIFF/ADDDATE/SUBDATE 的 `vecEval*` 实现与生成测试。
// 模板字符串完整保留 Go 原文；Rust 侧负责签名矩阵、FuncMap 注册、gofmt 与落盘。

// Generates time vector functions and tests.
// 不会被 Rust 模块自动调用；模板渲染、Go 格式化和文件 IO 只保留原生成工具的调用形状，等待依赖接线。

use std::fs;
use std::io;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use gtmpl::{Context, Func, FuncError, Template, Value};

/// addOrSubTime 完整保留 Go text/template 正文。
/// 模板覆盖全 NULL 输出、列缓冲复用、二进制字符串拒绝、字符串到 Duration 转换、零日期检查及各签名计算分支。
pub(crate) const ADD_OR_SUB_TIME_TEMPLATE: &str = r###"
{{ if eq $.FuncName "AddTime" }}
// Copyright 2019 PingCAP, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go generate in expression/generator; DO NOT EDIT.

package expression

import (
	"github.com/pingcap/tidb/pkg/parser/mysql"
	"github.com/pingcap/tidb/pkg/parser/terror"
	"github.com/pingcap/tidb/pkg/types"
	"github.com/pingcap/tidb/pkg/util/chunk"
)
{{ end }}
{{ define "SetNull" }}{{if .Output.Fixed}}result.SetNull(i, true){{else}}result.AppendNull(){{end}} // fixed: {{.Output.Fixed }}{{ end }}
{{ define "ConvertStringToDuration" }}
		{{ if and (ne .SigName "builtinAddStringAndStringSig") (ne .SigName "builtinSubStringAndStringSig") }}
		if !isDuration(arg1) {
			{{ template "SetNull" . }}
			continue
		}{{ end }}
		tc := typeCtx(ctx)
		arg1Duration, _, err := types.ParseDuration(tc, arg1, {{if eq .Output.TypeName "String"}}getFsp4TimeAddSub{{else}}types.GetFsp{{end}}(arg1))
		if err != nil {
			if terror.ErrorEqual(err, types.ErrTruncatedWrongVal) {
				tc.AppendWarning(err)
				{{ template "SetNull" . }}
				continue
			}
			return err
		}
{{ end }}

{{ define "CheckZeroDate" }}
		if arg0.IsZero() {
			{{ template "SetNull" . }}
			continue
		}
{{ end }}

{{ range .Sigs }}
{{ if .AllNull}}
func (b *{{.SigName}}) vecEval{{ .Output.TypeName }}(ctx EvalContext, input *chunk.Chunk, result *chunk.Column) error {
	n := input.NumRows()
	{{ if .Output.Fixed }}
	result.Resize{{ .Output.TypeNameInColumn }}(n, true)
	{{ else }}
	result.Reserve{{ .Output.TypeNameInColumn }}(n)
	for i := 0; i < n; i++ { result.AppendNull() }
	{{ end }}
	return nil
}
{{ else }}
func (b *{{.SigName}}) vecEval{{ .Output.TypeName }}(ctx EvalContext, input *chunk.Chunk, result *chunk.Column) error {
	n := input.NumRows()
{{ $reuse := (and (eq .TypeA.TypeName .Output.TypeName) .TypeA.Fixed) }}
{{ if $reuse }}
	if err := b.args[0].VecEval{{ .TypeA.TypeName }}(ctx, input, result); err != nil {
		return err
	}
	buf0 := result
{{ else }}
	buf0, err := b.bufAllocator.get()
	if err != nil {
		return err
	}
	defer b.bufAllocator.put(buf0)
	if err := b.args[0].VecEval{{ .TypeA.TypeName }}(ctx, input, buf0); err != nil {
		return err
	}
{{ end }}

{{ if or (eq .SigName "builtinAddStringAndStringSig") (eq .SigName "builtinSubStringAndStringSig") }}
	arg1Type := b.args[1].GetType(ctx)
	if mysql.HasBinaryFlag(arg1Type.GetFlag()) {
		result.Reserve{{ .Output.TypeNameInColumn }}(n)
		for i := 0; i < n; i++ {
			result.AppendNull()
		}
		return nil
	}
{{ end }}

	buf1, err := b.bufAllocator.get()
	if err != nil {
		return err
	}
	defer b.bufAllocator.put(buf1)
	if err := b.args[1].VecEval{{ .TypeB.TypeName }}(ctx, input, buf1); err != nil {
		return err
	}

{{ if $reuse }}
	result.MergeNulls(buf1)
{{ else if .Output.Fixed}}
	result.Resize{{ .Output.TypeNameInColumn }}(n, false)
	result.MergeNulls(buf0, buf1)
{{ else }}
	result.Reserve{{ .Output.TypeNameInColumn}}(n)
{{ end }}

{{ if .TypeA.Fixed }}
	arg0s := buf0.{{.TypeA.TypeNameInColumn}}s()
{{ end }}
{{ if .TypeB.Fixed }}
	arg1s := buf1.{{.TypeB.TypeNameInColumn}}s()
{{ end }}
{{ if .Output.Fixed }}
	resultSlice := result.{{.Output.TypeNameInColumn}}s()
{{ end }}
	for i := 0; i < n; i++ {
		{{ if .Output.Fixed }}
		if result.IsNull(i) {
			continue
		}
		{{ else }}
		if buf0.IsNull(i) || buf1.IsNull(i) {
			result.AppendNull()
			continue
		}
		{{ end }}

		// get arg0 & arg1
		{{ if .TypeA.Fixed }}
		arg0 := arg0s[i]
		{{ else }}
		arg0 := buf0.Get{{ .TypeA.TypeNameInColumn }}(i)
		{{ end }}
		{{ if .TypeB.Fixed }}
		arg1 := arg1s[i]
		{{ else }}
		arg1 := buf1.Get{{ .TypeB.TypeNameInColumn }}(i)
		{{ end }}

		// calculate
	{{ if or (eq .SigName "builtinAddDatetimeAndDurationSig") (eq .SigName "builtinSubDatetimeAndDurationSig") }}
		{{ template "CheckZeroDate" . }}
		{{ if eq $.FuncName "AddTime" }}
		output, err := arg0.Add(typeCtx(ctx), types.Duration{Duration: arg1, Fsp: -1})
		{{ else }}
		tc := typeCtx(ctx)
		arg1Duration := types.Duration{Duration: arg1, Fsp: -1}
		output, err := arg0.Add(tc, arg1Duration.Neg())
		{{ end }}
		if err != nil {
			return err
		}

	{{ else if or (eq .SigName "builtinAddDatetimeAndStringSig") (eq .SigName "builtinSubDatetimeAndStringSig") }}
		{{ template "CheckZeroDate" . }}
		{{ if eq $.FuncName "AddTime" }}
		{{ template "ConvertStringToDuration" . }}
		output, err := arg0.Add(typeCtx(ctx), arg1Duration)
		{{ else }}
		if !isDuration(arg1) {
			result.SetNull(i, true) // fixed: true
			continue
		}
		tc := typeCtx(ctx)
		arg1Duration, _, err := types.ParseDuration(tc, arg1, types.GetFsp(arg1))
		if err != nil {
			if terror.ErrorEqual(err, types.ErrTruncatedWrongVal) {
				tc.AppendWarning(err)
				result.SetNull(i, true) // fixed: true
				continue
			}
			return err
		}
		output, err := arg0.Add(typeCtx(ctx), arg1Duration.Neg())
		{{ end }}
		if err != nil {
			return err
		}
	{{ else if or (eq .SigName "builtinAddDurationAndDurationSig") (eq .SigName "builtinSubDurationAndDurationSig") }}
		{{ if eq $.FuncName "AddTime" }}
		output, err := types.AddDuration(arg0, arg1)
		if err != nil {
			return err
		}
		{{ else }}
		output, err := types.SubDuration(arg0, arg1)
		if err != nil {
			return err
		}
		{{ end }}
	{{ else if or (eq .SigName "builtinAddDurationAndStringSig") (eq .SigName "builtinSubDurationAndStringSig") }}
		{{ template "ConvertStringToDuration" . }}
		{{ if eq $.FuncName "AddTime" }}
		output, err := types.AddDuration(arg0, arg1Duration.Duration)
		if err != nil {
			return err
		}
		{{ else }}
		output, err := types.SubDuration(arg0, arg1Duration.Duration)
		if err != nil {
			return err
		}
		{{ end }}
	{{ else if or (eq .SigName "builtinAddStringAndDurationSig") (eq .SigName "builtinSubStringAndDurationSig") }}
		tc := typeCtx(ctx)
		fsp1 := b.args[1].GetType(ctx).GetDecimal()
		arg1Duration := types.Duration{Duration: arg1, Fsp: fsp1}
		var output string
		var isNull bool
		if isDuration(arg0) {
			{{ if eq $.FuncName "AddTime" }}
			output, err = strDurationAddDuration(tc, arg0, arg1Duration)
			{{ else }}
			output, err = strDurationSubDuration(tc, arg0, arg1Duration)
			{{ end }}
			if err != nil {
				if terror.ErrorEqual(err, types.ErrTruncatedWrongVal) {
					tc.AppendWarning(err)
					{{ template "SetNull" . }}
					continue
				}
				return err
			}
		} else {
			{{ if eq $.FuncName "AddTime" }}
			output, isNull, err = strDatetimeAddDuration(tc, arg0, arg1Duration)
			{{ else }}
			output, isNull, err = strDatetimeSubDuration(tc, arg0, arg1Duration)
			{{ end }}
			if err != nil {
				return err
			}
			if isNull {
				{{ template "SetNull" . }}
				continue
			}
		}
	{{ else if or (eq .SigName "builtinAddStringAndStringSig") (eq .SigName "builtinSubStringAndStringSig") }}
		{{ template "ConvertStringToDuration" . }}
		var output string
		var isNull bool
		if isDuration(arg0) {
			{{ if eq $.FuncName "AddTime" }}
			output, err = strDurationAddDuration(tc, arg0, arg1Duration)
			{{ else }}
			output, err = strDurationSubDuration(tc, arg0, arg1Duration)
			{{ end }}
			if err != nil {
				if terror.ErrorEqual(err, types.ErrTruncatedWrongVal) {
					tc.AppendWarning(err)
					{{ template "SetNull" . }}
					continue
				}
				return err
			}
		} else {
			{{ if eq $.FuncName "AddTime" }}
			output, isNull, err = strDatetimeAddDuration(tc, arg0, arg1Duration)
			{{ else }}
			output, isNull, err = strDatetimeSubDuration(tc, arg0, arg1Duration)
			{{ end }}
			if err != nil {
				return err
			}
			if isNull {
				{{ template "SetNull" . }}
				continue
			}
		}
	{{ else if or (eq .SigName "builtinAddDateAndDurationSig") (eq .SigName "builtinSubDateAndDurationSig") }}
		{{ template "CheckZeroDate" . }}
		fsp1 := b.args[1].GetType(ctx).GetDecimal()
		arg1Duration := types.Duration{Duration: arg1, Fsp: fsp1}
		tc := typeCtx(ctx)
		arg0.SetType(mysql.TypeDatetime)
		{{ if eq $.FuncName "AddTime" }}
		res, err := arg0.Add(tc, arg1Duration)
		{{ else }}
		res, err := arg0.Add(tc, arg1Duration.Neg())
		{{ end }}
		if err != nil {
			tc.AppendWarning(err)
			{{ template "SetNull" . }}
			continue
		}

		output := res.String()
	{{ else if or (eq .SigName "builtinAddDateAndStringSig") (eq .SigName "builtinSubDateAndStringSig") }}
		{{ template "CheckZeroDate" . }}
		{{ template "ConvertStringToDuration" . }}
		 arg0.SetType(mysql.TypeDatetime)
		{{ if eq $.FuncName "AddTime" }}
		res, err := arg0.Add(tc, arg1Duration)
		{{ else }}
		res, err := arg0.Add(tc, arg1Duration.Neg())
		{{ end }}
		if err != nil {
			tc.AppendWarning(err)
			{{ template "SetNull" . }}
			continue
		}

		output := res.String()
	{{ end }}

		// commit result
	{{ if .Output.Fixed }}
		resultSlice[i] = output
	{{ else }}
		result.Append{{ .Output.TypeNameInColumn }}(output)
	{{ end }}
	}
	return nil
}
{{ end }}{{/* if .AllNull */}}

func (b *{{.SigName}}) vectorized() bool {
	return true
}
{{ end }}{{/* range */}}
"###;

/// timeDiff 完整保留 TIMEDIFF 的缓冲分配与类型组合模板。
/// 字符串输入会在日期时间和 Duration 间判型；类型不匹配、计算溢出或 NULL 均按原分支处理。
pub(crate) const TIME_DIFF_TEMPLATE: &str = r###"
{{ define "BufAllocator0" }}
	buf0, err := b.bufAllocator.get()
	if err != nil {
		return err
	}
	defer b.bufAllocator.put(buf0)
{{ end }}
{{ define "BufAllocator1" }}
	buf1, err := b.bufAllocator.get()
	if err != nil {
		return err
	}
	defer b.bufAllocator.put(buf1)
{{ end }}
{{ define "ArgsVecEval" }}
	if err := b.args[0].VecEval{{ .TypeA.TypeName }}(ctx, input, buf0); err != nil {
		return err
	}
	if err := b.args[1].VecEval{{ .TypeB.TypeName }}(ctx, input, buf1); err != nil {
		return err
	}
{{ end }}

{{ range . }}
{{ $AIsString := (eq .TypeA.TypeName "String") }}
{{ $BIsString := (eq .TypeB.TypeName "String") }}
{{ $AIsTime := (eq .TypeA.TypeName "Time") }}
{{ $BIsTime := (eq .TypeB.TypeName "Time") }}
{{ $AIsDuration := (eq .TypeA.TypeName "Duration") }}
{{ $BIsDuration := (eq .TypeB.TypeName "Duration") }}
{{ $MaybeDuration := (or (or $AIsDuration $BIsDuration) (and $AIsString $AIsString)) }}
{{ $reuseA := (eq .TypeA.TypeName "Duration") }}
{{ $reuseB := (eq .TypeB.TypeName "Duration") }}
{{ $reuse  := (or $reuseA $reuseB ) }}
{{ $noNull := (ne .SigName "builtinNullTimeDiffSig") }}
func (b *{{.SigName}}) vecEvalDuration(ctx EvalContext, input *chunk.Chunk, result *chunk.Column) error {
	n := input.NumRows()
	{{- if not $noNull }}
	result.ResizeGoDuration(n, true)
	{{- else }}
		result.ResizeGoDuration(n, false)
		r64s := result.GoDurations()
		{{- if $reuseA }}
			buf0 := result
			{{- template "BufAllocator1" . }}
			{{- template "ArgsVecEval" . }}
			result.MergeNulls(buf1)
		{{- else if $reuseB }}
			buf1 := result
			{{- template "BufAllocator0" . }}
			{{- template "ArgsVecEval" . }}
			result.MergeNulls(buf0)
		{{- else }}
			{{- template "BufAllocator0" . }}
			{{- template "BufAllocator1" . }}
			{{- template "ArgsVecEval" . }}
			result.MergeNulls(buf0, buf1)
		{{- end }}
		{{- if .TypeA.Fixed }}
			arg0 := buf0.{{.TypeA.TypeNameInColumn}}s()
		{{- end }}
		{{- if .TypeB.Fixed }}
			arg1 := buf1.{{.TypeB.TypeNameInColumn}}s()
		{{- end }}

		{{- if (or $AIsDuration $BIsDuration) }}
			var (
				lhs    types.Duration
				rhs    types.Duration
			)
		{{- end }}
		{{- if or (or $AIsString $BIsString) (and $AIsTime $BIsTime) }}
			tc := typeCtx(ctx)
		{{- end }}
	for i:=0; i<n ; i++{
		if result.IsNull(i) {
			continue
		}

		{{- if $AIsString }}
			{{ if $BIsDuration }} lhsDur, _, lhsIsDuration,
			{{- else if $BIsTime }} _, lhsTime, lhsIsDuration,
			{{- else if $BIsString }} lhsDur, lhsTime, lhsIsDuration,
			{{- end }}  err := convertStringToDuration(tc, buf0.GetString(i), b.tp.GetDecimal())
			if err != nil  {
				return err
			}
			{{- if $BIsDuration }}
			if !lhsIsDuration {
				result.SetNull(i, true)
				continue
			}
			lhs = lhsDur
			{{- else if $BIsTime }}
			if lhsIsDuration {
				result.SetNull(i, true)
				continue
			}
			{{- end }}
		{{- else if $AIsTime }}
			lhsTime := arg0[i]
		{{- else }}
			lhs.Duration = arg0[i]
		{{- end }}

		{{- if $BIsString }}
			{{ if $AIsDuration }} rhsDur, _, rhsIsDuration,
			{{- else if $AIsTime }}_, rhsTime, rhsIsDuration,
			{{- else if $AIsString }} rhsDur, rhsTime, rhsIsDuration,
			{{- end}}  err := convertStringToDuration(tc, buf1.GetString(i), b.tp.GetDecimal())
			if err != nil  {
				return err
			}
			{{- if $AIsDuration }}
			if !rhsIsDuration {
				result.SetNull(i, true)
				continue
			}
			rhs = rhsDur
			{{- else if $AIsTime }}
			if rhsIsDuration {
				result.SetNull(i, true)
				continue
			}
			{{- end }}
		{{- else if $BIsTime }}
			rhsTime := arg1[i]
		{{- else }}
			rhs.Duration = arg1[i]
		{{- end }}

		{{- if and $AIsString $BIsString }}
			if lhsIsDuration != rhsIsDuration {
				result.SetNull(i, true)
				continue
			}
			var (
				d types.Duration
				isNull bool
			)
			if lhsIsDuration {
				d, isNull, err = calculateDurationTimeDiff(ctx, lhsDur, rhsDur)
			} else {
				d, isNull, err = calculateTimeDiff(tc, lhsTime, rhsTime)
			}
		{{- else if or $AIsDuration $BIsDuration }}
			d, isNull, err := calculateDurationTimeDiff(ctx, lhs, rhs)
		{{- else if or $AIsTime $BIsTime }}
			d, isNull, err := calculateTimeDiff(tc, lhsTime, rhsTime)
		{{- end }}
		if err != nil {
			return err
		}
		if isNull {
			result.SetNull(i, true)
			continue
		}
		r64s[i] = d.Duration
	}
	{{- end }} {{/* if $noNull */}}
	return nil
}

func (b *{{.SigName}}) vectorized() bool {
	return true
}
{{ end }}{{/* range */}}
"###;

/// 时间间隔拆成 Duration 结果和 Datetime 结果两组，与 Go 辅助函数返回顺序一致。
pub(crate) fn interval_units_for_duration_as_duration() -> Vec<&'static str> {
    vec![
        "MICROSECOND",
        "SECOND",
        "MINUTE",
        "HOUR",
        "SECOND_MICROSECOND",
        "MINUTE_MICROSECOND",
        "MINUTE_SECOND",
        "HOUR_MICROSECOND",
        "HOUR_SECOND",
        "HOUR_MINUTE",
        "DAY_MICROSECOND",
    ]
}
/// 产生 Datetime 结果的区间单位列表（DAY … YEAR_MONTH）。
pub(crate) fn interval_units_for_duration_as_datetime() -> Vec<&'static str> {
    vec![
        "DAY",
        "WEEK",
        "MONTH",
        "QUARTER",
        "YEAR",
        "DAY_SECOND",
        "DAY_MINUTE",
        "DAY_HOUR",
        "YEAR_MONTH",
    ]
}
/// getIntervalUnitList 对应 Go append：先放 Duration 单位，再追加 Datetime 单位。
pub(crate) fn interval_units() -> Vec<&'static str> {
    let mut u = interval_units_for_duration_as_duration();
    u.extend(interval_units_for_duration_as_datetime());
    u
}

/// testFile 完整保留生成测试文件的模板。
/// Go FuncMap 的三个区间函数由 render_test_template 显式注册，模板仍包含生成器、用例表、测试与基准入口。
pub(crate) const TEST_FILE_TEMPLATE: &str = r###"
// Copyright 2019 PingCAP, Inc.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by go generate in expression/generator; DO NOT EDIT.

package expression

import (
	"math"
	"testing"

	"github.com/pingcap/tidb/pkg/parser/ast"
	"github.com/pingcap/tidb/pkg/parser/mysql"
	"github.com/pingcap/tidb/pkg/types"
)

type gener struct {
	defaultGener
}

func (g gener) gen() any {
	result := g.defaultGener.gen()
	if _, ok := result.(string); ok {
		dg := newDefaultGener(0, types.ETDuration)
		d := dg.gen().(types.Duration)
		if d.Duration%2 == 0 {
			d.Fsp = 0
		} else {
			d.Fsp = 1
		}
		result = d.String()
	}
	return result
}

{{ define "addOrSubDateCases" }}
	{{- range $sig := .Sigs }}
		// {{ $sig.SigName }}
		{{- if and (eq $sig.TypeA.ETName "Duration") (eq $sig.Output.ETName "Duration") -}}
			{{- $unitList := getIntervalUnitListForDurationAsDuration -}}
			{{- range $unit := $unitList }}
				{
					retEvalType: types.ET{{ $sig.Output.ETName }},
					childrenTypes: []types.EvalType{types.ET{{ $sig.TypeA.ETName }}, types.ET{{ $sig.TypeB.ETName }}, types.ETString},
					geners: []dataGenerator{
						newDefaultGener(0.2, types.ET{{$sig.TypeA.ETName}}),

						{{- if eq $sig.TypeB.ETName "String" }}
							&numStrGener{rangeInt64Gener{math.MinInt32 + 1, math.MaxInt32, newDefaultRandGen()}},
						{{- else }}
							newDefaultGener(0.2, types.ET{{$sig.TypeB.ETName}}),
						{{- end }}
					},
					constants: []*Constant{nil, nil, {Value: types.NewStringDatum("{{$unit}}"), RetType: types.NewFieldType(mysql.TypeString)}},
					chunkSize: 128,
				},
			{{- end }}
		{{- else if and (eq $sig.TypeA.ETName "Duration") (eq $sig.Output.ETName "Datetime") -}}
			// TODO: Make the following cases stable, i.e., shouldn't be affected by crossing a day (date part is padded to current date).
			{{- $unitList := getIntervalUnitListForDurationAsDatetime -}}
			{{- range $unit := $unitList }}
				{
					retEvalType: types.ET{{ $sig.Output.ETName }},
					childrenTypes: []types.EvalType{types.ET{{ $sig.TypeA.ETName }}, types.ET{{ $sig.TypeB.ETName }}, types.ETString},
					geners: []dataGenerator{
						newDefaultGener(0.2, types.ET{{$sig.TypeA.ETName}}),

						{{- if eq $sig.TypeB.ETName "String" }}
							&numStrGener{rangeInt64Gener{math.MinInt32 + 1, math.MaxInt32, newDefaultRandGen()}},
						{{- else }}
							newDefaultGener(0.2, types.ET{{$sig.TypeB.ETName}}),
						{{- end }}
					},
					constants: []*Constant{nil, nil, {Value: types.NewStringDatum("{{$unit}}"), RetType: types.NewFieldType(mysql.TypeString)}},
					chunkSize: 128,
				},
			{{- end }}
		{{- else -}}
			{{- $unitList := getIntervalUnitList -}}
			{{- range $unit := $unitList }}
				{
					retEvalType: types.ET{{ $sig.Output.ETName }},
					childrenTypes: []types.EvalType{types.ET{{ $sig.TypeA.ETName }}, types.ET{{ $sig.TypeB.ETName }}, types.ETString},
					{{- if ne $sig.FieldTypeA "" }}
						childrenFieldTypes: []*types.FieldType{types.NewFieldType(mysql.Type{{$sig.FieldTypeA}}), types.NewFieldType(mysql.Type{{$sig.FieldTypeB}})},
					{{- end }}
					geners: []dataGenerator{
						{{- if eq $sig.FieldTypeA "Date" }}
							newNullWrappedGener(0.2, dateGener{randGen: newDefaultRandGen()}),
						{{- else if eq $sig.TypeA.ETName "String"}}
							newNullWrappedGener(0.2, dateOrDatetimeStrGener{dateRatio: 0.2, dateStrGener: dateStrGener{randGen: newDefaultRandGen()}, dateTimeStrGener: dateTimeStrGener{Fsp: -1, randGen: newDefaultRandGen()}}),
						{{- else if eq $sig.TypeA.ETName "Int"}}
							newNullWrappedGener(0.2, dateOrDatetimeIntGener{dateRatio: 0.2, dateIntGener: dateIntGener{dateGener: dateGener{randGen: newDefaultRandGen()}}, dateTimeIntGener: dateTimeIntGener{dateTimeGener: dateTimeGener{randGen: newDefaultRandGen()}}}),
						{{- else if eq $sig.TypeA.ETName "Real"}}
							newNullWrappedGener(0.2, dateOrDatetimeRealGener{dateRatio: 0.2, dateRealGener: dateRealGener{fspRatio: 0.5, dateGener: dateGener{randGen: newDefaultRandGen()}}, dateTimeRealGener: dateTimeRealGener{fspRatio: 0.5, dateTimeGener: dateTimeGener{randGen: newDefaultRandGen()}}}),
						{{- else if eq $sig.TypeA.ETName "Decimal"}}
							newNullWrappedGener(0.2, dateOrDatetimeDecimalGener{dateRatio: 0.2, dateDecimalGener: dateDecimalGener{fspRatio: 0.5, dateGener: dateGener{randGen: newDefaultRandGen()}}, dateTimeDecimalGener: dateTimeDecimalGener{fspRatio: 0.5, dateTimeGener: dateTimeGener{randGen: newDefaultRandGen()}}}),
						{{- else }}
							newDefaultGener(0.2, types.ET{{$sig.TypeA.ETName}}),
						{{- end }}

						{{- if eq $sig.TypeB.ETName "String" }}
							&numStrGener{rangeInt64Gener{math.MinInt32 + 1, math.MaxInt32, newDefaultRandGen()}},
						{{- else }}
							newDefaultGener(0.2, types.ET{{$sig.TypeB.ETName}}),
						{{- end }}
					},
					constants: []*Constant{nil, nil, {Value: types.NewStringDatum("{{$unit}}"), RetType: types.NewFieldType(mysql.TypeString)}},
					chunkSize: 128,
				},
			{{- end }}
		{{- end }}
	{{- end }}
{{ end }}

{{ define "addOrSubTimeCases" }}
	{{- range $sig := .Sigs }}
		// {{ $sig.SigName }}
			{
				retEvalType: types.ET{{ .Output.ETName }},
				childrenTypes: []types.EvalType{types.ET{{ .TypeA.ETName }}, types.ET{{ .TypeB.ETName }}},
				{{- if ne .FieldTypeA "" }}
				childrenFieldTypes: []*types.FieldType{types.NewFieldType(mysql.Type{{.FieldTypeA}}), types.NewFieldType(mysql.Type{{.FieldTypeB}})},
				{{- end }}
				geners: []dataGenerator{
					gener{*newDefaultGener(0.2, types.ET{{.TypeA.ETName}})},
					gener{*newDefaultGener(0.2, types.ET{{.TypeB.ETName}})},
				},
			},
	{{- end }}
{{ end }}

{{/* Add more test cases here if we have more functions in this file */}}
var vecBuiltin{{.Category}}GeneratedCases = map[string][]vecExprBenchCase{
{{- range .Functions }}
	{{- if eq .FuncName "AddTime" }}
		ast.AddTime: {
			{{- template "addOrSubTimeCases" . -}}
		},
	{{ end }}
	{{- if eq .FuncName "SubTime" }}
		ast.SubTime: {
			{{- template "addOrSubTimeCases" . -}}
		},
	{{ end }}
	{{- if eq .FuncName "TimeDiff" }}
		ast.TimeDiff: {
			// builtinNullTimeDiffSig
			{retEvalType: types.ETDuration, childrenTypes: []types.EvalType{types.ETDuration, types.ETDatetime}},
			{retEvalType: types.ETDuration, childrenTypes: []types.EvalType{types.ETDuration, types.ETTimestamp}},
			{retEvalType: types.ETDuration, childrenTypes: []types.EvalType{types.ETDatetime, types.ETDuration}},
			{retEvalType: types.ETDuration, childrenTypes: []types.EvalType{types.ETTimestamp, types.ETDuration}},
			// builtinDurationDurationTimeDiffSig
			{retEvalType: types.ETDuration, childrenTypes: []types.EvalType{types.ETDuration, types.ETDuration}},
			// builtinDurationStringTimeDiffSig
			{retEvalType: types.ETDuration, childrenTypes: []types.EvalType{types.ETDuration, types.ETString}, geners: []dataGenerator{nil, &dateTimeStrGener{Year: 2019, Month: 11, Fsp: 0, randGen: newDefaultRandGen()}}},
			{retEvalType: types.ETDuration, childrenTypes: []types.EvalType{types.ETDuration, types.ETString}, geners: []dataGenerator{nil, &dateTimeStrGener{Year: 2019, Month: 10, Fsp: 0, randGen: newDefaultRandGen()}}},
			{retEvalType: types.ETDuration, childrenTypes: []types.EvalType{types.ETDuration, types.ETString}, geners: []dataGenerator{nil, &dateTimeStrGener{Year: 2019, Month: 10, Fsp: 4, randGen: newDefaultRandGen()}}},
			// builtinTimeTimeTimeDiffSig
			{retEvalType: types.ETDuration, childrenTypes: []types.EvalType{types.ETDatetime, types.ETDatetime}, geners: []dataGenerator{&dateTimeGener{Year: 2019, Month: 10, randGen: newDefaultRandGen()}, &dateTimeGener{Year: 2019, Month: 10, randGen: newDefaultRandGen()}}},
			{retEvalType: types.ETDuration, childrenTypes: []types.EvalType{types.ETDatetime, types.ETTimestamp}, geners: []dataGenerator{&dateTimeGener{Year: 2019, Month: 10, randGen: newDefaultRandGen()}, &dateTimeGener{Year: 2019, Month: 10, randGen: newDefaultRandGen()}}},
			{retEvalType: types.ETDuration, childrenTypes: []types.EvalType{types.ETTimestamp, types.ETTimestamp}, geners: []dataGenerator{&dateTimeGener{Year: 2019, Month: 10, randGen: newDefaultRandGen()}, &dateTimeGener{Year: 2019, Month: 10, randGen: newDefaultRandGen()}}},
			{retEvalType: types.ETDuration, childrenTypes: []types.EvalType{types.ETTimestamp, types.ETDatetime}, geners: []dataGenerator{&dateTimeGener{Year: 2019, Month: 10, randGen: newDefaultRandGen()}, &dateTimeGener{Year: 2019, Month: 10, randGen: newDefaultRandGen()}}},
			// builtinTimeStringTimeDiffSig
			{retEvalType: types.ETDuration, childrenTypes: []types.EvalType{types.ETDatetime, types.ETString}, geners: []dataGenerator{&dateTimeGener{Year: 2019, Month: 10, randGen: newDefaultRandGen()}, &dateTimeStrGener{Year: 2019, Month: 10, Fsp: 0, randGen: newDefaultRandGen()}}},
			{retEvalType: types.ETDuration, childrenTypes: []types.EvalType{types.ETTimestamp, types.ETString}, geners: []dataGenerator{&dateTimeGener{Year: 2019, Month: 10, randGen: newDefaultRandGen()}, &dateTimeStrGener{Year: 2019, Month: 10, Fsp: 0, randGen: newDefaultRandGen()}}},
			// builtinStringDurationTimeDiffSig
			{retEvalType: types.ETDuration, childrenTypes: []types.EvalType{types.ETString, types.ETDuration}, geners: []dataGenerator{&dateTimeStrGener{Year: 2019, Month: 10, Fsp: 0, randGen: newDefaultRandGen()}, nil}},
			// builtinStringTimeTimeDiffSig
			{retEvalType: types.ETDuration, childrenTypes: []types.EvalType{types.ETString, types.ETDatetime}, geners: []dataGenerator{&dateTimeStrGener{Year: 2019, Month: 10, Fsp: 0, randGen: newDefaultRandGen()}, &dateTimeGener{Year: 2019, Month: 10, randGen: newDefaultRandGen()}}},
			{retEvalType: types.ETDuration, childrenTypes: []types.EvalType{types.ETString, types.ETTimestamp}, geners: []dataGenerator{&dateTimeStrGener{Year: 2019, Month: 10, Fsp: 0, randGen: newDefaultRandGen()}, &dateTimeGener{Year: 2019, Month: 10, randGen: newDefaultRandGen()}}},
			// builtinStringStringTimeDiffSig
			{retEvalType: types.ETDuration, childrenTypes: []types.EvalType{types.ETString, types.ETString}, geners: []dataGenerator{&dateTimeStrGener{Year: 2019, Month: 10, Fsp: 0, randGen: newDefaultRandGen()}, &dateTimeStrGener{Year: 2019, Month: 10, Fsp: 0, randGen: newDefaultRandGen()}}},
		},
	{{ end }}
	{{- if eq .FuncName "AddDate" }}
		ast.AddDate: {
			{{- template "addOrSubDateCases" . -}}
		},
	{{ end }}
	{{- if eq .FuncName "SubDate" }}
		ast.SubDate: {
			{{- template "addOrSubDateCases" . -}}
		},
	{{ end }}
{{ end }}
}

func TestVectorizedBuiltin{{.Category}}EvalOneVecGenerated(t *testing.T) {
	testVectorizedEvalOneVec(t, vecBuiltin{{.Category}}GeneratedCases)
}

func TestVectorizedBuiltin{{.Category}}FuncGenerated(t *testing.T) {
	testVectorizedBuiltinFunc(t, vecBuiltin{{.Category}}GeneratedCases)
}

func BenchmarkVectorizedBuiltin{{.Category}}EvalOneVecGenerated(b *testing.B) {
	benchmarkVectorizedEvalOneVec(b, vecBuiltin{{.Category}}GeneratedCases)
}

func BenchmarkVectorizedBuiltin{{.Category}}FuncGenerated(b *testing.B) {
	benchmarkVectorizedBuiltinFunc(b, vecBuiltin{{.Category}}GeneratedCases)
}
"###;

/// Sig 对应 Go sig；类型上下文暂用名称保存，避免虚构尚未迁移的 helper 模块所有权关系。
#[derive(Clone, Copy, Debug)]
pub(crate) struct Sig {
    sig_name: &'static str,
    type_a: &'static str,
    type_b: &'static str,
    output: &'static str,
    field_type_a: &'static str,
    field_type_b: &'static str,
    pub(crate) all_null: bool,
}
/// 构造签名字面量的便捷常量函数，字段顺序与 Go sig 结构体一致。
const fn sig(
    n: &'static str,
    a: &'static str,
    b: &'static str,
    o: &'static str,
    fa: &'static str,
    fb: &'static str,
    z: bool,
) -> Sig {
    Sig {
        sig_name: n,
        type_a: a,
        type_b: b,
        output: o,
        field_type_a: fa,
        field_type_b: fb,
        all_null: z,
    }
}

/// ADDTIME 普通签名及三个恒 NULL 签名，顺序与 Go 一致。
pub(crate) const ADD_TIME_SIGS: &[Sig] = &[
    sig(
        "builtinAddDatetimeAndDurationSig",
        "Datetime",
        "Duration",
        "Datetime",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDatetimeAndStringSig",
        "Datetime",
        "String",
        "Datetime",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDurationAndDurationSig",
        "Duration",
        "Duration",
        "Duration",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDurationAndStringSig",
        "Duration",
        "String",
        "Duration",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddStringAndDurationSig",
        "String",
        "Duration",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddStringAndStringSig",
        "String",
        "String",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateAndDurationSig",
        "Datetime",
        "Duration",
        "String",
        "Date",
        "Duration",
        false,
    ),
    sig(
        "builtinAddDateAndStringSig",
        "Datetime",
        "String",
        "String",
        "Date",
        "String",
        false,
    ),
    sig(
        "builtinAddTimeDateTimeNullSig",
        "Datetime",
        "Datetime",
        "Datetime",
        "",
        "",
        true,
    ),
    sig(
        "builtinAddTimeStringNullSig",
        "Datetime",
        "Datetime",
        "String",
        "Date",
        "Datetime",
        true,
    ),
    sig(
        "builtinAddTimeDurationNullSig",
        "Duration",
        "Datetime",
        "Duration",
        "",
        "",
        true,
    ),
];
/// SUBTIME 与 ADDTIME 对称，模板选择减法和 Duration 取负分支。
pub(crate) const SUB_TIME_SIGS: &[Sig] = &[
    sig(
        "builtinSubDatetimeAndDurationSig",
        "Datetime",
        "Duration",
        "Datetime",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDatetimeAndStringSig",
        "Datetime",
        "String",
        "Datetime",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDurationAndDurationSig",
        "Duration",
        "Duration",
        "Duration",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDurationAndStringSig",
        "Duration",
        "String",
        "Duration",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubStringAndDurationSig",
        "String",
        "Duration",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubStringAndStringSig",
        "String",
        "String",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateAndDurationSig",
        "Datetime",
        "Duration",
        "String",
        "Date",
        "Duration",
        false,
    ),
    sig(
        "builtinSubDateAndStringSig",
        "Datetime",
        "String",
        "String",
        "Date",
        "String",
        false,
    ),
    sig(
        "builtinSubTimeDateTimeNullSig",
        "Datetime",
        "Datetime",
        "Datetime",
        "",
        "",
        true,
    ),
    sig(
        "builtinSubTimeStringNullSig",
        "Datetime",
        "Datetime",
        "String",
        "Date",
        "Datetime",
        true,
    ),
    sig(
        "builtinSubTimeDurationNullSig",
        "Duration",
        "Datetime",
        "Duration",
        "",
        "",
        true,
    ),
];
/// TIMEDIFF 覆盖 Duration、Datetime/Timestamp、String 的有效组合及恒空签名。
pub(crate) const TIME_DIFF_SIGS: &[Sig] = &[
    sig("builtinNullTimeDiffSig", "", "", "Duration", "", "", false),
    sig(
        "builtinTimeStringTimeDiffSig",
        "Datetime",
        "String",
        "Duration",
        "",
        "",
        false,
    ),
    sig(
        "builtinDurationStringTimeDiffSig",
        "Duration",
        "String",
        "Duration",
        "",
        "",
        false,
    ),
    sig(
        "builtinDurationDurationTimeDiffSig",
        "Duration",
        "Duration",
        "Duration",
        "",
        "",
        false,
    ),
    sig(
        "builtinStringTimeTimeDiffSig",
        "String",
        "Datetime",
        "Duration",
        "",
        "",
        false,
    ),
    sig(
        "builtinStringDurationTimeDiffSig",
        "String",
        "Duration",
        "Duration",
        "",
        "",
        false,
    ),
    sig(
        "builtinStringStringTimeDiffSig",
        "String",
        "String",
        "Duration",
        "",
        "",
        false,
    ),
    sig(
        "builtinTimeTimeTimeDiffSig",
        "Datetime",
        "Datetime",
        "Duration",
        "",
        "",
        false,
    ),
];
/// ADDDATE 类型矩阵保留 Date 字段特化和 Duration 输出分流。
pub(crate) const ADD_DATE_SIGS: &[Sig] = &[
    sig(
        "builtinAddDateStringStringSig",
        "String",
        "String",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateStringIntSig",
        "String",
        "Int",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateStringRealSig",
        "String",
        "Real",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateStringDecimalSig",
        "String",
        "Decimal",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateIntStringSig",
        "Int",
        "String",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateIntIntSig",
        "Int",
        "Int",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateIntRealSig",
        "Int",
        "Real",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateIntDecimalSig",
        "Int",
        "Decimal",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateRealStringSig",
        "Real",
        "String",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateRealIntSig",
        "Real",
        "Int",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateRealRealSig",
        "Real",
        "Real",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateRealDecimalSig",
        "Real",
        "Decimal",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateDecimalStringSig",
        "Decimal",
        "String",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateDecimalIntSig",
        "Decimal",
        "Int",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateDecimalRealSig",
        "Decimal",
        "Real",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateDecimalDecimalSig",
        "Decimal",
        "Decimal",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateDatetimeStringSig",
        "Datetime",
        "String",
        "Datetime",
        "Date",
        "String",
        false,
    ),
    sig(
        "builtinAddDateDatetimeIntSig",
        "Datetime",
        "Int",
        "Datetime",
        "Date",
        "Longlong",
        false,
    ),
    sig(
        "builtinAddDateDatetimeRealSig",
        "Datetime",
        "Real",
        "Datetime",
        "Date",
        "Double",
        false,
    ),
    sig(
        "builtinAddDateDatetimeDecimalSig",
        "Datetime",
        "Decimal",
        "Datetime",
        "Date",
        "NewDecimal",
        false,
    ),
    sig(
        "builtinAddDateDatetimeStringSig",
        "Datetime",
        "String",
        "Datetime",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateDatetimeIntSig",
        "Datetime",
        "Int",
        "Datetime",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateDatetimeRealSig",
        "Datetime",
        "Real",
        "Datetime",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateDatetimeDecimalSig",
        "Datetime",
        "Decimal",
        "Datetime",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateDurationStringSig",
        "Duration",
        "String",
        "Duration",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateDurationIntSig",
        "Duration",
        "Int",
        "Duration",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateDurationRealSig",
        "Duration",
        "Real",
        "Duration",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateDurationDecimalSig",
        "Duration",
        "Decimal",
        "Duration",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateDurationStringSig",
        "Duration",
        "String",
        "Datetime",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateDurationIntSig",
        "Duration",
        "Int",
        "Datetime",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateDurationRealSig",
        "Duration",
        "Real",
        "Datetime",
        "",
        "",
        false,
    ),
    sig(
        "builtinAddDateDurationDecimalSig",
        "Duration",
        "Decimal",
        "Datetime",
        "",
        "",
        false,
    ),
];
/// SUBDATE 签名矩阵与 ADDDATE 对称。
pub(crate) const SUB_DATE_SIGS: &[Sig] = &[
    sig(
        "builtinSubDateStringStringSig",
        "String",
        "String",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateStringIntSig",
        "String",
        "Int",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateStringRealSig",
        "String",
        "Real",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateStringDecimalSig",
        "String",
        "Decimal",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateIntStringSig",
        "Int",
        "String",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateIntIntSig",
        "Int",
        "Int",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateIntRealSig",
        "Int",
        "Real",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateIntDecimalSig",
        "Int",
        "Decimal",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateRealStringSig",
        "Real",
        "String",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateRealIntSig",
        "Real",
        "Int",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateRealRealSig",
        "Real",
        "Real",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateRealDecimalSig",
        "Real",
        "Decimal",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateDecimalStringSig",
        "Decimal",
        "String",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateDecimalIntSig",
        "Decimal",
        "Int",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateDecimalRealSig",
        "Decimal",
        "Real",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateDecimalDecimalSig",
        "Decimal",
        "Decimal",
        "String",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateDatetimeStringSig",
        "Datetime",
        "String",
        "Datetime",
        "Date",
        "String",
        false,
    ),
    sig(
        "builtinSubDateDatetimeIntSig",
        "Datetime",
        "Int",
        "Datetime",
        "Date",
        "Longlong",
        false,
    ),
    sig(
        "builtinSubDateDatetimeRealSig",
        "Datetime",
        "Real",
        "Datetime",
        "Date",
        "Double",
        false,
    ),
    sig(
        "builtinSubDateDatetimeDecimalSig",
        "Datetime",
        "Decimal",
        "Datetime",
        "Date",
        "NewDecimal",
        false,
    ),
    sig(
        "builtinSubDateDatetimeStringSig",
        "Datetime",
        "String",
        "Datetime",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateDatetimeIntSig",
        "Datetime",
        "Int",
        "Datetime",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateDatetimeRealSig",
        "Datetime",
        "Real",
        "Datetime",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateDatetimeDecimalSig",
        "Datetime",
        "Decimal",
        "Datetime",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateDurationStringSig",
        "Duration",
        "String",
        "Duration",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateDurationIntSig",
        "Duration",
        "Int",
        "Duration",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateDurationRealSig",
        "Duration",
        "Real",
        "Duration",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateDurationDecimalSig",
        "Duration",
        "Decimal",
        "Duration",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateDurationStringSig",
        "Duration",
        "String",
        "Datetime",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateDurationIntSig",
        "Duration",
        "Int",
        "Datetime",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateDurationRealSig",
        "Duration",
        "Real",
        "Datetime",
        "",
        "",
        false,
    ),
    sig(
        "builtinSubDateDurationDecimalSig",
        "Duration",
        "Decimal",
        "Datetime",
        "",
        "",
        false,
    ),
];

/// Function 与 TmplVal 对应 Go 的模板输入结构。
#[derive(Debug)]
pub(crate) struct Function {
    /// 函数名，用于模板中选择 ADDTIME/SUBTIME 等分支。
    pub(crate) func_name: &'static str,
    /// 该函数下全部类型特化签名。
    pub(crate) sigs: &'static [Sig],
}
/// 顶层模板值：分类名 + 函数列表。
#[derive(Debug)]
pub(crate) struct TmplVal {
    category: &'static str,
    functions: &'static [Function],
}
/// Time 类五个函数的签名表入口，顺序与 Go 一致。
pub(crate) const FUNCTIONS: &[Function] = &[
    Function {
        func_name: "AddTime",
        sigs: ADD_TIME_SIGS,
    },
    Function {
        func_name: "SubTime",
        sigs: SUB_TIME_SIGS,
    },
    Function {
        func_name: "TimeDiff",
        sigs: TIME_DIFF_SIGS,
    },
    Function {
        func_name: "AddDate",
        sigs: ADD_DATE_SIGS,
    },
    Function {
        func_name: "SubDate",
        sigs: SUB_DATE_SIGS,
    },
];
/// 测试模板的默认输入（Category=Time）。
pub(crate) const TMPL_VAL: TmplVal = TmplVal {
    category: "Time",
    functions: FUNCTIONS,
};

/// 将模板解析/渲染错误包装为 `io::Error`。
fn template_error(error: impl std::fmt::Display) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, error.to_string())
}

/// 构造 gtmpl 对象（map）值，供模板字段访问。
fn object(entries: impl IntoIterator<Item = (&'static str, Value)>) -> Value {
    entries
        .into_iter()
        .map(|(key, value)| (key.to_owned(), value))
        .collect::<std::collections::HashMap<_, _>>()
        .into()
}

/// 将机械稿里的类型名恢复成 Go helper.TypeContext 的完整模板上下文。
fn type_context_value(name: &str) -> Value {
    let (et_name, type_name, column_name, go_name, fixed) = match name {
        "Int" => ("Int", "Int", "Int64", "int64", true),
        "Real" => ("Real", "Real", "Float64", "float64", true),
        "Decimal" => ("Decimal", "Decimal", "Decimal", "types.MyDecimal", true),
        "String" => ("String", "String", "String", "string", false),
        "Datetime" => ("Datetime", "Time", "Time", "types.Time", true),
        "Duration" => ("Duration", "Duration", "GoDuration", "time.Duration", true),
        "" => ("", "", "", "", false),
        other => (other, other, other, other, false),
    };
    object([
        ("ETName", et_name.into()),
        ("TypeName", type_name.into()),
        ("TypeNameInColumn", column_name.into()),
        ("TypeNameGo", go_name.into()),
        ("Fixed", fixed.into()),
    ])
}

/// 将单个 Sig 转为模板可访问的对象（含 TypeA/TypeB/Output 上下文）。
fn sig_value(sig: &Sig) -> Value {
    object([
        ("SigName", sig.sig_name.into()),
        ("TypeA", type_context_value(sig.type_a)),
        ("TypeB", type_context_value(sig.type_b)),
        ("Output", type_context_value(sig.output)),
        ("FieldTypeA", sig.field_type_a.into()),
        ("FieldTypeB", sig.field_type_b.into()),
        ("AllNull", sig.all_null.into()),
    ])
}

/// 将 Function 转为模板可访问的对象（FuncName + Sigs）。
fn function_value(function: &Function) -> Value {
    object([
        ("FuncName", function.func_name.into()),
        (
            "Sigs",
            function
                .sigs
                .iter()
                .map(sig_value)
                .collect::<Vec<_>>()
                .into(),
        ),
    ])
}

/// 可被 `render_template` 消费的模板数据抽象。
pub(crate) trait TemplateData {
    fn template_value(&self) -> Value;
}

impl TemplateData for Function {
    fn template_value(&self) -> Value {
        function_value(self)
    }
}

impl TemplateData for [Sig] {
    fn template_value(&self) -> Value {
        self.iter().map(sig_value).collect::<Vec<_>>().into()
    }
}

impl TemplateData for TmplVal {
    fn template_value(&self) -> Value {
        object([
            ("Category", self.category.into()),
            (
                "Functions",
                self.functions
                    .iter()
                    .map(function_value)
                    .collect::<Vec<_>>()
                    .into(),
            ),
        ])
    }
}

/// 解析模板、注册可选 FuncMap，再以数据渲染为字符串。
fn render_with_funcs<T: TemplateData + ?Sized>(
    template: &str,
    data: &T,
    funcs: &[(&str, Func)],
) -> io::Result<String> {
    let mut parsed = Template::default();
    parsed.add_funcs(funcs);
    parsed.parse(template).map_err(template_error)?;
    parsed
        .render(&Context::from(data.template_value()))
        .map_err(template_error)
}

/// Go text/template.Execute 的可运行迁移；解析和执行错误继续向上传播。
pub(crate) fn render_template<T: TemplateData + ?Sized>(
    template: &str,
    data: &T,
) -> io::Result<String> {
    render_with_funcs(template, data, &[])
}

/// 模板 FuncMap：返回 Duration 结果区间单位列表。
fn duration_as_duration_func(_: &[Value]) -> Result<Value, FuncError> {
    Ok(interval_units_for_duration_as_duration().into())
}

/// 模板 FuncMap：返回 Datetime 结果区间单位列表。
fn duration_as_datetime_func(_: &[Value]) -> Result<Value, FuncError> {
    Ok(interval_units_for_duration_as_datetime().into())
}

/// 模板 FuncMap：返回完整区间单位列表（Duration 组 + Datetime 组）。
fn interval_units_func(_: &[Value]) -> Result<Value, FuncError> {
    Ok(interval_units().into())
}

/// 测试模板额外注册三个区间单位函数，等价于 Go template.FuncMap。
pub(crate) fn render_test_template(template: &str, data: &TmplVal) -> io::Result<String> {
    let funcs = [
        (
            "getIntervalUnitListForDurationAsDuration",
            duration_as_duration_func as Func,
        ),
        (
            "getIntervalUnitListForDurationAsDatetime",
            duration_as_datetime_func as Func,
        ),
        ("getIntervalUnitList", interval_units_func as Func),
    ];
    render_with_funcs(template, data, &funcs)
}

/// 对应 go/format.Source；gofmt 不可用或拒绝输入时返回错误，由调用者保留原始源码。
fn format_go_source(source: &[u8]) -> io::Result<Vec<u8>> {
    let mut child = Command::new("gofmt")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()?;
    child
        .stdin
        .take()
        .expect("piped gofmt stdin")
        .write_all(source)?;
    let output = child.wait_with_output()?;
    if output.status.success() {
        Ok(output.stdout)
    } else {
        Err(io::Error::new(
            io::ErrorKind::InvalidData,
            String::from_utf8_lossy(&output.stderr).into_owned(),
        ))
    }
}

/// generateDotGo 依次展开 ADDTIME、SUBTIME、TIMEDIFF；任一模板错误都会阻止写入半成品。
fn generate_dot_go(file: &Path) -> io::Result<()> {
    let mut source = String::new();
    source.push_str(&render_template(
        ADD_OR_SUB_TIME_TEMPLATE,
        &Function {
            func_name: "AddTime",
            sigs: ADD_TIME_SIGS,
        },
    )?);
    source.push_str(&render_template(
        ADD_OR_SUB_TIME_TEMPLATE,
        &Function {
            func_name: "SubTime",
            sigs: SUB_TIME_SIGS,
        },
    )?);
    source.push_str(&render_template(TIME_DIFF_TEMPLATE, TIME_DIFF_SIGS)?);
    let data = match format_go_source(source.as_bytes()) {
        Ok(v) => v,
        Err(e) => {
            eprintln!("[Warn] {}: gofmt failed: {e}", file.display());
            source.into_bytes()
        }
    };
    fs::write(file, data)
}
/// generateTestDotGo 展开完整测试模板，格式化失败时同样写入原始内容供调试。
fn generate_test_dot_go(file: &Path) -> io::Result<()> {
    let source = render_test_template(TEST_FILE_TEMPLATE, &TMPL_VAL)?;
    let data = match format_go_source(source.as_bytes()) {
        Ok(v) => v,
        Err(e) => {
            eprintln!("[Warn] {}: gofmt failed: {e}", file.display());
            source.into_bytes()
        }
    };
    fs::write(file, data)
}
/// generateOneFile 先写实现，再写关联测试；实现生成失败时短路。
pub(crate) fn generate_one_file(prefix: &Path) -> io::Result<()> {
    generate_dot_go(&prefix.with_extension("go"))?;
    generate_test_dot_go(&PathBuf::from(format!("{}_test.go", prefix.display())))
}
/// main 保留固定当前目录输出及致命错误终止语义。
fn main() {
    let p = Path::new(".").join("builtin_time_vec_generated");
    if let Err(e) = generate_one_file(&p) {
        panic!("generateOneFile: {e}")
    }
}
