[package]
name = "astersql-statistics-handle-cache-internal"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[dependencies]
statistics = { package = "astersql-statistics", path = "../../../" }

[package.metadata.porting]
go-package = "pkg/statistics/handle/cache/internal"
legacy-tasks = ["task-735"]
