[package]
name = "astersql-metaservice"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[dependencies]
log = "0.4"
thiserror = "2"
url = "2"
astersql-util = { path = "../util" }
etcd-client = { version = "0.19", features = ["tls"] }
tokio = { version = "1", features = ["rt-multi-thread", "time", "macros"] }
tikv-client = { version = "=0.4.2", git = "ssh://git@github.com/astersql/client-rust.git", tag = "v0.4.2-aster.10", default-features = false }

[package.metadata.porting]
go-package = "pkg/metaservice"
legacy-tasks = ["task-21", "task-118"]
