[package]
name = "astersql-types-parser_driver"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[dependencies]
hex = "0.4"
parser-format = { package = "astersql-parser-format", path = "../../parser/format" }
parser-ast = { package = "astersql-parser-ast", path = "../../parser/ast" }
types = { package = "astersql-types-datum", path = "../internal/datum" }
types-scalar = { package = "astersql-types-scalar", path = "../internal/scalar" }
types-field = { package = "astersql-types-field", path = "../internal/field" }
types-decimal = { package = "astersql-types-decimal", path = "../internal/decimal" }

[dev-dependencies]
testsetup = { package = "astersql-testkit-testsetup", path = "../../testkit/testsetup" }

[package.metadata.porting]
go-package = "pkg/types/parser_driver"
legacy-tasks = ["task-401"]
