// Copyright 2026 AsterSQL.
// Copyright 2024 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Generates the Go `Hash64` and `Equals` methods for logical operators.
//!
//! Go discovers participating fields through reflection and the
//! `hash64-equals:"true"` struct tag. Rust cannot reflect over Go types, so the
//! same field/type information is represented explicitly below. The recursive
//! emitter otherwise follows the Go generator's pointer, slice, scalar and
//! `HashEquals` branches exactly.

#[derive(Clone, Debug, PartialEq, Eq)]
/// Public field kinds accepted by the metadata-driven generator API.
pub enum HashFieldKind {
    Bool,
    Integer,
    UnsignedInteger,
    Float,
    String,
    Bytes,
    Pointer,
    Slice,
    Interface,
    HashEquals,
    Ignored,
}

#[derive(Clone, Debug, PartialEq, Eq)]
/// One field carrying the Go `hash64-equals:"true"` tag.
pub struct HashField {
    pub name: String,
    pub kind: HashFieldKind,
}

#[derive(Clone, Debug, PartialEq, Eq)]
/// One logical operator and the fields used by its generated methods.
pub struct LogicalOperator {
    pub name: String,
    pub codec_name: String,
    pub fields: Vec<HashField>,
}

#[derive(Clone, Debug)]
enum FieldType {
    Bool,
    SignedInteger,
    UnsignedInteger,
    Float,
    String,
    /// A value whose `Equals` argument must be addressed (a Go struct value).
    HashEqualsValue,
    /// A pointer whose hash must encode nil/non-nil at the tagged-field level.
    HashEqualsPointer,
    /// An interface or other HashEquals value whose `Equals` argument is direct.
    HashEqualsDirect,
    Slice(Box<FieldType>),
}

#[derive(Clone, Debug)]
struct FieldSpec {
    name: String,
    kind: FieldType,
}

#[derive(Clone, Debug)]
struct OperatorSpec {
    name: String,
    codec_name: String,
    fields: Vec<FieldSpec>,
}

const CODE_GEN_HASH64_EQUALS_PREFIX: &str = r#"// Copyright 2024 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by hash64_equals_generator; DO NOT EDIT IT DIRECTLY.

package logicalop

import (
	"github.com/pingcap/tidb/pkg/planner/cascades/base"
	"github.com/pingcap/tidb/pkg/util/plancodec"
)
"#;

/// Generate complete, gofmt-shaped source for explicitly described operators.
pub fn gen_hash64_equals_for_logical_ops(operators: &[LogicalOperator]) -> Result<Vec<u8>, String> {
    let mut specs = Vec::with_capacity(operators.len());
    for operator in operators {
        validate_name(&operator.name)?;
        let fields = operator
            .fields
            .iter()
            .filter_map(public_field_spec)
            .collect();
        specs.push(OperatorSpec {
            name: operator.name.clone(),
            codec_name: operator.codec_name.clone(),
            fields,
        });
    }
    generate(&specs)
}

fn public_field_spec(field: &HashField) -> Option<FieldSpec> {
    let kind = match field.kind {
        HashFieldKind::Bool => FieldType::Bool,
        HashFieldKind::Integer => FieldType::SignedInteger,
        HashFieldKind::UnsignedInteger => FieldType::UnsignedInteger,
        HashFieldKind::Float => FieldType::Float,
        HashFieldKind::String => FieldType::String,
        HashFieldKind::Bytes => FieldType::Slice(Box::new(FieldType::UnsignedInteger)),
        HashFieldKind::Pointer => FieldType::HashEqualsPointer,
        HashFieldKind::Slice => FieldType::Slice(Box::new(FieldType::HashEqualsDirect)),
        HashFieldKind::Interface => FieldType::HashEqualsDirect,
        HashFieldKind::HashEquals => FieldType::HashEqualsValue,
        HashFieldKind::Ignored => return None,
    };
    Some(FieldSpec {
        name: field.name.clone(),
        kind,
    })
}

fn generate(operators: &[OperatorSpec]) -> Result<Vec<u8>, String> {
    let mut output = String::from(CODE_GEN_HASH64_EQUALS_PREFIX);
    output.push('\n');
    for operator in operators {
        validate_name(&operator.name)?;
        write_hash_method(&mut output, operator);
        write_equals_method(&mut output, operator);
    }
    if !operators.is_empty() {
        output.pop();
    }
    Ok(output.into_bytes())
}

fn write_hash_method(output: &mut String, operator: &OperatorSpec) {
    line(
        output,
        0,
        "// Hash64 implements the Hash64Equals interface.",
    );
    line(
        output,
        0,
        &format!("func (p *{}) Hash64(h base.Hasher) {{", operator.name),
    );
    line(output, 1, &format!("h.HashString({})", operator.codec_name));
    for field in &operator.fields {
        write_hash_field(output, field);
    }
    line(output, 0, "}");
    output.push('\n');
}

fn write_hash_field(output: &mut String, field: &FieldSpec) {
    let call_name = format!("p.{}", field.name);
    if matches!(
        field.kind,
        FieldType::HashEqualsPointer | FieldType::Slice(_)
    ) {
        line(output, 1, &format!("if {call_name} == nil {{"));
        line(output, 2, "h.HashByte(base.NilFlag)");
        line(output, 1, "} else {");
        line(output, 2, "h.HashByte(base.NotNilFlag)");
        write_hash_element(output, &field.kind, &call_name, 2);
        line(output, 1, "}");
    } else {
        write_hash_element(output, &field.kind, &call_name, 1);
    }
}

fn write_hash_element(output: &mut String, field_type: &FieldType, call_name: &str, indent: usize) {
    match field_type {
        FieldType::Slice(element) => {
            line(output, indent, &format!("h.HashInt(len({call_name}))"));
            let item_name = nested_item_name(call_name);
            line(
                output,
                indent,
                &format!("for _, {item_name} := range {call_name} {{"),
            );
            write_hash_element(output, element, &item_name, indent + 1);
            line(output, indent, "}");
        }
        FieldType::String => line(output, indent, &format!("h.HashString({call_name})")),
        FieldType::Bool => line(output, indent, &format!("h.HashBool({call_name})")),
        FieldType::SignedInteger => {
            line(output, indent, &format!("h.HashInt64(int64({call_name}))"));
        }
        FieldType::UnsignedInteger => {
            line(
                output,
                indent,
                &format!("h.HashUint64(uint64({call_name}))"),
            );
        }
        FieldType::Float => {
            line(
                output,
                indent,
                &format!("h.HashFloat64(float64({call_name}))"),
            );
        }
        FieldType::HashEqualsValue | FieldType::HashEqualsPointer | FieldType::HashEqualsDirect => {
            line(output, indent, &format!("{call_name}.Hash64(h)"));
        }
    }
}

fn write_equals_method(output: &mut String, operator: &OperatorSpec) {
    line(
        output,
        0,
        &format!(
            "// Equals implements the Hash64Equals interface, only receive *{} pointer.",
            operator.name
        ),
    );
    line(
        output,
        0,
        &format!("func (p *{}) Equals(other any) bool {{", operator.name),
    );
    line(output, 1, &format!("op2, ok := other.(*{})", operator.name));
    line(output, 1, "if !ok {");
    line(output, 2, "return false");
    line(output, 1, "}");
    line(output, 1, "if p == nil {");
    line(output, 2, "return op2 == nil");
    line(output, 1, "}");
    line(output, 1, "if op2 == nil {");
    line(output, 2, "return false");
    line(output, 1, "}");
    if operator.fields.is_empty() {
        line(output, 1, "_ = op2");
    }
    for field in &operator.fields {
        write_equals_element(
            output,
            &field.kind,
            &format!("p.{}", field.name),
            &format!("op2.{}", field.name),
            "i",
            1,
        );
    }
    line(output, 1, "return true");
    line(output, 0, "}");
    output.push('\n');
}

fn write_equals_element(
    output: &mut String,
    field_type: &FieldType,
    lhs: &str,
    rhs: &str,
    index: &str,
    indent: usize,
) {
    match field_type {
        FieldType::Slice(element) => {
            line(
                output,
                indent,
                &format!(
                    "if ({lhs} == nil && {rhs} != nil) || ({lhs} != nil && {rhs} == nil) || len({lhs}) != len({rhs}) {{"
                ),
            );
            line(output, indent + 1, "return false");
            line(output, indent, "}");
            let item_name = nested_item_name(lhs);
            line(
                output,
                indent,
                &format!("for {index}, {item_name} := range {lhs} {{"),
            );
            write_equals_element(
                output,
                element,
                &item_name,
                &format!("{rhs}[{index}]"),
                &format!("{index}i"),
                indent + 1,
            );
            line(output, indent, "}");
        }
        FieldType::Bool
        | FieldType::SignedInteger
        | FieldType::UnsignedInteger
        | FieldType::Float
        | FieldType::String => {
            line(output, indent, &format!("if {lhs} != {rhs} {{"));
            line(output, indent + 1, "return false");
            line(output, indent, "}");
        }
        FieldType::HashEqualsValue => {
            line(output, indent, &format!("if !{lhs}.Equals(&{rhs}) {{"));
            line(output, indent + 1, "return false");
            line(output, indent, "}");
        }
        FieldType::HashEqualsPointer | FieldType::HashEqualsDirect => {
            line(output, indent, &format!("if !{lhs}.Equals({rhs}) {{"));
            line(output, indent + 1, "return false");
            line(output, indent, "}");
        }
    }
}

fn nested_item_name(call_name: &str) -> String {
    if call_name.starts_with("one") {
        format!("{call_name}e")
    } else {
        "one".to_owned()
    }
}

fn line(output: &mut String, indent: usize, text: &str) {
    for _ in 0..indent {
        output.push('\t');
    }
    output.push_str(text);
    output.push('\n');
}

fn field(name: &str, kind: FieldType) -> FieldSpec {
    FieldSpec {
        name: name.to_owned(),
        kind,
    }
}

fn value(name: &str) -> FieldSpec {
    field(name, FieldType::HashEqualsValue)
}

fn pointer(name: &str) -> FieldSpec {
    field(name, FieldType::HashEqualsPointer)
}

fn direct(name: &str) -> FieldSpec {
    field(name, FieldType::HashEqualsDirect)
}

fn slice(name: &str, element: FieldType) -> FieldSpec {
    field(name, FieldType::Slice(Box::new(element)))
}

fn operator(name: &str, fields: Vec<FieldSpec>) -> OperatorSpec {
    OperatorSpec {
        name: name.to_owned(),
        codec_name: logical_op_name_to_plan_codec(name).to_owned(),
        fields,
    }
}

fn logical_operator_specs() -> Vec<OperatorSpec> {
    use FieldType::{
        Bool, HashEqualsDirect, HashEqualsPointer, HashEqualsValue, SignedInteger, UnsignedInteger,
    };

    vec![
        operator(
            "LogicalJoin",
            vec![
                value("LogicalSchemaProducer"),
                field("JoinType", SignedInteger),
                slice("EqualConditions", HashEqualsPointer),
                slice("NAEQConditions", HashEqualsPointer),
                slice("LeftConditions", HashEqualsDirect),
                slice("RightConditions", HashEqualsDirect),
                slice("OtherConditions", HashEqualsDirect),
            ],
        ),
        operator(
            "LogicalAggregation",
            vec![
                value("LogicalSchemaProducer"),
                slice("AggFuncs", HashEqualsPointer),
                slice("GroupByItems", HashEqualsDirect),
                value("PossibleProperties"),
            ],
        ),
        operator(
            "LogicalApply",
            vec![
                value("LogicalJoin"),
                slice("CorCols", HashEqualsPointer),
                field("NoDecorrelate", Bool),
                field("IsLateral", Bool),
            ],
        ),
        operator(
            "LogicalExpand",
            vec![
                value("LogicalSchemaProducer"),
                slice("DistinctGroupByCol", HashEqualsPointer),
                slice("DistinctGbyExprs", HashEqualsDirect),
                field("DistinctSize", SignedInteger),
                slice(
                    "RollupGroupingSets",
                    FieldType::Slice(Box::new(FieldType::Slice(Box::new(HashEqualsDirect)))),
                ),
                slice("LevelExprs", FieldType::Slice(Box::new(HashEqualsDirect))),
                pointer("GID"),
                pointer("GPos"),
            ],
        ),
        operator(
            "LogicalLimit",
            vec![
                value("LogicalSchemaProducer"),
                slice("PartitionBy", HashEqualsValue),
                field("Offset", UnsignedInteger),
                field("Count", UnsignedInteger),
            ],
        ),
        operator("LogicalMaxOneRow", vec![value("BaseLogicalPlan")]),
        operator(
            "DataSource",
            vec![
                value("LogicalSchemaProducer"),
                pointer("TableInfo"),
                pointer("TableAsName"),
                slice("PushedDownConds", HashEqualsDirect),
                slice("AllConds", HashEqualsDirect),
                field("PhysicalTableID", SignedInteger),
                field("PreferStoreType", SignedInteger),
                field("IsForUpdateRead", Bool),
            ],
        ),
        operator(
            "LogicalMemTable",
            vec![
                value("LogicalSchemaProducer"),
                value("DBName"),
                pointer("TableInfo"),
            ],
        ),
        operator("LogicalUnionAll", vec![value("LogicalSchemaProducer")]),
        operator("LogicalPartitionUnionAll", vec![value("LogicalUnionAll")]),
        operator(
            "LogicalProjection",
            vec![
                value("LogicalSchemaProducer"),
                slice("Exprs", HashEqualsDirect),
                field("CalculateNoDelay", Bool),
                field("Proj4Expand", Bool),
            ],
        ),
        operator(
            "LogicalSelection",
            vec![slice("Conditions", HashEqualsDirect)],
        ),
        operator("LogicalSequence", vec![value("BaseLogicalPlan")]),
        operator("LogicalShow", vec![value("LogicalSchemaProducer")]),
        operator("LogicalShowDDLJobs", vec![value("LogicalSchemaProducer")]),
        operator("LogicalSort", vec![slice("ByItems", HashEqualsPointer)]),
        operator(
            "LogicalTableDual",
            vec![
                value("LogicalSchemaProducer"),
                field("RowCount", SignedInteger),
            ],
        ),
        operator(
            "LogicalTopN",
            vec![
                value("LogicalSchemaProducer"),
                slice("ByItems", HashEqualsPointer),
                slice("PartitionBy", HashEqualsValue),
                field("Offset", UnsignedInteger),
                field("Count", UnsignedInteger),
                field("PreferLimitToCop", Bool),
            ],
        ),
        operator(
            "LogicalUnionScan",
            vec![slice("Conditions", HashEqualsDirect), direct("HandleCols")],
        ),
        operator(
            "LogicalWindow",
            vec![
                value("LogicalSchemaProducer"),
                slice("WindowFuncDescs", HashEqualsPointer),
                slice("PartitionBy", HashEqualsValue),
                slice("OrderBy", HashEqualsValue),
                pointer("Frame"),
            ],
        ),
        operator(
            "LogicalLock",
            vec![value("BaseLogicalPlan"), pointer("Lock")],
        ),
    ]
}

/// Exact Go logical-operator name to plan-codec mapping.
pub fn logical_op_name_to_plan_codec(name: &str) -> &'static str {
    match name {
        "LogicalJoin" => "plancodec.TypeJoin",
        "LogicalAggregation" => "plancodec.TypeAgg",
        "LogicalApply" => "plancodec.TypeApply",
        "LogicalExpand" => "plancodec.TypeExpand",
        "LogicalLimit" => "plancodec.TypeLimit",
        "LogicalMaxOneRow" => "plancodec.TypeMaxOneRow",
        "DataSource" => "plancodec.TypeDataSource",
        "LogicalMemTable" => "plancodec.TypeMemTableScan",
        "LogicalUnionAll" => "plancodec.TypeUnion",
        "LogicalPartitionUnionAll" => "plancodec.TypePartitionUnion",
        "LogicalProjection" => "plancodec.TypeProj",
        "LogicalSelection" => "plancodec.TypeSel",
        "LogicalSequence" => "plancodec.TypeSequence",
        "LogicalShow" => "plancodec.TypeShow",
        "LogicalShowDDLJobs" => "plancodec.TypeShowDDLJobs",
        "LogicalSort" => "plancodec.TypeSort",
        "LogicalTableDual" => "plancodec.TypeDual",
        "LogicalTopN" => "plancodec.TypeTopN",
        "LogicalUnionScan" => "plancodec.TypeUnionScan",
        "LogicalWindow" => "plancodec.TypeWindow",
        "LogicalLock" => "plancodec.TypeLock",
        _ => "",
    }
}

/// All logical operators covered by Go `GenHash64Equals4LogicalOps`.
pub const LOGICAL_STRUCTURES: &[&str] = &[
    "LogicalJoin",
    "LogicalAggregation",
    "LogicalApply",
    "LogicalExpand",
    "LogicalLimit",
    "LogicalMaxOneRow",
    "DataSource",
    "LogicalMemTable",
    "LogicalUnionAll",
    "LogicalPartitionUnionAll",
    "LogicalProjection",
    "LogicalSelection",
    "LogicalSequence",
    "LogicalShow",
    "LogicalShowDDLJobs",
    "LogicalSort",
    "LogicalTableDual",
    "LogicalTopN",
    "LogicalUnionScan",
    "LogicalWindow",
    "LogicalLock",
];

/// Rust counterpart of Go `GenHash64Equals4LogicalOps`.
pub fn GenHash64Equals4LogicalOps() -> Result<Vec<u8>, String> {
    generate(&logical_operator_specs())
}

fn validate_name(name: &str) -> Result<(), String> {
    let mut characters = name.chars();
    let Some(first) = characters.next() else {
        return Err("invalid empty Go identifier".to_owned());
    };
    if !(first == '_' || first.is_ascii_alphabetic())
        || !characters.all(|character| character == '_' || character.is_ascii_alphanumeric())
    {
        return Err(format!("invalid Go identifier {name}"));
    }
    Ok(())
}
