[package]
name = "astersql-testkit-testfailpoint"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[dependencies]
fail = { version = "0.5.1", features = ["failpoints"] }

[package.metadata.porting]
go-package = "pkg/testkit/testfailpoint"
legacy-tasks = ["task-51"]
