[package]
name = "astersql-sessionctx-variable"
version.workspace = true
edition.workspace = true
publish.workspace = true
autotests = false

[lib]
path = "lib.rs"
doctest = false

[dependencies]
url = "2"
chrono = "0.4"
config = { package = "astersql-config", path = "../../config" }
astersql-config-configtypes = { path = "../../config/configtypes" }
crc = "3"
execdetails = { package = "astersql-util-execdetails", path = "../../util/execdetails" }
kerneltype = { package = "astersql-config-kerneltype", path = "../../config/kerneltype" }
naming = { package = "astersql-util-naming", path = "../../util/naming" }
kv = { package = "astersql-kv", path = "../../kv" }
serde_json = "1"
traceevent = { package = "astersql-util-traceevent", path = "../../util/traceevent" }
parser-auth = { package = "astersql-parser-auth", path = "../../parser/auth" }
parser-ast = { package = "astersql-parser-ast", path = "../../parser/ast" }
parser-charset = { package = "astersql-parser-charset", path = "../../parser/charset" }
stmtctx-dependency = { package = "astersql-sessionctx-stmtctx", path = "../stmtctx" }
sysinfo = "0.33"
tiflashcompute = { package = "astersql-util-tiflashcompute", path = "../../util/tiflashcompute" }
tls_dependency = { package = "astersql-util-tls", path = "../../util/tls" }
vardef = { package = "astersql-sessionctx-vardef", path = "../vardef" }

[dev-dependencies]
serial_test = "3"

[package.metadata.porting]
go-package = "pkg/sessionctx/variable"
legacy-tasks = ["task-596", "task-598", "task-599"]
