// Copyright 2026 AsterSQL.
// Copyright 2025 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// ingestcli 公共接口与请求/响应类型。
//
// 定义写入流（WriteClient）与导入（Client::ingest）所需的 KV 对、Region 元数据、
// SplitClient（PD 侧取 Store 状态地址）以及可取消的 RequestContext。
// Region：TiKV 按键范围划分的分片；SST：写入完成后生成的有序文件，再被 ingest 进对应 Region。

use std::sync::Arc;

/// A KV pair accepted by the next-generation write API.
/// 新一代写入 API 接受的键值对。
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct Pair {
    pub key: Vec<u8>,
    pub value: Vec<u8>,
}

/// WriteRequest is the request to write KV to the storage layer.
/// 向存储层写入 KV 的请求，可含多对 Pair。
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct WriteRequest {
    pub pairs: Vec<Pair>,
}

/// WriteResponse contains the SST generated by a completed write stream.
/// 写流结束后返回的 SST 元数据（NextGenSstMeta）。
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct WriteResponse {
    pub(crate) next_gen_sst_meta: Option<crate::NextGenSstMeta>,
}

impl WriteResponse {
    /// 取出写流生成的 SST 元数据（若有）。
    pub fn sst_meta(&self) -> Option<&crate::NextGenSstMeta> {
        self.next_gen_sst_meta.as_ref()
    }
}

/// Region 的 epoch（版本）：conf_ver 配置变更、version 键范围变更。
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct RegionEpoch {
    pub conf_ver: u64,
    pub version: u64,
}

/// Region 的一个 Peer（副本），含 peer id 与所在 store_id。
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct Peer {
    pub id: u64,
    pub store_id: u64,
}

/// TiKV Region：键范围分片及其 epoch 与 peers。
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct Region {
    pub id: u64,
    pub start_key: Vec<u8>,
    pub end_key: Vec<u8>,
    pub region_epoch: Option<RegionEpoch>,
    pub peers: Vec<Peer>,
}

/// Region 加上可选 leader Peer，供 ingest 定位目标 store。
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct RegionInfo {
    pub region: Region,
    pub leader: Option<Peer>,
}

/// IngestRequest joins the target region with the SST created by WriteClient.
/// 将目标 Region 与 WriteClient 生成的 SST 绑定，供 Client::ingest 使用。
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct IngestRequest {
    pub region: RegionInfo,
    pub write_response: WriteResponse,
}

/// TiKV Store 的状态服务地址（用于拼 ingest HTTP URL）。
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct Store {
    pub status_address: String,
}

/// SplitClient is the small PD surface required by this package.
/// 本包所需的最小 PD（Placement Driver）接口：按 store_id 取 Store。
pub trait SplitClient: Send + Sync {
    fn get_store(&self, context: &dyn RequestContext, store_id: u64)
    -> Result<Store, crate::Error>;
}

/// RequestContext preserves Go's cancellation check at request boundaries.
/// 请求边界上的取消检查，对齐 Go context.Context 的取消语义。
pub trait RequestContext: Send + Sync {
    fn is_cancelled(&self) -> bool {
        false
    }
}

impl RequestContext for () {}

/// WriteClient supports multiple writes followed by one receive. Callers must
/// close it on an error path, matching the ownership contract in Go.
/// 支持多次 write、一次 recv；出错路径须 close，与 Go 所有权约定一致。
pub trait WriteClient: Send {
    fn write(&mut self, request: WriteRequest) -> Result<(), crate::Error>;
    fn recv(&mut self) -> Result<WriteResponse, crate::Error>;
    fn close(&mut self);

    /// Go 风格别名：Write。
    fn Write(&mut self, request: &WriteRequest) -> Result<(), crate::Error> {
        self.write(request.clone())
    }

    /// Go 风格别名：Recv。
    fn Recv(&mut self) -> Result<WriteResponse, crate::Error> {
        self.recv()
    }

    /// Go 风格别名：Close。
    fn Close(&mut self) {
        self.close()
    }
}

/// Client writes KV data and then ingests the generated SST into a region.
/// 先写 KV 生成 SST，再将 SST ingest 到指定 Region。
pub trait Client: Send + Sync {
    fn write_client(
        &self,
        context: &dyn RequestContext,
        commit_ts: u64,
    ) -> Result<Box<dyn WriteClient>, crate::Error>;

    fn ingest(
        &self,
        context: &dyn RequestContext,
        request: IngestRequest,
    ) -> Result<(), crate::Error>;

    /// Go 风格别名：WriteClient。
    fn WriteClient(
        &self,
        context: &dyn RequestContext,
        commit_ts: u64,
    ) -> Result<Box<dyn WriteClient>, crate::Error> {
        self.write_client(context, commit_ts)
    }

    /// Go 风格别名：Ingest。
    fn Ingest(
        &self,
        context: &dyn RequestContext,
        request: &IngestRequest,
    ) -> Result<(), crate::Error> {
        self.ingest(context, request.clone())
    }
}

/// 共享的 SplitClient 句柄。
pub type SharedSplitClient = Arc<dyn SplitClient>;
