[package]
name = "astersql-executor-test-jointest"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[package.metadata.porting]
go-package = "pkg/executor/test/jointest"
legacy-tasks = ["task-1343", "task-1344"]

[dev-dependencies]
"astersql-config" = { package = "astersql-config", path = "../../../config" }
"astersql-meta-autoid" = { package = "astersql-meta-autoid", path = "../../../meta/autoid" }
"astersql-session" = { package = "astersql-session", path = "../../../session" }
"astersql-testkit" = { package = "astersql-testkit", path = "../../../testkit" }
"astersql-testkit-testfailpoint" = { package = "astersql-testkit-testfailpoint", path = "../../../testkit/testfailpoint" }
"astersql-util-dbterror-exeerrors" = { package = "astersql-util-dbterror-exeerrors", path = "../../../util/dbterror/exeerrors" }
