// Copyright 2026 AsterSQL.
// Copyright 2023 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pingcap/tidb/pkg/dxf/framework/scheduler (interfaces: Extension)
//
// Generated by this command:
//
//	mockgen -destination pkg/dxf/framework/scheduler/mock/scheduler_mock.go -package mock github.com/pingcap/tidb/pkg/dxf/framework/scheduler Extension

// Extension trait 的 mockall 实现（由 Go MockGen 源迁移）。
//
// 提供 GetEligibleInstances、步骤推进、meta 修改与生命周期回调的可配置期望。

#![allow(non_snake_case)]

use anyhow::{Error, Result};

use crate::Context;
use crate::proto::{Modification, Step, Task, TaskBase};
use crate::storage;

// GoMock 的 controller/recorder 由 mockall 期望引擎承担。
// Handle 做成泛型：因 TaskHandle 含泛型回调，无法作为 trait object。
// GoMock's controller and recorder are represented by mockall's expectation
// engine. The handle type is generic because Rust's storage::TaskHandle has
// generic callback methods and therefore cannot be used as a trait object.
mockall::mock! {
    pub Extension<H: storage::TaskHandle + Send + Sync + 'static> {
        pub fn GetEligibleInstances(
            &self,
            context: Context,
            task: &Task,
        ) -> Result<Vec<String>>;

        pub fn GetNextStep(&self, task: &TaskBase) -> Step;

        pub fn IsRetryableErr(&self, error: Error) -> bool;

        pub fn ModifyMeta(
            &self,
            old_meta: Vec<u8>,
            modifications: Vec<Modification>,
        ) -> Result<Vec<u8>>;

        pub fn OnDone(
            &self,
            context: Context,
            handle: &H,
            task: &Task,
        ) -> Result<()>;

        pub fn OnNextSubtasksBatch(
            &self,
            context: Context,
            handle: &H,
            task: &Task,
            exec_ids: Vec<String>,
            next_step: Step,
        ) -> Result<Vec<Vec<u8>>>;

        pub fn OnPrepare(
            &self,
            context: Context,
            handle: &H,
            task: &mut Task,
        ) -> Result<()>;

        pub fn OnTick(&self, context: Context, task: &Task);
    }
}

impl<H> MockExtension<H>
where
    H: storage::TaskHandle + Send + Sync + 'static,
{
    /// 保留 GoMock 生成接口检查用的空标记方法。
    /// Retains the marker emitted by GoMock for generated-interface checks.
    pub fn ISGOMOCK(&self) {}

    /// 返回自身作为期望录制器；调用方用 `expect_*` 配置调用。
    /// Returns this mock as its expectation recorder.
    ///
    /// Rust callers configure calls with the generated `expect_*` methods.
    pub fn EXPECT(&mut self) -> &mut Self {
        self
    }
}

/// 创建空期望集的 Extension mock。
///
/// controller 参数仅保留 Go 构造形状；期望状态由 mockall 管理与校验。
/// Creates a new Extension mock with an empty expectation set.
///
/// The controller argument preserves the Go constructor shape. Mockall owns
/// and verifies the expectation state for each returned instance.
pub fn NewMockExtension<H, C>(_controller: &C) -> MockExtension<H>
where
    H: storage::TaskHandle + Send + Sync + 'static,
    C: ?Sized,
{
    MockExtension::new()
}
