// Copyright 2023 PingCAP, Inc.
// Copyright 2026 AsterSQL.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by "util/collate/ucadata/generator"; DO NOT EDIT.

// {{.Name}} is the collation element table for the corresponding unicode version.
// it's generated from {{.URL}}
/// UCA 权重表容器：主表 + 超长权重映射。
pub struct UcaDataTable<const N: usize> {
    /// 按码点索引的主权重表。
    pub MapTable4: [u64; N],
    /// 超长权重映射；按 rune 排序以支持二分查找。
    pub LongRuneMap: &'static [(u32, [u64; 2])],
}

impl<const N: usize> UcaDataTable<N> {
    /// 返回主表覆盖范围内码点的生成权重。
    pub fn map_table_weight(&self, rune: u32) -> Option<u64> {
        self.MapTable4.get(rune as usize).copied()
    }

    /// 在有序长权重表中按 rune 查找权重。
    pub fn long_rune_weight(&self, rune: u32) -> Option<[u64; 2]> {
        self.LongRuneMap
            .binary_search_by_key(&rune, |(key, _)| *key)
            .ok()
            .map(|index| self.LongRuneMap[index].1)
    }
}

/// Unicode 4.0.0 DUCET 表实例。
pub static {{.Name}}: UcaDataTable<{{.Length}}> = UcaDataTable {
    MapTable4: [
{{.MapTable4}}
    ],
    LongRuneMap: &[
{{.LongRuneMap}}
    ],
};
