// Copyright 2026 AsterSQL.
// Copyright 2015 PingCAP, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Hash（哈希表）语义：在 TxStructure 上按 field 读写类 Redis Hash 结构。
//
// 每个 hash 的 field 编码为独立 KV 条目；支持增删改、整数自增、正/反向迭代。
// 本文件经 `include!` 编入 hash_impl 模块。

// HashPair is the pair for (field, value) in a hash.
/// 哈希字段与值的配对。
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct HashPair {
    /// 字段名（二进制）。
    pub Field: Vec<u8>,
    /// 字段值（二进制）。
    pub Value: Vec<u8>,
}

impl TxStructure {
    // HSet sets the string value of a hash field.
    /// 设置哈希字段的字符串值；快照只读时返回写错误。
    pub fn HSet(
        &mut self,
        key: &[u8],
        field: &[u8],
        value: &[u8],
    ) -> Result<(), errors::SharedError> {
        if self.readWriter.is_none() {
            return Err(ErrWriteOnSnapshot.FastGenByArgs(&[]));
        }
        self.updateHash(key, field, |_| Ok(value.to_vec()))
    }

    // HGet gets the value of a hash field.
    /// 读取哈希字段值；不存在返回 None。
    pub fn HGet(&self, key: &[u8], field: &[u8]) -> Result<Option<Vec<u8>>, errors::SharedError> {
        let dataKey = self.encodeHashDataKey(key, field);
        match kv::GetValue(&kv::Context::todo(), self.reader.as_ref(), dataKey) {
            Ok(value) => Ok(Some(value)),
            Err(error) if kv::IsErrNotFound(&error) => Ok(None),
            Err(error) => Err(error),
        }
    }

    /// 将整数编码为十进制字符串字节，作为哈希字段的整数值表示。
    fn hashFieldIntegerVal(&self, value: i64) -> Vec<u8> {
        value.to_string().into_bytes()
    }

    // EncodeHashAutoIDKeyValue returns the hash key-value generated by the key and the field.
    /// 由 key/field 生成 AutoID 用的哈希数据键与整数字节值。
    pub fn EncodeHashAutoIDKeyValue(
        &self,
        key: &[u8],
        field: &[u8],
        value: i64,
    ) -> (kv::Key, Vec<u8>) {
        (
            self.encodeHashDataKey(key, field),
            self.hashFieldIntegerVal(value),
        )
    }

    // HInc increments the integer value of a hash field, by step.
    /// 将哈希字段按 step 做整数自增（wrapping）；缺省从 0 开始。
    pub fn HInc(
        &mut self,
        key: &[u8],
        field: &[u8],
        step: i64,
    ) -> Result<i64, errors::SharedError> {
        if self.readWriter.is_none() {
            return Err(ErrWriteOnSnapshot.FastGenByArgs(&[]));
        }
        let mut base = 0i64;
        self.updateHash(key, field, |oldValue| {
            // 旧值按十进制字符串解析；不存在则视为 0。
            if let Some(oldValue) = oldValue {
                let text = std::str::from_utf8(oldValue)
                    .map_err(|error| errors::New(error.to_string()))?;
                base = text
                    .parse::<i64>()
                    .map_err(|error| errors::New(error.to_string()))?;
            }
            base = base.wrapping_add(step);
            Ok(base.to_string().into_bytes())
        })?;
        Ok(base)
    }

    // HGetInt64 gets int64 value of a hash field.
    /// 以 int64 读取哈希字段；不存在返回 0。
    pub fn HGetInt64(&self, key: &[u8], field: &[u8]) -> Result<i64, errors::SharedError> {
        let Some(value) = self.HGet(key, field)? else {
            return Ok(0);
        };
        let text = std::str::from_utf8(&value).map_err(|error| errors::New(error.to_string()))?;
        text.parse::<i64>()
            .map_err(|error| errors::New(error.to_string()))
    }

    /// 通用哈希更新：加载旧值、经回调生成新值，值未变则跳过写入。
    fn updateHash<F>(
        &mut self,
        key: &[u8],
        field: &[u8],
        mut function: F,
    ) -> Result<(), errors::SharedError>
    where
        F: FnMut(Option<&[u8]>) -> Result<Vec<u8>, errors::SharedError>,
    {
        let dataKey = self.encodeHashDataKey(key, field);
        let oldValue = self.loadHashValue(dataKey.clone())?;
        let newValue = function(oldValue.as_deref())?;
        if oldValue.as_deref().unwrap_or_default() == newValue.as_slice() {
            return Ok(());
        }
        self.writer()?.Set(dataKey, newValue)
    }

    // HDel deletes one or more hash fields.
    /// 删除一个或多个哈希字段；仅删除已存在的条目。
    pub fn HDel(&mut self, key: &[u8], fields: &[Vec<u8>]) -> Result<(), errors::SharedError> {
        if self.readWriter.is_none() {
            return Err(ErrWriteOnSnapshot.FastGenByArgs(&[]));
        }
        for field in fields {
            let dataKey = self.encodeHashDataKey(key, field);
            if self.loadHashValue(dataKey.clone())?.is_some() {
                self.writer()?.Delete(dataKey)?;
            }
        }
        Ok(())
    }

    // HKeys gets all the fields in a hash.
    /// 列出哈希中全部字段名。
    pub fn HKeys(&self, key: &[u8]) -> Result<Vec<Vec<u8>>, errors::SharedError> {
        let mut keys = Vec::new();
        self.IterateHash(key, |field, _| {
            keys.push(field.to_vec());
            Ok(())
        })?;
        Ok(keys)
    }

    // HGetAll gets all the fields and values in a hash.
    /// 获取哈希中全部字段-值对。
    pub fn HGetAll(&self, key: &[u8]) -> Result<Vec<HashPair>, errors::SharedError> {
        let mut result = Vec::new();
        self.IterateHash(key, |field, value| {
            result.push(HashPair {
                Field: field.to_vec(),
                Value: value.to_vec(),
            });
            Ok(())
        })?;
        Ok(result)
    }

    // HGetIter iterates all the fields and values in hash.
    /// 以 HashPair 回调形式迭代全部字段。
    pub fn HGetIter<F>(&self, key: &[u8], mut function: F) -> Result<(), errors::SharedError>
    where
        F: FnMut(HashPair) -> Result<(), errors::SharedError>,
    {
        self.IterateHash(key, |field, value| {
            function(HashPair {
                Field: field.to_vec(),
                Value: value.to_vec(),
            })
        })
    }

    // HGetLen gets the length of hash.
    /// 返回哈希字段个数。
    pub fn HGetLen(&self, key: &[u8]) -> Result<u64, errors::SharedError> {
        let mut length = 0u64;
        self.IterateHash(key, |_, _| {
            length = length.wrapping_add(1);
            Ok(())
        })?;
        Ok(length)
    }

    // HGetLastN gets latest N fields and values in hash.
    /// 反向迭代取最近 N 个字段-值对（按编码序末尾优先）。
    pub fn HGetLastN(&self, key: &[u8], num: usize) -> Result<Vec<HashPair>, errors::SharedError> {
        let mut result = Vec::with_capacity(num);
        self.iterReverseHash(key, |field, value| {
            result.push(HashPair {
                Field: field.to_vec(),
                Value: value.to_vec(),
            });
            Ok(result.len() < num)
        })?;
        Ok(result)
    }

    // HClear removes the hash value of the key.
    /// 清除该 key 下全部哈希字段。
    pub fn HClear(&mut self, key: &[u8]) -> Result<(), errors::SharedError> {
        let mut keys = Vec::new();
        self.IterateHash(key, |field, _| {
            keys.push(self.encodeHashDataKey(key, field));
            Ok(())
        })?;
        for key in keys {
            self.writer()?.Delete(key)?;
        }
        Ok(())
    }

    // IterateHash iterates all the fields and values in hash.
    /// 正向扫描某 hash key 前缀下的全部 field/value。
    pub fn IterateHash<F>(&self, key: &[u8], mut function: F) -> Result<(), errors::SharedError>
    where
        F: FnMut(&[u8], &[u8]) -> Result<(), errors::SharedError>,
    {
        let prefix = self.hashDataKeyPrefix(key);
        let mut iterator = self
            .reader
            .Iter(prefix.clone(), Some(prefix.PrefixNext()))?;
        let result = (|| {
            while iterator.Valid() {
                let encoded = iterator.Key();
                if !encoded.HasPrefix(&prefix) {
                    break;
                }
                let (_, field) = self.decodeHashDataKey(encoded)?;
                let value = iterator.Value();
                function(&field, &value)?;
                iterator.Next()?;
            }
            Ok(())
        })();
        iterator.Close();
        result
    }

    // IterateHashWithBoundedKey iterates all hash entries in the bounded key range.
    /// 在哈希业务 key 的 `[hashStartKey, hashEndKey)` 范围内迭代全部条目。
    pub fn IterateHashWithBoundedKey<F>(
        &self,
        hashStartKey: &[u8],
        hashEndKey: &[u8],
        mut function: F,
    ) -> Result<(), errors::SharedError>
    where
        F: FnMut(&[u8], &[u8], &[u8]) -> Result<(), errors::SharedError>,
    {
        let start = self.hashDataKeyPrefix(hashStartKey);
        let end = self.hashDataKeyPrefix(hashEndKey);
        let mut iterator = self.reader.Iter(start, Some(end))?;
        let result = (|| {
            while iterator.Valid() {
                let decoded = self.decodeHashDataKey(iterator.Key());
                match decoded {
                    Ok((key, field)) => {
                        let value = iterator.Value();
                        function(&key, &field, &value)?;
                    }
                    Err(_) => {
                        // 非哈希数据键则跳过，继续扫描。
                        iterator.Next()?;
                        continue;
                    }
                }
                iterator.Next()?;
            }
            Ok(())
        })();
        iterator.Close();
        result
    }

    /// 反向扫描哈希字段；回调返回 false 时提前结束。
    fn iterReverseHash<F>(&self, key: &[u8], mut function: F) -> Result<(), errors::SharedError>
    where
        F: FnMut(&[u8], &[u8]) -> Result<bool, errors::SharedError>,
    {
        let prefix = self.hashDataKeyPrefix(key);
        let mut iterator = self.reader.IterReverse(Some(prefix.PrefixNext()), None)?;
        let result = (|| {
            while iterator.Valid() {
                let encoded = iterator.Key();
                if !encoded.HasPrefix(&prefix) {
                    break;
                }
                let (_, field) = self.decodeHashDataKey(encoded)?;
                let value = iterator.Value();
                if !function(&field, &value)? {
                    break;
                }
                iterator.Next()?;
            }
            Ok(())
        })();
        iterator.Close();
        result
    }

    /// 加载单个哈希数据键的值；不存在返回 None。
    fn loadHashValue(&self, dataKey: kv::Key) -> Result<Option<Vec<u8>>, errors::SharedError> {
        match kv::GetValue(&kv::Context::todo(), self.reader.as_ref(), dataKey) {
            Ok(value) => Ok(Some(value)),
            Err(error) if kv::IsErrNotFound(&error) => Ok(None),
            Err(error) => Err(error),
        }
    }
}

// ReverseHashIterator is the reverse hash iterator.
/// 哈希反向迭代器：从字段编码序末尾向前遍历。
pub struct ReverseHashIterator<'a> {
    /// 所属 TxStructure，用于解码。
    t: &'a TxStructure,
    /// 底层 KV 反向迭代器。
    iter: Box<dyn kv::Iterator>,
    /// 当前 hash key 的数据键前缀。
    prefix: kv::Key,
    /// 是否已越过前缀或耗尽。
    done: bool,
    /// 当前解码出的 field。
    field: Vec<u8>,
}

impl ReverseHashIterator<'_> {
    /// 前进到下一个字段；越界则标记 done。
    pub fn Next(&mut self) -> Result<(), errors::SharedError> {
        self.iter.Next()?;
        if !self.iter.Valid() || !self.iter.Key().HasPrefix(&self.prefix) {
            self.done = true;
            return Ok(());
        }
        self.field = self.t.decodeHashDataKey(self.iter.Key())?.1;
        Ok(())
    }

    /// 迭代器是否仍有效。
    pub fn Valid(&self) -> bool {
        self.iter.Valid() && !self.done
    }

    /// 当前字段名。
    pub fn Key(&self) -> &[u8] {
        &self.field
    }

    /// 当前字段值。
    pub fn Value(&self) -> Vec<u8> {
        self.iter.Value()
    }

    /// 关闭底层迭代器。
    pub fn Close(&mut self) {
        self.iter.Close();
    }
}

impl Drop for ReverseHashIterator<'_> {
    fn drop(&mut self) {
        self.iter.Close();
    }
}

/// 从哈希末尾创建反向迭代器。
pub fn NewHashReverseIter<'a>(
    structure: &'a TxStructure,
    key: &[u8],
) -> Result<ReverseHashIterator<'a>, errors::SharedError> {
    newHashReverseIter(structure, key, None)
}

/// 从指定 field 之后（编码序）开始创建反向迭代器。
pub fn NewHashReverseIterBeginWithField<'a>(
    structure: &'a TxStructure,
    key: &[u8],
    field: &[u8],
) -> Result<ReverseHashIterator<'a>, errors::SharedError> {
    newHashReverseIter(structure, key, Some(field))
}

/// 构造反向迭代器：无 field 时从前缀上界开始，否则从该 field 的下一键开始。
fn newHashReverseIter<'a>(
    structure: &'a TxStructure,
    key: &[u8],
    field: Option<&[u8]>,
) -> Result<ReverseHashIterator<'a>, errors::SharedError> {
    let prefix = structure.hashDataKeyPrefix(key);
    let start = match field {
        None | Some([]) => prefix.PrefixNext(),
        Some(field) => structure.encodeHashDataKey(key, field).PrefixNext(),
    };
    let iterator = structure.reader.IterReverse(Some(start), None)?;
    Ok(ReverseHashIterator {
        t: structure,
        iter: iterator,
        prefix,
        done: false,
        field: Vec::new(),
    })
}
