[package]
name = "astersql-statistics-handle-updatetest"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[package.metadata.porting]
go-package = "pkg/statistics/handle/updatetest"
legacy-tasks = ["task-1635"]

[dev-dependencies]
"astersql-statistics-handle" = { package = "astersql-statistics-handle", path = ".." }
"astersql-parser-ast" = { package = "astersql-parser-ast", path = "../../../parser/ast" }
"astersql-parser-mysql" = { package = "astersql-parser-mysql", path = "../../../parser/mysql" }
"astersql-sessionctx" = { package = "astersql-sessionctx", path = "../../../sessionctx" }
"astersql-sessionctx-stmtctx" = { package = "astersql-sessionctx-stmtctx", path = "../../../sessionctx/stmtctx" }
"astersql-sessionctx-variable" = { package = "astersql-sessionctx-variable", path = "../../../sessionctx/variable" }
"astersql-statistics" = { package = "astersql-statistics", path = "../.." }
"astersql-statistics-handle-ddl-testutil" = { package = "astersql-statistics-handle-ddl-testutil", path = "../ddl/testutil" }
"astersql-statistics-handle-usage" = { package = "astersql-statistics-handle-usage", path = "../usage" }
"astersql-statistics-handle-util" = { package = "astersql-statistics-handle-util", path = "../util" }
"astersql-testkit" = { package = "astersql-testkit", path = "../../../testkit" }
"astersql-testkit-analyzehelper" = { package = "astersql-testkit-analyzehelper", path = "../../../testkit/analyzehelper" }
"astersql-testkit-testsetup" = { package = "astersql-testkit-testsetup", path = "../../../testkit/testsetup" }
"astersql-types" = { package = "astersql-types", path = "../../../types" }
"astersql-util-collate" = { package = "astersql-util-collate", path = "../../../util/collate" }
"astersql-util-ranger" = { package = "astersql-util-ranger", path = "../../../util/ranger" }
