[package]
name = "astersql-table-tblctx"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"
doctest = false

[dependencies]
chrono-tz = "0.10"
chunk-dependency = { package = "astersql-util-chunk", path = "../../util/chunk" }
errctx-dependency = { package = "astersql-errctx", path = "../../errctx" }
exprctx-dependency = { package = "astersql-expression-exprctx", path = "../../expression/exprctx" }
infoschema-dependency = { package = "astersql-infoschema-context", path = "../../infoschema/context" }
intest-dependency = { package = "astersql-util-intest", path = "../../util/intest", default-features = false }
model-dependency = { package = "astersql-meta-model-group4", path = "../../meta/model/internal/group4" }
autoid-dependency = { package = "astersql-meta-autoid", path = "../../meta/autoid" }
stmtctx-dependency = { package = "astersql-sessionctx-stmtctx", path = "../../sessionctx/stmtctx" }
tablecodec-dependency = { package = "astersql-tablecodec", path = "../../tablecodec" }
tableutil-dependency = { package = "astersql-util-tableutil", path = "../../util/tableutil" }
variable-dependency = { package = "astersql-sessionctx-variable", path = "../../sessionctx/variable" }

[package.metadata.porting]
go-package = "pkg/table/tblctx"
legacy-tasks = ["task-609"]
