// Copyright 2026 AsterSQL.

//! 仓库内解析表产物的确定性生成、写入和防漂移检查。

use std::{
    error::Error,
    fmt, fs, io,
    path::{Path, PathBuf},
};

use crate::{GeneratedParser, Grammar};

const GENERATED_FILE_HEADER: &str =
    "// Copyright 2026 AsterSQL.\n\n// @generated by astersql-parsergen; do not edit.\n";

pub const GENERATED_OUTPUT_NAMES: [&str; 3] =
    ["main_tables.rs", "hint_tables.rs", "lexer_tokens.rs"];

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedOutput {
    pub name: &'static str,
    pub contents: String,
}

#[derive(Debug)]
pub struct GenerationError {
    message: String,
}

impl GenerationError {
    fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

impl fmt::Display for GenerationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.message)
    }
}

impl Error for GenerationError {}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum GeneratedOutputIssueKind {
    Missing,
    Stale,
}

impl fmt::Display for GeneratedOutputIssueKind {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Missing => formatter.write_str("missing"),
            Self::Stale => formatter.write_str("stale"),
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedOutputIssue {
    pub path: PathBuf,
    pub kind: GeneratedOutputIssueKind,
}

#[derive(Debug)]
pub struct CheckGeneratedOutputsError {
    pub issues: Vec<GeneratedOutputIssue>,
    message: Option<String>,
}

impl CheckGeneratedOutputsError {
    fn generation(error: GenerationError) -> Self {
        Self {
            issues: Vec::new(),
            message: Some(error.to_string()),
        }
    }

    fn io(operation: &str, path: &Path, error: io::Error) -> Self {
        Self {
            issues: Vec::new(),
            message: Some(format!("{operation} {}: {error}", path.display())),
        }
    }

    fn drift(issues: Vec<GeneratedOutputIssue>) -> Self {
        Self {
            issues,
            message: None,
        }
    }
}

impl fmt::Display for CheckGeneratedOutputsError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        if let Some(message) = &self.message {
            return formatter.write_str(message);
        }
        writeln!(formatter, "generated parser outputs are not current:")?;
        for issue in &self.issues {
            writeln!(formatter, "  {}: {}", issue.kind, issue.path.display())?;
        }
        formatter.write_str("run `astersql-parsergen generate`")
    }
}

impl Error for CheckGeneratedOutputsError {}

#[derive(Clone, Copy)]
enum ParserKind {
    Main,
    Hint,
}

pub fn generate_outputs(parser_root: &Path) -> Result<Vec<GeneratedOutput>, GenerationError> {
    let main = generate_parser_output(parser_root, "main.astergram", ParserKind::Main)?;
    let hint = generate_parser_output(parser_root, "hint.astergram", ParserKind::Hint)?;
    let lexer_tokens = format!(
        "{GENERATED_FILE_HEADER}{}\n",
        render_token_module(&main.1, "token", "i32").trim_end()
    );

    Ok(vec![
        GeneratedOutput {
            name: GENERATED_OUTPUT_NAMES[0],
            contents: main.0,
        },
        GeneratedOutput {
            name: GENERATED_OUTPUT_NAMES[1],
            contents: hint.0,
        },
        GeneratedOutput {
            name: GENERATED_OUTPUT_NAMES[2],
            contents: lexer_tokens,
        },
    ])
}

pub fn write_generated_outputs(parser_root: &Path) -> Result<(), GenerationError> {
    let outputs = generate_outputs(parser_root)?;
    let generated_directory = parser_root.join("generated");
    fs::create_dir_all(&generated_directory).map_err(|error| {
        GenerationError::new(format!(
            "create generated directory {}: {error}",
            generated_directory.display()
        ))
    })?;
    for output in outputs {
        let path = generated_directory.join(output.name);
        fs::write(&path, output.contents).map_err(|error| {
            GenerationError::new(format!(
                "write generated output {}: {error}",
                path.display()
            ))
        })?;
    }
    Ok(())
}

pub fn check_generated_outputs(parser_root: &Path) -> Result<(), CheckGeneratedOutputsError> {
    let outputs = generate_outputs(parser_root).map_err(CheckGeneratedOutputsError::generation)?;
    let generated_directory = parser_root.join("generated");
    let mut issues = Vec::new();
    for output in outputs {
        let path = generated_directory.join(output.name);
        match fs::read(&path) {
            Ok(contents) if contents == output.contents.as_bytes() => {}
            Ok(_) => issues.push(GeneratedOutputIssue {
                path,
                kind: GeneratedOutputIssueKind::Stale,
            }),
            Err(error) if error.kind() == io::ErrorKind::NotFound => {
                issues.push(GeneratedOutputIssue {
                    path,
                    kind: GeneratedOutputIssueKind::Missing,
                });
            }
            Err(error) => {
                return Err(CheckGeneratedOutputsError::io(
                    "read generated output",
                    &path,
                    error,
                ));
            }
        }
    }

    if issues.is_empty() {
        Ok(())
    } else {
        Err(CheckGeneratedOutputsError::drift(issues))
    }
}

fn generate_parser_output(
    parser_root: &Path,
    grammar_name: &str,
    kind: ParserKind,
) -> Result<(String, GeneratedParser), GenerationError> {
    let grammar_path = parser_root.join("grammar").join(grammar_name);
    let source = fs::read_to_string(&grammar_path).map_err(|error| {
        GenerationError::new(format!(
            "read Rust grammar {}: {error}",
            grammar_path.display()
        ))
    })?;
    let grammar = Grammar::parse(&source).map_err(|error| {
        GenerationError::new(format!(
            "parse Rust grammar {}: {error}",
            grammar_path.display()
        ))
    })?;
    let generated = GeneratedParser::build(&grammar).map_err(|error| {
        GenerationError::new(format!(
            "generate parser data {}: {error}",
            grammar_path.display()
        ))
    })?;
    let output = render_compatibility_tables(&grammar, &generated, kind);
    Ok((output, generated))
}

fn render_compatibility_tables(
    grammar: &Grammar,
    generated: &GeneratedParser,
    kind: ParserKind,
) -> String {
    let (prefix, integer, token_module) = match kind {
        ParserKind::Main => ("MAIN", "isize", "token"),
        ParserKind::Hint => ("HINT", "i32", "tokens"),
    };
    let mut output = String::from(GENERATED_FILE_HEADER);

    output.push_str(&render_token_module(generated, token_module, integer));

    output.push_str(&format!(
        "const GENERATED_{prefix}_ACCEPT: i32 = i32::MIN;\n"
    ));
    output.push_str(&format!(
        "static GENERATED_{prefix}_XLAT: &[({integer}, usize)] = &[\n    (0, 0),\n"
    ));
    for (number, column) in &generated.xlat {
        output.push_str(&format!("    ({number}, {column}),\n"));
    }
    output.push_str("];\n\n");

    output.push_str(&format!(
        "static GENERATED_{prefix}_SYMBOL_NAMES: &[&str] = &[\n"
    ));
    for name in &generated.symbol_names {
        output.push_str(&format!("    {name:?},\n"));
    }
    output.push_str("];\n\n");

    if matches!(kind, ParserKind::Main) {
        output.push_str(
            "#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]\n\
             pub(crate) struct RuleId(&'static str);\n\n\
             impl RuleId {\n\
                 pub(crate) const fn as_str(self) -> &'static str { self.0 }\n\
             }\n\n\
             static RULE_IDS_BY_REDUCTION: &[RuleId] = &[\n",
        );
        for rule_id in &generated.rule_ids_by_reduction {
            output.push_str(&format!("    RuleId({:?}),\n", rule_id.as_str()));
        }
        output.push_str("];\n\n");
    }

    output.push_str(&format!(
        "static GENERATED_{prefix}_REDUCTIONS: &[(usize, usize)] = &[\n"
    ));
    for reduction in &generated.reductions {
        output.push_str(&format!(
            "    ({}, {}),\n",
            reduction.symbol, reduction.components
        ));
    }
    output.push_str("];\n\n");

    output.push_str(&format!(
        "static GENERATED_{prefix}_LEGACY_RULES: &[usize] = &[\n"
    ));
    for rule_id in &generated.rule_ids_by_reduction {
        let rule = grammar
            .productions
            .iter()
            .position(|production| &production.rule_id == rule_id)
            .expect("generated rule originates from grammar")
            + 1;
        output.push_str(&format!("    {rule},\n"));
    }
    output.push_str("];\n\n");

    output.push_str(&format!(
        "static GENERATED_{prefix}_ACTION_REQUIRED: &[bool] = &[\n"
    ));
    for required in &generated.action_required_by_reduction {
        output.push_str(&format!("    {required},\n"));
    }
    output.push_str("];\n\n");

    output.push_str(&format!(
        "static GENERATED_{prefix}_PARSE_TABLE: &[&[(usize, i32)]] = &[\n"
    ));
    for row in &generated.parse_table.rows {
        output.push_str("    &[");
        for (index, entry) in row.entries().iter().enumerate() {
            if index != 0 {
                output.push_str(", ");
            }
            output.push_str(&format!("({}, {})", entry.column, entry.value));
        }
        output.push_str("],\n");
    }
    output.push_str("];\n");
    output
}

fn render_token_module(generated: &GeneratedParser, module: &str, integer: &str) -> String {
    let mut output = format!("#[allow(non_upper_case_globals)]\nmod {module} {{\n");
    for (name, number) in &generated.tokens {
        output.push_str(&format!(
            "    pub const {}: {integer} = {number};\n",
            rust_identifier(name)
        ));
    }
    output.push_str("}\n\n");
    output
}

fn rust_identifier(name: &str) -> String {
    match name {
        "super" => "superToken".to_owned(),
        "self" | "Self" | "crate" => format!("TOKEN_{name}"),
        "as" | "async" | "await" | "break" | "const" | "continue" | "dyn" | "else" | "enum"
        | "extern" | "false" | "fn" | "for" | "if" | "impl" | "in" | "let" | "loop" | "match"
        | "mod" | "move" | "mut" | "pub" | "ref" | "return" | "static" | "struct" | "trait"
        | "true" | "type" | "unsafe" | "use" | "where" | "while" | "abstract" | "become"
        | "box" | "do" | "final" | "macro" | "override" | "priv" | "typeof" | "unsized"
        | "virtual" | "yield" | "try" => {
            format!("r#{name}")
        }
        _ => name.to_owned(),
    }
}
