// Copyright 2026 AsterSQL.

// 显式解析表生成与防漂移检查的回归测试。

use std::{
    fs,
    path::{Path, PathBuf},
    sync::atomic::{AtomicU64, Ordering},
};

use crate::{
    GENERATED_OUTPUT_NAMES, GeneratedOutputIssueKind, check_generated_outputs, generate_outputs,
    write_generated_outputs,
};

static TEMP_DIRECTORY_SEQUENCE: AtomicU64 = AtomicU64::new(0);

struct TestDirectory(PathBuf);

impl TestDirectory {
    fn new() -> Self {
        let sequence = TEMP_DIRECTORY_SEQUENCE.fetch_add(1, Ordering::Relaxed);
        let path = std::env::temp_dir().join(format!(
            "astersql-parsergen-{}-{sequence}",
            std::process::id()
        ));
        fs::create_dir(&path).expect("test directory should be created");
        Self(path)
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for TestDirectory {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn write_minimal_grammars(parser_root: &Path) {
    let grammar_directory = parser_root.join("grammar");
    fs::create_dir_all(&grammar_directory).expect("grammar directory should be created");
    let grammar = r#"
%start statement;
%token IDENT 256;
%token PLUS 43 "+";
%%
statement : expression @action;
expression : IDENT
           | expression PLUS IDENT @action;
"#;
    fs::write(grammar_directory.join("main.astergram"), grammar)
        .expect("main grammar should be written");
    fs::write(grammar_directory.join("hint.astergram"), grammar)
        .expect("hint grammar should be written");
}

#[test]
fn generation_is_deterministic_and_names_all_outputs() {
    let parser_root = TestDirectory::new();
    write_minimal_grammars(parser_root.path());

    let first = generate_outputs(parser_root.path()).expect("first generation should succeed");
    let second = generate_outputs(parser_root.path()).expect("second generation should succeed");

    assert_eq!(
        first.iter().map(|output| output.name).collect::<Vec<_>>(),
        GENERATED_OUTPUT_NAMES
    );
    assert_eq!(first, second);
    assert!(first.iter().all(|output| !output.contents.is_empty()));
}

#[test]
fn check_reports_missing_or_stale_output() {
    let parser_root = TestDirectory::new();
    write_minimal_grammars(parser_root.path());

    write_generated_outputs(parser_root.path()).expect("initial generation should succeed");
    let generated_directory = parser_root.path().join("generated");
    let missing_path = generated_directory.join("hint_tables.rs");
    let stale_path = generated_directory.join("lexer_tokens.rs");
    fs::remove_file(&missing_path).expect("generated output should be removable");
    fs::write(&stale_path, "stale contents\n").expect("generated output should be replaceable");

    let error = check_generated_outputs(parser_root.path()).expect_err("drift must be reported");
    assert!(error.issues.iter().any(|issue| {
        issue.path == missing_path && issue.kind == GeneratedOutputIssueKind::Missing
    }));
    assert!(
        error
            .issues
            .iter()
            .any(|issue| issue.path == stale_path && issue.kind == GeneratedOutputIssueKind::Stale)
    );
    assert!(
        !missing_path.exists(),
        "check must not create missing output"
    );
    assert_eq!(
        fs::read_to_string(stale_path).expect("stale output should remain readable"),
        "stale contents\n",
        "check must not rewrite stale output"
    );
}

#[test]
fn committed_outputs_match_current_grammars() {
    let parser_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("parsergen should be located below the parser crate");

    check_generated_outputs(parser_root)
        .expect("checked-in parser outputs should match the current grammars");

    for output in GENERATED_OUTPUT_NAMES {
        let source = fs::read_to_string(parser_root.join("generated").join(output))
            .expect("checked-in parser output should be readable");
        assert!(source.starts_with("// Copyright 2026 AsterSQL.\n"));
        assert!(source.contains("// @generated by astersql-parsergen; do not edit.\n"));
    }
}
