// Copyright 2026 AsterSQL.
// Copyright 2025 PingCAP, Inc. Licensed under Apache-2.0.
// Licensed under the Apache License, Version 2.0.
//
// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pingcap/tidb/pkg/util/sqlexec (interfaces: RestrictedSQLExecutor)
//
// Generated by this command:
//
//	mockgen -package mock github.com/pingcap/tidb/pkg/util/sqlexec RestrictedSQLExecutor
//

// GoMock 风格的 `RestrictedSQLExecutor` 替身：期望队列 FIFO 消费与调用记录。
//
// 由 MockGen 生成逻辑机械迁移；`EXPECT()` 注册处理器，真实调用按顺序取出。

use std::any::Any;
use std::collections::VecDeque;
use std::sync::{Arc, Mutex, MutexGuard};

use crate::{ast, chunk, context, resolve, sqlexec};

/// 任意装箱参数值。
pub type AnyValue = Box<dyn Any>;
/// Mock 侧错误类型，等同 `GoError`。
pub type MockError = sqlexec::GoError;
/// 执行选项闭包类型别名。
pub type ExecOptionFn = sqlexec::OptionFuncAlias;

/// 受限执行返回：(行, 结果字段)。
type ExecResult = Result<(Vec<chunk::Row>, Vec<resolve::ResultField>), MockError>;
/// ExecRestrictedSQL 单次期望处理器。
type ExecRestrictedSQLHandler =
    Box<dyn FnOnce(&context::Context, Vec<ExecOptionFn>, &str, Vec<AnyValue>) -> ExecResult>;
/// ExecRestrictedStmt 单次期望处理器。
type ExecRestrictedStmtHandler =
    Box<dyn FnOnce(&context::Context, ast::NodeRef, Vec<ExecOptionFn>) -> ExecResult>;
/// ParseWithParams 单次期望处理器。
type ParseWithParamsHandler =
    Box<dyn FnOnce(&context::Context, &str, Vec<AnyValue>) -> Result<ast::NodeRef, MockError>>;

/// Observable calls in the same method and argument order as the GoMock mock.
/// 可观察调用记录，方法与参数计数顺序对齐 GoMock。
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Call {
    /// 记录一次 ExecRestrictedSQL。
    ExecRestrictedSQL {
        sql: String,
        option_count: usize,
        argument_count: usize,
    },
    /// 记录一次 ExecRestrictedStmt。
    ExecRestrictedStmt { option_count: usize },
    /// 记录一次 ParseWithParams。
    ParseWithParams { sql: String, argument_count: usize },
}

/// Mock 内部共享状态：调用日志与各方法期望队列。
#[derive(Default)]
struct State {
    calls: Vec<Call>,
    exec_restricted_sql: VecDeque<ExecRestrictedSQLHandler>,
    exec_restricted_stmt: VecDeque<ExecRestrictedStmtHandler>,
    parse_with_params: VecDeque<ParseWithParamsHandler>,
}

/// A strict mock of `sqlexec::RestrictedSQLExecutor`.
///
/// Each recorder method registers one call handler. Base methods consume the
/// handlers in FIFO order, matching GoMock's one-expectation-per-call behavior.
/// `RestrictedSQLExecutor` 的严格 mock：每期望对应一次调用，FIFO 消费。
#[derive(Clone, Default)]
pub struct MockRestrictedSQLExecutor {
    state: Arc<Mutex<State>>,
}

/// Recorder returned by `MockRestrictedSQLExecutor::EXPECT`.
/// 由 `EXPECT()` 返回的期望记录器。
#[derive(Clone)]
pub struct MockRestrictedSQLExecutorMockRecorder {
    state: Arc<Mutex<State>>,
}

/// 构造空期望的 mock 执行器。
pub fn NewMockRestrictedSQLExecutor() -> MockRestrictedSQLExecutor {
    MockRestrictedSQLExecutor::default()
}

/// 加锁取得 State；poison 时吞毒继续（测试场景）。
fn lock(state: &Arc<Mutex<State>>) -> MutexGuard<'_, State> {
    state
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner())
}

/// 从期望队列取出下一个处理器；无线程则 panic。
fn take<T>(queue: &mut VecDeque<T>, method: &str) -> T {
    queue
        .pop_front()
        .unwrap_or_else(|| panic!("unexpected {method} call: no expectation registered"))
}

impl MockRestrictedSQLExecutor {
    /// 返回可注册期望的 Recorder。
    pub fn EXPECT(&self) -> MockRestrictedSQLExecutorMockRecorder {
        MockRestrictedSQLExecutorMockRecorder {
            state: Arc::clone(&self.state),
        }
    }

    /// GoMock 兼容空操作标记。
    pub fn ISGOMOCK(&self) {}

    /// 返回已发生调用的快照。
    pub fn calls(&self) -> Vec<Call> {
        lock(&self.state).calls.clone()
    }

    /// Assert that every registered GoMock-style expected call was consumed.
    /// 断言所有已注册期望均已消费，否则失败。
    pub fn verify(&self) {
        let state = lock(&self.state);
        assert!(
            state.exec_restricted_sql.is_empty(),
            "unmet ExecRestrictedSQL expectations"
        );
        assert!(
            state.exec_restricted_stmt.is_empty(),
            "unmet ExecRestrictedStmt expectations"
        );
        assert!(
            state.parse_with_params.is_empty(),
            "unmet ParseWithParams expectations"
        );
    }
}

impl MockRestrictedSQLExecutorMockRecorder {
    /// 注册一次 ExecRestrictedSQL 期望处理器。
    pub fn ExecRestrictedSQL<F>(&self, handler: F)
    where
        F: FnOnce(&context::Context, Vec<ExecOptionFn>, &str, Vec<AnyValue>) -> ExecResult
            + 'static,
    {
        lock(&self.state)
            .exec_restricted_sql
            .push_back(Box::new(handler));
    }

    /// 注册一次 ExecRestrictedStmt 期望处理器。
    pub fn ExecRestrictedStmt<F>(&self, handler: F)
    where
        F: FnOnce(&context::Context, ast::NodeRef, Vec<ExecOptionFn>) -> ExecResult + 'static,
    {
        lock(&self.state)
            .exec_restricted_stmt
            .push_back(Box::new(handler));
    }

    /// 注册一次 ParseWithParams 期望处理器。
    pub fn ParseWithParams<F>(&self, handler: F)
    where
        F: FnOnce(&context::Context, &str, Vec<AnyValue>) -> Result<ast::NodeRef, MockError>
            + 'static,
    {
        lock(&self.state)
            .parse_with_params
            .push_back(Box::new(handler));
    }
}

impl sqlexec::RestrictedSQLExecutor for MockRestrictedSQLExecutor {
    fn ExecRestrictedSQL(
        &mut self,
        ctx: &context::Context,
        opts: Vec<ExecOptionFn>,
        sql: &str,
        args: Vec<AnyValue>,
    ) -> ExecResult {
        // 先记调用再取期望，避免处理器 panic 时丢失观测记录。
        let handler = {
            let mut state = lock(&self.state);
            state.calls.push(Call::ExecRestrictedSQL {
                sql: sql.to_owned(),
                option_count: opts.len(),
                argument_count: args.len(),
            });
            take(&mut state.exec_restricted_sql, "ExecRestrictedSQL")
        };
        handler(ctx, opts, sql, args)
    }

    fn ExecRestrictedStmt(
        &mut self,
        ctx: &context::Context,
        stmt: ast::NodeRef,
        opts: Vec<ExecOptionFn>,
    ) -> ExecResult {
        let handler = {
            let mut state = lock(&self.state);
            state.calls.push(Call::ExecRestrictedStmt {
                option_count: opts.len(),
            });
            take(&mut state.exec_restricted_stmt, "ExecRestrictedStmt")
        };
        handler(ctx, stmt, opts)
    }

    fn ParseWithParams(
        &mut self,
        ctx: &context::Context,
        sql: &str,
        args: Vec<AnyValue>,
    ) -> Result<ast::NodeRef, MockError> {
        let handler = {
            let mut state = lock(&self.state);
            state.calls.push(Call::ParseWithParams {
                sql: sql.to_owned(),
                argument_count: args.len(),
            });
            take(&mut state.parse_with_params, "ParseWithParams")
        };
        handler(ctx, sql, args)
    }
}
