[package]
name = "astersql-executor-test-loaddatatest"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "lib.rs"

[package.metadata.porting]
go-package = "pkg/executor/test/loaddatatest"
legacy-tasks = ["task-1346"]

[dev-dependencies]
astersql-session = { path = "../../../session" }

[target.'cfg(any())'.dev-dependencies]
"astersql-config" = { package = "astersql-config", path = "../../../config" }
"astersql-domain" = { package = "astersql-domain", path = "../../../domain" }
"astersql-executor" = { package = "astersql-executor", path = "../.." }
"astersql-kv" = { package = "astersql-kv", path = "../../../kv" }
"astersql-lightning-mydump" = { package = "astersql-lightning-mydump", path = "../../../lightning/mydump" }
"astersql-meta-autoid" = { package = "astersql-meta-autoid", path = "../../../meta/autoid" }
"astersql-resourcemanager" = { package = "astersql-resourcemanager", path = "../../../resourcemanager" }
"astersql-sessionctx" = { package = "astersql-sessionctx", path = "../../../sessionctx" }
"astersql-sessionctx-vardef" = { package = "astersql-sessionctx-vardef", path = "../../../sessionctx/vardef" }
"astersql-store-mockstore" = { package = "astersql-store-mockstore", path = "../../../store/mockstore" }
"astersql-testkit" = { package = "astersql-testkit", path = "../../../testkit" }
"astersql-util-dbterror" = { package = "astersql-util-dbterror", path = "../../../util/dbterror" }
"astersql-util-dbterror-exeerrors" = { package = "astersql-util-dbterror-exeerrors", path = "../../../util/dbterror/exeerrors" }
"astersql-util-gctuner" = { package = "astersql-util-gctuner", path = "../../../util/gctuner" }
